import { NextFunction, Request, RequestHandler, Response, Router } from 'express';
import { Pool, PoolClient } from 'pg';
import pool from '../../db/pool';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { getAuthenticatedContext, requireActiveCompany, requireAuth, requireCapability } from '../auth/auth.middleware';
import { requireSameOrigin } from '../auth/origin.middleware';

export const partnerRouter=Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
class NotFound extends Error{} class Conflict extends Error{} class Invalid extends Error{}
type Partner={id:string;company_id:string;name:string;is_active:boolean;version:number;created_at:Date;updated_at:Date};
type Ownership={id:string;company_id:string;partner_id:string;ownership_percentage:string|null;effective_from:string|null;effective_to:string|null;verification_status:'unconfirmed'|'confirmed';source_document_id:string|null;note:string|null;version:number;created_at:Date;updated_at:Date};
type OwnershipInput={ownership_percentage:string|null;effective_from:string|null;effective_to:string|null;verification_status:'unconfirmed'|'confirmed';source_document_id:string|null;note:string|null};
const asyncRoute=(h:(q:Request,s:Response,n:NextFunction)=>Promise<void>):RequestHandler=>(q,s,n)=>void h(q,s,n).catch(n);
const own=(o:unknown,k:string[])=>!!o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).every(x=>k.includes(x));
const identifier=(x:unknown)=>typeof x==='string'&&UUID.test(x)?x:null;
function partnerName(x:unknown){if(typeof x!=='string')return null;const n=x.trim();return n.length>0&&n.length<=200?n:null;}
function nullableText(x:unknown,max:number){if(x===null||x===undefined)return null;if(typeof x!=='string')throw new Invalid();const n=x.trim();return n?n.length<=max?n:(()=>{throw new Invalid()})():null;}
function date(x:unknown){if(x===null||x===undefined)return null;return typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&!Number.isNaN(Date.parse(`${x}T00:00:00Z`))?x:(()=>{throw new Invalid()})();}
function ownershipInput(body:unknown):OwnershipInput{const keys=['ownership_percentage','effective_from','effective_to','verification_status','source_document_id','note'];if(!own(body,keys))throw new Invalid();const b=body as Record<string,unknown>;const raw=b.ownership_percentage;let pct:string|null=null;if(raw!==null&&raw!==undefined){pct=typeof raw==='number'||typeof raw==='string'?String(raw).trim():'';if(!/^\d{1,3}(?:\.\d{1,4})?$/.test(pct)||Number(pct)<=0||Number(pct)>100)throw new Invalid();}const from=date(b.effective_from),to=date(b.effective_to);if(to&&(!from||to<from))throw new Invalid();const status=b.verification_status;if(status!=='unconfirmed'&&status!=='confirmed')throw new Invalid();if(status==='confirmed'&&(!pct||!from))throw new Invalid();const doc=b.source_document_id===null||b.source_document_id===undefined?null:identifier(b.source_document_id);if(b.source_document_id!=null&&!doc)throw new Invalid();return{ownership_percentage:pct,effective_from:from,effective_to:to,verification_status:status,source_document_id:doc,note:nullableText(b.note,1000)};}
class Service{private audit=new AuditLogRepository();constructor(private db:Pool){}private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const v=await fn(c);await c.query('COMMIT');return v;}catch(e){await c.query('ROLLBACK');if((e as {code?:string}).code==='23503')throw new NotFound();if((e as {code?:string}).code?.startsWith('23'))throw new Invalid();throw e;}finally{c.release();}}
 async list(company:string){const{rows}=await this.db.query(`SELECT p.*,o.ownership_percentage::text AS current_ownership_percentage,o.effective_from::text AS current_effective_from, EXISTS(SELECT 1 FROM partner_ownership_periods u WHERE u.partner_id=p.id AND u.company_id=p.company_id AND u.verification_status='unconfirmed') AS has_unconfirmed_ownership FROM partners p LEFT JOIN LATERAL (SELECT ownership_percentage,effective_from FROM partner_ownership_periods WHERE partner_id=p.id AND company_id=p.company_id AND verification_status='confirmed' AND effective_from<=CURRENT_DATE AND (effective_to IS NULL OR effective_to>=CURRENT_DATE) ORDER BY effective_from DESC,created_at DESC LIMIT 1)o ON TRUE WHERE p.company_id=$1 ORDER BY p.is_active DESC,p.name`,[company]);return{partners:rows};}
 async create(company:string,actor:string,name:string){return this.tx(async c=>{const{rows}=await c.query<Partner>('INSERT INTO partners(company_id,name,created_by_user_id) VALUES($1,$2,$3) RETURNING *',[company,name,actor]);const p=rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'partner.create',entity_type:'partner',entity_id:p.id,before_data:null,after_data:{name:p.name,is_active:p.is_active,version:p.version}},c);return p;});}
 async update(id:string,company:string,actor:string,input:{name?:string;is_active?:boolean;version:number}){return this.tx(async c=>{const{rows:[before]}=await c.query<Partner>('SELECT * FROM partners WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,company]);if(!before)throw new NotFound();if(before.version!==input.version)throw new Conflict();const name=input.name??before.name,active=input.is_active??before.is_active;const{rows}=await c.query<Partner>('UPDATE partners SET name=$3,is_active=$4,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *',[id,company,name,active]);const after=rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:before.is_active&&!active?'partner.disable':'partner.update',entity_type:'partner',entity_id:id,before_data:{name:before.name,is_active:before.is_active,version:before.version},after_data:{name:after.name,is_active:after.is_active,version:after.version}},c);return after;});}
 async history(id:string,company:string){const p=await this.db.query('SELECT 1 FROM partners WHERE id=$1 AND company_id=$2',[id,company]);if(!p.rowCount)throw new NotFound();const{rows}=await this.db.query<Ownership>('SELECT *,ownership_percentage::text,effective_from::text,effective_to::text FROM partner_ownership_periods WHERE partner_id=$1 AND company_id=$2 ORDER BY effective_from DESC NULLS LAST,created_at DESC',[id,company]);return{ownership:rows};}
 private async validate(c:PoolClient,company:string,partner:string,input:OwnershipInput,exclude?:string){await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${company}:${partner}`]);if(input.source_document_id){const d=await c.query('SELECT 1 FROM documents WHERE id=$1 AND company_id=$2',[input.source_document_id,company]);if(!d.rowCount)throw new NotFound();}if(input.verification_status==='confirmed'){const overlap=await c.query(`SELECT 1 FROM partner_ownership_periods WHERE company_id=$1 AND partner_id=$2 AND verification_status='confirmed' AND ($3::uuid IS NULL OR id<>$3) AND daterange(effective_from,COALESCE(effective_to,'infinity'::date),'[]') && daterange($4::date,COALESCE($5::date,'infinity'::date),'[]') LIMIT 1`,[company,partner,exclude??null,input.effective_from,input.effective_to]);if(overlap.rowCount)throw new Conflict();}}
 async createOwnership(partner:string,company:string,actor:string,input:OwnershipInput){return this.tx(async c=>{const p=await c.query('SELECT 1 FROM partners WHERE id=$1 AND company_id=$2 FOR UPDATE',[partner,company]);if(!p.rowCount)throw new NotFound();await this.validate(c,company,partner,input);const{rows}=await c.query<Ownership>('INSERT INTO partner_ownership_periods(company_id,partner_id,ownership_percentage,effective_from,effective_to,verification_status,source_document_id,note,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *,ownership_percentage::text,effective_from::text,effective_to::text',[company,partner,input.ownership_percentage,input.effective_from,input.effective_to,input.verification_status,input.source_document_id,input.note,actor]);const o=rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'partner_ownership.create',entity_type:'partner_ownership',entity_id:o.id,before_data:null,after_data:{...input,partner_id:partner,version:o.version}},c);return o;});}
 async updateOwnership(partner:string,id:string,company:string,actor:string,input:OwnershipInput,version:number,reason:string|null){return this.tx(async c=>{const p=await c.query('SELECT 1 FROM partners WHERE id=$1 AND company_id=$2 FOR UPDATE',[partner,company]);if(!p.rowCount)throw new NotFound();const{rows:[before]}=await c.query<Ownership>('SELECT *,ownership_percentage::text,effective_from::text,effective_to::text FROM partner_ownership_periods WHERE id=$1 AND partner_id=$2 AND company_id=$3 FOR UPDATE',[id,partner,company]);if(!before)throw new NotFound();if(before.version!==version)throw new Conflict();if(before.verification_status==='confirmed'&&!reason)throw new Invalid();await this.validate(c,company,partner,input,id);const{rows}=await c.query<Ownership>('UPDATE partner_ownership_periods SET ownership_percentage=$4,effective_from=$5,effective_to=$6,verification_status=$7,source_document_id=$8,note=$9,version=version+1,updated_at=NOW() WHERE id=$1 AND partner_id=$2 AND company_id=$3 RETURNING *,ownership_percentage::text,effective_from::text,effective_to::text',[id,partner,company,input.ownership_percentage,input.effective_from,input.effective_to,input.verification_status,input.source_document_id,input.note]);const after=rows[0]!;const confirming=before.verification_status==='unconfirmed'&&after.verification_status==='confirmed';await this.audit.logEvent({company_id:company,actor_user_id:actor,action:confirming?'partner_ownership.confirm':'partner_ownership.update',entity_type:'partner_ownership',entity_id:id,before_data:before as unknown as Record<string,unknown>,after_data:after as unknown as Record<string,unknown>,reason},c);return after;});}}
function svc(res:Response){if(!pool){res.status(503).json({error:'Database unavailable'});return null;}return new Service(pool);}function ctx(req:Request){return getAuthenticatedContext(req)! as ReturnType<typeof getAuthenticatedContext>&{activeCompanyId:string};}function errors(e:unknown,res:Response){if(e instanceof Invalid){res.status(400).json({error:'Invalid partner request'});return true;}if(e instanceof NotFound){res.status(404).json({error:'Not found'});return true;}if(e instanceof Conflict){res.status(409).json({error:'Conflict'});return true;}return false;}
const read=[requireAuth,requireActiveCompany,requireCapability('partner.view')],write=[requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('partner.manage')];
partnerRouter.get('/partners',...read,asyncRoute(async(q,s)=>{const v=svc(s);if(v)try{s.json(await v.list(ctx(q).activeCompanyId));}catch(e){if(!errors(e,s))throw e;}}));
partnerRouter.post('/partners',...write,asyncRoute(async(q,s)=>{const v=svc(s),n=partnerName((q.body as Record<string,unknown>)?.name);if(!v)return;if(!own(q.body,['name'])||!n){s.status(400).json({error:'Invalid partner request'});return;}try{s.status(201).json(await v.create(ctx(q).activeCompanyId,ctx(q).user.id,n));}catch(e){if(!errors(e,s))throw e;}}));
partnerRouter.patch('/partners/:id',...write,asyncRoute(async(q,s)=>{const v=svc(s),id=identifier(q.params.id),b=q.body as Record<string,unknown>;if(!v)return;if(!id||!own(b,['name','is_active','version'])||!Number.isInteger(b.version)||(!('name'in b)&&!('is_active'in b))||('name'in b&&!partnerName(b.name))||('is_active'in b&&typeof b.is_active!=='boolean')){s.status(400).json({error:'Invalid partner request'});return;}try{s.json(await v.update(id,ctx(q).activeCompanyId,ctx(q).user.id,{name:'name'in b?partnerName(b.name)!:undefined,is_active:b.is_active as boolean|undefined,version:b.version as number}));}catch(e){if(!errors(e,s))throw e;}}));
partnerRouter.get('/partners/:id/ownership',...read,asyncRoute(async(q,s)=>{const v=svc(s),id=identifier(q.params.id);if(!v)return;if(!id){s.status(404).json({error:'Not found'});return;}try{s.json(await v.history(id,ctx(q).activeCompanyId));}catch(e){if(!errors(e,s))throw e;}}));
partnerRouter.post('/partners/:id/ownership',...write,asyncRoute(async(q,s)=>{const v=svc(s),id=identifier(q.params.id);if(!v)return;try{if(!id)throw new NotFound();s.status(201).json(await v.createOwnership(id,ctx(q).activeCompanyId,ctx(q).user.id,ownershipInput(q.body)));}catch(e){if(!errors(e,s))throw e;}}));
partnerRouter.patch('/partners/:partnerId/ownership/:ownershipId',...write,asyncRoute(async(q,s)=>{const v=svc(s),pid=identifier(q.params.partnerId),oid=identifier(q.params.ownershipId),b=q.body as Record<string,unknown>;if(!v)return;try{if(!pid||!oid||!own(b,['ownership_percentage','effective_from','effective_to','verification_status','source_document_id','note','version','reason'])||!Number.isInteger(b.version))throw new Invalid();const input=ownershipInput(Object.fromEntries(Object.entries(b).filter(([k])=>k!=='version'&&k!=='reason')));const reason=nullableText(b.reason,500);s.json(await v.updateOwnership(pid,oid,ctx(q).activeCompanyId,ctx(q).user.id,input,b.version as number,reason));}catch(e){if(!errors(e,s))throw e;}}));
