import { Pool, PoolClient } from 'pg';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { TaxPath, TaxWorkpaper } from './tax-working-paper.types';

export class TaxWorkpaperNotFoundError extends Error {}
export class TaxWorkpaperValidationError extends Error {}
export class TaxWorkpaperConflictError extends Error {}
const PATH:Record<string,TaxPath>={zakat_applicable:'zakat',income_tax_applicable:'income_tax',mixed:'mixed',needs_review:'needs_review'};
const SELECT=`w.*,w.prepared_at::text,w.reviewed_at::text,w.approved_at::text,w.created_at::text,w.updated_at::text`;

export class TaxWorkpaperService {
  private audit=new AuditLogRepository();
  constructor(private db:Pool){}
  private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const result=await fn(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  private async load(company:string,year:string,runner:Pool|PoolClient,lock=false):Promise<TaxWorkpaper|null>{
    const row=(await runner.query<any>(`SELECT ${SELECT} FROM tax_working_papers w WHERE w.company_id=$1 AND w.fiscal_year_id=$2${lock?' FOR UPDATE':''}`,[company,year])).rows[0];
    if(!row)return null;
    row.adjustments=(await runner.query(`SELECT *,amount::text FROM tax_working_paper_adjustments WHERE company_id=$1 AND workpaper_id=$2 ORDER BY created_at,id`,[company,row.id])).rows;
    return row;
  }
  get(company:string,year:string){return this.load(company,year,this.db);}
  private async applicability(company:string,year:string,c:PoolClient){
    const fy=(await c.query<{start_date:string;end_date:string}>(`SELECT start_date::text,end_date::text FROM fiscal_years WHERE id=$1 AND company_id=$2`,[year,company])).rows[0];
    if(!fy)throw new TaxWorkpaperNotFoundError();
    const profile=(await c.query<{id:string;tax_treatment:string}>(`SELECT id,tax_treatment FROM company_accounting_profiles WHERE company_id=$1 AND workflow_status='approved' AND effective_from<=$2 AND (effective_to IS NULL OR effective_to>=$3) AND (tax_effective_from IS NULL OR tax_effective_from<=$2) ORDER BY effective_from DESC,version_no DESC LIMIT 1`,[company,fy.start_date,fy.end_date])).rows[0];
    return {profileId:profile?.id??null,path:profile?PATH[profile.tax_treatment]??'needs_review':'needs_review' as TaxPath};
  }
  create(company:string,year:string,actor:string,notes:string|null){return this.tx(async c=>{const applicable=await this.applicability(company,year,c);try{const row=(await c.query<any>(`INSERT INTO tax_working_papers(company_id,fiscal_year_id,accounting_profile_id,tax_path,notes,professional_review_required,prepared_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[company,year,applicable.profileId,applicable.path,notes,applicable.path==='needs_review',actor])).rows[0];row.adjustments=[];await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'tax_workpaper.create',entity_type:'tax_working_paper',entity_id:row.id,before_data:null,after_data:row as never},c);return row;}catch(e){if((e as{code?:string}).code==='23505')throw new TaxWorkpaperConflictError('A workpaper already exists for this fiscal year');throw e;}});}
  private editable(w:TaxWorkpaper,version:number){if(w.workflow_status!=='draft')throw new TaxWorkpaperConflictError('Only draft workpapers may be edited');if(w.version!==version)throw new TaxWorkpaperConflictError('Workpaper was modified');}
  update(company:string,year:string,actor:string,input:{notes?:string|null;professional_review_required?:boolean;version:number}){return this.tx(async c=>{const before=await this.load(company,year,c,true);if(!before)throw new TaxWorkpaperNotFoundError();this.editable(before,input.version);const applicable=await this.applicability(company,year,c);const after=(await c.query<any>(`UPDATE tax_working_papers SET notes=COALESCE($3,notes),professional_review_required=COALESCE($4,professional_review_required),accounting_profile_id=$5,tax_path=$6,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 AND version=$7 RETURNING *`,[before.id,company,input.notes===undefined?null:input.notes,input.professional_review_required,applicable.profileId,applicable.path,input.version])).rows[0];after.adjustments=before.adjustments;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'tax_workpaper.update',entity_type:'tax_working_paper',entity_id:before.id,before_data:before as never,after_data:after as never},c);return after;});}
  resolveProfessionalReview(company:string,year:string,actor:string,version:number){return this.tx(async c=>{const before=await this.load(company,year,c,true);if(!before)throw new TaxWorkpaperNotFoundError();if(before.workflow_status!=='needs_review'||before.version!==version||!before.professional_review_required)throw new TaxWorkpaperConflictError('Professional review resolution requires the current flagged needs-review workpaper');const after=(await c.query<any>(`UPDATE tax_working_papers SET professional_review_required=FALSE,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 AND workflow_status='needs_review' AND professional_review_required=TRUE AND version=$3 RETURNING *`,[before.id,company,version])).rows[0];if(!after)throw new TaxWorkpaperConflictError('Workpaper was modified');after.adjustments=before.adjustments;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'tax_workpaper.professional_review.resolve',entity_type:'tax_working_paper',entity_id:before.id,before_data:before as never,after_data:after as never},c);return after;});}
  addAdjustment(company:string,year:string,actor:string,input:{description:string;direction:'add'|'deduct';amount:string;notes:string|null;source_reference:string|null;professional_review_required:boolean;version:number}){return this.tx(async c=>{const before=await this.load(company,year,c,true);if(!before)throw new TaxWorkpaperNotFoundError();this.editable(before,input.version);const item=(await c.query<any>(`INSERT INTO tax_working_paper_adjustments(company_id,workpaper_id,description,direction,amount,notes,source_reference,professional_review_required,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *,amount::text`,[company,before.id,input.description,input.direction,input.amount,input.notes,input.source_reference,input.professional_review_required,actor])).rows[0];await c.query('UPDATE tax_working_papers SET version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2',[before.id,company]);await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'tax_workpaper.adjustment.create',entity_type:'tax_working_paper_adjustment',entity_id:item.id,before_data:null,after_data:item as never},c);return item;});}
  async changeAdjustment(company:string,year:string,id:string,actor:string,input:{description?:string;direction?:'add'|'deduct';amount?:string;notes?:string|null;source_reference?:string|null;professional_review_required?:boolean;version:number}){return this.tx(async c=>{const w=await this.load(company,year,c,true);if(!w)throw new TaxWorkpaperNotFoundError();if(w.workflow_status!=='draft')throw new TaxWorkpaperConflictError('Only draft workpapers may be edited');const before=w.adjustments.find(x=>x.id===id);if(!before)throw new TaxWorkpaperNotFoundError();const after=(await c.query<any>(`UPDATE tax_working_paper_adjustments SET description=COALESCE($4,description),direction=COALESCE($5,direction),amount=COALESCE($6,amount),notes=CASE WHEN $7 THEN $8 ELSE notes END,source_reference=CASE WHEN $9 THEN $10 ELSE source_reference END,professional_review_required=COALESCE($11,professional_review_required),version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 AND workpaper_id=$3 AND version=$12 RETURNING *,amount::text`,[id,company,w.id,input.description,input.direction,input.amount,'notes'in input,input.notes,'source_reference'in input,input.source_reference,input.professional_review_required,input.version])).rows[0];if(!after)throw new TaxWorkpaperConflictError('Adjustment was modified');await c.query('UPDATE tax_working_papers SET version=version+1,updated_at=NOW() WHERE id=$1',[w.id]);await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'tax_workpaper.adjustment.update',entity_type:'tax_working_paper_adjustment',entity_id:id,before_data:before as never,after_data:after as never},c);return after;});}
  resolveAdjustmentProfessionalReview(company:string,year:string,id:string,actor:string,input:{version:number;adjustmentVersion:number}){return this.tx(async c=>{const w=await this.load(company,year,c,true);if(!w)throw new TaxWorkpaperNotFoundError();if(w.workflow_status!=='needs_review'||w.version!==input.version)throw new TaxWorkpaperConflictError('Professional review resolution requires the current needs-review workpaper');const before=w.adjustments.find(x=>x.id===id);if(!before)throw new TaxWorkpaperNotFoundError();if(!before.professional_review_required)throw new TaxWorkpaperConflictError('Adjustment does not require professional review');const after=(await c.query<any>(`UPDATE tax_working_paper_adjustments SET professional_review_required=FALSE,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 AND workpaper_id=$3 AND professional_review_required=TRUE AND version=$4 RETURNING *,amount::text`,[id,company,w.id,input.adjustmentVersion])).rows[0];if(!after)throw new TaxWorkpaperConflictError('Adjustment was modified');const workpaperUpdate=await c.query(`UPDATE tax_working_papers SET version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 AND workflow_status='needs_review' AND version=$3`,[w.id,company,input.version]);if(workpaperUpdate.rowCount!==1)throw new TaxWorkpaperConflictError('Workpaper was modified');await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'tax_workpaper.adjustment.professional_review.resolve',entity_type:'tax_working_paper_adjustment',entity_id:id,before_data:before as never,after_data:after as never},c);return after;});}
  removeAdjustment(company:string,year:string,id:string,actor:string,version:number){return this.tx(async c=>{const w=await this.load(company,year,c,true);if(!w)throw new TaxWorkpaperNotFoundError();if(w.workflow_status!=='draft')throw new TaxWorkpaperConflictError('Only draft workpapers may be edited');const before=w.adjustments.find(x=>x.id===id);if(!before)throw new TaxWorkpaperNotFoundError();if(before.version!==version)throw new TaxWorkpaperConflictError('Adjustment was modified');await c.query('DELETE FROM tax_working_paper_adjustments WHERE id=$1 AND company_id=$2 AND workpaper_id=$3',[id,company,w.id]);await c.query('UPDATE tax_working_papers SET version=version+1,updated_at=NOW() WHERE id=$1',[w.id]);await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'tax_workpaper.adjustment.delete',entity_type:'tax_working_paper_adjustment',entity_id:id,before_data:before as never,after_data:null},c);});}
  transition(company:string,year:string,actor:string,from:string,to:string,version:number){return this.tx(async c=>{const before=await this.load(company,year,c,true);if(!before)throw new TaxWorkpaperNotFoundError();if(before.workflow_status!==from||before.version!==version)throw new TaxWorkpaperConflictError('Invalid or concurrent workflow transition');const applicable=await this.applicability(company,year,c);if(to==='reviewed'&&(before.professional_review_required||before.adjustments.some(x=>x.professional_review_required)))throw new TaxWorkpaperValidationError('Professional review items must be resolved');if(to==='approved'&&(applicable.path==='needs_review'||applicable.profileId!==before.accounting_profile_id))throw new TaxWorkpaperValidationError('Approved accounting profile applicability is required');const metadata=to==='reviewed'?',reviewed_by_user_id=$6,reviewed_at=NOW()':to==='approved'?',approved_by_user_id=$6,approved_at=NOW()':'';const args=metadata?[before.id,company,from,to,version,actor]:[before.id,company,from,to,version];const after=(await c.query<any>(`UPDATE tax_working_papers SET workflow_status=$4,version=version+1,updated_at=NOW()${metadata} WHERE id=$1 AND company_id=$2 AND workflow_status=$3 AND version=$5 RETURNING *`,args)).rows[0];after.adjustments=before.adjustments;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:`tax_workpaper.${to==='needs_review'?'submit_review':to}`,entity_type:'tax_working_paper',entity_id:before.id,before_data:before as never,after_data:after as never},c);return after;});}
}
