import { Request, Response, NextFunction, Router } from 'express';
import pool from '../../db/pool';
import { getAuthenticatedContext, requireActiveCompany, requireAuth, requireCapability } from '../auth/auth.middleware';
import { requireSameOrigin } from '../auth/origin.middleware';
import { TaxWorkpaperConflictError, TaxWorkpaperNotFoundError, TaxWorkpaperService, TaxWorkpaperValidationError } from './tax-working-paper.service';

export const taxWorkpaperRouter=Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const amount=(v:unknown)=>typeof v==='string'&&/^(?:0|[1-9]\d{0,15})\.\d{2}$/.test(v)&&v!=='0.00'?v:null;
const plain=(v:unknown):v is Record<string,unknown>=>Boolean(v)&&typeof v==='object'&&!Array.isArray(v);
const ctx=(r:Request)=>getAuthenticatedContext(r)! as NonNullable<ReturnType<typeof getAuthenticatedContext>>&{activeCompanyId:string};
const service=(res:Response)=>{if(!pool){res.status(503).json({error:'Database unavailable'});return null;}return new TaxWorkpaperService(pool);};
const handle=(e:unknown,res:Response,next:NextFunction)=>{if(e instanceof TaxWorkpaperNotFoundError)res.status(404).json({error:'Not found'});else if(e instanceof TaxWorkpaperValidationError)res.status(400).json({error:e.message});else if(e instanceof TaxWorkpaperConflictError)res.status(409).json({error:e.message});else next(e);};
const route=(fn:(req:Request,res:Response,next:NextFunction)=>Promise<void>)=>(req:Request,res:Response,next:NextFunction)=>void fn(req,res,next).catch(next);
const base=[requireAuth,requireActiveCompany]; const write=[requireSameOrigin,...base];
const version=(v:unknown)=>plain(v)&&Number.isInteger(v.version)&&Number(v.version)>0?Number(v.version):null;
const validText=(v:unknown,max:number,nullable=true)=>v===null&&nullable||typeof v==='string'&&v.trim().length>0&&v.length<=max;

taxWorkpaperRouter.get('/tax-working-papers/:fiscalYearId',...base,requireCapability('tax_workpaper.view'),route(async(req,res,next)=>{if(!UUID.test(req.params.fiscalYearId)){res.status(400).json({error:'Invalid fiscal year'});return;}const s=service(res);if(!s)return;try{const workpaper=await s.get(ctx(req).activeCompanyId,req.params.fiscalYearId);res.json({workpaper});}catch(e){handle(e,res,next);}}));
taxWorkpaperRouter.post('/tax-working-papers/:fiscalYearId',...write,requireCapability('tax_workpaper.manage'),route(async(req,res,next)=>{if(!UUID.test(req.params.fiscalYearId)||!plain(req.body)||Object.keys(req.body).some(k=>k!=='notes')||('notes'in req.body&&!validText(req.body.notes,4000))){res.status(400).json({error:'Invalid request'});return;}const s=service(res);if(!s)return;try{res.status(201).json({workpaper:await s.create(ctx(req).activeCompanyId,req.params.fiscalYearId,ctx(req).user.id,(req.body.notes as string|null|undefined)??null)});}catch(e){handle(e,res,next);}}));
taxWorkpaperRouter.patch('/tax-working-papers/:fiscalYearId',...write,requireCapability('tax_workpaper.manage'),route(async(req,res,next)=>{const v=version(req.body);if(!UUID.test(req.params.fiscalYearId)||v===null||Object.keys(req.body).some(k=>!['notes','professional_review_required','version'].includes(k))||('notes'in req.body&&!validText(req.body.notes,4000))||('professional_review_required'in req.body&&typeof req.body.professional_review_required!=='boolean')){res.status(400).json({error:'Invalid request'});return;}const s=service(res);if(!s)return;try{res.json({workpaper:await s.update(ctx(req).activeCompanyId,req.params.fiscalYearId,ctx(req).user.id,{notes:req.body.notes as string|null|undefined,professional_review_required:req.body.professional_review_required as boolean|undefined,version:v})});}catch(e){handle(e,res,next);}}));
const adjustment=(body:unknown,partial=false)=>{if(!plain(body))return null;const allowed=['description','direction','amount','notes','source_reference','professional_review_required','version'];if(Object.keys(body).some(k=>!allowed.includes(k))||!Number.isInteger(body.version))return null;if((!partial||'description'in body)&&!validText(body.description,500,false))return null;if((!partial||'direction'in body)&&!['add','deduct'].includes(String(body.direction)))return null;if((!partial||'amount'in body)&&!amount(body.amount))return null;if('notes'in body&&!validText(body.notes,2000))return null;if('source_reference'in body&&!validText(body.source_reference,500))return null;if('professional_review_required'in body&&typeof body.professional_review_required!=='boolean')return null;return body;};
taxWorkpaperRouter.post('/tax-working-papers/:fiscalYearId/adjustments',...write,requireCapability('tax_workpaper.manage'),route(async(req,res,next)=>{const b=adjustment(req.body);if(!UUID.test(req.params.fiscalYearId)||!b){res.status(400).json({error:'Invalid adjustment'});return;}const s=service(res);if(!s)return;try{res.status(201).json({adjustment:await s.addAdjustment(ctx(req).activeCompanyId,req.params.fiscalYearId,ctx(req).user.id,{description:String(b.description).trim(),direction:b.direction as 'add'|'deduct',amount:String(b.amount),notes:(b.notes as string|null|undefined)??null,source_reference:(b.source_reference as string|null|undefined)??null,professional_review_required:Boolean(b.professional_review_required),version:Number(b.version)})});}catch(e){handle(e,res,next);}}));
taxWorkpaperRouter.patch('/tax-working-papers/:fiscalYearId/adjustments/:id',...write,requireCapability('tax_workpaper.manage'),route(async(req,res,next)=>{const b=adjustment(req.body,true);if(!UUID.test(req.params.fiscalYearId)||!UUID.test(req.params.id)||!b){res.status(400).json({error:'Invalid adjustment'});return;}const s=service(res);if(!s)return;try{res.json({adjustment:await s.changeAdjustment(ctx(req).activeCompanyId,req.params.fiscalYearId,req.params.id,ctx(req).user.id,b as never)});}catch(e){handle(e,res,next);}}));
taxWorkpaperRouter.delete('/tax-working-papers/:fiscalYearId/adjustments/:id',...write,requireCapability('tax_workpaper.manage'),route(async(req,res,next)=>{const v=version(req.body);if(!UUID.test(req.params.fiscalYearId)||!UUID.test(req.params.id)||v===null){res.status(400).json({error:'Invalid request'});return;}const s=service(res);if(!s)return;try{await s.removeAdjustment(ctx(req).activeCompanyId,req.params.fiscalYearId,req.params.id,ctx(req).user.id,v);res.status(204).end();}catch(e){handle(e,res,next);}}));
for(const [action,cap,from,to] of [['submit-review','tax_workpaper.manage','draft','needs_review'],['review','tax_workpaper.review','needs_review','reviewed'],['approve','tax_workpaper.approve','reviewed','approved']] as const)taxWorkpaperRouter.post(`/tax-working-papers/:fiscalYearId/${action}`,...write,requireCapability(cap),route(async(req,res,next)=>{const v=version(req.body);if(!UUID.test(req.params.fiscalYearId)||v===null||Object.keys(req.body).some(k=>k!=='version')){res.status(400).json({error:'Invalid request'});return;}const s=service(res);if(!s)return;try{res.json({workpaper:await s.transition(ctx(req).activeCompanyId,req.params.fiscalYearId,ctx(req).user.id,from,to,v)});}catch(e){handle(e,res,next);}}));
