const ar = {
  app: { title: 'إقفال — المالية والعمليات', shortTitle: 'إقفال', subtitle: 'الإدارة والإقفال المالي', switchLanguage: 'Switch to English', loading: 'جارٍ التحميل…' },
  nav: { main: 'التنقل الرئيسي', home: 'الرئيسية', fiscalYears: 'السنوات المالية', documents: 'المستندات', banks: 'البنوك', openMenu: 'فتح قائمة التنقل' },
  home: { workspace: 'مساحة عمل الشركة', welcome: 'مرحبًا بعودتك', context: 'كل ما تحتاجه للبدء في متابعة أعمال الشركة المالية من مكان واحد.', currentUser: 'المستخدم الحالي', quickActions: 'الإجراءات السريعة', quickActionsDescription: 'انتقل مباشرة إلى المهام الأساسية المتاحة لك.', documentsDescription: 'مراجعة وإدارة المستندات المالية للشركة النشطة.', uploadDescription: 'إضافة فاتورة أو مستند جديد إلى مساحة عمل الشركة.', fiscalYearsDescription: 'عرض وإدارة السنوات المالية المتاحة للشركة.', openDocuments: 'عرض المستندات', uploadDocument: 'رفع مستند', openFiscalYears: 'عرض السنوات المالية' },
  auth: { email: 'البريد الإلكتروني', password: 'كلمة المرور', login: 'تسجيل الدخول', logout: 'تسجيل الخروج', invalid: 'تعذر تسجيل الدخول. تحقق من البيانات وحاول مرة أخرى.' },
  company: { label: 'الشركة النشطة', none: 'لا توجد شركات متاحة', switchAriaLabel: 'تبديل الشركة النشطة', switching: 'جارٍ تبديل الشركة…' },
  common: { cancel: 'إلغاء', close: 'إغلاق', save: 'حفظ', confirm: 'تأكيد', retry: 'إعادة المحاولة' },
  fiscalYears: { title: 'السنوات المالية', description: 'إدارة السنوات المالية للشركة النشطة.', loading: 'جارٍ تحميل السنوات المالية…', empty: 'لم يتم إنشاء أي سنة مالية بعد.', error: 'تعذر تحميل السنوات المالية أو حفظها.', invalidRequest: 'تحقق من بيانات السنة المالية وحاول مرة أخرى.', forbidden: 'ليس لديك صلاحية تنفيذ هذا الإجراء.', notFound: 'تعذر العثور على السنة المالية.', conflict: 'تتعارض السنة المالية مع سنة قائمة أو مع حالتها الحالية.', invalidRange: 'يجب أن يكون تاريخ النهاية بعد تاريخ البداية.', retry: 'إعادة المحاولة', noAccess: 'ليس لديك صلاحية عرض السنوات المالية.', create: 'إنشاء سنة مالية', createTitle: 'إنشاء سنة مالية', editTitle: 'تعديل السنة المالية', name: 'الاسم', start: 'تاريخ البداية', end: 'تاريخ النهاية', status: 'الحالة', actions: 'الإجراءات', open: 'مفتوحة', closed: 'مقفلة', edit: 'تعديل', close: 'إقفال', closeTitle: 'إقفال السنة المالية', closeConfirmation: 'هل تريد إقفال {{name}}؟ وفق الوظائف المتاحة حاليًا، لا يمكن تعديل السنة المالية المقفلة.', reason: 'السبب (اختياري)', confirmClose: 'تأكيد الإقفال' },
  documents: {
    title: 'المستندات', workspace: 'مساحة عمل المستندات', list: 'قائمة المستندات', workflow: 'إجراءات سير العمل', uploadTitle: 'رفع مستند', accepted: 'PDF أو JPEG أو PNG أو WebP · الحد الأقصى 10 ميجابايت', reasonRequired: 'السبب مطلوب.', approvalNote: 'ملاحظة (اختيارية)', description: 'رفع مستندات الشركة النشطة والوصول إليها بأمان.', chooseFile: 'اختيار مستند', upload: 'رفع مستند', uploading: 'جارٍ الرفع…', loading: 'جارٍ تحميل المستندات…', empty: 'لا توجد مستندات مرفوعة بعد.', error: 'تعذر تحميل المستندات أو رفعها.', invalid: 'استخدم ملف PDF أو JPEG أو PNG أو WebP صالحًا وبحجم لا يتجاوز 10 ميجابايت.', tooLarge: 'حجم المستند أكبر من 10 ميجابايت.', file: 'الملف', status: 'الحالة', size: 'الحجم', actions: 'الإجراءات', open: 'فتح', reviewError: 'تعذر تحديث مراجعة المستند.', reviewConflict: 'تمت مراجعة هذا المستند بالفعل. حدّث الصفحة وحاول مجددًا.', reviewReason: 'السبب', reviewNote: 'ملاحظة المراجعة', reviewedAt: 'وقت المراجعة',
    intake: { title: 'بيانات الإدخال', readOnly: 'بيانات الإدخال للقراءة فقط لهذا المستند.', documentType: 'نوع المستند', document_type: 'نوع المستند', counterparty: 'اسم الطرف المقابل / المورد / الجهة', counterparty_name: 'اسم الطرف المقابل / المورد / الجهة', documentDate: 'تاريخ المستند', document_date: 'تاريخ المستند', reference: 'رقم الفاتورة / المرجع', reference_number: 'رقم الفاتورة / المرجع', totalAmount: 'المبلغ الإجمالي', total_amount: 'المبلغ الإجمالي', note: 'ملاحظة اختيارية', intake_note: 'ملاحظة اختيارية', none: 'غير محدد', save: 'حفظ بيانات الإدخال', saving: 'جارٍ الحفظ…', error: 'تعذر حفظ بيانات الإدخال.', types: { purchase: 'شراء', expense: 'مصروف', sale: 'بيع', other: 'أخرى' } },
    reviewActions: { submit: 'إرسال للمراجعة', approved: 'اعتماد', incomplete: 'تحديد كناقص', rejected: 'رفض' }, dialogs: { approvedTitle: 'اعتماد المستند', approvedConfirmation: 'أكد أن المستند جاهز للاعتماد.', incompleteTitle: 'تحديد المستند كناقص', incompleteConfirmation: 'وضح البيانات الناقصة قبل إعادة المستند.', rejectedTitle: 'رفض المستند', rejectedConfirmation: 'وضح سبب رفض هذا المستند.' }, statuses: { uploaded: 'مرفوع', needs_review: 'يحتاج مراجعة', approved: 'معتمد', incomplete: 'ناقص', rejected: 'مرفوض' }
  },
  banks: {
    title:'البنوك', description:'استيراد كشوف الحسابات البنكية بأمان للشركة النشطة.', noAccess:'ليس لديك صلاحية عرض بيانات البنوك.', error:'تعذر تحميل أو تحديث بيانات البنوك.', accounts:'الحسابات البنكية', account:'الحساب البنكي', accountName:'اسم الحساب', bankName:'اسم البنك', currency:'العملة', createAccount:'إنشاء حساب', noAccounts:'لا توجد حسابات بنكية بعد.', active:'نشط', inactive:'غير نشط', status:'الحالة', import:'استيراد كشف', accepted:'CSV أو XLSX · الحد الأقصى 5 ميجابايت · حتى 10,000 صف بيانات', file:'الملف', upload:'رفع', mapping:'ربط الأعمدة', amountMode:'صيغة المبلغ', signed:'مبلغ بإشارة', debitCredit:'مدين / دائن منفصلان', dateFormat:'صيغة التاريخ', transactionDate:'تاريخ الحركة', amount:'المبلغ', debit:'مدين', credit:'دائن', valueDate:'تاريخ القيمة', descriptionField:'الوصف', reference:'المرجع البنكي', balance:'الرصيد الجاري', preview:'معاينة الاستيراد', confirm:'تأكيد الاستيراد', total:'الإجمالي', valid:'صحيح', duplicates:'مكرر', possibleDuplicates:'مكرر محتمل', invalid:'غير صالح', importHistory:'سجل الاستيراد', noImports:'لا توجد عمليات استيراد بعد.', transactions:'الحركات البنكية', noTransactions:'لا توجد حركات مستوردة بعد.',
    rowStatus:{valid:'صحيح',duplicate:'مكرر',possible_duplicate:'مكرر محتمل',invalid:'غير صالح'}, batchStatus:{mapping_required:'يحتاج ربط الأعمدة',preview_ready:'المعاينة جاهزة',confirmed:'مؤكد'}
  }
} as const;
export default ar;
