import { NextFunction, Request, RequestHandler, Response, Router } from 'express';
import { Pool, PoolClient } from 'pg';
import pool from '../../db/pool';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { getAuthenticatedContext, requireActiveCompany, requireAuth, requireCapability } from '../auth/auth.middleware';
import { requireSameOrigin } from '../auth/origin.middleware';
import { AccountingPeriodClosedError, assertAccountingDateWritable } from '../monthly-close/accounting-period.guard';
import { isOperationalSourceType, loadOperationalSources, operationalSourceQuery, OperationalSource, OperationalSourceType } from './operational-sources';
import { enforceVatRecognition, VAT_RECOGNITION_ERROR_CODE, VatRecognitionIncompleteError } from './vat-recognition';

export const accountingRouter = Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const DATE=/^\d{4}-\d{2}-\d{2}$/;
const ACCOUNT_TYPES=['asset','liability','equity','revenue','expense'] as const;
type AccountType=typeof ACCOUNT_TYPES[number];
type EntryType='standard'|'opening_balance';
type Account={id:string;company_id:string;code:string;name:string;account_type:AccountType;parent_account_id:string|null;is_active:boolean;created_at:Date;updated_at:Date};
type Journal={id:string;company_id:string;fiscal_year_id:string;accounting_date:string;description:string;reference:string|null;source_type:string|null;source_id:string|null;entry_type:EntryType;status:'draft'|'posted';created_by:string;posted_by:string|null;posted_at:Date|null;created_at:Date;updated_at:Date};
type Line={id:string;company_id:string;journal_entry_id:string;account_id:string;debit:string;credit:string;memo:string|null;sequence:number};
type AccountInput={code:string;name:string;accountType:AccountType;parentId:string|null;active:boolean};
type JournalInput={fiscalYearId:string;accountingDate:string;description:string;reference:string|null;sourceType:string|null;sourceId:string|null;entryType:EntryType};
type LineInput={accountId:string;debit:string;credit:string;memo:string|null;sequence:number};
export class AccountingValidationError extends Error{}
export class AccountingNotFoundError extends Error{}
export class AccountingConflictError extends Error{}
const route=(handler:(req:Request,res:Response)=>Promise<void>):RequestHandler=>(req,res,next:NextFunction)=>void handler(req,res).catch(next);
const context=(req:Request)=>getAuthenticatedContext(req)! as ReturnType<typeof getAuthenticatedContext>&{activeCompanyId:string};
const validDate=(x:unknown):x is string=>typeof x==='string'&&DATE.test(x)&&!Number.isNaN(Date.parse(`${x}T00:00:00Z`));
const object=(body:unknown):Record<string,unknown>|null=>body!==null&&typeof body==='object'&&!Array.isArray(body)?body as Record<string,unknown>:null;
const keysAllowed=(x:Record<string,unknown>,keys:string[])=>Object.keys(x).every(k=>keys.includes(k));
const textValue=(x:unknown,max:number,required=false):string|null|undefined=>{if(x===null&&!required)return null;if(typeof x!=='string')return undefined;const value=x.trim();return value&&value.length<=max?value:required?undefined:null;};
function accountInput(body:unknown,partial=false):Partial<AccountInput>|null{const x=object(body);if(!x||!keysAllowed(x,['code','name','account_type','parent_account_id','is_active']))return null;const out:Partial<AccountInput>={};if('code'in x){const v=textValue(x.code,50,true);if(v==null)return null;out.code=v;}if('name'in x){const v=textValue(x.name,200,true);if(v==null)return null;out.name=v;}if('account_type'in x){if(typeof x.account_type!=='string'||!ACCOUNT_TYPES.includes(x.account_type as AccountType))return null;out.accountType=x.account_type as AccountType;}if('parent_account_id'in x){if(x.parent_account_id!==null&&(typeof x.parent_account_id!=='string'||!UUID.test(x.parent_account_id)))return null;out.parentId=x.parent_account_id as string|null;}if('is_active'in x){if(typeof x.is_active!=='boolean')return null;out.active=x.is_active;}if(!partial&&(['code','name','accountType'] as const).some(k=>out[k]===undefined))return null;return out;}
function journalInput(body:unknown,partial=false):Partial<JournalInput>|null{const x=object(body);if(!x||!keysAllowed(x,['fiscal_year_id','accounting_date','description','reference','source_type','source_id','entry_type']))return null;const out:Partial<JournalInput>={};if('fiscal_year_id'in x){if(typeof x.fiscal_year_id!=='string'||!UUID.test(x.fiscal_year_id))return null;out.fiscalYearId=x.fiscal_year_id;}if('accounting_date'in x){if(!validDate(x.accounting_date))return null;out.accountingDate=x.accounting_date;}if('description'in x){const v=textValue(x.description,500,true);if(v==null)return null;out.description=v;}if('reference'in x){const v=textValue(x.reference,200);if(v===undefined)return null;out.reference=v;}if('source_type'in x){const v=textValue(x.source_type,100);if(v===undefined)return null;out.sourceType=v;}if('source_id'in x){if(x.source_id!==null&&(typeof x.source_id!=='string'||!UUID.test(x.source_id)))return null;out.sourceId=x.source_id as string|null;}if('entry_type'in x){if(x.entry_type!=='standard'&&x.entry_type!=='opening_balance')return null;out.entryType=x.entry_type;}if((out.sourceType===null)!==(out.sourceId===null)&&('source_type'in x&&'source_id'in x))return null;if(!partial&&(['fiscalYearId','accountingDate','description'] as const).some(k=>out[k]===undefined))return null;return out;}
function money(value:unknown){if(typeof value!=='string'&&typeof value!=='number')return null;const v=String(value);if(!/^(?:0|[1-9]\d{0,15})(?:\.\d{1,2})?$/.test(v))return null;return Number(v).toFixed(2);}
function linesInput(body:unknown):LineInput[]|null{const x=object(body);if(!x||!keysAllowed(x,['lines'])||!Array.isArray(x.lines))return null;const result:LineInput[]=[];for(let i=0;i<x.lines.length;i++){const row=object(x.lines[i]);if(!row||!keysAllowed(row,['account_id','debit','credit','memo'])||typeof row.account_id!=='string'||!UUID.test(row.account_id))return null;const debit=money(row.debit),credit=money(row.credit),memo=textValue(row.memo,500);if(debit===null||credit===null||memo===undefined||((debit==='0.00')===(credit==='0.00')))return null;result.push({accountId:row.account_id,debit,credit,memo,sequence:i+1});}return result;}

export class AccountingService{
 private audit=new AuditLogRepository();constructor(private db:Pool){}
 private async tx<T>(fn:(client:PoolClient)=>Promise<T>){const client=await this.db.connect();try{await client.query('BEGIN');const value=await fn(client);await client.query('COMMIT');return value;}catch(error){await client.query('ROLLBACK');const code=(error as{code?:string}).code;if(code==='23505')throw new AccountingConflictError('Duplicate accounting record');if(code==='23503'||code==='23514')throw new AccountingValidationError('Invalid accounting relationship');throw error;}finally{client.release();}}
 private async fiscalYear(companyId:string,id:string,client:PoolClient){return (await client.query<{start_date:string;end_date:string}>('SELECT start_date::text,end_date::text FROM fiscal_years WHERE id=$1 AND company_id=$2',[id,companyId])).rows[0];}
 private async validateJournal(companyId:string,input:JournalInput,client:PoolClient){const year=await this.fiscalYear(companyId,input.fiscalYearId,client);if(!year)throw new AccountingValidationError('Fiscal year does not belong to the active company');if(input.accountingDate<year.start_date||input.accountingDate>year.end_date)throw new AccountingValidationError('Accounting date must be within the fiscal year');if(input.entryType==='opening_balance'&&input.accountingDate!==year.start_date)throw new AccountingValidationError('Opening balance date must equal fiscal year start');}
 private async source(companyId:string,type:string,id:string,client:PoolClient){if(!isOperationalSourceType(type))throw new AccountingValidationError('Unsupported operational source type');const row=(await client.query<OperationalSource>(operationalSourceQuery(type),[id,companyId])).rows[0];if(!row)throw new AccountingNotFoundError();return row;}
 async listOperationalSources(companyId:string,filter?:string){if(filter&&!isOperationalSourceType(filter))throw new AccountingValidationError('Unsupported operational source type');const client=await this.db.connect();try{const sources=await loadOperationalSources(companyId,client,filter as OperationalSourceType|undefined);const unbound:OperationalSource[]=[];for(const source of sources){if(!(await client.query('SELECT 1 FROM journal_entries WHERE company_id=$1 AND source_type=$2 AND source_id=$3',[companyId,source.source_type,source.source_id])).rowCount)unbound.push(source);}return{sources:unbound.sort((a,b)=>b.accounting_date.localeCompare(a.accounting_date))};}finally{client.release();}}
 async listAccounts(companyId:string){return{accounts:(await this.db.query<Account>('SELECT * FROM accounts WHERE company_id=$1 ORDER BY code,id',[companyId])).rows};}
 async createAccount(companyId:string,actor:string,input:AccountInput){return this.tx(async client=>{const account=(await client.query<Account>('INSERT INTO accounts(company_id,code,name,account_type,parent_account_id,is_active) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[companyId,input.code,input.name,input.accountType,input.parentId,input.active])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'account.create',entity_type:'account',entity_id:account.id,before_data:null,after_data:account as never},client);return account;});}
 async updateAccount(companyId:string,actor:string,id:string,input:Partial<AccountInput>){return this.tx(async client=>{const before=(await client.query<Account>('SELECT * FROM accounts WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!before)throw new AccountingNotFoundError();if(input.parentId===id)throw new AccountingValidationError('Account cannot be its own parent');const after=(await client.query<Account>(`UPDATE accounts SET code=$3,name=$4,account_type=$5,parent_account_id=$6,is_active=$7,updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *`,[id,companyId,input.code??before.code,input.name??before.name,input.accountType??before.account_type,input.parentId===undefined?before.parent_account_id:input.parentId,input.active??before.is_active])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'account.update',entity_type:'account',entity_id:id,before_data:before as never,after_data:after as never},client);return after;});}
 async listJournals(companyId:string){return{journals:(await this.db.query<Journal>("SELECT *,accounting_date::text FROM journal_entries WHERE company_id=$1 ORDER BY journal_entries.accounting_date DESC,journal_entries.created_at DESC,journal_entries.id",[companyId])).rows};}
 async readJournal(companyId:string,id:string){const journal=(await this.db.query<Journal>('SELECT *,accounting_date::text FROM journal_entries WHERE id=$1 AND company_id=$2',[id,companyId])).rows[0];if(!journal)throw new AccountingNotFoundError();const lines=(await this.db.query<Line>('SELECT * FROM journal_lines WHERE journal_entry_id=$1 AND company_id=$2 ORDER BY sequence,id',[id,companyId])).rows;return{...journal,lines};}
 async createJournal(companyId:string,actor:string,input:JournalInput){return this.tx(async client=>{if((input.sourceType===null)!==(input.sourceId===null))throw new AccountingValidationError('Source type and id must be supplied together');if(input.sourceType&&input.sourceId){const source=await this.source(companyId,input.sourceType,input.sourceId,client);if(input.accountingDate!==source.accounting_date)throw new AccountingValidationError('Accounting date must match the operational source');if((await client.query('SELECT 1 FROM journal_entries WHERE company_id=$1 AND source_type=$2 AND source_id=$3',[companyId,input.sourceType,input.sourceId])).rowCount)throw new AccountingConflictError('Operational source already has a journal');}await this.validateJournal(companyId,input,client);await assertAccountingDateWritable(companyId,input.accountingDate,client);const journal=(await client.query<Journal>(`INSERT INTO journal_entries(company_id,fiscal_year_id,accounting_date,description,reference,source_type,source_id,entry_type,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *,accounting_date::text`,[companyId,input.fiscalYearId,input.accountingDate,input.description,input.reference,input.sourceType,input.sourceId,input.entryType,actor])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'journal.create',entity_type:'journal_entry',entity_id:journal.id,before_data:null,after_data:journal as never},client);return journal;});}
 async updateJournal(companyId:string,actor:string,id:string,input:Partial<JournalInput>){return this.tx(async client=>{const before=(await client.query<Journal>('SELECT *,accounting_date::text FROM journal_entries WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!before)throw new AccountingNotFoundError();if(before.status!=='draft')throw new AccountingConflictError('Posted journal is immutable');const merged:JournalInput={fiscalYearId:input.fiscalYearId??before.fiscal_year_id,accountingDate:input.accountingDate??before.accounting_date,description:input.description??before.description,reference:input.reference===undefined?before.reference:input.reference,sourceType:input.sourceType===undefined?before.source_type:input.sourceType,sourceId:input.sourceId===undefined?before.source_id:input.sourceId,entryType:input.entryType??before.entry_type};if((merged.sourceType===null)!==(merged.sourceId===null))throw new AccountingValidationError('Source type and id must be supplied together');if(before.source_type!==merged.sourceType||before.source_id!==merged.sourceId)throw new AccountingConflictError('Operational source identity is immutable');if(merged.sourceType&&merged.sourceId){const source=await this.source(companyId,merged.sourceType,merged.sourceId,client);if(merged.accountingDate!==source.accounting_date)throw new AccountingValidationError('Accounting date must match the operational source');}await this.validateJournal(companyId,merged,client);if(merged.accountingDate!==before.accounting_date)await assertAccountingDateWritable(companyId,merged.accountingDate,client);const after=(await client.query<Journal>(`UPDATE journal_entries SET fiscal_year_id=$3,accounting_date=$4,description=$5,reference=$6,source_type=$7,source_id=$8,entry_type=$9,updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *,accounting_date::text`,[id,companyId,merged.fiscalYearId,merged.accountingDate,merged.description,merged.reference,merged.sourceType,merged.sourceId,merged.entryType])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'journal.update',entity_type:'journal_entry',entity_id:id,before_data:before as never,after_data:after as never},client);return after;});}
 async replaceLines(companyId:string,actor:string,id:string,lines:LineInput[]){return this.tx(async client=>{const journal=(await client.query<Journal>('SELECT * FROM journal_entries WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!journal)throw new AccountingNotFoundError();if(journal.status!=='draft')throw new AccountingConflictError('Posted journal is immutable');const accountIds=[...new Set(lines.map(x=>x.accountId))];if(accountIds.length){const count=(await client.query<{count:string}>('SELECT COUNT(*)::text count FROM accounts WHERE company_id=$1 AND id=ANY($2::uuid[])',[companyId,accountIds])).rows[0]!.count;if(Number(count)!==accountIds.length)throw new AccountingValidationError('Account does not belong to the active company');}const before=(await client.query<Line>('SELECT * FROM journal_lines WHERE journal_entry_id=$1 AND company_id=$2 ORDER BY sequence',[id,companyId])).rows;await client.query('DELETE FROM journal_lines WHERE journal_entry_id=$1 AND company_id=$2',[id,companyId]);for(const line of lines)await client.query('INSERT INTO journal_lines(company_id,journal_entry_id,account_id,debit,credit,memo,sequence) VALUES($1,$2,$3,$4,$5,$6,$7)',[companyId,id,line.accountId,line.debit,line.credit,line.memo,line.sequence]);const after=(await client.query<Line>('SELECT * FROM journal_lines WHERE journal_entry_id=$1 AND company_id=$2 ORDER BY sequence',[id,companyId])).rows;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'journal.lines.replace',entity_type:'journal_entry',entity_id:id,before_data:{lines:before},after_data:{lines:after}},client);return{lines:after};});}
 async post(companyId:string,actor:string,id:string){return this.tx(async client=>{const journal=(await client.query<Journal>('SELECT *,accounting_date::text FROM journal_entries WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!journal)throw new AccountingNotFoundError();if(journal.status!=='draft')throw new AccountingConflictError('Journal is already posted');const year=await this.fiscalYear(companyId,journal.fiscal_year_id,client);if(!year||journal.accounting_date<year.start_date||journal.accounting_date>year.end_date)throw new AccountingValidationError('Accounting date must be within the fiscal year');if(journal.entry_type==='opening_balance'&&journal.accounting_date!==year.start_date)throw new AccountingValidationError('Opening balance date must equal fiscal year start');await assertAccountingDateWritable(companyId,journal.accounting_date,client);const summary=(await client.query<{count:string;debit:string;credit:string;active:string}>(`SELECT COUNT(*)::text count,COALESCE(SUM(l.debit),0)::text debit,COALESCE(SUM(l.credit),0)::text credit,COUNT(*) FILTER(WHERE a.is_active)::text active FROM journal_lines l JOIN accounts a ON a.id=l.account_id AND a.company_id=l.company_id WHERE l.journal_entry_id=$1 AND l.company_id=$2`,[id,companyId])).rows[0]!;if(Number(summary.count)<2)throw new AccountingValidationError('A posted journal requires at least two lines');if(summary.count!==summary.active)throw new AccountingValidationError('Inactive accounts cannot receive postings');if(summary.debit!==summary.credit)throw new AccountingValidationError('Journal is not balanced');if(journal.source_type&&journal.source_id){const source=await this.source(companyId,journal.source_type,journal.source_id,client);if(journal.accounting_date!==source.accounting_date)throw new AccountingValidationError('Operational source date changed');const amount=(await client.query<{matches:boolean}>('SELECT $1::numeric(18,2)=$2::numeric(18,2) matches',[summary.debit,source.amount])).rows[0]!.matches;if(!amount)throw new AccountingValidationError('Journal total must match the operational source amount');await enforceVatRecognition(companyId,id,journal.source_type,journal.source_id,client);}const after=(await client.query<Journal>("UPDATE journal_entries SET status='posted',posted_by=$3,posted_at=NOW(),updated_at=NOW() WHERE id=$1 AND company_id=$2 AND status='draft' RETURNING *,accounting_date::text",[id,companyId,actor])).rows[0];if(!after)throw new AccountingConflictError('Journal is already posted');await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'journal.post',entity_type:'journal_entry',entity_id:id,before_data:{status:'draft'},after_data:{status:'posted',posted_by:actor,posted_at:after.posted_at}},client);return after;});}
 async trialBalance(companyId:string,fiscalYearId:string,start:string|undefined,end:string|undefined){const fy=(await this.db.query<{start_date:string;end_date:string}>('SELECT start_date::text,end_date::text FROM fiscal_years WHERE id=$1 AND company_id=$2',[fiscalYearId,companyId])).rows[0];if(!fy)throw new AccountingNotFoundError();const from=start??fy.start_date,to=end??fy.end_date;if(!validDate(from)||!validDate(to)||from>to||from<fy.start_date||to>fy.end_date)throw new AccountingValidationError('Invalid report date range');const rows=(await this.db.query(`SELECT a.id account_id,a.code,a.name,a.account_type,COALESCE(SUM(l.debit),0)::text debit_movement,COALESCE(SUM(l.credit),0)::text credit_movement,GREATEST(COALESCE(SUM(l.debit-l.credit),0),0)::text debit_balance,GREATEST(COALESCE(SUM(l.credit-l.debit),0),0)::text credit_balance FROM accounts a LEFT JOIN (journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.company_id=l.company_id AND j.status='posted' AND j.fiscal_year_id=$2 AND j.accounting_date BETWEEN $3 AND $4) ON a.id=l.account_id AND a.company_id=l.company_id WHERE a.company_id=$1 GROUP BY a.id,a.code,a.name,a.account_type ORDER BY a.code,a.id`,[companyId,fiscalYearId,from,to])).rows;return{fiscal_year_id:fiscalYearId,start_date:from,end_date:to,accounts:rows};}
 async ledger(companyId:string,accountId:string,fiscalYearId:string,start:string|undefined,end:string|undefined){const account=(await this.db.query<Account>('SELECT * FROM accounts WHERE id=$1 AND company_id=$2',[accountId,companyId])).rows[0];if(!account)throw new AccountingNotFoundError();const fy=(await this.db.query<{start_date:string;end_date:string}>('SELECT start_date::text,end_date::text FROM fiscal_years WHERE id=$1 AND company_id=$2',[fiscalYearId,companyId])).rows[0];if(!fy)throw new AccountingNotFoundError();const from=start??fy.start_date,to=end??fy.end_date;if(!validDate(from)||!validDate(to)||from>to||from<fy.start_date||to>fy.end_date)throw new AccountingValidationError('Invalid report date range');const rows=(await this.db.query(`SELECT j.accounting_date::text,j.id journal_id,j.reference,j.description,l.id line_id,l.debit::text,l.credit::text,l.memo,SUM(l.debit-l.credit) OVER(ORDER BY j.accounting_date,j.created_at,j.id,l.sequence,l.id)::text running_balance FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.company_id=l.company_id WHERE l.company_id=$1 AND l.account_id=$2 AND j.fiscal_year_id=$3 AND j.status='posted' AND j.accounting_date BETWEEN $4 AND $5 ORDER BY j.accounting_date,j.created_at,j.id,l.sequence,l.id`,[companyId,accountId,fiscalYearId,from,to])).rows;return{account,fiscal_year_id:fiscalYearId,start_date:from,end_date:to,activity:rows};}
}
function service(res:Response){if(!pool){res.status(503).json({error:'Database unavailable'});return null;}return new AccountingService(pool);}
function handle(error:unknown,res:Response){if(error instanceof VatRecognitionIncompleteError)res.status(400).json({error:error.message,code:VAT_RECOGNITION_ERROR_CODE});else if(error instanceof AccountingValidationError)res.status(400).json({error:error.message});else if(error instanceof AccountingNotFoundError)res.status(404).json({error:'Not found'});else if(error instanceof AccountingConflictError)res.status(409).json({error:error.message});else if(error instanceof AccountingPeriodClosedError)res.status(409).json({error:error.message,code:'ACCOUNTING_PERIOD_CLOSED'});else throw error;}
const base=[requireAuth,requireActiveCompany] as const;
accountingRouter.get('/accounting/operational-sources',...base,requireCapability('accounting.view'),route(async(req,res)=>{try{if(req.query.source_type!==undefined&&typeof req.query.source_type!=='string')throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.json(await s.listOperationalSources(context(req).activeCompanyId,req.query.source_type as string|undefined));}catch(e){handle(e,res);}}));
accountingRouter.get('/accounts',...base,requireCapability('accounting.view'),route(async(req,res)=>{const s=service(res);if(s)res.json(await s.listAccounts(context(req).activeCompanyId));}));
accountingRouter.post('/accounts',requireSameOrigin,...base,requireCapability('accounting.chart.manage'),route(async(req,res)=>{try{const v=accountInput(req.body) as AccountInput|null;if(!v)throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.status(201).json(await s.createAccount(context(req).activeCompanyId,context(req).user.id,{...v,parentId:v.parentId??null,active:v.active??true}));}catch(e){handle(e,res);}}));
accountingRouter.patch('/accounts/:id',requireSameOrigin,...base,requireCapability('accounting.chart.manage'),route(async(req,res)=>{try{const v=accountInput(req.body,true);if(!UUID.test(req.params.id)||!v||!Object.keys(v).length)throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.json(await s.updateAccount(context(req).activeCompanyId,context(req).user.id,req.params.id,v));}catch(e){handle(e,res);}}));
accountingRouter.get('/journals',...base,requireCapability('accounting.view'),route(async(req,res)=>{const s=service(res);if(s)res.json(await s.listJournals(context(req).activeCompanyId));}));
accountingRouter.get('/journals/:id',...base,requireCapability('accounting.view'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new AccountingNotFoundError();const s=service(res);if(s)res.json(await s.readJournal(context(req).activeCompanyId,req.params.id));}catch(e){handle(e,res);}}));
accountingRouter.post('/journals',requireSameOrigin,...base,requireCapability('accounting.journal.manage'),route(async(req,res)=>{try{const v=journalInput(req.body) as JournalInput|null;if(!v)throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.status(201).json(await s.createJournal(context(req).activeCompanyId,context(req).user.id,{...v,reference:v.reference??null,sourceType:v.sourceType??null,sourceId:v.sourceId??null,entryType:v.entryType??'standard'}));}catch(e){handle(e,res);}}));
accountingRouter.patch('/journals/:id',requireSameOrigin,...base,requireCapability('accounting.journal.manage'),route(async(req,res)=>{try{const v=journalInput(req.body,true);if(!UUID.test(req.params.id)||!v||!Object.keys(v).length)throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.json(await s.updateJournal(context(req).activeCompanyId,context(req).user.id,req.params.id,v));}catch(e){handle(e,res);}}));
accountingRouter.put('/journals/:id/lines',requireSameOrigin,...base,requireCapability('accounting.journal.manage'),route(async(req,res)=>{try{const v=linesInput(req.body);if(!UUID.test(req.params.id)||!v)throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.json(await s.replaceLines(context(req).activeCompanyId,context(req).user.id,req.params.id,v));}catch(e){handle(e,res);}}));
accountingRouter.post('/journals/:id/post',requireSameOrigin,...base,requireCapability('accounting.journal.post'),route(async(req,res)=>{try{if(!UUID.test(req.params.id)||Object.keys(req.body??{}).length)throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.json(await s.post(context(req).activeCompanyId,context(req).user.id,req.params.id));}catch(e){handle(e,res);}}));
accountingRouter.get('/trial-balance',...base,requireCapability('accounting.view'),route(async(req,res)=>{try{if(typeof req.query.fiscal_year_id!=='string'||!UUID.test(req.query.fiscal_year_id)||(req.query.start_date!==undefined&&!validDate(req.query.start_date))||(req.query.end_date!==undefined&&!validDate(req.query.end_date)))throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.json(await s.trialBalance(context(req).activeCompanyId,req.query.fiscal_year_id,req.query.start_date as string|undefined,req.query.end_date as string|undefined));}catch(e){handle(e,res);}}));
accountingRouter.get('/general-ledger',...base,requireCapability('accounting.view'),route(async(req,res)=>{try{if(typeof req.query.account_id!=='string'||!UUID.test(req.query.account_id)||typeof req.query.fiscal_year_id!=='string'||!UUID.test(req.query.fiscal_year_id)||(req.query.start_date!==undefined&&!validDate(req.query.start_date))||(req.query.end_date!==undefined&&!validDate(req.query.end_date)))throw new AccountingValidationError('Invalid request');const s=service(res);if(s)res.json(await s.ledger(context(req).activeCompanyId,req.query.account_id,req.query.fiscal_year_id,req.query.start_date as string|undefined,req.query.end_date as string|undefined));}catch(e){handle(e,res);}}));