import { PoolClient } from 'pg';

export const OPERATIONAL_SOURCE_TYPES=['obligation','document_settlement','obligation_settlement','custody_allocation','custody_funding','custody_return','asset_depreciation','asset_disposal'] as const;
export type OperationalSourceType=typeof OPERATIONAL_SOURCE_TYPES[number];
export type JournalOperationalSourceType=OperationalSourceType|'periodic_adjustment';
export type OperationalSource={source_type:JournalOperationalSourceType;source_id:string;accounting_date:string;amount:string;description:string;reference:string|null;context:Record<string,unknown>};
type QueryRunner=Pick<PoolClient,'query'>;

export function isOperationalSourceType(value:string):value is OperationalSourceType{return OPERATIONAL_SOURCE_TYPES.includes(value as OperationalSourceType);}

export function operationalSourceQuery(type:JournalOperationalSourceType){return {
  obligation:`SELECT 'obligation' source_type,o.id source_id,o.recognized_on::text accounting_date,o.original_amount::text amount,('Obligation: '||c.name) description,NULL::text reference,jsonb_build_object('direction',o.direction,'counterparty',c.name,'document_id',o.document_id,'invoice_id',o.invoice_id,'invoice_vat_amount',(SELECT i.vat_amount::text FROM invoices i WHERE i.id=o.invoice_id AND i.company_id=o.company_id)) context FROM obligations o JOIN counterparties c ON c.id=o.counterparty_id AND c.company_id=o.company_id WHERE o.id=$1 AND o.company_id=$2 AND o.verification_status='confirmed' AND NOT o.is_cancelled`,
  document_settlement:`SELECT 'document_settlement' source_type,s.id source_id,t.transaction_date::text accounting_date,s.amount::text,('Document settlement: '||d.original_filename) description,t.bank_reference reference,jsonb_build_object('document_id',d.id,'bank_transaction_id',t.id) context FROM document_settlements s JOIN documents d ON d.id=s.document_id AND d.company_id=s.company_id JOIN bank_transactions t ON t.id=s.bank_transaction_id AND t.company_id=s.company_id WHERE s.id=$1 AND s.company_id=$2`,
  obligation_settlement:`SELECT 'obligation_settlement' source_type,s.id source_id,t.transaction_date::text accounting_date,s.amount::text,('Obligation settlement: '||c.name) description,t.bank_reference reference,jsonb_build_object('obligation_id',o.id,'bank_transaction_id',t.id) context FROM obligation_settlements s JOIN obligations o ON o.id=s.obligation_id AND o.company_id=s.company_id JOIN counterparties c ON c.id=o.counterparty_id AND c.company_id=o.company_id JOIN bank_transactions t ON t.id=s.bank_transaction_id AND t.company_id=s.company_id WHERE s.id=$1 AND s.company_id=$2`,
  custody_allocation:`SELECT 'custody_allocation' source_type,a.id source_id,d.document_date::text accounting_date,a.amount::text,('Custody allocation: '||d.original_filename) description,NULL::text reference,jsonb_build_object('custody_id',a.custody_id,'document_id',d.id) context FROM custody_document_allocations a JOIN documents d ON d.id=a.document_id AND d.company_id=a.company_id WHERE a.id=$1 AND a.company_id=$2 AND d.document_date IS NOT NULL`,
  custody_funding:`SELECT 'custody_funding' source_type,m.id source_id,t.transaction_date::text accounting_date,ABS(t.amount)::text amount,('Custody funding: '||COALESCE(t.description,'')) description,t.bank_reference reference,jsonb_build_object('custody_id',m.custody_id,'bank_transaction_id',t.id) context FROM bank_transaction_matches m JOIN bank_transactions t ON t.id=m.bank_transaction_id AND t.company_id=m.company_id WHERE m.id=$1 AND m.company_id=$2 AND m.match_type='custody_funding'`,
  custody_return:`SELECT 'custody_return' source_type,m.id source_id,t.transaction_date::text accounting_date,ABS(t.amount)::text amount,('Custody return: '||COALESCE(t.description,'')) description,t.bank_reference reference,jsonb_build_object('custody_id',m.custody_id,'bank_transaction_id',t.id) context FROM bank_transaction_matches m JOIN bank_transactions t ON t.id=m.bank_transaction_id AND t.company_id=m.company_id WHERE m.id=$1 AND m.company_id=$2 AND m.match_type='custody_return'`,
  asset_depreciation:`SELECT 'asset_depreciation' source_type,d.id source_id,d.period_end::text accounting_date,d.depreciation_amount::text amount,('Asset depreciation: '||a.asset_number||' '||a.name) description,a.asset_number reference,jsonb_build_object('asset_id',a.id,'asset_number',a.asset_number,'asset_account_id',COALESCE(p.asset_account_id,c.asset_account_id),'depreciation_expense_account_id',COALESCE(p.depreciation_expense_account_id,c.depreciation_expense_account_id),'accumulated_depreciation_account_id',COALESCE(p.accumulated_depreciation_account_id,c.accumulated_depreciation_account_id),'depreciation_policy_version_id',a.depreciation_policy_version_id) context FROM asset_depreciation_entries d JOIN fixed_assets a ON a.id=d.asset_id AND a.company_id=d.company_id JOIN asset_categories c ON c.id=a.asset_category_id AND c.company_id=a.company_id LEFT JOIN asset_category_depreciation_policies p ON p.id=a.depreciation_policy_version_id AND p.company_id=a.company_id WHERE d.id=$1 AND d.company_id=$2 AND d.status='pending' AND d.period_end<=CURRENT_DATE AND a.status IN ('active','fully_depreciated')`,
  asset_disposal:`SELECT 'asset_disposal' source_type,d.id source_id,d.disposal_date::text accounting_date,GREATEST(a.acquisition_cost+GREATEST(-d.calculated_gain_loss,0),a.opening_accumulated_depreciation+COALESCE(pd.total,0)+d.disposal_proceeds+GREATEST(d.calculated_gain_loss,0))::text amount,('Asset disposal: '||a.asset_number||' '||a.name) description,a.asset_number reference,jsonb_build_object('asset_id',a.id,'asset_number',a.asset_number,'asset_account_id',COALESCE(p.asset_account_id,c.asset_account_id),'accumulated_depreciation_account_id',COALESCE(p.accumulated_depreciation_account_id,c.accumulated_depreciation_account_id),'asset_cost',a.acquisition_cost,'accumulated_depreciation',a.opening_accumulated_depreciation+COALESCE(pd.total,0),'proceeds',d.disposal_proceeds,'gain_loss',d.calculated_gain_loss,'sale_document_id',d.source_sale_document_id,'depreciation_policy_version_id',a.depreciation_policy_version_id) context FROM asset_disposals d JOIN fixed_assets a ON a.id=d.asset_id AND a.company_id=d.company_id JOIN asset_categories c ON c.id=a.asset_category_id AND c.company_id=a.company_id LEFT JOIN asset_category_depreciation_policies p ON p.id=a.depreciation_policy_version_id AND p.company_id=a.company_id LEFT JOIN LATERAL (SELECT SUM(depreciation_amount) total FROM asset_depreciation_entries e WHERE e.asset_id=a.id AND e.company_id=a.company_id AND e.status='posted' AND e.period_end<=d.disposal_date) pd ON TRUE WHERE d.id=$1 AND d.company_id=$2 AND a.status='disposed'`,
  periodic_adjustment:`SELECT 'periodic_adjustment' source_type,s.id source_id,s.recognition_date::text accounting_date,s.amount::text,a.description,a.reference,jsonb_build_object('adjustment_id',a.id,'adjustment_type',a.adjustment_type,'balance_account_id',a.balance_account_id,'pnl_account_id',a.pnl_account_id) context FROM periodic_adjustment_schedule s JOIN periodic_adjustments a ON a.id=s.adjustment_id AND a.company_id=s.company_id WHERE s.id=$1 AND s.company_id=$2 AND s.status='pending' AND a.workflow_status='approved'`
}[type];}

function operationalSourceIdsQuery(type:OperationalSourceType){return type==='obligation'?"SELECT id FROM obligations WHERE company_id=$1 AND verification_status='confirmed' AND NOT is_cancelled":type==='document_settlement'?'SELECT id FROM document_settlements WHERE company_id=$1':type==='obligation_settlement'?'SELECT id FROM obligation_settlements WHERE company_id=$1':type==='custody_allocation'?'SELECT a.id FROM custody_document_allocations a JOIN documents d ON d.id=a.document_id AND d.company_id=a.company_id WHERE a.company_id=$1 AND d.document_date IS NOT NULL':type==='asset_depreciation'?"SELECT d.id FROM asset_depreciation_entries d JOIN fixed_assets a ON a.id=d.asset_id AND a.company_id=d.company_id WHERE d.company_id=$1 AND d.status='pending' AND d.period_end<=CURRENT_DATE AND a.status IN ('active','fully_depreciated')":type==='asset_disposal'?"SELECT d.id FROM asset_disposals d JOIN fixed_assets a ON a.id=d.asset_id AND a.company_id=d.company_id WHERE d.company_id=$1 AND a.status='disposed'":`SELECT id FROM bank_transaction_matches WHERE company_id=$1 AND match_type='${type}'`;}

export async function loadOperationalSources(companyId:string,client:QueryRunner,filter?:OperationalSourceType){const sources:OperationalSource[]=[];for(const type of filter?[filter]:OPERATIONAL_SOURCE_TYPES){for(const {id} of (await client.query<{id:string}>(operationalSourceIdsQuery(type),[companyId])).rows){const source=(await client.query<OperationalSource>(operationalSourceQuery(type),[id,companyId])).rows[0];if(source)sources.push(source);}}return sources;}
