import { createHash } from 'node:crypto';
import { Pool, PoolClient } from 'pg';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { AnnualClosingService } from './annual-closing.service';
import { AnnualClosingResponse, PackageManifestSection } from './annual-closing.types';

export class AnnualPackageNotFoundError extends Error {}
export class AnnualPackageConflictError extends Error {}
export class AnnualPackageValidationError extends Error { constructor(message:string, public blockers:string[]=[]){super(message);} }
type Runner=Pool|PoolClient;
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stable(v)}`).join(',')}}`:JSON.stringify(value);
export const fingerprint=(value:unknown)=>createHash('sha256').update(stable(value)).digest('hex');
const criticalSections=['fiscal_year','monthly_close','trial_balance','general_ledger','statement_of_financial_position','profit_or_loss','changes_in_equity','cash_flow','tax_zakat_working_paper','vat_periods_returns','bank_reconciliation','receivables_payables','document_exceptions','partners_ownership','fixed_assets_depreciation','periodic_adjustments','opening_balances'];

export function packageManifest(readiness:AnnualClosingResponse,asOf=new Date().toISOString()):PackageManifestSection[]{
  const domain=(name:string)=>readiness.domains[name]!;
  const specs:Array<[string,string,string|undefined]>=([
    ['fiscal_year','fiscal-years',undefined],['monthly_close','monthly-close','monthly_close'],['trial_balance','accounting','ledger'],['general_ledger','accounting','ledger'],
    ['statement_of_financial_position','financial-statements','ledger'],['profit_or_loss','financial-statements','ledger'],['changes_in_equity','financial-statements','ledger'],['cash_flow','financial-statements','ledger'],
    ['tax_zakat_working_paper','tax-working-papers','zakat'],['vat_periods_returns','vat','vat'],['bank_reconciliation','banking','banking'],['receivables_payables','obligations','receivables_payables'],
    ['document_exceptions','documents','documents'],['partners_ownership','partners','partners'],['fixed_assets_depreciation','fixed-assets','assets'],['periodic_adjustments','periodic-adjustments','adjustments'],['opening_balances','opening-balances','opening_balances'],
  ]);
  return specs.map(([section,source,key])=>{const item=key?domain(key):null;const status=item?.status??'ready';const summary=item?.summary??{fiscal_year_id:readiness.fiscal_year.id,start_date:readiness.fiscal_year.start_date,end_date:readiness.fiscal_year.end_date};const blockers=String(summary.blockers??'').split(',').filter(Boolean);if(item&&item.blocker_count&&!blockers.length)blockers.push(`${section}_not_ready`);const reference={fiscal_year_id:readiness.fiscal_year.id,scope:'annual-summary'};return {section,status,critical:true,blocker_count:item?.blocker_count??0,blockers,source,source_reference:reference,summary,snapshot_as_of:asOf,fingerprint:fingerprint({section,status,blockers,summary,reference})};});
}
export function finalizationBlockers(manifest:PackageManifestSection[]){const bySection=new Map(manifest.map(x=>[x.section,x]));return criticalSections.flatMap(section=>{const item=bySection.get(section);if(!item)return [`${section}:missing`];if(item.status!=='ready')return [`${section}:${item.status}`,...item.blockers.map(x=>`${section}:${x}`)];return [];});}

export class AnnualPackageService{
  private audit=new AuditLogRepository(); constructor(private db:Pool){}
  private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const value=await fn(c);await c.query('COMMIT');return value;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  private async ensureYear(company:string,year:string,r:Runner){if(!(await r.query('SELECT 1 FROM fiscal_years WHERE id=$1 AND company_id=$2',[year,company])).rowCount)throw new AnnualPackageNotFoundError();}
  private async load(company:string,year:string,r:Runner,lock=false){await this.ensureYear(company,year,r);const p=(await r.query<any>(`SELECT *,finalized_at::text,handed_off_at::text,created_at::text,updated_at::text FROM annual_closing_packages WHERE company_id=$1 AND fiscal_year_id=$2${lock?' FOR UPDATE':''}`,[company,year])).rows[0]??null;if(!p)return null;p.snapshots=(await r.query<any>('SELECT *,created_at::text FROM annual_closing_package_snapshots WHERE company_id=$1 AND package_id=$2 AND fiscal_year_id=$3 ORDER BY snapshot_no',[company,p.id,year])).rows;return p;}
  private async live(company:string,year:string,r:Runner){const readiness=await new AnnualClosingService(r).readiness(company,year);const manifest=packageManifest(readiness);return {readiness,manifest,source_fingerprint:fingerprint(manifest.map(({snapshot_as_of,...x})=>x))};}
  async get(company:string,year:string){const packageRow=await this.load(company,year,this.db);if(!packageRow)return {package:null,live:null,drift:false};const live=await this.live(company,year,this.db);const final=packageRow.snapshots.find((x:any)=>x.id===packageRow.final_snapshot_id);return {package:packageRow,live,drift:Boolean(final&&final.source_fingerprint!==live.source_fingerprint)};}
  create(company:string,year:string,actor:string){return this.tx(async c=>{await this.ensureYear(company,year,c);try{const p=(await c.query<any>('INSERT INTO annual_closing_packages(company_id,fiscal_year_id) VALUES($1,$2) RETURNING *',[company,year])).rows[0];await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'annual_package.created',entity_type:'annual_closing_package',entity_id:p.id,before_data:null,after_data:p},c);p.snapshots=[];return p;}catch(e){if((e as {code?:string}).code==='23505')throw new AnnualPackageConflictError('Package already exists');throw e;}});}
  snapshot(company:string,year:string,actor:string,version:number){return this.tx(async c=>{const p=await this.load(company,year,c,true);if(!p)throw new AnnualPackageNotFoundError();if(p.status!=='draft'||p.version!==version)throw new AnnualPackageConflictError('Only the current draft package can be previewed');const live=await this.live(company,year,c);const no=Number((await c.query<{n:string}>('SELECT (COALESCE(MAX(snapshot_no),0)+1)::text n FROM annual_closing_package_snapshots WHERE company_id=$1 AND package_id=$2',[company,p.id])).rows[0]!.n);const s=(await c.query<any>(`INSERT INTO annual_closing_package_snapshots(company_id,package_id,fiscal_year_id,snapshot_no,snapshot_type,manifest,readiness,source_fingerprint,created_by_user_id) VALUES($1,$2,$3,$4,'preview',$5,$6,$7,$8) RETURNING *`,[company,p.id,year,no,JSON.stringify(live.manifest),JSON.stringify(live.readiness),live.source_fingerprint,actor])).rows[0];await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'annual_package.snapshot_created',entity_type:'annual_closing_package_snapshot',entity_id:s.id,before_data:null,after_data:{package_id:p.id,snapshot_no:no,snapshot_type:'preview',source_fingerprint:live.source_fingerprint}},c);return s;});}
  finalize(company:string,year:string,actor:string,version:number){return this.tx(async c=>{const p=await this.load(company,year,c,true);if(!p)throw new AnnualPackageNotFoundError();if(p.status!=='draft'||p.version!==version)throw new AnnualPackageConflictError('Package is not the current draft');const live=await this.live(company,year,c);const blockers=finalizationBlockers(live.manifest);if(blockers.length)throw new AnnualPackageValidationError('Annual package is blocked',blockers);const no=Number((await c.query<{n:string}>('SELECT (COALESCE(MAX(snapshot_no),0)+1)::text n FROM annual_closing_package_snapshots WHERE company_id=$1 AND package_id=$2',[company,p.id])).rows[0]!.n);const s=(await c.query<any>(`INSERT INTO annual_closing_package_snapshots(company_id,package_id,fiscal_year_id,snapshot_no,snapshot_type,manifest,readiness,source_fingerprint,created_by_user_id) VALUES($1,$2,$3,$4,'final',$5,$6,$7,$8) RETURNING *`,[company,p.id,year,no,JSON.stringify(live.manifest),JSON.stringify(live.readiness),live.source_fingerprint,actor])).rows[0];const after=(await c.query<any>(`UPDATE annual_closing_packages SET status='finalized',final_snapshot_id=$3,finalized_by_user_id=$4,finalized_at=NOW(),version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 AND status='draft' AND version=$5 RETURNING *`,[p.id,company,s.id,actor,version])).rows[0];if(!after)throw new AnnualPackageConflictError('Package was modified');await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'annual_package.snapshot_created',entity_type:'annual_closing_package_snapshot',entity_id:s.id,before_data:null,after_data:{package_id:p.id,snapshot_no:no,snapshot_type:'final',source_fingerprint:live.source_fingerprint}},c);await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'annual_package.finalized',entity_type:'annual_closing_package',entity_id:p.id,before_data:{status:p.status,version:p.version},after_data:{status:after.status,version:after.version,final_snapshot_id:s.id}},c);return after;});}
  handoff(company:string,year:string,actor:string,input:{version:number;note:string|null;reference:string|null}){return this.tx(async c=>{const p=await this.load(company,year,c,true);if(!p)throw new AnnualPackageNotFoundError();if(p.status!=='finalized'||p.version!==input.version)throw new AnnualPackageConflictError('Only the current finalized package can be handed off');const after=(await c.query<any>(`UPDATE annual_closing_packages SET status='handed_off',handed_off_by_user_id=$3,handed_off_at=NOW(),handoff_note=$4,handoff_reference=$5,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 AND status='finalized' AND version=$6 RETURNING *`,[p.id,company,actor,input.note,input.reference,input.version])).rows[0];if(!after)throw new AnnualPackageConflictError('Package was modified');await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'annual_package.handed_off',entity_type:'annual_closing_package',entity_id:p.id,before_data:{status:p.status,version:p.version},after_data:{status:after.status,version:after.version,handed_off_at:after.handed_off_at,handoff_note:input.note,handoff_reference:input.reference}},c);return after;});}
}
