import {NextFunction,Request,RequestHandler,Response,Router} from 'express';
import {Pool,PoolClient} from 'pg';
import pool from '../../db/pool';
import {operationalDate} from '../../operational-date';
import {AuditLogRepository} from '../audit-log/audit-log.repository';
import {getAuthenticatedContext,requireActiveCompany,requireAuth,requireCapability} from '../auth/auth.middleware';
import {requireSameOrigin} from '../auth/origin.middleware';
import {AccountingPeriodClosedError,assertAccountingDateWritable} from '../monthly-close/accounting-period.guard';

export const obligationRouter=Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i, MONEY=/^\d{1,16}(?:\.\d{1,2})?$/, DATE=/^\d{4}-\d{2}-\d{2}$/;
class Invalid extends Error{} class NotFound extends Error{} class Conflict extends Error{} class Forbidden extends Error{}
const route=(h:(q:Request,s:Response)=>Promise<void>):RequestHandler=>(q,s,n:NextFunction)=>void h(q,s).catch(n);
const object=(x:unknown):x is Record<string,unknown>=>!!x&&typeof x==='object'&&!Array.isArray(x);
const allowed=(x:unknown,keys:string[])=>object(x)&&Object.keys(x).every(k=>keys.includes(k));
const id=(x:unknown)=>typeof x==='string'&&UUID.test(x)?x:null;
const text=(x:unknown,max:number,required=false)=>{if(x==null&&!required)return null;if(typeof x!=='string')throw new Invalid();const v=x.trim();if((required&&!v)||v.length>max)throw new Invalid();return v||null;};
const date=(x:unknown,nullable=false)=>x==null&&nullable?null:typeof x==='string'&&DATE.test(x)&&!Number.isNaN(Date.parse(x+'T00:00:00Z'))?x:(()=>{throw new Invalid()})();
const amount=(x:unknown)=>{const v=typeof x==='number'?String(x):typeof x==='string'?x.trim():'';if(!MONEY.test(v)||cents(v)<=0n)throw new Invalid();return v;};
const cents=(v:string)=>{const [w,f='']=v.split('.');return BigInt(w)*100n+BigInt((f+'00').slice(0,2));};
const money=(v:bigint)=>`${v/100n}.${(v%100n).toString().padStart(2,'0')}`;
type CP={id:string;company_id:string;name:string;type:string;is_active:boolean;version:number};
type OB={id:string;company_id:string;direction:string;counterparty_id:string;document_id:string|null;original_amount:string;recognized_on:string;due_on:string|null;verification_status:string;source_type:string;source_note:string|null;is_cancelled:boolean;version:number};
export class ObligationService{private audit=new AuditLogRepository();constructor(private db:Pool){}private async tx<T>(f:(c:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const x=await f(c);await c.query('COMMIT');return x;}catch(e){await c.query('ROLLBACK');const code=(e as {code?:string}).code;if(code==='23505')throw new Conflict();if(code==='23503')throw new NotFound();if(code?.startsWith('23'))throw new Invalid();throw e;}finally{c.release();}}
 async counterparties(company:string){return{counterparties:(await this.db.query<CP>('SELECT * FROM counterparties WHERE company_id=$1 ORDER BY is_active DESC,name',[company])).rows};}
 async createCounterparty(company:string,actor:string,name:string,type:string){return this.tx(async c=>{const p=(await c.query<CP>('INSERT INTO counterparties(company_id,name,type,created_by_user_id) VALUES($1,$2,$3,$4) RETURNING *',[company,name,type,actor])).rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'counterparty.create',entity_type:'counterparty',entity_id:p.id,before_data:null,after_data:p as never},c);return p;});}
 async updateCounterparty(company:string,actor:string,cid:string,b:Record<string,unknown>){return this.tx(async c=>{const before=(await c.query<CP>('SELECT * FROM counterparties WHERE id=$1 AND company_id=$2 FOR UPDATE',[cid,company])).rows[0];if(!before)throw new NotFound();if(before.version!==b.version)throw new Conflict();const after=(await c.query<CP>('UPDATE counterparties SET name=$3,type=$4,is_active=$5,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *',[cid,company,b.name??before.name,b.type??before.type,b.is_active??before.is_active])).rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:before.is_active&&!after.is_active?'counterparty.disable':'counterparty.update',entity_type:'counterparty',entity_id:cid,before_data:before as never,after_data:after as never},c);return after;});}
 async list(company:string){const rows=(await this.db.query(`SELECT o.*,o.original_amount::text,o.recognized_on::text,o.due_on::text,c.name counterparty_name,c.type counterparty_type,d.original_filename,d.status document_status,
 CASE WHEN o.source_type='document' THEN COALESCE((SELECT SUM(s.amount) FROM document_settlements s WHERE s.document_id=o.document_id AND s.company_id=o.company_id),0) ELSE COALESCE((SELECT SUM(s.amount) FROM obligation_settlements s WHERE s.obligation_id=o.id AND s.company_id=o.company_id),0) END::text settled_amount
 FROM obligations o JOIN counterparties c ON c.id=o.counterparty_id AND c.company_id=o.company_id LEFT JOIN documents d ON d.id=o.document_id AND d.company_id=o.company_id WHERE o.company_id=$1 ORDER BY o.recognized_on DESC,o.created_at DESC`,[company])).rows as Array<OB&Record<string,unknown>&{settled_amount:string}>;const [directHistory,documentHistory,eligible]=await Promise.all([this.db.query('SELECT s.*,s.amount::text,t.transaction_date::text,t.description FROM obligation_settlements s JOIN bank_transactions t ON t.id=s.bank_transaction_id AND t.company_id=s.company_id WHERE s.company_id=$1 ORDER BY s.created_at DESC',[company]),this.db.query('SELECT s.*,s.amount::text,t.transaction_date::text,t.description FROM document_settlements s JOIN bank_transactions t ON t.id=s.bank_transaction_id AND t.company_id=s.company_id WHERE s.company_id=$1 ORDER BY s.created_at DESC',[company]),this.db.query("SELECT d.id,d.original_filename,d.total_amount::text,d.counterparty_id FROM documents d WHERE d.company_id=$1 AND d.status='approved' AND d.total_amount IS NOT NULL AND d.counterparty_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM obligations o WHERE o.document_id=d.id AND o.company_id=d.company_id) ORDER BY d.created_at DESC",[company])]);const today=operationalDate();const obligations=rows.map(o=>{const remaining=cents(o.original_amount)-cents(o.settled_amount);return{...o,settlement_history:o.source_type==='document'?documentHistory.rows.filter(s=>s.document_id===o.document_id):directHistory.rows.filter(s=>s.obligation_id===o.id),remaining_amount:money(remaining),state:cents(o.settled_amount)===0n?'open':remaining===0n?'settled':'partial',is_overdue:!!o.due_on&&o.due_on<today&&remaining>0n&&!o.is_cancelled};});const active=obligations.filter(o=>!o.is_cancelled),confirmed=active.filter(o=>o.verification_status==='confirmed'),unconfirmed=active.filter(o=>o.verification_status==='unconfirmed');return{obligations,eligible_documents:eligible.rows,summary:{open_receivables:money(confirmed.filter(o=>o.direction==='receivable').reduce((n,o)=>n+cents(o.remaining_amount),0n)),open_payables:money(confirmed.filter(o=>o.direction==='payable').reduce((n,o)=>n+cents(o.remaining_amount),0n)),unconfirmed_receivables:money(unconfirmed.filter(o=>o.direction==='receivable').reduce((n,o)=>n+cents(o.remaining_amount),0n)),unconfirmed_payables:money(unconfirmed.filter(o=>o.direction==='payable').reduce((n,o)=>n+cents(o.remaining_amount),0n)),unconfirmed_count:unconfirmed.length,partially_settled_count:active.filter(o=>o.state==='partial').length,overdue_count:active.filter(o=>o.is_overdue).length}};}
 async createObligation(company:string,actor:string,b:Record<string,unknown>){return this.tx(async c=>{await assertAccountingDateWritable(company,String(b.recognized_on),c);const cp=(await c.query<{type?:string}>('SELECT type FROM counterparties WHERE id=$1 AND company_id=$2',[b.counterparty_id,company])).rows[0];if(!cp)throw new NotFound();if(b.source_type==='opening_balance'&&!(await c.query('SELECT 1 FROM fiscal_years WHERE company_id=$1 AND start_date=$2',[company,b.recognized_on])).rowCount)throw new Conflict();if(b.source_type==='document'){const d=(await c.query<{status:string;document_type:string|null;document_date:string|null;total_amount:string|null;counterparty_id:string|null}>('SELECT status,document_type,document_date::text,total_amount::text,counterparty_id FROM documents WHERE id=$1 AND company_id=$2 FOR UPDATE',[b.document_id,company])).rows[0];if(!d)throw new NotFound();const expectedDirection=d.document_type==='sale'?'receivable':d.document_type==='purchase'||d.document_type==='expense'?'payable':null;const expectedCounterpartyType=d.document_type==='sale'?'customer':d.document_type==='purchase'||d.document_type==='expense'?'supplier':null;if(d.status!=='approved'||!expectedDirection||!expectedCounterpartyType||b.direction!==expectedDirection||(cp.type!==undefined&&cp.type!==expectedCounterpartyType)||!d.document_date||b.recognized_on!==d.document_date||d.total_amount===null||cents(d.total_amount)!==cents(String(b.original_amount))||d.counterparty_id===null||d.counterparty_id!==b.counterparty_id)throw new Conflict();if((await c.query('SELECT 1 FROM custody_document_allocations WHERE document_id=$1 AND company_id=$2',[b.document_id,company])).rowCount)throw new Conflict();}const o=(await c.query<OB>('INSERT INTO obligations(company_id,direction,counterparty_id,document_id,original_amount,recognized_on,due_on,verification_status,source_type,source_note,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *,original_amount::text,recognized_on::text,due_on::text',[company,b.direction,b.counterparty_id,b.document_id,b.original_amount,b.recognized_on,b.due_on,b.verification_status,b.source_type,b.source_note,actor])).rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'obligation.create',entity_type:'obligation',entity_id:o.id,before_data:null,after_data:o as never},c);return o;});}
 async updateObligation(company:string,actor:string,oid:string,b:Record<string,unknown>,canConfirm=false){return this.tx(async c=>{const before=(await c.query<OB>('SELECT *,original_amount::text,recognized_on::text,due_on::text FROM obligations WHERE id=$1 AND company_id=$2 FOR UPDATE',[oid,company])).rows[0];if(!before)throw new NotFound();await assertAccountingDateWritable(company,before.recognized_on,c);if(before.version!==b.version)throw new Conflict();const changesVerification=b.verification_status!==undefined&&b.verification_status!==before.verification_status;if(changesVerification&&!canConfirm)throw new Forbidden();if(before.verification_status==='confirmed'&&b.verification_status==='unconfirmed'&&!text(b.reason,500,true))throw new Invalid();if(before.source_type==='document'&&b.original_amount!==undefined&&cents(String(b.original_amount))!==cents(before.original_amount))throw new Conflict();const settled=cents((await c.query<{x:string}>(`SELECT COALESCE(SUM(amount),0)::text x FROM ${before.source_type==='document'?'document_settlements WHERE document_id':'obligation_settlements WHERE obligation_id'}=$1 AND company_id=$2`,[before.document_id??oid,company])).rows[0]!.x);if(b.is_cancelled===true&&(!text(b.reason,500,true)||settled>0n))throw settled>0n?new Conflict():new Invalid();if(before.verification_status==='confirmed'&&b.original_amount!==undefined&&cents(String(b.original_amount))!==cents(before.original_amount)&&!text(b.reason,500,true))throw new Invalid();const original=String(b.original_amount??before.original_amount);if(cents(original)<settled)throw new Conflict();const after=(await c.query<OB>('UPDATE obligations SET original_amount=$3,due_on=$4,verification_status=$5,source_note=$6,is_cancelled=$7,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *,original_amount::text,recognized_on::text,due_on::text',[oid,company,original,b.due_on===undefined?before.due_on:b.due_on,b.verification_status??before.verification_status,b.source_note===undefined?before.source_note:b.source_note,b.is_cancelled??before.is_cancelled])).rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:!before.is_cancelled&&after.is_cancelled?'obligation.cancel':'obligation.update',entity_type:'obligation',entity_id:oid,before_data:before as never,after_data:after as never,reason:text(b.reason,500)},c);return after;});}
 async settle(company:string,actor:string,oid:string,bank:string,value:string,note:string|null){return this.tx(async c=>{const o=(await c.query<OB>('SELECT *,original_amount::text FROM obligations WHERE id=$1 AND company_id=$2 FOR UPDATE',[oid,company])).rows[0];if(!o)throw new NotFound();if(o.source_type==='document'||o.is_cancelled)throw new Conflict();const bankTx=(await c.query<{amount:string;transaction_date:string}>('SELECT amount::text,transaction_date::text FROM bank_transactions WHERE id=$1 AND company_id=$2 FOR UPDATE',[bank,company])).rows[0];if(!bankTx)throw new NotFound();await assertAccountingDateWritable(company,bankTx.transaction_date,c);const bankCents=cents(bankTx.amount);if((o.direction==='receivable'&&bankCents<=0n)||(o.direction==='payable'&&bankCents>=0n)||cents(value)!==(bankCents<0n?-bankCents:bankCents))throw new Conflict();if((await c.query('SELECT 1 FROM bank_transaction_matches WHERE bank_transaction_id=$1 UNION ALL SELECT 1 FROM document_settlements WHERE bank_transaction_id=$1 UNION ALL SELECT 1 FROM obligation_settlements WHERE bank_transaction_id=$1',[bank])).rowCount)throw new Conflict();const prior=(await c.query<{x:string}>('SELECT COALESCE(SUM(amount),0)::text x FROM obligation_settlements WHERE obligation_id=$1 AND company_id=$2',[oid,company])).rows[0]!.x;if(cents(prior)+cents(value)>cents(o.original_amount))throw new Conflict();const s=(await c.query('INSERT INTO obligation_settlements(company_id,obligation_id,bank_transaction_id,amount,created_by_user_id,note) VALUES($1,$2,$3,$4,$5,$6) RETURNING *,amount::text',[company,oid,bank,value,actor,note])).rows[0];await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'obligation_settlement.create',entity_type:'obligation_settlement',entity_id:s.id,before_data:{settled_amount:prior},after_data:s},c);return s;});}
 async remove(company:string,actor:string,oid:string,sid:string,reason:string){return this.tx(async c=>{const o=await c.query('SELECT 1 FROM obligations WHERE id=$1 AND company_id=$2 FOR UPDATE',[oid,company]);if(!o.rowCount)throw new NotFound();const s=(await c.query('SELECT s.*,s.amount::text,t.transaction_date::text FROM obligation_settlements s JOIN bank_transactions t ON t.id=s.bank_transaction_id AND t.company_id=s.company_id WHERE s.id=$1 AND s.obligation_id=$2 AND s.company_id=$3 FOR UPDATE OF s',[sid,oid,company])).rows[0];if(!s)throw new NotFound();await assertAccountingDateWritable(company,String(s.transaction_date),c);await c.query('DELETE FROM obligation_settlements WHERE id=$1 AND obligation_id=$2 AND company_id=$3',[sid,oid,company]);await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'obligation_settlement.remove',entity_type:'obligation_settlement',entity_id:sid,before_data:s,after_data:null,reason},c);});}}
const read=[requireAuth,requireActiveCompany,requireCapability('obligation.view')],write=[requireSameOrigin,requireAuth,requireActiveCompany];
const requireAll=(capabilities:(q:Request)=>string[]):RequestHandler=>(q,s,n)=>{const auth=getAuthenticatedContext(q);if(!auth||!auth.activeCompanyId||capabilities(q).some(capability=>!auth.capabilities.includes(capability))){s.status(403).json({error:'Forbidden'});return;}n();};
const counterpartyPatchCapabilities=(q:Request)=>{const b=object(q.body)?q.body:{};const capabilities:string[]=[];if('name'in b||'type'in b||b.is_active===true)capabilities.push('counterparty.edit');if(b.is_active===false)capabilities.push('counterparty.disable');return capabilities;};
const obligationCreateCapabilities=(q:Request)=>['obligation.create',...(object(q.body)&&q.body.verification_status==='confirmed'?['obligation.confirm']:[])];
const obligationPatchCapabilities=(q:Request)=>{const b=object(q.body)?q.body:{};const capabilities:string[]=[];if(['original_amount','due_on','source_note'].some(key=>key in b)||b.is_cancelled===false)capabilities.push('obligation.edit');if('verification_status'in b)capabilities.push('obligation.confirm');if(b.is_cancelled===true)capabilities.push('obligation.cancel');return capabilities;};
const context=(q:Request)=>getAuthenticatedContext(q)! as ReturnType<typeof getAuthenticatedContext>&{activeCompanyId:string};const service=(s:Response)=>pool?new ObligationService(pool):(s.status(503).json({ error: 'Database unavailable', code: 'DB_UNAVAILABLE' }),null);const err=(e:unknown,s:Response)=>{if(e instanceof AccountingPeriodClosedError)s.status(409).json({error:e.message,code:'ACCOUNTING_PERIOD_CLOSED'});else if(e instanceof Forbidden)s.status(403).json({error:'Forbidden'});else if(e instanceof Invalid)s.status(400).json({error:'Invalid request'});else if(e instanceof NotFound)s.status(404).json({error:'Not found'});else if(e instanceof Conflict)s.status(409).json({error:'Conflict'});else throw e;};
obligationRouter.get('/counterparties',...read,route(async(q,s)=>{const v=service(s);if(v)s.json(await v.counterparties(context(q).activeCompanyId));}));
obligationRouter.post('/counterparties',...write,requireCapability('counterparty.create'),route(async(q,s)=>{try{if(!allowed(q.body,['name','type']))throw new Invalid();const b=q.body as Record<string,unknown>,n=text(b.name,200,true),t=b.type;if(!['customer','supplier','government','other'].includes(String(t)))throw new Invalid();const v=service(s);if(v)s.status(201).json(await v.createCounterparty(context(q).activeCompanyId,context(q).user.id,n!,String(t)));}catch(e){err(e,s);}}));
obligationRouter.patch('/counterparties/:id',...write,requireAll(counterpartyPatchCapabilities),route(async(q,s)=>{try{const cid=id(q.params.id),b=q.body;if(!cid||!allowed(b,['name','type','is_active','version'])||!Number.isInteger(b.version)||(!('name'in b)&&!('type'in b)&&!('is_active'in b)))throw new Invalid();if('name'in b)text(b.name,200,true);if('type'in b&&!['customer','supplier','government','other'].includes(String(b.type)))throw new Invalid();if('is_active'in b&&typeof b.is_active!=='boolean')throw new Invalid();const v=service(s);if(v)s.json(await v.updateCounterparty(context(q).activeCompanyId,context(q).user.id,cid,b));}catch(e){err(e,s);}}));
obligationRouter.get('/obligations',...read,route(async(q,s)=>{const v=service(s);if(v)s.json(await v.list(context(q).activeCompanyId));}));
obligationRouter.post('/obligations',...write,requireAll(obligationCreateCapabilities),route(async(q,s)=>{try{const keys=['direction','counterparty_id','document_id','original_amount','recognized_on','due_on','verification_status','source_type','source_note'];if(!allowed(q.body,keys))throw new Invalid();const b=q.body as Record<string,unknown>;if(!['receivable','payable'].includes(String(b.direction))||!id(b.counterparty_id)||!['unconfirmed','confirmed'].includes(String(b.verification_status))||!['document','opening_balance','manual'].includes(String(b.source_type)))throw new Invalid();b.original_amount=amount(b.original_amount);b.recognized_on=date(b.recognized_on);b.due_on=date(b.due_on,true);b.source_note=text(b.source_note,1000);b.document_id=b.document_id==null?null:id(b.document_id);if((b.source_type==='document')!==!!b.document_id||b.due_on&&String(b.due_on)<String(b.recognized_on))throw new Invalid();if(b.verification_status==='confirmed'&&!context(q).capabilities.includes('obligation.confirm'))throw new Forbidden();const v=service(s);if(v)s.status(201).json(await v.createObligation(context(q).activeCompanyId,context(q).user.id,b));}catch(e){err(e,s);}}));
obligationRouter.patch('/obligations/:id',...write,requireAll(obligationPatchCapabilities),route(async(q,s)=>{try{const oid=id(q.params.id),b=q.body;const mutationKeys=['original_amount','due_on','verification_status','source_note','is_cancelled'];if(!oid||!allowed(b,[...mutationKeys,'version','reason'])||!Number.isInteger(b.version)||!mutationKeys.some(key=>key in b))throw new Invalid();if('original_amount'in b)b.original_amount=amount(b.original_amount);if('due_on'in b)b.due_on=date(b.due_on,true);if('verification_status'in b&&!['unconfirmed','confirmed'].includes(String(b.verification_status)))throw new Invalid();if('source_note'in b)b.source_note=text(b.source_note,1000);if('is_cancelled'in b&&typeof b.is_cancelled!=='boolean')throw new Invalid();const v=service(s);if(v)s.json(await v.updateObligation(context(q).activeCompanyId,context(q).user.id,oid,b,context(q).capabilities.includes('obligation.confirm')));}catch(e){err(e,s);}}));
obligationRouter.post('/obligations/:id/settlements',...write,requireCapability('obligation.settlement.create'),route(async(q,s)=>{try{const oid=id(q.params.id);if(!oid||!allowed(q.body,['bank_transaction_id','amount','note']))throw new Invalid();const b=q.body as Record<string,unknown>,bank=id(b.bank_transaction_id),value=amount(b.amount),note=text(b.note,500);if(!bank)throw new Invalid();const v=service(s);if(v)s.status(201).json(await v.settle(context(q).activeCompanyId,context(q).user.id,oid,bank,value,note));}catch(e){err(e,s);}}));
obligationRouter.delete('/obligations/:id/settlements/:settlementId',...write,requireCapability('obligation.settlement.remove'),route(async(q,s)=>{try{const oid=id(q.params.id),sid=id(q.params.settlementId);if(!oid||!sid||!allowed(q.body,['reason']))throw new Invalid();const reason=text((q.body as Record<string,unknown>).reason,500,true)!;const v=service(s);if(v){await v.remove(context(q).activeCompanyId,context(q).user.id,oid,sid,reason);s.status(204).end();}}catch(e){err(e,s);}}));
