import { NextFunction, Request, RequestHandler, Response, Router } from 'express';
import { Pool, PoolClient } from 'pg';
import pool from '../../db/pool';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { getAuthenticatedContext, requireActiveCompany, requireAuth, requireCapability } from '../auth/auth.middleware';
import { requireSameOrigin } from '../auth/origin.middleware';
import { AccountingPeriodClosedError, assertAccountingDateWritable } from '../monthly-close/accounting-period.guard';
import { AuthSessionContext } from '../auth/session.service';

export const custodyRouter = Router();

const VIEW='custody.view'; const MANAGE='custody.manage'; const CLOSE='custody.close';
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const AMOUNT_RE=/^\d{1,16}(?:\.\d{1,2})?$/;
type ActiveContext=AuthSessionContext&{activeCompanyId:string};
type Custody={id:string;company_id:string;holder_user_id:string;purpose:string|null;status:'open'|'closed';created_by_user_id:string;created_at:Date;closed_by_user_id:string|null;closed_at:Date|null};
type Tx={id:string;company_id:string;amount:string;currency_code:string;transaction_date:string;description:string|null;bank_reference:string|null;reconciliation_status:'unmatched'|'matched'|'reconciled'};
type Allocation={id:string;company_id:string;custody_id:string;document_id:string;amount:string;created_by_user_id:string;created_at:Date;note:string|null;original_filename?:string;total_amount?:string|null};
type ReturnView={bank_transaction_id:string;amount:string;currency_code:string;transaction_date:string;description:string|null;bank_reference:string|null;reconciliation_status:string;matched_at:Date;note:string|null};

class NotFoundError extends Error{} class ConflictError extends Error{} class ValidationError extends Error{}
function asyncRoute(handler:(req:Request,res:Response,next:NextFunction)=>Promise<void>):RequestHandler{return(req,res,next)=>void handler(req,res,next).catch(next);}
function context(req:Request,res:Response):ActiveContext|null{const c=getAuthenticatedContext(req);if(!c?.activeCompanyId){res.status(403).json({error:'No active company'});return null;}return c as ActiveContext;}
function service(res:Response):CustodyService|null{if(!pool){res.status(503).json({error:'Database unavailable'});return null;}return new CustodyService(pool);}
function id(v:unknown){return typeof v==='string'&&UUID_RE.test(v)?v:null;}
function note(v:unknown,max=500):string|null|undefined{if(v===undefined||v===null)return null;if(typeof v!=='string')return undefined;const x=v.trim();return x&&x.length<=max?x:null;}
function amount(v:unknown):string|null{const x=typeof v==='string'?v.trim():typeof v==='number'?String(v):'';return AMOUNT_RE.test(x)&&toCents(x)>0n?x:null;}
function toCents(v:string):bigint{const neg=v.startsWith('-');const raw=neg?v.slice(1):v;const[w,f='']=raw.split('.');const n=BigInt(w)*100n+BigInt((f+'00').slice(0,2));return neg?-n:n;}
function money(v:bigint):string{const neg=v<0n;const a=neg?-v:v;return `${neg?'-':''}${a/100n}.${(a%100n).toString().padStart(2,'0')}`;}
function reasonBody(body:unknown):string|null{if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;if(Object.keys(x).length!==1||typeof x.reason!=='string')return null;const r=x.reason.trim();return r&&r.length<=500?r:null;}

class Repo{
 constructor(private db:Pool){}
 async custody(custodyId:string,companyId:string,client?:PoolClient,lock=false){const q=client??this.db;const{rows}=await q.query<Custody>(`SELECT * FROM custody_advances WHERE id=$1 AND company_id=$2${lock?' FOR UPDATE':''}`,[custodyId,companyId]);return rows[0]??null;}
 async list(companyId:string){const{rows}=await this.db.query<Custody>('SELECT * FROM custody_advances WHERE company_id=$1 ORDER BY created_at DESC',[companyId]);return rows;}
 async txRow(txId:string,companyId:string,client:PoolClient,lock=false){const{rows}=await client.query<Tx>(`SELECT id,company_id,amount::text,currency_code,transaction_date::text,description,bank_reference,reconciliation_status FROM bank_transactions WHERE id=$1 AND company_id=$2${lock?' FOR UPDATE':''}`,[txId,companyId]);return rows[0]??null;}
 async match(txId:string,companyId:string,client:PoolClient){const{rows}=await client.query<{id:string;match_type:string;custody_id:string|null;document_id:string|null}>('SELECT id,match_type,custody_id,document_id FROM bank_transaction_matches WHERE bank_transaction_id=$1 AND company_id=$2',[txId,companyId]);return rows[0]??null;}
 async funding(custodyId:string,companyId:string,client?:PoolClient){const q=client??this.db;const{rows}=await q.query<Tx>(`SELECT t.id,t.company_id,t.amount::text,t.currency_code,t.transaction_date::text,t.description,t.bank_reference,t.reconciliation_status FROM bank_transaction_matches m JOIN bank_transactions t ON t.id=m.bank_transaction_id AND t.company_id=m.company_id WHERE m.custody_id=$1 AND m.company_id=$2 AND m.match_type='custody_funding'`,[custodyId,companyId]);return rows[0]??null;}
 async returns(custodyId:string,companyId:string,client?:PoolClient){const q=client??this.db;const{rows}=await q.query<ReturnView>(`SELECT t.id AS bank_transaction_id,t.amount::text,t.currency_code,t.transaction_date::text,t.description,t.bank_reference,t.reconciliation_status,m.matched_at,m.note FROM bank_transaction_matches m JOIN bank_transactions t ON t.id=m.bank_transaction_id AND t.company_id=m.company_id WHERE m.custody_id=$1 AND m.company_id=$2 AND m.match_type='custody_return' ORDER BY m.matched_at DESC`,[custodyId,companyId]);return rows;}
 async allocations(custodyId:string,companyId:string,client?:PoolClient){const q=client??this.db;const{rows}=await q.query<Allocation>(`SELECT a.*,d.original_filename,d.total_amount::text FROM custody_document_allocations a JOIN documents d ON d.id=a.document_id AND d.company_id=a.company_id WHERE a.custody_id=$1 AND a.company_id=$2 ORDER BY a.created_at DESC`,[custodyId,companyId]);return rows;}
 async allocatedTotal(custodyId:string,companyId:string,client?:PoolClient){const q=client??this.db;const{rows}=await q.query<{total:string}>('SELECT COALESCE(SUM(amount),0)::text AS total FROM custody_document_allocations WHERE custody_id=$1 AND company_id=$2',[custodyId,companyId]);return rows[0]?.total??'0';}
 async returnedTotal(custodyId:string,companyId:string,client?:PoolClient){const q=client??this.db;const{rows}=await q.query<{total:string}>(`SELECT COALESCE(SUM(t.amount),0)::text AS total FROM bank_transaction_matches m JOIN bank_transactions t ON t.id=m.bank_transaction_id AND t.company_id=m.company_id WHERE m.custody_id=$1 AND m.company_id=$2 AND m.match_type='custody_return'`,[custodyId,companyId]);return rows[0]?.total??'0';}
 async document(documentId:string,companyId:string,client:PoolClient,lock=false){const{rows}=await client.query<{id:string;status:string;total_amount:string|null;original_filename:string;document_date:string|null}>(`SELECT id,status,total_amount::text,original_filename,document_date::text FROM documents WHERE id=$1 AND company_id=$2${lock?' FOR UPDATE':''}`,[documentId,companyId]);return rows[0]??null;}
 async documentFunding(documentId:string,companyId:string,client:PoolClient){const [settled,allocated]=await Promise.all([client.query<{id:string}>('SELECT id FROM document_settlements WHERE document_id=$1 AND company_id=$2 LIMIT 1',[documentId,companyId]),client.query<{id:string}>('SELECT id FROM custody_document_allocations WHERE document_id=$1 AND company_id=$2 LIMIT 1',[documentId,companyId])]);return settled.rows[0]??allocated.rows[0]??null;}
 async allocation(allocationId:string,custodyId:string,companyId:string,client:PoolClient,lock=false){const{rows}=await client.query<Allocation>(`SELECT * FROM custody_document_allocations WHERE id=$1 AND custody_id=$2 AND company_id=$3${lock?' FOR UPDATE':''}`,[allocationId,custodyId,companyId]);return rows[0]??null;}
 async insertCustody(companyId:string,holder:string,purpose:string|null,client:PoolClient){const{rows}=await client.query<Custody>('INSERT INTO custody_advances(company_id,holder_user_id,purpose,created_by_user_id) VALUES($1,$2,$3,$2) RETURNING *',[companyId,holder,purpose]);return rows[0]!;}
 async insertMatch(companyId:string,txId:string,custodyId:string,type:'custody_funding'|'custody_return',actor:string,noteValue:string|null,client:PoolClient){await client.query(`INSERT INTO bank_transaction_matches(company_id,bank_transaction_id,document_id,custody_id,match_type,matched_by_user_id,note) VALUES($1,$2,NULL,$3,$4,$5,$6)`,[companyId,txId,custodyId,type,actor,noteValue]);await client.query("UPDATE bank_transactions SET reconciliation_status='matched',reconciled_by_user_id=NULL,reconciled_at=NULL WHERE id=$1 AND company_id=$2",[txId,companyId]);}
 async insertAllocation(companyId:string,custodyId:string,documentId:string,amountValue:string,actor:string,noteValue:string|null,client:PoolClient){const{rows}=await client.query<Allocation>('INSERT INTO custody_document_allocations(company_id,custody_id,document_id,amount,created_by_user_id,note) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[companyId,custodyId,documentId,amountValue,actor,noteValue]);return rows[0]!;}
}

export class CustodyService{
 private repo:Repo;private audit=new AuditLogRepository();constructor(private db:Pool){this.repo=new Repo(db);}
 private async run<T>(fn:(c:PoolClient)=>Promise<T>):Promise<T>{const c=await this.db.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 private async summaryOf(custody:Custody,companyId:string,client?:PoolClient){const funding=await this.repo.funding(custody.id,companyId,client);if(!funding)throw new ConflictError('Custody funding transaction is missing');const [allocations,returns,allocatedRaw,returnedRaw]=await Promise.all([this.repo.allocations(custody.id,companyId,client),this.repo.returns(custody.id,companyId,client),this.repo.allocatedTotal(custody.id,companyId,client),this.repo.returnedTotal(custody.id,companyId,client)]);const funded=-toCents(funding.amount);const allocated=toCents(allocatedRaw);const returned=toCents(returnedRaw);const remaining=funded-allocated-returned;if(remaining<0n)throw new ConflictError('Custody balances are inconsistent');return{custody,funding_transaction:funding,funded_amount:money(funded),allocated_amount:money(allocated),returned_amount:money(returned),remaining_amount:money(remaining),derived_status:custody.status==='closed'?'closed':remaining===0n?'ready_to_close':allocated>0n||returned>0n?'partially_settled':'open',allocations,returns};}
 async list(companyId:string){const rows=await this.repo.list(companyId);return{custodies:await Promise.all(rows.map(x=>this.summaryOf(x,companyId)))};}
 async detail(custodyId:string,companyId:string){const x=await this.repo.custody(custodyId,companyId);if(!x)throw new NotFoundError('Custody not found');return this.summaryOf(x,companyId);}
 async create(companyId:string,actor:string,txId:string,purpose:string|null){return this.run(async c=>{const tx=await this.repo.txRow(txId,companyId,c,true);if(!tx)throw new NotFoundError('Bank transaction not found');await assertAccountingDateWritable(companyId,tx.transaction_date,c);if(tx.reconciliation_status!=='unmatched'||await this.repo.match(txId,companyId,c))throw new ConflictError('Bank transaction is already matched');if(toCents(tx.amount)>=0n)throw new ConflictError('Custody funding requires an outbound bank transaction');const custody=await this.repo.insertCustody(companyId,actor,purpose,c);await this.repo.insertMatch(companyId,txId,custody.id,'custody_funding',actor,purpose,c);await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'custody.create',entity_type:'custody',entity_id:custody.id,before_data:null,after_data:{holder_user_id:actor,funding_bank_transaction_id:txId,funded_amount:money(-toCents(tx.amount)),purpose}},c);return this.summaryOf(custody,companyId,c);}).catch(e=>{if((e as{code?:string}).code==='23505')throw new ConflictError('Bank transaction is already matched');throw e;});}
 async allocate(custodyId:string,companyId:string,actor:string,documentId:string,amountValue:string,noteValue:string|null){return this.run(async c=>{const custody=await this.repo.custody(custodyId,companyId,c,true);if(!custody)throw new NotFoundError('Custody not found');if(custody.status!=='open')throw new ConflictError('Custody is closed');const doc=await this.repo.document(documentId,companyId,c,true);if(!doc)throw new NotFoundError('Document not found');if(doc.document_date)await assertAccountingDateWritable(companyId,doc.document_date,c);if(doc.status!=='approved'||doc.total_amount===null)throw new ConflictError('Document must be approved with a total amount');if(await this.repo.documentFunding(documentId,companyId,c))throw new ConflictError('Document already has a funding source');const before=await this.summaryOf(custody,companyId,c);const requested=toCents(amountValue);if(requested!==toCents(doc.total_amount))throw new ConflictError('Custody allocation must equal document total in this phase');if(requested>toCents(before.remaining_amount))throw new ConflictError('Allocation exceeds custody remaining amount');const allocation=await this.repo.insertAllocation(companyId,custodyId,documentId,amountValue,actor,noteValue,c);await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'custody.document.allocate',entity_type:'custody',entity_id:custodyId,before_data:{remaining_amount:before.remaining_amount},after_data:{document_id:documentId,allocation_id:allocation.id,amount:amountValue,note:noteValue}},c);return this.summaryOf(custody,companyId,c);}).catch(e=>{if((e as{code?:string}).code==='23505')throw new ConflictError('Document already has a funding source');throw e;});}
 async removeAllocation(custodyId:string,allocationId:string,companyId:string,actor:string,reason:string){return this.run(async c=>{const custody=await this.repo.custody(custodyId,companyId,c,true);if(!custody)throw new NotFoundError('Custody not found');if(custody.status!=='open')throw new ConflictError('Custody is closed');const a=await this.repo.allocation(allocationId,custodyId,companyId,c,true);if(!a)throw new NotFoundError('Allocation not found');const doc=await this.repo.document(a.document_id,companyId,c,true);if(doc?.document_date)await assertAccountingDateWritable(companyId,doc.document_date,c);await c.query('DELETE FROM custody_document_allocations WHERE id=$1 AND custody_id=$2 AND company_id=$3',[allocationId,custodyId,companyId]);await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'custody.document.remove',entity_type:'custody',entity_id:custodyId,before_data:{allocation_id:a.id,document_id:a.document_id,amount:a.amount},after_data:{reason}},c);return this.summaryOf(custody,companyId,c);});}
 async addReturn(custodyId:string,companyId:string,actor:string,txId:string,noteValue:string|null){return this.run(async c=>{const custody=await this.repo.custody(custodyId,companyId,c,true);if(!custody)throw new NotFoundError('Custody not found');if(custody.status!=='open')throw new ConflictError('Custody is closed');const tx=await this.repo.txRow(txId,companyId,c,true);if(!tx)throw new NotFoundError('Bank transaction not found');await assertAccountingDateWritable(companyId,tx.transaction_date,c);if(tx.reconciliation_status!=='unmatched'||await this.repo.match(txId,companyId,c))throw new ConflictError('Bank transaction is already matched');if(toCents(tx.amount)<=0n)throw new ConflictError('Custody return requires an inbound bank transaction');const before=await this.summaryOf(custody,companyId,c);if(tx.currency_code!==before.funding_transaction.currency_code)throw new ConflictError('Return currency must match custody funding currency');if(toCents(tx.amount)>toCents(before.remaining_amount))throw new ConflictError('Return exceeds custody remaining amount');await this.repo.insertMatch(companyId,txId,custodyId,'custody_return',actor,noteValue,c);await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'custody.return.link',entity_type:'custody',entity_id:custodyId,before_data:{remaining_amount:before.remaining_amount},after_data:{bank_transaction_id:txId,amount:tx.amount,note:noteValue}},c);return this.summaryOf(custody,companyId,c);}).catch(e=>{if((e as{code?:string}).code==='23505')throw new ConflictError('Bank transaction is already matched');throw e;});}
 async removeReturn(custodyId:string,companyId:string,actor:string,txId:string,reason:string){return this.run(async c=>{const custody=await this.repo.custody(custodyId,companyId,c,true);if(!custody)throw new NotFoundError('Custody not found');if(custody.status!=='open')throw new ConflictError('Custody is closed');const tx=await this.repo.txRow(txId,companyId,c,true);if(!tx)throw new NotFoundError('Bank transaction not found');await assertAccountingDateWritable(companyId,tx.transaction_date,c);if(tx.reconciliation_status==='reconciled')throw new ConflictError('Reopen bank reconciliation before unlinking return');const m=await this.repo.match(txId,companyId,c);if(!m||m.match_type!=='custody_return'||m.custody_id!==custodyId)throw new NotFoundError('Custody return not found');await c.query('DELETE FROM bank_transaction_matches WHERE bank_transaction_id=$1 AND company_id=$2',[txId,companyId]);await c.query("UPDATE bank_transactions SET reconciliation_status='unmatched',reconciled_by_user_id=NULL,reconciled_at=NULL WHERE id=$1 AND company_id=$2",[txId,companyId]);await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'custody.return.unlink',entity_type:'custody',entity_id:custodyId,before_data:{bank_transaction_id:txId,amount:tx.amount},after_data:{reason}},c);return this.summaryOf(custody,companyId,c);});}
 async close(custodyId:string,companyId:string,actor:string){return this.run(async c=>{const custody=await this.repo.custody(custodyId,companyId,c,true);if(!custody)throw new NotFoundError('Custody not found');if(custody.status!=='open')throw new ConflictError('Custody is already closed');const before=await this.summaryOf(custody,companyId,c);if(toCents(before.remaining_amount)!==0n)throw new ConflictError('Custody cannot close while a balance remains');await c.query("UPDATE custody_advances SET status='closed',closed_by_user_id=$3,closed_at=NOW() WHERE id=$1 AND company_id=$2",[custodyId,companyId,actor]);await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'custody.close',entity_type:'custody',entity_id:custodyId,before_data:{status:'open'},after_data:{status:'closed',remaining_amount:'0.00'}},c);return{status:'closed' as const};});}
 async reopen(custodyId:string,companyId:string,actor:string,reason:string){return this.run(async c=>{const custody=await this.repo.custody(custodyId,companyId,c,true);if(!custody)throw new NotFoundError('Custody not found');if(custody.status!=='closed')throw new ConflictError('Custody is not closed');await c.query("UPDATE custody_advances SET status='open',closed_by_user_id=NULL,closed_at=NULL WHERE id=$1 AND company_id=$2",[custodyId,companyId]);await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'custody.reopen',entity_type:'custody',entity_id:custodyId,before_data:{status:'closed'},after_data:{status:'open',reason}},c);return{status:'open' as const};});}
}

function errors(e:unknown,res:Response){if(e instanceof ValidationError){res.status(400).json({error:e.message});return true;}if(e instanceof NotFoundError){res.status(404).json({error:e.message});return true;}if(e instanceof AccountingPeriodClosedError){res.status(409).json({error:e.message});return true;}if(e instanceof ConflictError){res.status(409).json({error:e.message});return true;}return false;}
function parseCreate(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;if(Object.keys(x).some(k=>!['bank_transaction_id','purpose'].includes(k)))return null;const tx=id(x.bank_transaction_id);const p=note(x.purpose);return tx&&p!==undefined?{tx,p}:null;}
function parseAllocation(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;if(Object.keys(x).some(k=>!['document_id','amount','note'].includes(k)))return null;const d=id(x.document_id),a=amount(x.amount),n=note(x.note);return d&&a&&n!==undefined?{d,a,n}:null;}
function parseReturn(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;if(Object.keys(x).some(k=>!['bank_transaction_id','note'].includes(k)))return null;const tx=id(x.bank_transaction_id),n=note(x.note);return tx&&n!==undefined?{tx,n}:null;}

custodyRouter.get('/custodies',requireAuth,requireActiveCompany,requireCapability(VIEW),asyncRoute(async(req,res)=>{const c=context(req,res);if(!c)return;const s=service(res);if(!s)return;try{res.json(await s.list(c.activeCompanyId));}catch(e){if(!errors(e,res))throw e;}}));
custodyRouter.get('/custodies/:id',requireAuth,requireActiveCompany,requireCapability(VIEW),asyncRoute(async(req,res)=>{const c=context(req,res),cid=id(req.params.id);if(!c)return;if(!cid){res.status(400).json({error:'Invalid custody id'});return;}const s=service(res);if(!s)return;try{res.json(await s.detail(cid,c.activeCompanyId));}catch(e){if(!errors(e,res))throw e;}}));
custodyRouter.post('/custodies',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability(MANAGE),asyncRoute(async(req,res)=>{const c=context(req,res),b=parseCreate(req.body);if(!c)return;if(!b){res.status(400).json({error:'Invalid custody request'});return;}const s=service(res);if(!s)return;try{res.status(201).json(await s.create(c.activeCompanyId,c.user.id,b.tx,b.p));}catch(e){if(!errors(e,res))throw e;}}));
custodyRouter.post('/custodies/:id/documents',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability(MANAGE),asyncRoute(async(req,res)=>{const c=context(req,res),cid=id(req.params.id),b=parseAllocation(req.body);if(!c)return;if(!cid||!b){res.status(400).json({error:'Invalid custody allocation'});return;}const s=service(res);if(!s)return;try{res.status(201).json(await s.allocate(cid,c.activeCompanyId,c.user.id,b.d,b.a,b.n));}catch(e){if(!errors(e,res))throw e;}}));
custodyRouter.delete('/custodies/:id/documents/:allocationId',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability(MANAGE),asyncRoute(async(req,res)=>{const c=context(req,res),cid=id(req.params.id),aid=id(req.params.allocationId),r=reasonBody(req.body);if(!c)return;if(!cid||!aid||!r){res.status(400).json({error:'Invalid allocation removal'});return;}const s=service(res);if(!s)return;try{res.json(await s.removeAllocation(cid,aid,c.activeCompanyId,c.user.id,r));}catch(e){if(!errors(e,res))throw e;}}));
custodyRouter.post('/custodies/:id/returns',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability(MANAGE),asyncRoute(async(req,res)=>{const c=context(req,res),cid=id(req.params.id),b=parseReturn(req.body);if(!c)return;if(!cid||!b){res.status(400).json({error:'Invalid custody return'});return;}const s=service(res);if(!s)return;try{res.status(201).json(await s.addReturn(cid,c.activeCompanyId,c.user.id,b.tx,b.n));}catch(e){if(!errors(e,res))throw e;}}));
custodyRouter.delete('/custodies/:id/returns/:transactionId',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability(MANAGE),asyncRoute(async(req,res)=>{const c=context(req,res),cid=id(req.params.id),tx=id(req.params.transactionId),r=reasonBody(req.body);if(!c)return;if(!cid||!tx||!r){res.status(400).json({error:'Invalid custody return removal'});return;}const s=service(res);if(!s)return;try{res.json(await s.removeReturn(cid,c.activeCompanyId,c.user.id,tx,r));}catch(e){if(!errors(e,res))throw e;}}));
custodyRouter.post('/custodies/:id/close',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability(CLOSE),asyncRoute(async(req,res)=>{const c=context(req,res),cid=id(req.params.id);if(!c)return;if(!cid){res.status(400).json({error:'Invalid custody id'});return;}const s=service(res);if(!s)return;try{res.json(await s.close(cid,c.activeCompanyId,c.user.id));}catch(e){if(!errors(e,res))throw e;}}));
custodyRouter.post('/custodies/:id/reopen',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability(CLOSE),asyncRoute(async(req,res)=>{const c=context(req,res),cid=id(req.params.id),r=reasonBody(req.body);if(!c)return;if(!cid||!r){res.status(400).json({error:'Invalid custody reopen request'});return;}const s=service(res);if(!s)return;try{res.json(await s.reopen(cid,c.activeCompanyId,c.user.id,r));}catch(e){if(!errors(e,res))throw e;}}));
