import {NextFunction,Request,RequestHandler,Response,Router} from 'express';
import {Pool,PoolClient} from 'pg';
import pool from '../../db/pool';
import {AuditLogRepository} from '../audit-log/audit-log.repository';
import {getAuthenticatedContext,requireActiveCompany,requireAuth,requireCapability} from '../auth/auth.middleware';
import {requireSameOrigin} from '../auth/origin.middleware';
import {assertAccountingDateWritable} from '../monthly-close/accounting-period.guard';

export const assetEstimateChangeRouter=Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const DATE=/^\d{4}-\d{2}-\d{2}$/;
type EstimateChangeStatus='draft'|'reviewed'|'approved';
type EstimateChange={id:string;company_id:string;asset_id:string;effective_from:string;old_useful_life_months:number|null;new_remaining_useful_life_months:number|null;old_residual_value:string;new_residual_value:string|null;reason:string;policy_exception:boolean;policy_exception_reason:string|null;status:EstimateChangeStatus;reviewed_by:string|null;reviewed_at:Date|null;approved_by:string|null;approved_at:Date|null;created_by:string;created_at:Date;updated_at:Date};
type Asset={id:string;company_id:string;depreciation_policy_version_id:string|null;acquisition_cost:string;opening_accumulated_depreciation:string;residual_value:string;useful_life_months:number|null;depreciation_start_date:string|null;status:string};
type EstimateInput={effectiveFrom:string;remainingUsefulLifeMonths:number|null;residualValue:string|null;reason:string;policyExceptionReason:string|null};

export class AssetEstimateChangeValidationError extends Error{}
export class AssetEstimateChangeNotFoundError extends Error{}
export class AssetEstimateChangeConflictError extends Error{}
const route=(fn:(req:Request,res:Response)=>Promise<void>):RequestHandler=>(req,res,next:NextFunction)=>void fn(req,res).catch(next);
const context=(req:Request)=>getAuthenticatedContext(req)! as ReturnType<typeof getAuthenticatedContext>&{activeCompanyId:string};
const object=(x:unknown):Record<string,unknown>|null=>x!==null&&typeof x==='object'&&!Array.isArray(x)?x as Record<string,unknown>:null;
const validDate=(x:unknown):x is string=>typeof x==='string'&&DATE.test(x)&&!Number.isNaN(Date.parse(`${x}T00:00:00Z`));
const textValue=(x:unknown,max:number,required=false)=>{if(x===null&&!required)return null;if(typeof x!=='string')return undefined;const v=x.trim();return v&&v.length<=max?v:required?undefined:null};
const cents=(x:unknown)=>{if(typeof x!=='string'&&typeof x!=='number')return null;const m=/^(0|[1-9]\d{0,15})(?:\.(\d{1,2}))?$/.exec(String(x).trim());return m?BigInt(m[1])*100n+BigInt((m[2]??'').padEnd(2,'0')):null};
const money=(x:bigint)=>`${x/100n}.${String(x%100n).padStart(2,'0')}`;
const monthEnd=(start:string)=>{const d=new Date(`${start}T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(0);return d.toISOString().slice(0,10)};
const nextMonth=(start:string)=>{const d=new Date(`${start.slice(0,7)}-01T00:00:00Z`);d.setUTCMonth(d.getUTCMonth()+1);return d.toISOString().slice(0,10)};

function parseInput(body:unknown,partial=false):Partial<EstimateInput>|null{
 const x=object(body);if(!x)return null;
 const allowed=['effective_from','remaining_useful_life_months','residual_value','reason','policy_exception_reason'];
 if(Object.keys(x).some(k=>!allowed.includes(k)))return null;
 const out:Partial<EstimateInput>={};
 if('effective_from'in x){if(!validDate(x.effective_from)||x.effective_from.slice(8,10)!=='01')return null;out.effectiveFrom=x.effective_from}
 if('remaining_useful_life_months'in x){if(x.remaining_useful_life_months!==null&&(!Number.isInteger(x.remaining_useful_life_months)||Number(x.remaining_useful_life_months)<=0||Number(x.remaining_useful_life_months)>1200))return null;out.remainingUsefulLifeMonths=x.remaining_useful_life_months as number|null}
 if('residual_value'in x){if(x.residual_value===null)out.residualValue=null;else{const v=cents(x.residual_value);if(v===null)return null;out.residualValue=money(v)}}
 if('reason'in x){const v=textValue(x.reason,1000,true);if(!v)return null;out.reason=v}
 if('policy_exception_reason'in x){const v=textValue(x.policy_exception_reason,1000);if(v===undefined)return null;out.policyExceptionReason=v}
 if(!partial&&(['effectiveFrom','reason'] as const).some(k=>out[k]===undefined))return null;
 if(!partial&&out.remainingUsefulLifeMonths==null&&out.residualValue==null)return null;
 return out;
}

function buildProspectiveSchedule(openingNbv:string,residualValue:string,months:number,start:string,openingAccumulated:string){
 const nbv=cents(openingNbv)!,residual=cents(residualValue)!,acc0=cents(openingAccumulated)!;
 if(months<=0||residual>nbv)throw new AssetEstimateChangeValidationError('Invalid prospective estimate');
 let left=nbv-residual,acc=acc0,currentNbv=nbv,period=start;
 const base=left/BigInt(months),rows:{periodStart:string;periodEnd:string;openingNbv:string;amount:string;accumulated:string;closingNbv:string}[]=[];
 for(let i=0;i<months;i++){
  const amount=i===months-1?left:base;
  left-=amount;acc+=amount;const closing=currentNbv-amount;
  rows.push({periodStart:period,periodEnd:monthEnd(period),openingNbv:money(currentNbv),amount:money(amount),accumulated:money(acc),closingNbv:money(closing)});
  currentNbv=closing;period=nextMonth(period);
 }
 return rows;
}

export class AssetEstimateChangeService{
 private audit=new AuditLogRepository();
 constructor(private db:Pool){}
 private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const v=await fn(c);await c.query('COMMIT');return v}catch(e){await c.query('ROLLBACK');const code=(e as{code?:string}).code;if(code==='23505')throw new AssetEstimateChangeConflictError('Conflicting estimate-change request');if(code==='23503'||code==='23514')throw new AssetEstimateChangeValidationError((e as Error).message);throw e}finally{c.release()}}
 private async asset(c:PoolClient,companyId:string,assetId:string,lock=false){const sql=`SELECT id,company_id,depreciation_policy_version_id,acquisition_cost::text,opening_accumulated_depreciation::text,residual_value::text,useful_life_months,depreciation_start_date::text,status FROM fixed_assets WHERE id=$1 AND company_id=$2${lock?' FOR UPDATE':''}`;const a=(await c.query<Asset>(sql,[assetId,companyId])).rows[0];if(!a)throw new AssetEstimateChangeNotFoundError();return a}
 private async baselineEstimates(c:PoolClient,companyId:string,asset:Asset,effectiveFrom:string){
  const pending=(await c.query<{count:string}>("SELECT COUNT(*)::text count FROM asset_depreciation_entries WHERE company_id=$1 AND asset_id=$2 AND status='pending' AND period_start>=$3",[companyId,asset.id,effectiveFrom])).rows[0]!;
  const priorResidual=(await c.query<{new_residual_value:string|null}>("SELECT new_residual_value::text FROM asset_estimate_changes WHERE company_id=$1 AND asset_id=$2 AND status='approved' AND effective_from<$3 AND new_residual_value IS NOT NULL ORDER BY effective_from DESC,approved_at DESC LIMIT 1",[companyId,asset.id,effectiveFrom])).rows[0];
  return{remainingMonths:Number(pending.count),residualValue:priorResidual?.new_residual_value??asset.residual_value};
 }
 private async classifyPolicyException(c:PoolClient,asset:Asset,input:EstimateInput){if(!asset.depreciation_policy_version_id)return false;const p=(await c.query<{useful_life_mode:string;residual_value_policy:string}>('SELECT useful_life_mode,residual_value_policy FROM asset_category_depreciation_policies WHERE id=$1 AND company_id=$2',[asset.depreciation_policy_version_id,asset.company_id])).rows[0];if(!p)return false;return(input.remainingUsefulLifeMonths!==null&&p.useful_life_mode==='fixed')||(input.residualValue!==null&&cents(input.residualValue)!>0n&&p.residual_value_policy==='zero')}
 private async validateInput(c:PoolClient,companyId:string,asset:Asset,input:EstimateInput){if(asset.status!=='active')throw new AssetEstimateChangeConflictError('Only active assets support estimate changes');if(input.effectiveFrom.slice(8,10)!=='01')throw new AssetEstimateChangeValidationError('Estimate change must be effective on the first day of a month');await assertAccountingDateWritable(companyId,input.effectiveFrom,c);if((await c.query("SELECT 1 FROM asset_depreciation_entries WHERE company_id=$1 AND asset_id=$2 AND status='posted' AND period_end>=$3 LIMIT 1",[companyId,asset.id,input.effectiveFrom])).rowCount)throw new AssetEstimateChangeConflictError('Posted depreciation exists on or after the effective date');if(input.residualValue!==null&&cents(input.residualValue)!>cents(asset.acquisition_cost)!)throw new AssetEstimateChangeValidationError('Residual value cannot exceed acquisition cost');const policyException=await this.classifyPolicyException(c,asset,input);if(policyException&&!input.policyExceptionReason)throw new AssetEstimateChangeValidationError('Policy exception reason is required');return policyException}
 async list(companyId:string,assetId:string){if(!(await this.db.query('SELECT 1 FROM fixed_assets WHERE id=$1 AND company_id=$2',[assetId,companyId])).rowCount)throw new AssetEstimateChangeNotFoundError();return{changes:(await this.db.query<EstimateChange>('SELECT *,effective_from::text,old_residual_value::text,new_residual_value::text FROM asset_estimate_changes WHERE company_id=$1 AND asset_id=$2 ORDER BY effective_from DESC,created_at DESC',[companyId,assetId])).rows}}
 async create(companyId:string,actor:string,assetId:string,body:unknown){const input=parseInput(body) as EstimateInput|null;if(!input)throw new AssetEstimateChangeValidationError('Invalid request');return this.tx(async c=>{await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`asset-estimate:${companyId}:${assetId}`]);const asset=await this.asset(c,companyId,assetId,true);const policyException=await this.validateInput(c,companyId,asset,input);const baseline=await this.baselineEstimates(c,companyId,asset,input.effectiveFrom);if(baseline.remainingMonths<=0)throw new AssetEstimateChangeConflictError('No remaining depreciation periods are available for the prospective change');const row=(await c.query<EstimateChange>(`INSERT INTO asset_estimate_changes(company_id,asset_id,effective_from,old_useful_life_months,new_remaining_useful_life_months,old_residual_value,new_residual_value,reason,policy_exception,policy_exception_reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *,effective_from::text,old_residual_value::text,new_residual_value::text`,[companyId,assetId,input.effectiveFrom,baseline.remainingMonths,input.remainingUsefulLifeMonths,baseline.residualValue,input.residualValue,input.reason,policyException,policyException?input.policyExceptionReason:null,actor])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'asset.estimate_change.create',entity_type:'asset_estimate_change',entity_id:row.id,before_data:null,after_data:row,reason:input.reason},c);return row})}
 async update(companyId:string,actor:string,id:string,body:unknown){const patch=parseInput(body,true);if(!patch||!Object.keys(patch).length)throw new AssetEstimateChangeValidationError('Invalid request');return this.tx(async c=>{const before=(await c.query<EstimateChange>('SELECT *,effective_from::text,old_residual_value::text,new_residual_value::text FROM asset_estimate_changes WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!before)throw new AssetEstimateChangeNotFoundError();if(before.status!=='draft')throw new AssetEstimateChangeConflictError('Reviewed estimate change is immutable');const input:EstimateInput={effectiveFrom:patch.effectiveFrom??before.effective_from,remainingUsefulLifeMonths:patch.remainingUsefulLifeMonths===undefined?before.new_remaining_useful_life_months:patch.remainingUsefulLifeMonths,residualValue:patch.residualValue===undefined?before.new_residual_value:patch.residualValue,reason:patch.reason??before.reason,policyExceptionReason:patch.policyExceptionReason===undefined?before.policy_exception_reason:patch.policyExceptionReason};if(input.remainingUsefulLifeMonths==null&&input.residualValue==null)throw new AssetEstimateChangeValidationError('At least one estimate must change');const asset=await this.asset(c,companyId,before.asset_id,true);const policyException=await this.validateInput(c,companyId,asset,input);const baseline=await this.baselineEstimates(c,companyId,asset,input.effectiveFrom);if(baseline.remainingMonths<=0)throw new AssetEstimateChangeConflictError('No remaining depreciation periods are available for the prospective change');const after=(await c.query<EstimateChange>(`UPDATE asset_estimate_changes SET effective_from=$3,old_useful_life_months=$4,new_remaining_useful_life_months=$5,old_residual_value=$6,new_residual_value=$7,reason=$8,policy_exception=$9,policy_exception_reason=$10,updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *,effective_from::text,old_residual_value::text,new_residual_value::text`,[id,companyId,input.effectiveFrom,baseline.remainingMonths,input.remainingUsefulLifeMonths,baseline.residualValue,input.residualValue,input.reason,policyException,policyException?input.policyExceptionReason:null])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'asset.estimate_change.update',entity_type:'asset_estimate_change',entity_id:id,before_data:before,after_data:after,reason:input.reason},c);return after})}
 async review(companyId:string,actor:string,id:string){return this.tx(async c=>{const before=(await c.query<EstimateChange>('SELECT *,effective_from::text,old_residual_value::text,new_residual_value::text FROM asset_estimate_changes WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!before)throw new AssetEstimateChangeNotFoundError();if(before.status!=='draft')throw new AssetEstimateChangeConflictError('Estimate change is not reviewable');const asset=await this.asset(c,companyId,before.asset_id,true);const input:EstimateInput={effectiveFrom:before.effective_from,remainingUsefulLifeMonths:before.new_remaining_useful_life_months,residualValue:before.new_residual_value,reason:before.reason,policyExceptionReason:before.policy_exception_reason};await this.validateInput(c,companyId,asset,input);const after=(await c.query<EstimateChange>("UPDATE asset_estimate_changes SET status='reviewed',reviewed_by=$3,reviewed_at=NOW(),updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *,effective_from::text,old_residual_value::text,new_residual_value::text",[id,companyId,actor])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'asset.estimate_change.review',entity_type:'asset_estimate_change',entity_id:id,before_data:before,after_data:after},c);return after})}
 async approve(companyId:string,actor:string,id:string){return this.tx(async c=>{const before=(await c.query<EstimateChange>('SELECT *,effective_from::text,old_residual_value::text,new_residual_value::text FROM asset_estimate_changes WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!before)throw new AssetEstimateChangeNotFoundError();if(before.status!=='reviewed')throw new AssetEstimateChangeConflictError('Estimate change must be reviewed before approval');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`asset-estimate:${companyId}:${before.asset_id}`]);const asset=await this.asset(c,companyId,before.asset_id,true);const input:EstimateInput={effectiveFrom:before.effective_from,remainingUsefulLifeMonths:before.new_remaining_useful_life_months,residualValue:before.new_residual_value,reason:before.reason,policyExceptionReason:before.policy_exception_reason};await this.validateInput(c,companyId,asset,input);
  const baseline=await this.baselineEstimates(c,companyId,asset,before.effective_from);
  const posted=(await c.query<{total:string}>("SELECT COALESCE(SUM(depreciation_amount),0)::text total FROM asset_depreciation_entries WHERE company_id=$1 AND asset_id=$2 AND status='posted' AND period_end<$3",[companyId,asset.id,before.effective_from])).rows[0]!;
  const accumulated=cents(asset.opening_accumulated_depreciation)!+cents(posted.total)!;
  const nbv=cents(asset.acquisition_cost)!-accumulated;
  const residual=input.residualValue??baseline.residualValue;
  if(cents(residual)!>nbv)throw new AssetEstimateChangeValidationError('Residual value cannot exceed net book value at the effective date');
  const months=input.remainingUsefulLifeMonths??baseline.remainingMonths;
  if(!months||months<=0)throw new AssetEstimateChangeConflictError('No remaining depreciation periods are available for the prospective change');
  await c.query("DELETE FROM asset_depreciation_entries WHERE company_id=$1 AND asset_id=$2 AND status='pending' AND period_start>=$3",[companyId,asset.id,before.effective_from]);
  const schedule=buildProspectiveSchedule(money(nbv),residual,months,before.effective_from,money(accumulated));
  for(const row of schedule)await c.query(`INSERT INTO asset_depreciation_entries(company_id,asset_id,period_start,period_end,opening_nbv,depreciation_amount,accumulated_depreciation,closing_nbv) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[companyId,asset.id,row.periodStart,row.periodEnd,row.openingNbv,row.amount,row.accumulated,row.closingNbv]);
  const after=(await c.query<EstimateChange>("UPDATE asset_estimate_changes SET status='approved',approved_by=$3,approved_at=NOW(),updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *,effective_from::text,old_residual_value::text,new_residual_value::text",[id,companyId,actor])).rows[0]!;
  await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'asset.estimate_change.schedule_rebuild',entity_type:'fixed_asset',entity_id:asset.id,before_data:{effective_from:before.effective_from,remaining_periods:baseline.remainingMonths,residual_value:baseline.residualValue},after_data:{effective_from:before.effective_from,remaining_periods:months,net_book_value:money(nbv),residual_value:residual}},c);
  await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'asset.estimate_change.approve',entity_type:'asset_estimate_change',entity_id:id,before_data:before,after_data:after,reason:before.reason},c);return after})}
}

function service(res:Response){if(!pool){res.status(503).json({error:'Database unavailable'});return null}return new AssetEstimateChangeService(pool)}
function handle(e:unknown,res:Response){if(e instanceof AssetEstimateChangeValidationError)res.status(400).json({error:e.message});else if(e instanceof AssetEstimateChangeNotFoundError)res.status(404).json({error:'Not found'});else if(e instanceof AssetEstimateChangeConflictError)res.status(409).json({error:e.message});else throw e}
const base=[requireAuth,requireActiveCompany] as const,mutation=[requireSameOrigin,...base] as const;
assetEstimateChangeRouter.get('/assets/:id/estimate-changes',...base,requireCapability('asset.view'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new AssetEstimateChangeValidationError('Invalid request');const s=service(res);if(s)res.json(await s.list(context(req).activeCompanyId,req.params.id))}catch(e){handle(e,res)}}));
assetEstimateChangeRouter.post('/assets/:id/estimate-changes',...mutation,requireCapability('asset.estimate_change.create'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new AssetEstimateChangeValidationError('Invalid request');const s=service(res);if(s)res.status(201).json(await s.create(context(req).activeCompanyId,context(req).user.id,req.params.id,req.body))}catch(e){handle(e,res)}}));
assetEstimateChangeRouter.patch('/asset-estimate-changes/:id',...mutation,requireCapability('asset.estimate_change.create'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new AssetEstimateChangeValidationError('Invalid request');const s=service(res);if(s)res.json(await s.update(context(req).activeCompanyId,context(req).user.id,req.params.id,req.body))}catch(e){handle(e,res)}}));
assetEstimateChangeRouter.post('/asset-estimate-changes/:id/review',...mutation,requireCapability('asset.estimate_change.review'),route(async(req,res)=>{try{if(!UUID.test(req.params.id)||Object.keys(req.body??{}).length)throw new AssetEstimateChangeValidationError('Invalid request');const s=service(res);if(s)res.json(await s.review(context(req).activeCompanyId,context(req).user.id,req.params.id))}catch(e){handle(e,res)}}));
assetEstimateChangeRouter.post('/asset-estimate-changes/:id/approve',...mutation,requireCapability('asset.estimate_change.approve'),route(async(req,res)=>{try{if(!UUID.test(req.params.id)||Object.keys(req.body??{}).length)throw new AssetEstimateChangeValidationError('Invalid request');const s=service(res);if(s)res.json(await s.approve(context(req).activeCompanyId,context(req).user.id,req.params.id))}catch(e){handle(e,res)}}));
