import { Pool, PoolClient } from 'pg';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { CompanyAccountingProfileRepository } from './company-accounting-profile.repository';
import { CompanyAccountingProfile, CreateProfileInput, ProfileConflictError, ProfileNotFoundError, ProfileValidationError, ProfileValues, UpdateProfileInput } from './company-accounting-profile.types';

const snapshot=(p:CompanyAccountingProfile):Record<string,unknown>=>({...p});
const yesterday=(date:string):string=>{const value=new Date(`${date}T00:00:00Z`);value.setUTCDate(value.getUTCDate()-1);return value.toISOString().slice(0,10);};
const professionalKeys=['accounting_framework','accounting_framework_notes','tax_treatment','ownership_context','tax_effective_from','tax_notes','wht_profile','has_non_resident_dealings'] as const;

export class CompanyAccountingProfileService {
  private readonly repo:CompanyAccountingProfileRepository;
  private readonly audit=new AuditLogRepository();
  constructor(private readonly pool:Pool){this.repo=new CompanyAccountingProfileRepository(pool);}

  private async tx<T>(fn:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query('BEGIN');const value=await fn(client);await client.query('COMMIT');return value;}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
  private async lockCompany(companyId:string,client:PoolClient){await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[companyId]);}
  private validate(v:ProfileValues,approval=false):void{
    if(v.effective_from&&v.effective_to&&v.effective_to<v.effective_from)throw new ProfileValidationError('Invalid effective period');
    if(v.vat_status==='registered'&&(!v.vat_registration_number?.trim()||!v.vat_registered_from||!v.vat_filing_frequency))throw new ProfileValidationError('Registered VAT fields are required');
    if(v.vat_status==='deregistered'&&(!v.vat_registration_number?.trim()||!v.vat_registered_from||!v.vat_deregistered_from))throw new ProfileValidationError('Deregistered VAT fields are required');
    if(v.vat_status==='not_registered'&&(v.vat_registration_number!==null||v.vat_registered_from!==null||v.vat_deregistered_from!==null||v.vat_filing_frequency!==null))throw new ProfileValidationError('Not-registered VAT profile is contradictory');
    if(v.vat_deregistered_from&&v.vat_registered_from&&v.vat_deregistered_from<v.vat_registered_from)throw new ProfileValidationError('VAT deregistration precedes registration');
    if(approval&&!v.effective_from)throw new ProfileValidationError('Approved profile requires effective_from');
  }
  private values(p:CompanyAccountingProfile):ProfileValues{const {accounting_framework,accounting_framework_notes,functional_currency,reporting_currency,first_live_accounting_date,vat_status,vat_registration_number,vat_registered_from,vat_deregistered_from,vat_filing_frequency,tax_treatment,ownership_context,tax_effective_from,tax_notes,wht_profile,has_non_resident_dealings,effective_from,effective_to,change_reason}=p;return{accounting_framework,accounting_framework_notes,functional_currency,reporting_currency,first_live_accounting_date,vat_status,vat_registration_number,vat_registered_from,vat_deregistered_from,vat_filing_frequency,tax_treatment,ownership_context,tax_effective_from,tax_notes,wht_profile,has_non_resident_dealings,effective_from,effective_to,change_reason};}
  private async auditEvent(client:PoolClient,company:string,actor:string,action:string,profile:CompanyAccountingProfile,before:CompanyAccountingProfile|null,reason?:string|null){await this.audit.logEvent({company_id:company,actor_user_id:actor,action,entity_type:'company_accounting_profile',entity_id:profile.id,before_data:before?snapshot(before):null,after_data:snapshot(profile),reason:reason??profile.change_reason},client);}

  current(company:string,date=new Date().toISOString().slice(0,10)){return this.repo.current(company,date);}
  history(company:string){return this.repo.history(company);}
  async get(company:string,id:string){const value=await this.repo.byId(company,id);if(!value)throw new ProfileNotFoundError();return value;}

  async createInitial(company:string,actor:string,input:CreateProfileInput){this.validate(input);return this.tx(async client=>{await this.lockCompany(company,client);if(await this.repo.hasAny(company,client))throw new ProfileConflictError('Initial profile already exists');const profile=await this.repo.create(company,1,actor,input,client);profile.closed_period_impact=await this.repo.closedPeriodImpact(company,profile.effective_from,client);await this.auditEvent(client,company,actor,'company_accounting_profile.create',profile,null);return profile;});}
  async createVersion(company:string,actor:string,input:UpdateProfileInput){if(!input.change_reason?.trim())throw new ProfileValidationError('change_reason is required');return this.tx(async client=>{await this.lockCompany(company,client);const base=await this.repo.latestApproved(company,client);if(!base)throw new ProfileConflictError('No approved profile to version');const values={...this.values(base),...input};this.validate(values);const profile=await this.repo.create(company,await this.repo.nextVersion(company,client),actor,values,client);profile.closed_period_impact=await this.repo.closedPeriodImpact(company,profile.effective_from,client);await this.auditEvent(client,company,actor,'company_accounting_profile.create',profile,null,profile.change_reason);return profile;});}
  async updateDraft(company:string,actor:string,id:string,input:UpdateProfileInput){if(!Object.keys(input).length)throw new ProfileValidationError('No changes supplied');return this.tx(async client=>{const before=await this.repo.byId(company,id,client,true);if(!before)throw new ProfileNotFoundError();if(before.workflow_status!=='draft')throw new ProfileConflictError('Only drafts may be edited');const values={...this.values(before),...input};this.validate(values);const profile=await this.repo.updateDraft(company,id,input,client);if(!profile)throw new ProfileConflictError('Draft changed concurrently');profile.closed_period_impact=await this.repo.closedPeriodImpact(company,profile.effective_from,client);await this.auditEvent(client,company,actor,'company_accounting_profile.update_draft',profile,before,input.change_reason);return profile;});}
  async updateProfessionalReview(company:string,actor:string,id:string,input:UpdateProfileInput){const keys=Object.keys(input);if(!keys.length)throw new ProfileValidationError('No changes supplied');if(keys.some(key=>!professionalKeys.includes(key as typeof professionalKeys[number])))throw new ProfileValidationError('Only professional review fields may be changed');return this.tx(async client=>{const before=await this.repo.byId(company,id,client,true);if(!before)throw new ProfileNotFoundError();if(before.workflow_status!=='needs_review')throw new ProfileConflictError('Only profiles awaiting review may be professionally edited');const values={...this.values(before),...input};this.validate(values);const profile=await this.repo.updateNeedsReview(company,id,input,client);if(!profile)throw new ProfileConflictError('Profile changed concurrently');profile.closed_period_impact=await this.repo.closedPeriodImpact(company,profile.effective_from,client);await this.auditEvent(client,company,actor,'company_accounting_profile.update_professional_review',profile,before,input.change_reason);return profile;});}
  private async move(company:string,actor:string,id:string,from:'draft'|'needs_review'|'reviewed',to:'needs_review'|'reviewed',action:string,reason?:string){return this.tx(async client=>{const before=await this.repo.byId(company,id,client,true);if(!before)throw new ProfileNotFoundError();if(before.workflow_status!==from)throw new ProfileConflictError('Invalid workflow transition');const profile=await this.repo.transition(company,id,from,to,actor,client);if(!profile)throw new ProfileConflictError('Profile changed concurrently');profile.closed_period_impact=await this.repo.closedPeriodImpact(company,profile.effective_from,client);await this.auditEvent(client,company,actor,action,profile,before,reason);return profile;});}
  submitReview(company:string,actor:string,id:string){return this.move(company,actor,id,'draft','needs_review','company_accounting_profile.submit_review');}
  async review(company:string,actor:string,id:string){return this.tx(async client=>{const before=await this.repo.byId(company,id,client,true);if(!before)throw new ProfileNotFoundError();if(before.workflow_status!=='needs_review')throw new ProfileConflictError('Invalid workflow transition');if(before.professional_review_required)throw new ProfileValidationError('Professional review must be resolved before review');const profile=await this.repo.transition(company,id,'needs_review','reviewed',actor,client);if(!profile)throw new ProfileConflictError('Profile changed concurrently');profile.closed_period_impact=await this.repo.closedPeriodImpact(company,profile.effective_from,client);await this.auditEvent(client,company,actor,'company_accounting_profile.review',profile,before);return profile;});}
  returnForReview(company:string,actor:string,id:string,reason:string){if(!reason.trim())throw new ProfileValidationError('reason is required');return this.move(company,actor,id,'reviewed','needs_review','company_accounting_profile.review',reason.trim());}
  async approve(company:string,actor:string,id:string){return this.tx(async client=>{await this.lockCompany(company,client);const before=await this.repo.byId(company,id,client,true);if(!before)throw new ProfileNotFoundError();if(before.workflow_status!=='reviewed')throw new ProfileConflictError('Profile must be reviewed before approval');if(before.professional_review_required)throw new ProfileValidationError('Professional review must be resolved before approval');const values=this.values(before);this.validate(values,true);const overlaps=await this.repo.approvedOverlaps(company,id,values.effective_from!,values.effective_to,client);if(overlaps.length>1)throw new ProfileConflictError('Approved effective periods overlap');for(const old of overlaps){if(old.effective_from!>=values.effective_from!||values.effective_to!==null)throw new ProfileConflictError('Approved effective periods overlap');const end=yesterday(values.effective_from!);if(end<old.effective_from!)throw new ProfileConflictError('Approved effective periods overlap');const closed=await this.repo.closeEffectivePeriod(company,old.id,end,client);if(!closed)throw new ProfileConflictError('Effective profile changed concurrently');await this.auditEvent(client,company,actor,'company_accounting_profile.supersede',closed,old,before.change_reason);}
    const profile=await this.repo.transition(company,id,'reviewed','approved',actor,client);if(!profile)throw new ProfileConflictError('Profile changed concurrently');profile.closed_period_impact=await this.repo.closedPeriodImpact(company,profile.effective_from,client);await this.auditEvent(client,company,actor,'company_accounting_profile.approve',profile,before,before.change_reason);return profile;});}
}
