import { fireEvent, render, screen } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import i18n from '../i18n';
import { Accounting } from '../components/Accounting';

const accountId='11111111-1111-4111-8111-111111111111';
const year={id:'year-1',name:'2026',start_date:'2026-01-01',end_date:'2026-12-31'};

describe('Accounting UX foundation',()=>{
 beforeEach(async()=>{await i18n.changeLanguage('en');window.history.replaceState(null,'','/?page=accounting')});
 it('shows a specific closed-period message instead of the generic accounting error',async()=>{const fetchMock=vi.fn(async(url:string,options?:RequestInit)=>{if(url==='/api/accounts')return new Response(JSON.stringify({accounts:[]}));if(url==='/api/fiscal-years')return new Response(JSON.stringify({fiscalYears:[year]}));if(url==='/api/journals'&&(options?.method??'GET')==='GET')return new Response(JSON.stringify({journals:[]}));if(url==='/api/accounting/operational-sources')return new Response(JSON.stringify({sources:[]}));if(url==='/api/journals'&&options?.method==='POST')return new Response(JSON.stringify({error:'Accounting period is closed',code:'ACCOUNTING_PERIOD_CLOSED'}),{status:409,headers:{'content-type':'application/json'}});return new Response(null,{status:404})});vi.stubGlobal('fetch',fetchMock);render(<Accounting canView canManageChart={false} canManageJournals canPost={false} onUnauthorized={vi.fn()}/>);fireEvent.click(await screen.findByRole('tab',{name:'Journals'}));fireEvent.change(screen.getByLabelText('Accounting date'),{target:{value:'2026-09-15'}});fireEvent.change(screen.getByLabelText('Description'),{target:{value:'Closed period entry'}});fireEvent.click(screen.getByRole('button',{name:'Create journal'}));expect(await screen.findByText('A journal cannot be created or posted inside a closed accounting period.')).toBeInTheDocument();expect(screen.queryByText('Unable to load or update accounting.')).not.toBeInTheDocument()});
 it('shows debit, credit, and difference as separate journal totals',async()=>{const journal={id:'22222222-2222-4222-8222-222222222222',fiscal_year_id:year.id,accounting_date:'2026-08-01',description:'UX journal',reference:'JE-100',entry_type:'standard' as const,status:'draft' as const};const lines=[{id:'line-1',company_id:'company-1',journal_entry_id:journal.id,account_id:accountId,debit:'100.00',credit:'0.00',memo:null,sequence:1},{id:'line-2',company_id:'company-1',journal_entry_id:journal.id,account_id:accountId,debit:'0.00',credit:'75.00',memo:null,sequence:2}];const fetchMock=vi.fn(async(url:string)=>{if(url==='/api/accounts')return new Response(JSON.stringify({accounts:[{id:accountId,code:'1000',name:'Cash',account_type:'asset',parent_account_id:null,is_active:true}]}));if(url==='/api/fiscal-years')return new Response(JSON.stringify({fiscalYears:[year]}));if(url==='/api/journals')return new Response(JSON.stringify({journals:[journal]}));if(url==='/api/accounting/operational-sources')return new Response(JSON.stringify({sources:[]}));if(url===`/api/journals/${journal.id}`)return new Response(JSON.stringify({...journal,lines}));return new Response(null,{status:404})});vi.stubGlobal('fetch',fetchMock);render(<Accounting canView canManageChart={false} canManageJournals canPost onUnauthorized={vi.fn()}/>);fireEvent.click(await screen.findByRole('tab',{name:'Journals'}));fireEvent.click(await screen.findByRole('button',{name:/UX journal/}));expect(await screen.findByText('Difference')).toBeInTheDocument();expect(screen.getByText('25.00')).toBeInTheDocument();expect(screen.getByText('Unbalanced')).toBeInTheDocument()});
});