import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { CompanyAccountingProfile } from '../components/CompanyAccountingProfile';
import i18n from '../i18n';

const approved={id:'33333333-3333-4333-8333-333333333333',version_no:1,workflow_status:'approved',accounting_framework:'IFRS',accounting_framework_notes:null,functional_currency:'SAR',reporting_currency:'SAR',first_live_accounting_date:'2026-01-01',vat_status:'not_registered',vat_registration_number:null,vat_registered_from:null,vat_deregistered_from:null,vat_filing_frequency:null,tax_treatment:'zakat_applicable',ownership_context:'saudi_gcc_only',tax_effective_from:null,tax_notes:null,wht_profile:'not_currently_applicable',has_non_resident_dealings:'no',effective_from:'2026-01-01',effective_to:null,change_reason:'initial',prepared_by_user_id:'u1',reviewed_by_user_id:'u2',approved_by_user_id:'u3',closed_period_impact:false,professional_review_required:false};
const draft={...approved,id:'55555555-5555-4555-8555-555555555555',workflow_status:'draft'};
const waiting={...approved,id:'44444444-4444-4444-8444-444444444444',version_no:2,workflow_status:'needs_review',tax_treatment:'needs_review',wht_profile:'needs_review',professional_review_required:true};
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}}));

function mockLoad(current:unknown,history:unknown[]){return vi.fn().mockImplementation((url:string)=>url.endsWith('/current')?response({profile:current}):response({profiles:history}));}

describe('CompanyAccountingProfile',()=>{
  beforeEach(async()=>{await i18n.changeLanguage('en');vi.restoreAllMocks();});
  it('shows no-access state without reading the API',()=>{const fetchMock=vi.fn();vi.stubGlobal('fetch',fetchMock);render(<CompanyAccountingProfile canView={false} canCreate={false} canEdit={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(screen.getByText(/do not have permission/i)).toBeInTheDocument();expect(fetchMock).not.toHaveBeenCalled();});
  it('renders approved profile read-only and offers versioning only to creators',async()=>{vi.stubGlobal('fetch',mockLoad(approved,[approved]));render(<CompanyAccountingProfile canView canCreate canEdit canSubmit canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect((await screen.findAllByText('Approved')).length).toBeGreaterThan(0);expect(screen.getByRole('button',{name:'Create new version'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Edit draft'})).not.toBeInTheDocument();});
  it('gates draft edit and submit actions independently',async()=>{vi.stubGlobal('fetch',mockLoad(null,[draft]));const view=render(<CompanyAccountingProfile canView canCreate={false} canEdit canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('button',{name:'Edit draft'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Submit for review'})).not.toBeInTheDocument();view.rerender(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(screen.queryByRole('button',{name:'Edit draft'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Submit for review'})).toBeInTheDocument();});
  it('shows professional correction controls only while awaiting accountant review',async()=>{vi.stubGlobal('fetch',mockLoad(approved,[waiting,approved]));render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview canApprove={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('heading',{name:'Accountant review'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Mark professionally reviewed'})).not.toBeInTheDocument();expect(screen.getByLabelText('Zakat / income tax treatment')).toBeInTheDocument();expect(screen.queryByLabelText('Functional currency')).not.toBeInTheDocument();});
  it('submits a reviewer correction to the dedicated endpoint and reloads',async()=>{const fetchMock=vi.fn().mockImplementation((url:string,options?:RequestInit)=>{if(url.endsWith('/current'))return response({profile:approved});if(url.endsWith('/history'))return response({profiles:[waiting,approved]});if(url.endsWith('/professional-review')){expect(options?.method).toBe('PATCH');return response({profile:{...waiting,tax_treatment:'zakat_applicable',wht_profile:'not_currently_applicable',professional_review_required:false}});}return response({});});vi.stubGlobal('fetch',fetchMock);render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview canApprove={false} onUnauthorized={vi.fn()}/>);const tax=await screen.findByLabelText('Zakat / income tax treatment');fireEvent.change(tax,{target:{value:'zakat_applicable'}});fireEvent.change(screen.getByLabelText('Withholding-tax profile'),{target:{value:'not_currently_applicable'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>String(url).endsWith('/professional-review'))).toBe(true));});
  it('shows approval action only for reviewed profile with approve capability',async()=>{const reviewed={...approved,workflow_status:'reviewed'};vi.stubGlobal('fetch',mockLoad(null,[reviewed]));render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview={false} canApprove onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('button',{name:'Approve profile'})).toBeInTheDocument();});
});
