import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { CompanyAccountingProfile } from '../components/CompanyAccountingProfile';
import i18n from '../i18n';

const approved={id:'33333333-3333-4333-8333-333333333333',version_no:1,workflow_status:'approved',accounting_framework:'IFRS',accounting_framework_notes:null,functional_currency:'SAR',reporting_currency:'SAR',first_live_accounting_date:'2026-01-01',vat_status:'not_registered',vat_registration_number:null,vat_registered_from:null,vat_deregistered_from:null,vat_filing_frequency:null,tax_treatment:'zakat_applicable',ownership_context:'saudi_gcc_only',tax_effective_from:null,tax_notes:null,wht_profile:'not_currently_applicable',has_non_resident_dealings:'no',effective_from:'2026-01-01',effective_to:null,change_reason:'initial',prepared_by_user_id:'u1',reviewed_by_user_id:'u2',approved_by_user_id:'u3',closed_period_impact:false,professional_review_required:false};
const draft={...approved,id:'55555555-5555-4555-8555-555555555555',workflow_status:'draft'};
const waiting={...approved,id:'44444444-4444-4444-8444-444444444444',version_no:2,workflow_status:'needs_review',tax_treatment:'needs_review',wht_profile:'needs_review',professional_review_required:true};
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}}));

function mockLoad(current:unknown,history:unknown[]){return vi.fn().mockImplementation((url:string)=>url.endsWith('/current')?response({profile:current}):response({profiles:history}));}

describe('CompanyAccountingProfile',()=>{
  beforeEach(async()=>{await i18n.changeLanguage('en');vi.restoreAllMocks();});
  it('shows no-access state without reading the API',()=>{const fetchMock=vi.fn();vi.stubGlobal('fetch',fetchMock);render(<CompanyAccountingProfile canView={false} canCreate={false} canEdit={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(screen.getByText(/do not have permission/i)).toBeInTheDocument();expect(fetchMock).not.toHaveBeenCalled();});
  it('renders approved profile read-only and offers versioning only to creators',async()=>{vi.stubGlobal('fetch',mockLoad(approved,[approved]));render(<CompanyAccountingProfile canView canCreate canEdit canSubmit canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect((await screen.findAllByText('Approved')).length).toBeGreaterThan(0);expect(screen.getByRole('button',{name:'Create new version'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Edit draft'})).not.toBeInTheDocument();});
  it('gates draft edit and submit actions independently',async()=>{vi.stubGlobal('fetch',mockLoad(null,[draft]));const view=render(<CompanyAccountingProfile canView canCreate={false} canEdit canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('button',{name:'Edit draft'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Submit for review'})).not.toBeInTheDocument();view.rerender(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(screen.queryByRole('button',{name:'Edit draft'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Submit for review'})).toBeInTheDocument();});
  it('shows professional correction controls only while awaiting accountant review',async()=>{vi.stubGlobal('fetch',mockLoad(approved,[waiting,approved]));render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview canApprove={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('heading',{name:'Accountant review'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Mark professionally reviewed'})).not.toBeInTheDocument();expect(screen.getByLabelText('Zakat / income tax treatment')).toBeInTheDocument();expect(screen.queryByLabelText('Functional currency')).not.toBeInTheDocument();});
  it('submits a reviewer correction to the dedicated endpoint and reloads',async()=>{const fetchMock=vi.fn().mockImplementation((url:string,options?:RequestInit)=>{if(url.endsWith('/current'))return response({profile:approved});if(url.endsWith('/history'))return response({profiles:[waiting,approved]});if(url.endsWith('/professional-review')){expect(options?.method).toBe('PATCH');return response({profile:{...waiting,tax_treatment:'zakat_applicable',wht_profile:'not_currently_applicable',professional_review_required:false}});}return response({});});vi.stubGlobal('fetch',fetchMock);render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview canApprove={false} onUnauthorized={vi.fn()}/>);const tax=await screen.findByLabelText('Zakat / income tax treatment');fireEvent.change(tax,{target:{value:'zakat_applicable'}});fireEvent.change(screen.getByLabelText('Withholding-tax profile'),{target:{value:'not_currently_applicable'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(fetchMock.mock.calls.some(([url])=>String(url).endsWith('/professional-review'))).toBe(true));});
  it('shows approval action only for reviewed profile with approve capability',async()=>{const reviewed={...approved,workflow_status:'reviewed'};vi.stubGlobal('fetch',mockLoad(null,[reviewed]));render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview={false} canApprove onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('button',{name:'Approve profile'})).toBeInTheDocument();});
  it('shows empty state with create button that opens the form only on click',async()=>{vi.stubGlobal('fetch',mockLoad(null,[]));render(<CompanyAccountingProfile canView canCreate canEdit={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);const create=await screen.findByRole('button',{name:'Create initial profile'});expect(screen.queryByLabelText('Functional currency')).not.toBeInTheDocument();fireEvent.click(create);expect(screen.getByLabelText('Functional currency')).toBeInTheDocument();});
  it('renders draft details as label/value text and switches to inputs on edit',async()=>{vi.stubGlobal('fetch',mockLoad(null,[draft]));render(<CompanyAccountingProfile canView canCreate={false} canEdit canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('heading',{name:'Accounting setup'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'VAT'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Tax treatment & ownership'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Withholding tax & non-resident dealings'})).toBeInTheDocument();expect(screen.queryByLabelText('Functional currency')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Edit draft'}));expect(screen.getByLabelText('Functional currency')).toBeInTheDocument();});
  it('shows the generic professional review warning only when the backend flag is true',async()=>{vi.stubGlobal('fetch',mockLoad(waiting,[waiting]));const view=render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByText(/requires professional review/i)).toBeInTheDocument();view.unmount();vi.stubGlobal('fetch',mockLoad(approved,[approved]));render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);await screen.findByRole('heading',{name:'Accounting setup'});expect(screen.queryByText(/requires professional review/i)).not.toBeInTheDocument();});
  it('offers mark-reviewed once the flag is false, and not approve before reviewed',async()=>{const ready={...waiting,professional_review_required:false};vi.stubGlobal('fetch',mockLoad(null,[ready]));render(<CompanyAccountingProfile canView canCreate={false} canEdit={false} canSubmit={false} canReview canApprove onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('button',{name:'Mark professionally reviewed'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Approve profile'})).not.toBeInTheDocument();});
  it('keeps VAT fields visible and preserves existing VAT values in the payload when status needs review',async()=>{const vat={...draft,vat_status:'needs_review',vat_registration_number:'300000000000003',vat_registered_from:'2026-02-01',vat_filing_frequency:'monthly'};let body:Record<string,unknown>={};const fetchMock=vi.fn().mockImplementation((url:string,options?:RequestInit)=>{if(url.endsWith('/current'))return response({profile:null});if(url.endsWith('/history'))return response({profiles:[vat]});if(options?.method==='PATCH'){body=JSON.parse(String(options.body));return response({profile:vat});}return response({});});vi.stubGlobal('fetch',fetchMock);render(<CompanyAccountingProfile canView canCreate={false} canEdit canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:'Edit draft'}));expect(screen.getByLabelText('VAT registration number')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(body.vat_status).toBe('needs_review'));expect(body.vat_registration_number).toBe('300000000000003');expect(body.vat_registered_from).toBe('2026-02-01');expect(body.vat_filing_frequency).toBeNull();});
  it('renders version history and the bounded new-version form',async()=>{vi.stubGlobal('fetch',mockLoad(approved,[approved,{...approved,id:'66666666-6666-4666-8666-666666666666',version_no:0}]));render(<CompanyAccountingProfile canView canCreate canEdit={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('heading',{name:'Version history'})).toBeInTheDocument();expect(screen.getAllByRole('row').length).toBe(3);fireEvent.click(screen.getByRole('button',{name:'Create new version'}));const reason=screen.getByLabelText('Change reason');expect(reason).toBeRequired();expect(reason).toHaveAttribute('maxlength','500');});
  it('shows the existing error state when loading fails',async()=>{vi.stubGlobal('fetch',vi.fn().mockImplementation(()=>response({},500)));render(<CompanyAccountingProfile canView canCreate canEdit canSubmit canReview canApprove onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('alert')).toHaveTextContent(/Unable to load/i);});
});
