import { render, screen, waitFor, within } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { CompanyProvider } from '../context/CompanyContext';
import { Home } from '../components/Home';
import i18n from '../i18n';

const navigate=vi.fn(),navigateToDiscovery=vi.fn(),onUnauthorized=vi.fn();
function renderHome(capabilities:string[]){return render(<CompanyProvider allowedCompanies={[{id:'co-1',name:'Company One'}]} initialCompanyId="co-1"><Home capabilities={capabilities} navigate={navigate} navigateToDiscovery={navigateToDiscovery} startPurchaseEntry={vi.fn()} startSalesEntry={vi.fn()} onUnauthorized={onUnauthorized}/></CompanyProvider>)}
const period={period_start:'2026-09-01',period_end:'2026-09-30',status:'open',ready:false,disclosed_total:3,has_hidden_blockers:false,blockers:{documents:2,obligations:1,bank_transactions:0,vat:0,ledger:0,assets:0,opening_balances:0,periodic_adjustments:0}};
const snapshot={metrics:{bank_balances:{state:'available',accounts:[{id:'b1',display_name:'Operating account',currency_code:'SAR',balance:{state:'available',amount:'1250.50'}},{id:'b2',display_name:'Reserve account',currency_code:'USD',balance:{state:'unavailable'}}]},amounts_to_collect:{state:'available',amount:'400.25'},amounts_to_pay:{state:'available',amount:'90.00'},total_assets:{state:'available',amount:'9800.75'}}};
const alert={key:'overdue_obligations',class:'needs_action_now',ownership:'waiting_for_accountant',count:2,amount:'175.25',destination:'obligations',parameters:{overdue:'1'}};
function api(options:{periods?:unknown[];alerts?:unknown[];snapshot?:unknown}={}){return vi.fn(async(url:string)=>{if(url==='/api/monthly-close-periods')return new Response(JSON.stringify({periods:options.periods??[]}),{status:200});if(url==='/api/home-alerts')return new Response(JSON.stringify({alerts:options.alerts??[]}),{status:200});if(url==='/api/manager-financial-snapshot')return new Response(JSON.stringify(options.snapshot??snapshot),{status:200});return new Response('',{status:404})})}

describe('Phase 15 Home financial overview',()=>{
 beforeEach(async()=>{await i18n.changeLanguage('en');vi.clearAllMocks()});
 it('starts with the financial overview and omits superseded dashboard sections',()=>{vi.stubGlobal('fetch',api());renderHome([]);expect(screen.getByRole('heading',{name:'Financial overview',level:1})).toBeInTheDocument();expect(screen.queryByText('Welcome back')).not.toBeInTheDocument();expect(screen.queryByText('Daily Operations')).not.toBeInTheDocument()});
 it('renders the four approved KPI meanings from the snapshot without demo substitutes',async()=>{vi.stubGlobal('fetch',api({snapshot}));renderHome(['bank.view','obligation.view','accounting.view']);expect(await screen.findByText('1250.50 SAR')).toBeInTheDocument();for(const name of ['Cash and cash equivalents','Receivables','Payables','Total assets'])expect(screen.getByRole('heading',{name})).toBeInTheDocument();expect(screen.getByText('9800.75')).toBeInTheDocument();expect(screen.queryByText('Current-month sales')).not.toBeInTheDocument();expect(screen.getByText('Reserve account').parentElement).toHaveTextContent('Unavailable')});
 it('shows permission-hidden KPI states rather than invented values',async()=>{vi.stubGlobal('fetch',api({snapshot:{metrics:{...snapshot.metrics,total_assets:{state:'hidden'}}}}));renderHome(['bank.view']);expect(await screen.findByText('1250.50 SAR')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Total assets'}).parentElement).toHaveTextContent('Restricted by permissions')});
 it('renders a dense truthful follow-up table and preserves drill-through',async()=>{vi.stubGlobal('fetch',api({alerts:[alert,{key:'documents_needs_review',class:'needs_review_completion',ownership:'current_user',count:1,destination:'documents',parameters:{status:'needs_review'}}]}));renderHome(['obligation.view','document.view']);const table=await screen.findByRole('table');expect(within(table).getByText('175.25')).toBeInTheDocument();expect(within(table).getByText('Accountant')).toBeInTheDocument();expect(within(table).getByText('You')).toBeInTheDocument();expect(within(table).getByText('—')).toBeInTheDocument();expect(document.body).not.toHaveTextContent('Ahmed');within(table).getAllByRole('button',{name:'Open'})[0]!.click();expect(navigateToDiscovery).toHaveBeenCalledWith('obligations',{overdue:'1'})});
 it('maps all real monthly-close blocker categories without percentages',async()=>{vi.stubGlobal('fetch',api({periods:[period]}));renderHome(['monthly_close.view','document.view']);expect(await screen.findByRole('heading',{name:'Monthly close readiness'})).toBeInTheDocument();for(const label of ['Documents','Obligations','Bank reconciliation','VAT readiness','Accounting and posting','Assets and depreciation','Opening balances','Periodic adjustments'])expect(screen.getByText(label)).toBeInTheDocument();expect(document.body).not.toHaveTextContent('%');screen.getByRole('button',{name:/Documents 2 blockers/}).click();expect(navigateToDiscovery).toHaveBeenCalledWith('documents',{from:'2026-09-01',to:'2026-09-30'})});
 it('preserves hidden blocker masking',async()=>{vi.stubGlobal('fetch',api({periods:[{...period,has_hidden_blockers:true,disclosed_total:2}]}));renderHome(['monthly_close.view']);expect(await screen.findByText('There are blockers that require an authorized user.')).toBeInTheDocument();expect(document.body).not.toHaveTextContent('99')});
 it('does not request protected read models without their capabilities',async()=>{const fetchMock=api();vi.stubGlobal('fetch',fetchMock);renderHome([]);await waitFor(()=>expect(fetchMock).not.toHaveBeenCalled());expect(screen.queryByRole('table')).not.toBeInTheDocument()});
});
