import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import '../i18n';
import i18n from '../i18n';
import { MonthlyClose } from '../components/MonthlyClose';

const allViews={documents:true,obligations:true,bank:true,vat:true,accounting:true,assets:true,openingBalances:true,periodicAdjustments:true};
const open={id:'period-open',fiscal_year_id:'fy',period_start:'2026-01-01',period_end:'2026-01-31',status:'open',ready:false,disclosed_total:18,has_hidden_blockers:false,blockers:{documents:1,obligations:2,bank_transactions:3,vat:4,assets:0,opening_balances:1,periodic_adjustments:2,ledger:5}} as const;
const closed={...open,id:'period-closed',period_start:'2025-12-01',period_end:'2025-12-31',status:'closed',ready:true,disclosed_total:0,has_hidden_blockers:false,blockers:{documents:0,obligations:0,bank_transactions:0,vat:0,assets:0,opening_balances:0,periodic_adjustments:0,ledger:0}} as const;
const years={fiscalYears:[{id:'fy',name:'FY 2026',start_date:'2026-01-01',end_date:'2026-12-31'}]};

beforeEach(async()=>{window.history.replaceState(null,'','/?page=monthlyClose');await i18n.changeLanguage('en');vi.restoreAllMocks();});

describe('MonthlyClose',()=>{
 it('uses the fiscal-year view endpoint when that capability is available',async()=>{const fetchMock=vi.fn(async(url:string)=>new Response(JSON.stringify(url==='/api/fiscal-years'?years:{periods:[]})));vi.stubGlobal('fetch',fetchMock);render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears canCreate canClose={false} canReopen={false} onUnauthorized={vi.fn()}/>);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/fiscal-years',expect.anything()));expect(fetchMock).not.toHaveBeenCalledWith('/api/monthly-close-fiscal-years',expect.anything());});
 it('creates a period without fiscal_year.view using the creation-support endpoint',async()=>{const fetchMock=vi.fn(async(url:string,options?:RequestInit)=>{if(url==='/api/monthly-close-periods'&&options?.method==='POST')return new Response(JSON.stringify(open),{status:201});if(url==='/api/monthly-close-periods')return new Response(JSON.stringify({periods:[]}));if(url==='/api/monthly-close-fiscal-years')return new Response(JSON.stringify(years));return new Response(null,{status:404});});vi.stubGlobal('fetch',fetchMock);render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears={false} canCreate canClose={false} canReopen={false} onUnauthorized={vi.fn()}/>);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/monthly-close-fiscal-years',expect.anything()));fireEvent.click(screen.getByRole('button',{name:'Create period'}));expect(screen.getByRole('combobox',{name:'Fiscal year'})).toHaveValue('fy');fireEvent.change(screen.getByLabelText('Period start'),{target:{value:'2026-01-01'}});fireEvent.change(screen.getByLabelText('Period end'),{target:{value:'2026-01-31'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(fetchMock.mock.calls.some(([url,options])=>url==='/api/monthly-close-periods'&&options?.method==='POST')).toBe(true));const call=fetchMock.mock.calls.find(([url,options])=>url==='/api/monthly-close-periods'&&options?.method==='POST')!;expect(JSON.parse(String(call[1]?.body))).toEqual({fiscal_year_id:'fy',period_start:'2026-01-01',period_end:'2026-01-31'});expect(fetchMock.mock.calls.some(([url])=>url==='/api/fiscal-years')).toBe(false);});
 it('shows all selected period blockers and preserves authorized state actions',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({periods:[open,closed]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200})));render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears canCreate canClose canReopen onUnauthorized={vi.fn()}/>);expect(await screen.findByText('18 blocking items')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Documents 1'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Obligations 2'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Bank transactions 3'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'VAT 4'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Opening Balance Review 1'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Periodic Adjustments 2'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Accounting / General Ledger 5'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Close period'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:/01\/12\/2025/}));expect(screen.getByText('Ready to close')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Reopen period'})).toBeEnabled();expect(screen.queryByRole('button',{name:'Close period'})).not.toBeInTheDocument();});

 it('restores valid close context, falls back from invalid context, and URL-backs changes',async()=>{window.history.replaceState(null,'','/?page=monthlyClose&closeYear=fy&closePeriod=period-closed');vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({periods:[open,closed]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200})));render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears canCreate canClose canReopen onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('button',{name:/01\/12\/2025/})).toHaveAttribute('aria-pressed','true');expect(screen.getByRole('combobox',{name:'Fiscal year'})).toHaveValue('fy');fireEvent.click(screen.getByRole('button',{name:/01\/01\/2026/}));expect(window.location.search).toContain('closePeriod=period-open');});
 it('uses exact supported drill-through subsets, excludes stale state, and disables zero counts',async()=>{const navigate=vi.fn();vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({periods:[{...open,blockers:{...open.blockers,assets:1}}]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200})));render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears canCreate canClose canReopen onNavigate={navigate} onUnauthorized={vi.fn()}/>);await screen.findByText('18 blocking items');fireEvent.click(screen.getByRole('button',{name:'Documents 1'}));expect(navigate).toHaveBeenLastCalledWith('documents',{from:'2026-01-01',to:'2026-01-31'});fireEvent.click(screen.getByRole('button',{name:'Obligations 2'}));expect(navigate).toHaveBeenLastCalledWith('obligations',{confirmation:'unconfirmed',recognizedFrom:'2026-01-01',recognizedTo:'2026-01-31'});fireEvent.click(screen.getByRole('button',{name:'Bank transactions 3'}));expect(navigate).toHaveBeenLastCalledWith('banks',{section:'transactions',from:'2026-01-01',to:'2026-01-31'});fireEvent.click(screen.getByRole('button',{name:'VAT 4'}));expect(navigate).toHaveBeenLastCalledWith('vat',{vatFrom:'2026-01-01',vatTo:'2026-01-31'});fireEvent.click(screen.getByRole('button',{name:'Fixed Assets 1'}));expect(navigate).toHaveBeenLastCalledWith('assets',{assetFrom:'2026-01-01',assetTo:'2026-01-31'});fireEvent.click(screen.getByRole('button',{name:'Opening Balance Review 1'}));expect(navigate).toHaveBeenLastCalledWith('openingBalances',{fiscalYear:'fy'});fireEvent.click(screen.getByRole('button',{name:'Periodic Adjustments 2'}));expect(navigate).toHaveBeenLastCalledWith('periodicAdjustments',{adjustmentFrom:'2026-01-01',adjustmentTo:'2026-01-31'});fireEvent.click(screen.getByRole('button',{name:'Accounting / General Ledger 5'}));expect(navigate).toHaveBeenLastCalledWith('accounting',{accountingTab:'sources',sourceFrom:'2026-01-01',sourceTo:'2026-01-31'});});
 it('renders zero-count blocker rows as non-actionable while preserving their counts',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({periods:[{...open,ready:false,blockers:{...open.blockers,documents:0}}]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200})));render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears canCreate canClose canReopen onUnauthorized={vi.fn()}/>);const row=(await screen.findByText('Documents')).closest('tr')!;expect(row).toHaveTextContent('Documents');expect(row.querySelector('.mc-count')).toHaveTextContent('0');expect(screen.queryByRole('button',{name:/Documents/})).not.toBeInTheDocument();});
 it('requires and sends a reopen reason',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({periods:[closed]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({...closed,status:'open'}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({periods:[]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200}));vi.stubGlobal('fetch',fetchMock);render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears canCreate={false} canClose={false} canReopen onUnauthorized={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:'Reopen period'}));const reason=screen.getByLabelText('Reason');expect(reason).toBeRequired();fireEvent.change(reason,{target:{value:'Correct January invoice'}});fireEvent.submit(reason.closest('form')!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(5));expect(fetchMock.mock.calls[2]![0]).toBe('/api/monthly-close-periods/period-closed/reopen');expect(JSON.parse(fetchMock.mock.calls[2]![1].body)).toEqual({reason:'Correct January invoice'});});
 it('does not fetch without view access',()=>{const fetchMock=vi.fn();vi.stubGlobal('fetch',fetchMock);render(<MonthlyClose viewCapabilities={allViews} canView={false} canViewFiscalYears canCreate canClose canReopen onUnauthorized={vi.fn()}/>);expect(screen.getByText(/do not have permission/)).toBeInTheDocument();expect(fetchMock).not.toHaveBeenCalled();});
 it('hides unauthorized blocker categories and keeps close unavailable for hidden-only blockers',async()=>{const hidden={...open,disclosed_total:0,has_hidden_blockers:true,blockers:{}};vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({periods:[hidden]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200})));render(<MonthlyClose viewCapabilities={{documents:false,obligations:false,bank:false,vat:false,accounting:false,assets:false,openingBalances:false,periodicAdjustments:false}} canView canViewFiscalYears canCreate={false} canClose canReopen={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByText('There are blockers that require an authorized user.')).toBeInTheDocument();expect(screen.queryByText(/Documents/)).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Documents|Obligations|Bank transactions|VAT|Accounting/})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Close period'})).toBeDisabled();expect(screen.queryByText(/18/)).not.toBeInTheDocument();});
 it('does not expose period creation to close-only users',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({periods:[open]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200})));render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears canCreate={false} canClose canReopen={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByText('18 blocking items')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Create period'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Close period'})).toBeInTheDocument();});
 it('keeps the period start before the end inside an LTR-isolated range in RTL',async()=>{await i18n.changeLanguage('ar');vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({periods:[open]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify(years),{status:200})));const {container}=render(<MonthlyClose viewCapabilities={allViews} canView canViewFiscalYears canCreate canClose canReopen onUnauthorized={vi.fn()}/>);await waitFor(()=>expect(container.querySelector('.mc-summary .mc-range')).not.toBeNull());const ranges=Array.from(container.querySelectorAll('.mc-range'));expect(ranges.length).toBe(2);for(const range of ranges){expect(range).toHaveAttribute('dir','ltr');const dates=range.querySelectorAll('bdi');expect(dates).toHaveLength(2);expect(dates[0]).toHaveTextContent('01');expect(dates[1]).toHaveTextContent('31');expect(dates[0].compareDocumentPosition(dates[1])&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();}});
});
