import{act,fireEvent,render,screen,waitFor}from'@testing-library/react';
import{beforeEach,describe,expect,it,vi}from'vitest';
import'../i18n';import i18n from'../i18n';import{Obligations}from'../components/Obligations';

const base={id:'OB-OPEN',direction:'receivable' as const,counterparty_id:'c1',counterparty_name:'Acme العربية',source_type:'document' as const,original_amount:'100.00',settled_amount:'0.00',remaining_amount:'100.00',recognized_on:'2026-01-01',due_on:'2026-01-15',verification_status:'unconfirmed' as const,state:'open' as const,is_overdue:true,is_cancelled:false,document_id:'DOC-15',source_note:'January invoice',version:1,settlement_history:[]};
const partial={...base,id:'OB-PARTIAL',direction:'payable' as const,counterparty_id:'c2',counterparty_name:'Beta',source_type:'manual' as const,document_id:null,due_on:'2026-01-31',verification_status:'confirmed' as const,state:'partial' as const,settled_amount:'25.00',remaining_amount:'75.00',is_overdue:false,source_note:'Office rent'};
const settled={...base,id:'OB-SETTLED',due_on:'2025-12-31',verification_status:'confirmed' as const,state:'settled' as const,settled_amount:'100.00',remaining_amount:'0.00',is_overdue:true};
const cancelled={...base,id:'OB-CANCELLED',due_on:'2025-12-30',is_cancelled:true,is_overdue:true};
const data=(obligations:any[]= [base,partial,settled,cancelled])=>({obligations,eligible_documents:[],summary:{open_receivables:'100.00',open_payables:'75.00',unconfirmed_receivables:'100.00',unconfirmed_payables:'0.00',unconfirmed_count:2,partially_settled_count:1,overdue_count:1}});
const parties={counterparties:[{id:'c1',name:'Acme العربية',type:'customer',is_active:false,version:1},{id:'c2',name:'Beta',type:'supplier',is_active:true,version:1}]};
const mount=(body=data())=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(JSON.stringify(body))).mockResolvedValueOnce(new Response(JSON.stringify(parties))));return render(<Obligations canView canManage={false} canSettle={false} onUnauthorized={vi.fn()}/>)};
const shown=(name:string)=>screen.queryAllByRole('cell',{name});
beforeEach(async()=>{await i18n.changeLanguage('en');vi.restoreAllMocks();window.history.replaceState(null,'','/?page=obligations')});

describe('Obligations operational discovery',()=>{
 it('keeps multilingual trimmed search and filters actual identifiers, direction, state, party, and source',async()=>{mount();await waitFor(()=>expect(shown('Acme العربية').length).toBeGreaterThan(0));fireEvent.change(screen.getByRole('searchbox',{name:'Search obligations'}),{target:{value:'  العربية  '}});expect(shown('Acme العربية').length).toBeGreaterThan(0);fireEvent.change(screen.getByRole('searchbox'),{target:{value:'doc-15'}});expect(shown('Acme العربية').length).toBeGreaterThan(0);fireEvent.change(screen.getByRole('searchbox'),{target:{value:''}});fireEvent.change(screen.getByLabelText('Direction'),{target:{value:'payable'}});expect(shown('Beta').length).toBeGreaterThan(0);fireEvent.change(screen.getByLabelText('State'),{target:{value:'open'}});expect(screen.getByText('0 obligations')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('State'),{target:{value:''}});fireEvent.change(screen.getByLabelText('Counterparty'),{target:{value:'c2'}});expect(shown('Beta').length).toBeGreaterThan(0);fireEvent.change(screen.getByLabelText('Source'),{target:{value:'document'}});expect(screen.getByText('0 obligations')).toBeInTheDocument()});
 it.each([['confirmed','Beta'],['unconfirmed','Acme العربية']])('filters %s confirmation',async(value,name)=>{mount();await waitFor(()=>expect(shown('Acme العربية').length).toBeGreaterThan(0));fireEvent.change(screen.getByLabelText('Confirmation'),{target:{value}});expect(shown(name).length).toBeGreaterThan(0)});
 it('uses server overdue semantics while excluding settled and cancelled rows',async()=>{mount();await waitFor(()=>expect(shown('Acme العربية').length).toBeGreaterThan(0));fireEvent.change(screen.getByLabelText('Due status'),{target:{value:'1'}});expect(screen.getByText('1 obligations')).toBeInTheDocument();expect(shown('Acme العربية').length).toBeGreaterThan(0)});
 it('applies inclusive from, to, and combined due ranges',async()=>{mount();await waitFor(()=>expect(shown('Acme العربية').length).toBeGreaterThan(0));fireEvent.change(screen.getByLabelText('Due from'),{target:{value:'2026-01-15'}});expect(shown('Acme العربية').length).toBeGreaterThan(0);expect(shown('Beta').length).toBeGreaterThan(0);fireEvent.change(screen.getByLabelText('Due to'),{target:{value:'2026-01-15'}});expect(screen.getByText('1 obligations')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Due from'),{target:{value:''}});expect(shown('Acme العربية').length).toBeGreaterThan(0)});
 it('initializes validated URL state and restores browser history',async()=>{window.history.replaceState(null,'','/?page=obligations&confirmation=confirmed&source=non_document&dueFrom=2026-01-31');mount();expect(await screen.findByLabelText('Confirmation')).toHaveValue('confirmed');expect(shown('Beta').length).toBeGreaterThan(0);act(()=>{window.history.pushState(null,'','/?page=obligations&direction=receivable');window.dispatchEvent(new PopStateEvent('popstate'))});expect(screen.getByLabelText('Direction')).toHaveValue('receivable');expect(shown('Acme العربية').length).toBeGreaterThan(0);act(()=>{window.history.pushState(null,'','/?page=obligations&direction=bad&state=bad&overdue=yes&dueFrom=2026-02-31');window.dispatchEvent(new PopStateEvent('popstate'))});expect(screen.getByLabelText('Direction')).toHaveValue('');expect(screen.getByLabelText('Due from')).toHaveValue('')});

 it('restores recognized-on range and ignores invalid stale dates',async()=>{window.history.replaceState(null,'','/?page=obligations&recognizedFrom=2026-01-01&recognizedTo=2026-01-01');mount(data([base,{...partial,recognized_on:'2025-12-31'}]));expect(await screen.findByLabelText('Recognized from')).toHaveValue('2026-01-01');expect(screen.getByText('1 obligations')).toBeInTheDocument();expect(shown('Acme العربية').length).toBeGreaterThan(0);act(()=>{window.history.pushState(null,'','/?page=obligations&recognizedFrom=2026-02-31&recognizedTo=stale');window.dispatchEvent(new PopStateEvent('popstate'))});expect(screen.getByLabelText('Recognized from')).toHaveValue('');expect(screen.getByLabelText('Recognized to')).toHaveValue('');expect(screen.getByText('2 obligations')).toBeInTheDocument()});
 it('clears only discovery state, preserves page and unrelated navigation, and reports filtered zero',async()=>{window.history.replaceState(null,'','/?page=obligations&search=missing&safe=keep');mount();expect(await screen.findByText('0 obligations')).toBeInTheDocument();expect(document.querySelector('[data-state="no-results"]')).toBeInTheDocument();fireEvent.click(screen.getAllByRole('button',{name:'Clear filters'})[0]!);expect(window.location.search).toContain('page=obligations');expect(window.location.search).toContain('safe=keep');expect(window.location.search).not.toContain('search=')});
 it('distinguishes a genuine empty workspace and exposes RTL-accessible controls',async()=>{mount(data([]));expect((await screen.findByText('No obligations yet.')).closest('[data-state]')).toHaveAttribute('data-state','empty');expect(document.querySelector('[aria-label="Obligation discovery filters"]')).toBeInTheDocument();await i18n.changeLanguage('ar');expect(document.querySelector('[aria-label="فلاتر اكتشاف الذمم"]')).toBeInTheDocument()});
});
