import { fireEvent, render, screen } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import '../i18n'; import i18n from '../i18n'; import { Partners } from '../components/Partners';
const unknown={id:'p1',name:'Unknown Partner',is_active:true,version:1,current_ownership_percentage:null,current_effective_from:null,has_unconfirmed_ownership:true};
const confirmed={id:'p2',name:'Known Partner',is_active:true,version:1,current_ownership_percentage:'35.5000',current_effective_from:'2026-01-01',has_unconfirmed_ownership:false};
beforeEach(async()=>{await i18n.changeLanguage('en');vi.restoreAllMocks()});
describe('Partners',()=>{
 it('renders unknown and confirmed ownership without guessing zero',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({partners:[unknown,confirmed]}),{status:200})));render(<Partners canView canManage={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByText('Unknown Partner')).toBeInTheDocument();expect(screen.getAllByText('Unknown').length).toBeGreaterThan(0);expect(screen.queryByText('0%')).not.toBeInTheDocument();expect(screen.getByText('35.5000%')).toBeInTheDocument();expect(screen.getByText('Unconfirmed')).toBeInTheDocument()});
 it('hides manage actions without capability',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({partners:[unknown]}),{status:200})));render(<Partners canView canManage={false} onUnauthorized={vi.fn()}/>);await screen.findByText('Unknown Partner');expect(screen.queryByText('Create partner')).not.toBeInTheDocument();expect(screen.queryByText('Edit')).not.toBeInTheDocument()});
 it('shows history evidence and manage actions',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({partners:[unknown]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({ownership:[{id:'o1',ownership_percentage:null,effective_from:null,effective_to:null,verification_status:'unconfirmed',source_document_id:'doc-1',note:'Pending evidence',version:1}]}),{status:200}));vi.stubGlobal('fetch',fetchMock);render(<Partners canView canManage onUnauthorized={vi.fn()}/>);fireEvent.click(await screen.findByText('Unknown Partner'));expect(await screen.findByText('Pending evidence')).toBeInTheDocument();expect(screen.getByText(/doc-1/)).toBeInTheDocument();expect(screen.getByText('Add ownership period')).toBeInTheDocument()});
 it('renders the Arabic path',async()=>{await i18n.changeLanguage('ar');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({partners:[]}),{status:200})));render(<Partners canView canManage={false} onUnauthorized={vi.fn()}/>);expect(await screen.findByText('لا يوجد شركاء بعد.')).toBeInTheDocument();expect(screen.getByRole('heading',{name:'الشركاء'})).toBeInTheDocument()});
});
