import{render,screen}from'@testing-library/react';
import{beforeEach,describe,expect,it,vi}from'vitest';
import i18n from'../i18n';
import{PeriodicAdjustments}from'../components/PeriodicAdjustments';

const adjustment=(id:string,status:'draft'|'in_review'|'approved'|'completed',start:string,end:string,schedule:any[]=[])=>({id,adjustment_type:'accrued_expense',total_amount:'100.00',recognition_start:start,recognition_end:end,document_id:null,obligation_id:null,document_name:null,description:id,reference:null,notes:null,balance_account_id:'a',pnl_account_id:'b',workflow_status:status,review_note:null,version:1,schedule});
const items=[adjustment('overlapping-draft','draft','2025-12-15','2026-01-15'),adjustment('outside-review','in_review','2026-02-01','2026-02-28'),adjustment('pending-approved','approved','2025-01-01','2025-12-31',[{id:'s',period_start:'2026-01-01',period_end:'2026-01-31',recognition_date:'2026-01-31',amount:'10.00',status:'pending',journal_entry_id:null}]),adjustment('posted-approved','approved','2026-01-01','2026-01-31',[{id:'p',period_start:'2026-01-01',period_end:'2026-01-31',recognition_date:'2026-01-31',amount:'10.00',status:'posted',journal_entry_id:'j'}])];
const mount=()=>{vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request)=>{const url=String(input);if(url==='/api/periodic-adjustments')return new Response(JSON.stringify({adjustments:items}));if(url==='/api/accounts')return new Response(JSON.stringify({accounts:[]}));if(url==='/api/documents')return new Response(JSON.stringify({documents:[]}));if(url==='/api/obligations')return new Response(JSON.stringify({obligations:[]}));throw Error(url)}));return render(<PeriodicAdjustments canView canCreate={false} canEdit={false} canSubmit={false} canReview={false} canApprove={false} canPost={false} onUnauthorized={vi.fn()}/>)};
beforeEach(async()=>{vi.restoreAllMocks();await i18n.changeLanguage('en');window.history.replaceState(null,'','/?page=periodicAdjustments')});
describe('Periodic Adjustments close discovery',()=>{
 it('shows only overlapping draft/review and approved pending schedule blockers',async()=>{window.history.replaceState(null,'','/?page=periodicAdjustments&adjustmentFrom=2026-01-01&adjustmentTo=2026-01-31');mount();expect(await screen.findByText('overlapping-draft')).toBeInTheDocument();expect(screen.getAllByText('pending-approved').length).toBeGreaterThan(0);expect(screen.queryByText('outside-review')).not.toBeInTheDocument();expect(screen.queryByText('posted-approved')).not.toBeInTheDocument()});
 it('falls back to the default workspace for invalid or reversed context',async()=>{window.history.replaceState(null,'','/?page=periodicAdjustments&adjustmentFrom=invalid&adjustmentTo=2026-01-31');mount();expect(await screen.findByText('outside-review')).toBeInTheDocument();expect(screen.getAllByText('posted-approved').length).toBeGreaterThan(0)});
});
