import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import i18n from '../i18n';
import { Sales } from '../components/Sales';

const sale={id:'sale-1',original_filename:'invoice.pdf',reference_number:'INV-1',document_date:'2026-01-10',total_amount:'100.00',document_status:'approved',counterparty_id:'cp-1',customer_name:'Acme',receivable_id:null,original_amount:null,collected_amount:'25.00',remaining_amount:'75.00',due_on:null,financial_state:'partial',settlement_history:[{id:'s-1',amount:'25.00',transaction_date:'2026-01-20',description:'Transfer',bank_reference:null}]};

describe('Sales',()=>{
 beforeEach(async()=>{await i18n.changeLanguage('en');vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({sales:[sale]}),{status:200,headers:{'content-type':'application/json'}})));});
 it('renders sale relationship, independent states, collection history, filters, and receivable action',async()=>{render(<Sales canView canCreateReceivable onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('cell',{name:'Acme'})).toBeInTheDocument();expect(screen.getAllByText('Partial')).toHaveLength(2);expect(screen.getAllByText('Approved')).toHaveLength(2);fireEvent.click(screen.getByRole('cell',{name:'Acme'}));expect(screen.getByText(/Transfer/)).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open original document'})).toHaveAttribute('href','/api/documents/sale-1/file');expect(screen.getByRole('button',{name:'Create receivable'})).toBeInTheDocument();fireEvent.change(screen.getByRole('searchbox'),{target:{value:'missing'}});expect(screen.getByText('No sales match the current filters.')).toBeInTheDocument();});
 it('creates through the existing obligation write path and sends inherited sale fields',async()=>{const fetchMock=vi.mocked(fetch);fetchMock.mockResolvedValueOnce(new Response(JSON.stringify({sales:[sale]}),{status:200})).mockResolvedValueOnce(new Response('{}',{status:201})).mockResolvedValueOnce(new Response(JSON.stringify({sales:[{...sale,receivable_id:'r-1'}]}),{status:200}));render(<Sales canView canCreateReceivable onUnauthorized={vi.fn()}/>);fireEvent.click(await screen.findByRole('cell',{name:'Acme'}));fireEvent.click(screen.getByRole('button',{name:'Create receivable'}));fireEvent.submit(screen.getByRole('button',{name:'Confirm'}).closest('form')!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(3));expect(fetchMock.mock.calls[1]![0]).toBe('/api/obligations');expect(JSON.parse(String((fetchMock.mock.calls[1]![1] as RequestInit).body))).toMatchObject({direction:'receivable',counterparty_id:'cp-1',document_id:'sale-1',original_amount:'100.00',recognized_on:'2026-01-10',source_type:'document'});});
 it('has English and Arabic translation coverage and denies rendering without read capabilities',async()=>{const{rerender}=render(<Sales canView={false} canCreateReceivable={false} onUnauthorized={vi.fn()}/>);expect(screen.getByText('You do not have permission to view sales.')).toBeInTheDocument();await i18n.changeLanguage('ar');rerender(<Sales canView={false} canCreateReceivable={false} onUnauthorized={vi.fn()}/>);expect(screen.getByText('ليس لديك صلاحية عرض المبيعات.')).toBeInTheDocument();});
});
