import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import i18n from '../i18n';
import { TaxWorkpaper } from '../components/TaxWorkpaper';

const granularWriteProps={canCreate:true,canEdit:true,canCreateAdjustment:true,canEditAdjustment:true,canDeleteAdjustment:true,canSubmit:true};

describe('Tax working paper',()=>{
 beforeEach(async()=>{vi.restoreAllMocks();await i18n.changeLanguage('en');});
 it('renders the applicable mixed path, readiness workflow, and traceable adjustments',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({workpaper:{id:'w',tax_path:'mixed',workflow_status:'draft',notes:null,professional_review_required:false,version:2,adjustments:[{id:'a',description:'Professional adjustment',direction:'add',amount:'12.30',notes:null,source_reference:'REF-1',professional_review_required:true,version:1}]}}),{status:200}));render(<TaxWorkpaper yearId="fy" canView {...granularWriteProps} canReview canApprove onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);expect(await screen.findByText('Mixed')).toBeInTheDocument();expect(screen.getByText('REF-1')).toBeInTheDocument();expect(screen.getAllByText(/Professional review required/).length).toBeGreaterThan(0);});
 it('allows an authorized user to create a missing workpaper',async()=>{const fetchMock=vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify({workpaper:null}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({workpaper:{}}),{status:201})).mockResolvedValueOnce(new Response(JSON.stringify({workpaper:null}),{status:200}));render(<TaxWorkpaper yearId="fy" canView {...granularWriteProps} canReview={false} canApprove={false} onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:'Create working paper'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/tax-working-papers/fy',expect.objectContaining({method:'POST'})));});
 it('accepts positive amounts with exactly two decimal places in the browser',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({workpaper:{id:'w',tax_path:'mixed',workflow_status:'draft',notes:null,professional_review_required:false,version:1,adjustments:[]}}),{status:200}));render(<TaxWorkpaper yearId="fy" canView {...granularWriteProps} canReview={false} canApprove={false} onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);const amount=await screen.findByLabelText('Amount') as HTMLInputElement;for(const value of ['100.00','0.01']){fireEvent.change(amount,{target:{value}});expect(amount.checkValidity()).toBe(true);}});
 it('lets a reviewer resolve only professional-review flags in needs review',async()=>{const workpaper={id:'w',tax_path:'mixed',workflow_status:'needs_review',notes:'locked content',professional_review_required:true,version:4,adjustments:[{id:'a',description:'Locked adjustment',direction:'add',amount:'12.30',notes:null,source_reference:'REF-1',professional_review_required:true,version:2}]};const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>new Response(JSON.stringify({workpaper}),{status:200}));render(<TaxWorkpaper yearId="fy" canView {...granularWriteProps} canReview canApprove={false} onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);const row=await screen.findByText(/Locked adjustment/).then(cell=>cell.closest('tr')!);expect(within(row).queryByRole('button',{name:'Edit'})).not.toBeInTheDocument();fireEvent.click(within(row).getByRole('button',{name:'Mark reviewed'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/tax-working-papers/fy/adjustments/a/resolve-professional-review',expect.objectContaining({method:'POST',body:JSON.stringify({version:4,adjustment_version:2})})));fireEvent.click(screen.getByRole('status').querySelector('button')!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/tax-working-papers/fy/resolve-professional-review',expect.objectContaining({method:'POST',body:JSON.stringify({version:4})})));});
 it('does not show professional-review resolution controls without review capability',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({workpaper:{id:'w',tax_path:'mixed',workflow_status:'needs_review',notes:null,professional_review_required:true,version:1,adjustments:[]}}),{status:200}));render(<TaxWorkpaper yearId="fy" canView {...granularWriteProps} canReview={false} canApprove={false} onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);expect(await screen.findByRole('status')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Mark reviewed'})).not.toBeInTheDocument();});
 it('shows reconciliation values and permits refresh only with edit capability',async()=>{const workpaper={id:'w',tax_path:'mixed',workflow_status:'draft',notes:null,professional_review_required:false,starting_financial_base:'750.00',additions_total:'25.50',deductions_total:'10.25',reconciled_base:'765.25',source_reconciled_at:'2026-01-01',source_drift:true,version:2,adjustments:[]};const fetchMock=vi.spyOn(globalThis,'fetch').mockImplementation(async()=>new Response(JSON.stringify({workpaper}),{status:200}));const {rerender}=render(<TaxWorkpaper yearId="fy" canView canCreate={false} canEdit canCreateAdjustment={false} canEditAdjustment={false} canDeleteAdjustment={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);expect(await screen.findByText('Starting financial base')).toBeInTheDocument();for(const amount of ['750.00','25.50','10.25','765.25'])expect(screen.getByText(amount)).toBeInTheDocument();expect(screen.getByText(/Posted financial data has changed/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Refresh / reconcile'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/tax-working-papers/fy/reconcile',expect.objectContaining({method:'POST',body:JSON.stringify({version:2})})));rerender(<TaxWorkpaper yearId="fy" canView canCreate={false} canEdit={false} canCreateAdjustment={false} canEditAdjustment={false} canDeleteAdjustment={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);expect(screen.queryByRole('button',{name:'Refresh / reconcile'})).not.toBeInTheDocument();});
 it('reconciles an approved drifted workpaper with its current version and reloads the workflow',async()=>{const approved={id:'w',tax_path:'mixed',workflow_status:'approved',notes:null,professional_review_required:false,starting_financial_base:'750.00',additions_total:'0.00',deductions_total:'0.00',reconciled_base:'750.00',source_reconciled_at:'2026-01-01',source_drift:true,version:7,adjustments:[]};const reconciled={...approved,workflow_status:'needs_review',source_drift:false,version:8};const fetchMock=vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify({workpaper:approved}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({workpaper:reconciled}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({workpaper:reconciled}),{status:200}));render(<TaxWorkpaper yearId="fy" canView canCreate={false} canEdit canCreateAdjustment={false} canEditAdjustment={false} canDeleteAdjustment={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:'Refresh / reconcile'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith('/api/tax-working-papers/fy/reconcile',expect.objectContaining({method:'POST',body:JSON.stringify({version:7})})));expect(await screen.findByText('Needs review')).toBeInTheDocument();});
 it('does not expose reconcile for an approved drifted workpaper without edit capability',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValue(new Response(JSON.stringify({workpaper:{id:'w',tax_path:'mixed',workflow_status:'approved',notes:null,professional_review_required:false,starting_financial_base:'750.00',additions_total:'0.00',deductions_total:'0.00',reconciled_base:'750.00',source_reconciled_at:'2026-01-01',source_drift:true,version:7,adjustments:[]}}),{status:200}));render(<TaxWorkpaper yearId="fy" canView canCreate={false} canEdit={false} canCreateAdjustment={false} canEditAdjustment={false} canDeleteAdjustment={false} canSubmit={false} canReview={false} canApprove={false} onUnauthorized={vi.fn()} onChanged={vi.fn()}/>);expect(await screen.findByText(/Posted financial data has changed/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Refresh / reconcile'})).not.toBeInTheDocument();});

});
