import {fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import '../i18n';
import i18n from '../i18n';
import {Vat} from '../components/Vat';

const period={id:'vat-1',fiscal_year_id:'fy',period_start:'2026-01-01',period_end:'2026-03-31',status:'open',ready:true,blockers:{unapproved_documents:0,missing_reviews:0,pending_reviews:0,total:0}};
const documents=[
 {id:'d1',status:'approved',original_filename:'sale-acme.pdf',document_type:'sale',document_date:'2026-01-10',counterparty_name:'Acme',total_amount:'115.00',review_id:'r1',tax_date:'2026-01-10',treatment:'standard',taxable_amount:'100.00',vat_amount:'15.00',review_status:'reviewed',review_note:'Invoice REF-1',version:1},
 {id:'d2',status:'approved',original_filename:'expense-beta.pdf',document_type:'expense',document_date:'2026-01-11',counterparty_name:'Beta',total_amount:'57.50',review_id:null,tax_date:null,treatment:null,taxable_amount:null,vat_amount:null,review_status:null,review_note:null,version:null},
] as any[];
function mock(){vi.stubGlobal('fetch',vi.fn(async(url:string)=>{if(url==='/api/vat-periods')return new Response(JSON.stringify({periods:[period]}),{status:200});if(url==='/api/fiscal-years')return new Response(JSON.stringify({fiscalYears:[{id:'fy',name:'FY 2026',start_date:'2026-01-01',end_date:'2026-12-31'}]}),{status:200});return new Response(JSON.stringify({period,documents}),{status:200})}))}
beforeEach(async()=>{await i18n.changeLanguage('en');vi.restoreAllMocks()});
describe('VAT review workspace',()=>{
 it('filters displayed documents locally by search and treatment',async()=>{mock();render(<Vat canView canReview canClose canReopen onUnauthorized={vi.fn()}/>);expect(await screen.findByRole('cell',{name:'sale-acme.pdf'})).toBeInTheDocument();fireEvent.change(screen.getByRole('searchbox',{name:'Search documents'}),{target:{value:'Beta'}});expect(screen.queryByRole('cell',{name:'sale-acme.pdf'})).not.toBeInTheDocument();expect(screen.getByRole('cell',{name:'expense-beta.pdf'})).toBeInTheDocument();fireEvent.change(screen.getByLabelText('VAT treatment'),{target:{value:'standard'}});expect(screen.getByText('No documents match the current search and filters.')).toBeInTheDocument()});
 it('keeps period and review actions capability and status gated',async()=>{mock();render(<Vat canView canReview={false} canClose={false} canReopen={false} onUnauthorized={vi.fn()}/>);await screen.findByRole('cell',{name:'sale-acme.pdf'});expect(screen.queryByRole('button',{name:'Create VAT period'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:/Review VAT|Edit VAT review/})).not.toBeInTheDocument();expect(within(screen.getByRole('table')).getAllByText('—').length).toBeGreaterThan(0)});
 it('refreshes the open detail pane after saving a VAT review',async()=>{let saved=false;const updated={...documents[0],tax_date:'2026-02-20',treatment:'zero_rated',taxable_amount:'220.00',vat_amount:'0.00',review_note:'Updated REF-2',version:2};const fetchMock=vi.fn(async(url:string,options?:RequestInit)=>{if(url==='/api/documents/d1/vat-review'&&options?.method==='PUT'){saved=true;return new Response('{}',{status:200})}if(url==='/api/vat-periods')return new Response(JSON.stringify({periods:[period]}),{status:200});if(url==='/api/fiscal-years')return new Response(JSON.stringify({fiscalYears:[{id:'fy',name:'FY 2026',start_date:'2026-01-01',end_date:'2026-12-31'}]}),{status:200});return new Response(JSON.stringify({period,documents:saved?[updated,documents[1]]:documents}),{status:200})});vi.stubGlobal('fetch',fetchMock);render(<Vat canView canReview canClose canReopen onUnauthorized={vi.fn()}/>);fireEvent.click(await screen.findByRole('cell',{name:'sale-acme.pdf'}));expect(screen.getByText('Invoice REF-1')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Edit VAT review'}));const reviewDialog=screen.getByRole('dialog',{name:'Review VAT'});fireEvent.change(within(reviewDialog).getByLabelText('Tax date'),{target:{value:'2026-02-20'}});fireEvent.change(within(reviewDialog).getByLabelText('VAT treatment'),{target:{value:'zero_rated'}});fireEvent.change(within(reviewDialog).getByLabelText('Taxable amount'),{target:{value:'220.00'}});fireEvent.change(within(reviewDialog).getByLabelText('VAT amount'),{target:{value:'0.00'}});fireEvent.change(within(reviewDialog).getByLabelText('Review note'),{target:{value:'Updated REF-2'}});fireEvent.click(within(reviewDialog).getByRole('button',{name:'Save'}));await waitFor(()=>{const detail=screen.getByRole('complementary',{name:'VAT document details'});expect(within(detail).getByText('Updated REF-2')).toBeInTheDocument();expect(within(detail).getByText('Zero-rated')).toBeInTheDocument();expect(within(detail).getByText('220.00')).toBeInTheDocument();expect(within(detail).getByText('0.00')).toBeInTheDocument();expect(within(detail).queryByText('Invoice REF-1')).not.toBeInTheDocument()})});
});
