import express, { NextFunction, Request, Response } from 'express';
import request from 'supertest';
import { beforeEach, describe, expect, it, vi } from 'vitest';
const TX='11111111-1111-4111-8111-111111111111';const DOC='22222222-2222-4222-8222-222222222222';const OTHER='33333333-3333-4333-8333-333333333333';const CUSTODY='55555555-5555-4555-8555-555555555555';
const mocks=vi.hoisted(()=>({context:null as null|{user:{id:string;email:string};allowedCompanies:{id:string;name:string;name_ar:string|null}[];activeCompanyId:string|null;capabilities:string[]},query:vi.fn(),connect:vi.fn(),auditLogEvent:vi.fn()}));
vi.mock('../src/db/pool',()=>({default:{query:mocks.query,connect:mocks.connect}}));
vi.mock('../src/modules/monthly-close/accounting-period.guard',()=>({AccountingPeriodClosedError:class extends Error{},assertAccountingDateWritable:vi.fn().mockResolvedValue(undefined),lockAccountingRange:vi.fn().mockResolvedValue(undefined)}));
vi.mock('../src/modules/audit-log/audit-log.repository',()=>({AuditLogRepository:class{logEvent=mocks.auditLogEvent;}}));
vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:vi.fn(()=>mocks.context),requireAuth:(_req:Request,res:Response,next:NextFunction)=>mocks.context?next():void res.status(401).json({error:'Unauthenticated'}),requireActiveCompany:(_req:Request,res:Response,next:NextFunction)=>mocks.context?.activeCompanyId?next():void res.status(403).json({error:'No active company'}),requireCapability:(capability:string)=>(_req:Request,res:Response,next:NextFunction)=>mocks.context?.capabilities.includes(capability)?next():void res.status(403).json({error:'Forbidden'})}));
import { bankReconciliationRouter } from '../src/modules/banking/bank-reconciliation.router';
const app=express();app.use(express.json());app.use('/api',bankReconciliationRouter);app.use((err:unknown,_req:Request,res:Response,_next:NextFunction)=>res.status(500).json({error:err instanceof Error?err.message:'error'}));
function setContext(capabilities:string[],companyId:string|null='co-a'){mocks.context={user:{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',email:'u@example.com'},allowedCompanies:[{id:'co-a',name:'A',name_ar:null}],activeCompanyId:companyId,capabilities};}
function makeClient(handler:(sql:string,params?:unknown[])=>unknown|Promise<unknown>){return{query:vi.fn((sql:string,params?:unknown[])=>Promise.resolve(handler(sql,params))),release:vi.fn()};}
const tx=(status:'unmatched'|'matched'|'reconciled',amount='-100.00')=>({id:TX,company_id:'co-a',reconciliation_status:status,reconciled_by_user_id:status==='reconciled'?'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa':null,reconciled_at:status==='reconciled'?new Date():null,transaction_date:'2026-08-01',amount});
const match={id:'44444444-4444-4444-8444-444444444444',company_id:'co-a',bank_transaction_id:TX,document_id:DOC,custody_id:null,match_type:'document',matched_by_user_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',matched_at:new Date(),note:null};
const approved={id:DOC,status:'approved',document_type:'expense',counterparty_name:'Vendor',document_date:'2026-08-01',reference_number:'INV-1',total_amount:'100.00',original_filename:'invoice.pdf'};
beforeEach(()=>{mocks.context=null;mocks.query.mockReset();mocks.connect.mockReset();mocks.auditLogEvent.mockReset();mocks.auditLogEvent.mockResolvedValue({});});
describe('Bank reconciliation authorization',()=>{
 it('requires authentication and active company',async()=>{expect((await request(app).get(`/api/bank-transactions/${TX}/match-candidates`)).status).toBe(401);setContext(['bank.view'],null);expect((await request(app).get(`/api/bank-transactions/${TX}/match-candidates`)).status).toBe(403);});
 it('separates view, match, and reconcile capabilities',async()=>{setContext(['bank.view']);expect((await request(app).post(`/api/bank-transactions/${TX}/match`).send({document_id:DOC})).status).toBe(403);expect((await request(app).post(`/api/bank-transactions/${TX}/reconciliation`).send({status:'reconciled'})).status).toBe(403);setContext(['bank.match']);expect((await request(app).post(`/api/bank-transactions/${TX}/reconciliation`).send({status:'reconciled'})).status).toBe(403);});
 it('scopes candidate lookup to active company and returns safe 404',async()=>{setContext(['bank.view']);mocks.query.mockResolvedValueOnce({rows:[]});const res=await request(app).get(`/api/bank-transactions/${OTHER}/match-candidates?company_id=co-b`);expect(res.status).toBe(404);expect(mocks.query).toHaveBeenCalledWith(expect.stringContaining('id=$1 AND company_id=$2'),[OTHER,'co-a']);});
});
describe('Bank reconciliation state machine',()=>{
 it('returns only direction-compatible candidates with linked obligation context',async()=>{setContext(['bank.view']);mocks.query.mockImplementation(async(sql:string)=>{if(sql.includes('FROM bank_transactions'))return{rows:[tx('unmatched','1150.00')]};if(sql.includes('FROM bank_transaction_matches'))return{rows:[]};if(sql.includes('FROM documents d'))return{rows:[{...approved,document_type:'sale',linked_obligation:{id:'ob-a',direction:'receivable',counterparty:'Customer A',original_amount:'1150.00',settled_amount:'150.00',remaining_amount:'1000.00',state:'partial'}},{...approved,id:OTHER,document_type:'expense',linked_obligation:null}]};return{rows:[]};});const res=await request(app).get(`/api/bank-transactions/${TX}/match-candidates`);expect(res.status).toBe(200);expect(res.body.documents).toEqual([expect.objectContaining({id:DOC,document_type:'sale',linked_obligation:expect.objectContaining({id:'ob-a',direction:'receivable',remaining_amount:'1000.00',state:'partial'})})]);expect(mocks.query).toHaveBeenCalledWith(expect.stringContaining("o.document_id=d.id AND o.company_id=d.company_id"),['co-a']);});
 it('matches an eligible document and writes audit atomically',async()=>{setContext(['bank.match']);const client=makeClient(sql=>{if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('unmatched')]};if(sql.includes('FROM documents'))return{rows:[approved]};if(sql.includes('INSERT INTO bank_transaction_matches'))return{rows:[match]};if(sql.includes('UPDATE bank_transactions'))return{rows:[]};return{rows:[]};});mocks.connect.mockResolvedValue(client);const res=await request(app).post(`/api/bank-transactions/${TX}/match`).send({document_id:DOC});expect(res.status).toBe(201);expect(res.body.status).toBe('matched');expect(mocks.auditLogEvent).toHaveBeenCalledWith(expect.objectContaining({action:'bank_transaction.match',company_id:'co-a'}),client);expect(client.query).toHaveBeenCalledWith(expect.stringContaining('FOR UPDATE'),[TX,'co-a']);});
 it('rejects a document whose type conflicts with the bank transaction direction',async()=>{setContext(['bank.match']);const client=makeClient(sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('unmatched','100.00')]};if(sql.includes('FROM documents'))return{rows:[approved]};return{rows:[]};});mocks.connect.mockResolvedValue(client);const res=await request(app).post(`/api/bank-transactions/${TX}/match`).send({document_id:DOC});expect(res.status).toBe(409);expect(res.body.error).toMatch(/direction/i);});
 it('requires payment.settle as well as bank.reconcile for a document reconciliation',async()=>{setContext(['bank.reconcile']);const client=makeClient(sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('matched')]};if(sql.includes('FROM bank_transaction_matches'))return{rows:[match]};return{rows:[]};});mocks.connect.mockResolvedValue(client);expect((await request(app).post(`/api/bank-transactions/${TX}/reconciliation`).send({status:'reconciled'})).status).toBe(403);});
 it('creates the exact matched document settlement before reconciling',async()=>{setContext(['bank.reconcile','payment.settle']);const inserted:{documentId?:unknown;amount?:unknown}={};const client=makeClient((sql,params)=>{if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('matched','1150.00')]};if(sql.includes('FROM bank_transaction_matches'))return{rows:[match]};if(sql.includes('FROM documents'))return{rows:[{...approved,document_type:'sale',total_amount:'1150.00'}]};if(sql.includes('SUM(amount)'))return{rows:[{total:'0'}]};if(sql.includes("FROM obligations WHERE document_id=$1"))return{rows:[{id:'ob-a',original_amount:'1150.00'}]};if(sql.includes('INSERT INTO document_settlements')){inserted.documentId=params?.[1];inserted.amount=params?.[3];return{rows:[{id:'66666666-6666-4666-8666-666666666666',company_id:'co-a',document_id:DOC,bank_transaction_id:TX,amount:'1150.00',created_by_user_id:mocks.context!.user.id,created_at:new Date(),note:null}]};}return{rows:[]};});mocks.connect.mockResolvedValue(client);const res=await request(app).post(`/api/bank-transactions/${TX}/reconciliation`).send({status:'reconciled'});expect(res.status).toBe(200);expect(inserted).toEqual({documentId:DOC,amount:'1150.00'});expect(client.query).toHaveBeenCalledWith('COMMIT');expect(mocks.auditLogEvent).toHaveBeenCalledWith(expect.objectContaining({action:'document_settlement.create'}),client);expect(mocks.auditLogEvent).toHaveBeenCalledWith(expect.objectContaining({action:'bank_transaction.reconcile'}),client);});
 it('rolls back settlement validation failure without state transition or reconciliation audit',async()=>{setContext(['bank.reconcile','payment.settle']);const client=makeClient(sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('matched','1150.00')]};if(sql.includes('FROM bank_transaction_matches'))return{rows:[match]};if(sql.includes('FROM documents'))return{rows:[{...approved,document_type:'sale',total_amount:'1000.00'}]};if(sql.includes('SUM(amount)'))return{rows:[{total:'0'}]};return{rows:[]};});mocks.connect.mockResolvedValue(client);const res=await request(app).post(`/api/bank-transactions/${TX}/reconciliation`).send({status:'reconciled'});expect(res.status).toBe(409);expect(client.query).toHaveBeenCalledWith('ROLLBACK');expect(client.query).not.toHaveBeenCalledWith(expect.stringContaining('INSERT INTO document_settlements'),expect.anything());expect(client.query).not.toHaveBeenCalledWith(expect.stringContaining('UPDATE bank_transactions'),expect.anything());expect(mocks.auditLogEvent).not.toHaveBeenCalled();});
 it('allows custody explanation to reconcile without document approval',async()=>{setContext(['bank.reconcile']);const custodyMatch={...match,document_id:null,custody_id:CUSTODY,match_type:'custody_funding'};const client=makeClient(sql=>{if(sql==='BEGIN'||sql==='COMMIT')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('matched')]};if(sql.includes('FROM bank_transaction_matches'))return{rows:[custodyMatch]};if(sql.includes('FROM custody_advances'))return{rows:[{id:CUSTODY}]};if(sql.includes('UPDATE bank_transactions'))return{rows:[]};return{rows:[]};});mocks.connect.mockResolvedValue(client);const res=await request(app).post(`/api/bank-transactions/${TX}/reconciliation`).send({status:'reconciled'});expect(res.status).toBe(200);expect(res.body.status).toBe('reconciled');expect(client.query).not.toHaveBeenCalledWith(expect.stringContaining('INSERT INTO document_settlements'),expect.anything());});
 it('prevents generic unmatch of custody relationships',async()=>{setContext(['bank.match']);const custodyMatch={...match,document_id:null,custody_id:CUSTODY,match_type:'custody_return'};const client=makeClient(sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('matched')]};if(sql.includes('FROM bank_transaction_matches'))return{rows:[custodyMatch]};return{rows:[]};});mocks.connect.mockResolvedValue(client);expect((await request(app).delete(`/api/bank-transactions/${TX}/match`)).status).toBe(409);});
 it('prevents direct unmatch of a reconciled transaction',async()=>{setContext(['bank.match']);const client=makeClient(sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('reconciled')]};return{rows:[]};});mocks.connect.mockResolvedValue(client);expect((await request(app).delete(`/api/bank-transactions/${TX}/match`)).status).toBe(409);});
 it('rejects reopening while the document settlement remains intact',async()=>{setContext(['bank.reconcile']);const client=makeClient(sql=>{if(sql==='BEGIN'||sql==='ROLLBACK')return{rows:[]};if(sql.includes('FROM bank_transactions'))return{rows:[tx('reconciled')]};if(sql.includes('FROM bank_transaction_matches'))return{rows:[match]};if(sql.includes('FROM document_settlements'))return{rows:[{id:'66666666-6666-4666-8666-666666666666'}]};return{rows:[]};});mocks.connect.mockResolvedValue(client);const res=await request(app).post(`/api/bank-transactions/${TX}/reconciliation`).send({status:'matched'});expect(res.status).toBe(409);expect(client.query).toHaveBeenCalledWith('ROLLBACK');expect(client.query).not.toHaveBeenCalledWith(expect.stringContaining('DELETE FROM document_settlements'),expect.anything());expect(client.query).not.toHaveBeenCalledWith(expect.stringContaining('UPDATE bank_transactions'),expect.anything());expect(mocks.auditLogEvent).not.toHaveBeenCalled();});
});
