import { Pool, PoolClient } from 'pg';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { CompanyAccountingProfileService } from '../src/modules/company-accounting-profile/company-accounting-profile.service';
import { CompanyAccountingProfile, ProfileConflictError, ProfileNotFoundError, ProfileValidationError, ProfileValues } from '../src/modules/company-accounting-profile/company-accounting-profile.types';

const COMPANY='11111111-1111-4111-8111-111111111111';
const OTHER='22222222-2222-4222-8222-222222222222';
const ACTOR='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const ID='33333333-3333-4333-8333-333333333333';
const values:ProfileValues={accounting_framework:'IFRS',accounting_framework_notes:null,functional_currency:'SAR',reporting_currency:'SAR',first_live_accounting_date:'2026-01-01',vat_status:'not_registered',vat_registration_number:null,vat_registered_from:null,vat_deregistered_from:null,vat_filing_frequency:null,tax_treatment:'zakat_applicable',ownership_context:'saudi_gcc_only',tax_effective_from:null,tax_notes:null,wht_profile:'not_currently_applicable',has_non_resident_dealings:'no',effective_from:'2026-01-01',effective_to:null,change_reason:'initial'};
const profile=(status:CompanyAccountingProfile['workflow_status']='draft',overrides:Partial<CompanyAccountingProfile>={}):CompanyAccountingProfile=>({id:ID,company_id:COMPANY,version_no:1,workflow_status:status,...values,prepared_by_user_id:ACTOR,reviewed_by_user_id:null,reviewed_at:null,approved_by_user_id:null,approved_at:null,created_at:new Date(),updated_at:new Date(),closed_period_impact:false,professional_review_required:false,...overrides});

function setup(){
  const commands:string[]=[];
  const client={query:vi.fn(async(sql:string)=>{commands.push(sql);return{rows:[],rowCount:0};}),release:vi.fn()} as unknown as PoolClient;
  const pool={connect:vi.fn(async()=>client)} as unknown as Pool;
  const service=new CompanyAccountingProfileService(pool);
  const repo={hasAny:vi.fn(),create:vi.fn(),closedPeriodImpact:vi.fn().mockResolvedValue(false),byId:vi.fn(),updateDraft:vi.fn(),transition:vi.fn(),latestApproved:vi.fn(),nextVersion:vi.fn(),approvedOverlaps:vi.fn(),closeEffectivePeriod:vi.fn(),current:vi.fn(),history:vi.fn()};
  const audit={logEvent:vi.fn().mockResolvedValue({})};
  Object.assign(service as unknown as {repo:unknown;audit:unknown},{repo,audit});
  return{service,repo,audit,commands,client};
}

describe('company accounting profile service',()=>{
  beforeEach(()=>vi.clearAllMocks());
  it('creates initial version one, detects closed-period impact, and audits atomically',async()=>{const x=setup();x.repo.hasAny.mockResolvedValue(false);x.repo.create.mockResolvedValue(profile());x.repo.closedPeriodImpact.mockResolvedValue(true);const result=await x.service.createInitial(COMPANY,ACTOR,values);expect(x.repo.create).toHaveBeenCalledWith(COMPANY,1,ACTOR,values,x.client);expect(result.closed_period_impact).toBe(true);expect(x.audit.logEvent).toHaveBeenCalledWith(expect.objectContaining({company_id:COMPANY,action:'company_accounting_profile.create'}),x.client);expect(x.commands).toEqual(expect.arrayContaining(['BEGIN','COMMIT']));});
  it('rejects a second initial profile with no mutation or audit',async()=>{const x=setup();x.repo.hasAny.mockResolvedValue(true);await expect(x.service.createInitial(COMPANY,ACTOR,values)).rejects.toBeInstanceOf(ProfileConflictError);expect(x.repo.create).not.toHaveBeenCalled();expect(x.audit.logEvent).not.toHaveBeenCalled();expect(x.commands).toContain('ROLLBACK');});
  it('updates only a tenant-owned draft and blocks approved or cross-company identifiers',async()=>{const x=setup();x.repo.byId.mockResolvedValueOnce(profile()).mockResolvedValueOnce(profile('approved')).mockResolvedValueOnce(null);x.repo.updateDraft.mockResolvedValue(profile('draft',{tax_notes:'changed'}));await x.service.updateDraft(COMPANY,ACTOR,ID,{tax_notes:'changed'});expect(x.repo.byId).toHaveBeenCalledWith(COMPANY,ID,x.client,true);expect(x.audit.logEvent).toHaveBeenCalledWith(expect.objectContaining({action:'company_accounting_profile.update_draft'}),x.client);await expect(x.service.updateDraft(COMPANY,ACTOR,ID,{tax_notes:'x'})).rejects.toBeInstanceOf(ProfileConflictError);await expect(x.service.updateDraft(OTHER,ACTOR,ID,{tax_notes:'x'})).rejects.toBeInstanceOf(ProfileNotFoundError);});
  it('enforces draft to needs_review to reviewed and rejects direct approval',async()=>{const x=setup();x.repo.byId.mockResolvedValueOnce(profile()).mockResolvedValueOnce(profile('needs_review')).mockResolvedValueOnce(profile());x.repo.transition.mockResolvedValueOnce(profile('needs_review')).mockResolvedValueOnce(profile('reviewed'));await x.service.submitReview(COMPANY,ACTOR,ID);await x.service.review(COMPANY,ACTOR,ID);await expect(x.service.approve(COMPANY,ACTOR,ID)).rejects.toBeInstanceOf(ProfileConflictError);expect(x.repo.transition).toHaveBeenNthCalledWith(1,COMPANY,ID,'draft','needs_review',ACTOR,x.client);expect(x.repo.transition).toHaveBeenNthCalledWith(2,COMPANY,ID,'needs_review','reviewed',ACTOR,x.client);expect(x.audit.logEvent.mock.calls.map(c=>c[0].action)).toEqual(['company_accounting_profile.submit_review','company_accounting_profile.review']);});
  it('approves reviewed profile, supersedes without deleting history, and audits both changes',async()=>{const x=setup();const reviewed=profile('reviewed',{version_no:2,effective_from:'2026-07-01'});const old=profile('approved',{id:'44444444-4444-4444-8444-444444444444'});const closed={...old,effective_to:'2026-06-30'};x.repo.byId.mockResolvedValue(reviewed);x.repo.approvedOverlaps.mockResolvedValue([old]);x.repo.closeEffectivePeriod.mockResolvedValue(closed);x.repo.transition.mockResolvedValue(profile('approved',{version_no:2,effective_from:'2026-07-01'}));await x.service.approve(COMPANY,ACTOR,ID);expect(x.repo.closeEffectivePeriod).toHaveBeenCalledWith(COMPANY,old.id,'2026-06-30',x.client);expect(x.repo.transition).toHaveBeenCalledWith(COMPANY,ID,'reviewed','approved',ACTOR,x.client);expect(x.audit.logEvent.mock.calls.map(c=>c[0].action)).toEqual(['company_accounting_profile.supersede','company_accounting_profile.approve']);});
  it('prevents effective overlap that cannot be superseded safely',async()=>{const x=setup();const reviewed=profile('reviewed',{effective_from:'2026-01-01'});x.repo.byId.mockResolvedValue(reviewed);x.repo.approvedOverlaps.mockResolvedValue([profile('approved',{effective_from:'2026-01-01'})]);await expect(x.service.approve(COMPANY,ACTOR,ID)).rejects.toBeInstanceOf(ProfileConflictError);expect(x.repo.transition).not.toHaveBeenCalled();expect(x.commands).toContain('ROLLBACK');});
  it('creates the safe next version from an approved row and preserves it',async()=>{const x=setup();x.repo.latestApproved.mockResolvedValue(profile('approved'));x.repo.nextVersion.mockResolvedValue(2);x.repo.create.mockResolvedValue(profile('draft',{version_no:2}));await x.service.createVersion(COMPANY,ACTOR,{change_reason:'material'});expect(x.repo.nextVersion).toHaveBeenCalledWith(COMPANY,x.client);expect(x.repo.create).toHaveBeenCalledWith(COMPANY,2,ACTOR,expect.objectContaining({change_reason:'material'}),x.client);expect(x.repo.closeEffectivePeriod).not.toHaveBeenCalled();});
  it.each([
    [{...values,vat_status:'registered' as const},'Registered VAT fields are required'],
    [{...values,vat_registration_number:'123'},'Not-registered VAT profile is contradictory'],
    [{...values,effective_from:null},'Approved profile requires effective_from'],
  ])('propagates VAT and approval validation without writing',async(bad,message)=>{const x=setup();if(message==='Approved profile requires effective_from'){x.repo.byId.mockResolvedValue(profile('reviewed',{effective_from:null}));await expect(x.service.approve(COMPANY,ACTOR,ID)).rejects.toThrow(message);}else await expect(x.service.createInitial(COMPANY,ACTOR,bad)).rejects.toThrow(message);expect(x.repo.create).not.toHaveBeenCalled();});
  it('marks deterministic accounting/tax uncertainty through persisted profile metadata',()=>{for(const changed of [{accounting_framework:'Other / accountant-reviewed'},{tax_treatment:'needs_review'},{ownership_context:'unknown_needs_review'},{wht_profile:'needs_review'},{has_non_resident_dealings:'unknown'}]){const p=profile('draft',changed as Partial<CompanyAccountingProfile>);const required=p.accounting_framework==='Other / accountant-reviewed'||p.tax_treatment==='needs_review'||p.ownership_context==='unknown_needs_review'||p.wht_profile==='needs_review'||p.has_non_resident_dealings==='unknown';expect(required).toBe(true);}});
  it('rolls back the business transaction when its audit insert fails',async()=>{const x=setup();x.repo.hasAny.mockResolvedValue(false);x.repo.create.mockResolvedValue(profile());x.audit.logEvent.mockRejectedValue(new Error('audit failed'));await expect(x.service.createInitial(COMPANY,ACTOR,values)).rejects.toThrow('audit failed');expect(x.commands).toContain('ROLLBACK');expect(x.commands).not.toContain('COMMIT');});
});
