import express,{NextFunction,Request,Response}from'express';
import request from'supertest';
import{beforeEach,describe,expect,it,vi}from'vitest';
import{ProfileNotFoundError}from'../src/modules/company-accounting-profile/company-accounting-profile.types';

const COMPANY='11111111-1111-4111-8111-111111111111',OTHER='22222222-2222-4222-8222-222222222222',USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',ID='33333333-3333-4333-8333-333333333333';
const mocks=vi.hoisted(()=>({context:null as null|{user:{id:string};activeCompanyId:string|null;capabilities:string[]},current:vi.fn(),history:vi.fn(),get:vi.fn(),createInitial:vi.fn(),createVersion:vi.fn(),updateDraft:vi.fn(),updateProfessionalReview:vi.fn(),submitReview:vi.fn(),review:vi.fn(),returnForReview:vi.fn(),approve:vi.fn()}));
vi.mock('../src/db/pool',()=>({default:{query:vi.fn(),connect:vi.fn()}}));
vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:()=>mocks.context,requireAuth:(_q:Request,s:Response,n:NextFunction)=>mocks.context?n():void s.status(401).json({error:'Unauthenticated'}),requireActiveCompany:(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId?n():void s.status(403).json({error:'No active company'}),requireCapability:(capability:string)=>(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId&&mocks.context.capabilities.includes(capability)?n():void s.status(403).json({error:'Forbidden'})}));
vi.mock('../src/modules/company-accounting-profile/company-accounting-profile.service',()=>({CompanyAccountingProfileService:class{current=mocks.current;history=mocks.history;get=mocks.get;createInitial=mocks.createInitial;createVersion=mocks.createVersion;updateDraft=mocks.updateDraft;updateProfessionalReview=mocks.updateProfessionalReview;submitReview=mocks.submitReview;review=mocks.review;returnForReview=mocks.returnForReview;approve=mocks.approve;}}));
const{companyAccountingProfileRouter}=await import('../src/modules/company-accounting-profile/company-accounting-profile.router');
const app=express();app.use(express.json());app.use('/api',companyAccountingProfileRouter);app.use((error:unknown,_q:Request,res:Response,_n:NextFunction)=>res.status(500).json({error:error instanceof Error?error.message:'error'}));
const draft={accounting_framework:'IFRS',functional_currency:'SAR',reporting_currency:'SAR',first_live_accounting_date:'2026-01-01',vat_status:'not_registered',tax_treatment:'zakat_applicable',ownership_context:'saudi_gcc_only',wht_profile:'not_currently_applicable',has_non_resident_dealings:'no'};
function context(capabilities:string[],company:string|null=COMPANY){mocks.context={user:{id:USER},activeCompanyId:company,capabilities};}
beforeEach(()=>{mocks.context=null;for(const value of Object.values(mocks))if(typeof value==='function'&&'mockReset'in value)(value as ReturnType<typeof vi.fn>).mockReset();});

describe('company accounting profile HTTP authorization and tenancy',()=>{
  it('denies the view endpoint without company_accounting_profile.view',async()=>{context([]);expect((await request(app).get('/api/company-accounting-profiles/current')).status).toBe(403);expect(mocks.current).not.toHaveBeenCalled();});
  it.each([
    ['company_accounting_profile.create','post','/api/company-accounting-profiles',draft],
    ['company_accounting_profile.create','post','/api/company-accounting-profiles/versions',{change_reason:'new basis'}],
    ['company_accounting_profile.edit','patch',`/api/company-accounting-profiles/${ID}`,{tax_notes:'x'}],
    ['company_accounting_profile.submit','post',`/api/company-accounting-profiles/${ID}/submit-review`,{}],
  ] as const)('requires %s for %s %s',async(capability,method,path,body)=>{context([]);expect((await request(app)[method](path).send(body)).status).toBe(403);context([capability]);const serviceMethod=path.endsWith('/versions')?mocks.createVersion:path.endsWith('/submit-review')?mocks.submitReview:method==='patch'?mocks.updateDraft:mocks.createInitial;serviceMethod.mockResolvedValue({id:ID});expect((await request(app)[method](path).send(body)).status).toBeLessThan(300);});
  it.each(['company_accounting_profile.create','company_accounting_profile.edit','company_accounting_profile.submit','company_accounting_profile.review','company_accounting_profile.approve','company_accounting_profile.manage'])('%s alone cannot authorize other corrected actions',async capability=>{context([capability]);const responses=await Promise.all([request(app).post('/api/company-accounting-profiles').send(draft),request(app).post('/api/company-accounting-profiles/versions').send({change_reason:'new basis'}),request(app).patch(`/api/company-accounting-profiles/${ID}`).send({tax_notes:'x'}),request(app).post(`/api/company-accounting-profiles/${ID}/submit-review`).send({})]);const expected=capability==='company_accounting_profile.create'?[201,201,403,403]:capability==='company_accounting_profile.edit'?[403,403,200,403]:capability==='company_accounting_profile.submit'?[403,403,403,200]:[403,403,403,403];expect(responses.map(response=>response.status)).toEqual(expected);});
  it('denies reviewer corrections and transitions without company_accounting_profile.review',async()=>{context(['company_accounting_profile.create','company_accounting_profile.edit','company_accounting_profile.submit']);expect((await request(app).patch(`/api/company-accounting-profiles/${ID}/professional-review`).send({tax_treatment:'zakat_applicable'})).status).toBe(403);expect(mocks.updateProfessionalReview).not.toHaveBeenCalled();expect((await request(app).post(`/api/company-accounting-profiles/${ID}/review`).send({})).status).toBe(403);expect(mocks.review).not.toHaveBeenCalled();expect((await request(app).post(`/api/company-accounting-profiles/${ID}/return-review`).send({reason:'fix'})).status).toBe(403);expect(mocks.returnForReview).not.toHaveBeenCalled();});
  it('denies approval without company_accounting_profile.approve',async()=>{context(['company_accounting_profile.review']);expect((await request(app).post(`/api/company-accounting-profiles/${ID}/approve`).send({})).status).toBe(403);expect(mocks.approve).not.toHaveBeenCalled();});
  it('requires an active company and always passes that company to reads',async()=>{context(['company_accounting_profile.view'],null);expect((await request(app).get('/api/company-accounting-profiles/history')).status).toBe(403);context(['company_accounting_profile.view'],OTHER);mocks.current.mockResolvedValue(null);expect((await request(app).get('/api/company-accounting-profiles/current')).status).toBe(200);expect(mocks.current).toHaveBeenCalledWith(OTHER,undefined);});
  it('does not expose or mutate a valid UUID owned by another company',async()=>{context(['company_accounting_profile.view','company_accounting_profile.edit','company_accounting_profile.review'],OTHER);mocks.get.mockRejectedValue(new ProfileNotFoundError());mocks.updateDraft.mockRejectedValue(new ProfileNotFoundError());mocks.updateProfessionalReview.mockRejectedValue(new ProfileNotFoundError());expect((await request(app).get(`/api/company-accounting-profiles/${ID}`)).status).toBe(404);expect(mocks.get).toHaveBeenCalledWith(OTHER,ID);expect((await request(app).patch(`/api/company-accounting-profiles/${ID}`).send({tax_notes:'x'})).status).toBe(404);expect(mocks.updateDraft).toHaveBeenCalledWith(OTHER,USER,ID,{tax_notes:'x'});expect((await request(app).patch(`/api/company-accounting-profiles/${ID}/professional-review`).send({tax_notes:'x'})).status).toBe(404);expect(mocks.updateProfessionalReview).toHaveBeenCalledWith(OTHER,USER,ID,{tax_notes:'x'});});
  it('enforces same-origin protection before every write',async()=>{context(['company_accounting_profile.create','company_accounting_profile.edit','company_accounting_profile.submit','company_accounting_profile.review','company_accounting_profile.approve']);for(const call of [request(app).post('/api/company-accounting-profiles').send(draft),request(app).patch(`/api/company-accounting-profiles/${ID}`).send({tax_notes:'x'}),request(app).patch(`/api/company-accounting-profiles/${ID}/professional-review`).send({tax_notes:'x'}),request(app).post(`/api/company-accounting-profiles/${ID}/review`).send({}),request(app).post(`/api/company-accounting-profiles/${ID}/return-review`).send({reason:'fix'}),request(app).post(`/api/company-accounting-profiles/${ID}/approve`).send({})]){expect((await call.set('Origin','https://evil.example')).status).toBe(403);}expect(mocks.createInitial).not.toHaveBeenCalled();expect(mocks.updateDraft).not.toHaveBeenCalled();expect(mocks.updateProfessionalReview).not.toHaveBeenCalled();expect(mocks.review).not.toHaveBeenCalled();expect(mocks.returnForReview).not.toHaveBeenCalled();expect(mocks.approve).not.toHaveBeenCalled();});
  it('allows only professional fields through the reviewer correction endpoint',async()=>{context(['company_accounting_profile.review']);mocks.updateProfessionalReview.mockResolvedValue({id:ID,company_id:COMPANY,workflow_status:'needs_review'});expect((await request(app).patch(`/api/company-accounting-profiles/${ID}/professional-review`).send({tax_treatment:'zakat_applicable',tax_notes:' reviewed '})).status).toBe(200);expect(mocks.updateProfessionalReview).toHaveBeenCalledWith(COMPANY,USER,ID,{tax_treatment:'zakat_applicable',tax_notes:'reviewed'});expect((await request(app).patch(`/api/company-accounting-profiles/${ID}/professional-review`).send({functional_currency:'USD'})).status).toBe(400);expect((await request(app).patch(`/api/company-accounting-profiles/${ID}/professional-review`).send({})).status).toBe(400);expect(mocks.updateProfessionalReview).toHaveBeenCalledTimes(1);});
  it('allows the reviewer return path only for a valid reason and active tenant',async()=>{context(['company_accounting_profile.review']);mocks.returnForReview.mockResolvedValue({id:ID,company_id:COMPANY,workflow_status:'needs_review'});expect((await request(app).post(`/api/company-accounting-profiles/${ID}/return-review`).send({reason:' Correct evidence '})).status).toBe(200);expect(mocks.returnForReview).toHaveBeenCalledWith(COMPANY,USER,ID,' Correct evidence ');expect((await request(app).post(`/api/company-accounting-profiles/${ID}/return-review`).send({reason:' '})).status).toBe(400);});
});
