import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
const sql=readFileSync(new URL('../migrations/015_custody_advances.sql',import.meta.url),'utf8');
const source=readFileSync(new URL('../src/modules/banking/custody.router.ts',import.meta.url),'utf8');
describe('Phase 3D custody integrity',()=>{
 it('adds independent custody capabilities',()=>expect(sql).toContain("VALUES ('custody.view'), ('custody.manage'), ('custody.close')"));
 it('keeps custody company scoped',()=>expect(sql).toMatch(/UNIQUE \(id, company_id\)/));
 it('binds holder to a membership in the same company',()=>expect(sql).toMatch(/FOREIGN KEY \(holder_user_id, company_id\)[\s\S]*memberships\(user_id, company_id\)/));
 it('extends one bank match boundary with explicit match types',()=>{expect(sql).toContain("match_type TEXT NOT NULL DEFAULT 'document'");expect(sql).toContain("'custody_funding','custody_return'");});
 it('requires exactly one document or custody target',()=>expect(sql).toMatch(/match_type='document'[\s\S]*document_id IS NOT NULL[\s\S]*custody_id IS NULL[\s\S]*custody_funding[\s\S]*document_id IS NULL[\s\S]*custody_id IS NOT NULL/));
 it('enforces same-company custody match FK',()=>expect(sql).toMatch(/FOREIGN KEY \(custody_id, company_id\)[\s\S]*custody_advances\(id, company_id\)/));
 it('enforces same-company document allocation FKs',()=>{expect(sql).toMatch(/FOREIGN KEY \(custody_id, company_id\)[\s\S]*custody_advances\(id, company_id\)/);expect(sql).toMatch(/FOREIGN KEY \(document_id, company_id\)[\s\S]*documents\(id, company_id\)/);});
 it('prevents multiple custody sources for one document in this phase',()=>expect(sql).toMatch(/UNIQUE \(document_id\)/));
 it('allows only positive allocation amounts',()=>expect(sql).toContain('CHECK (amount > 0)'));
 it('keeps close metadata consistent with status',()=>expect(sql).toMatch(/status='closed'[\s\S]*closed_by_user_id IS NOT NULL[\s\S]*closed_at IS NOT NULL/));
 it('uses exact integer-cent arithmetic',()=>{expect(source).toContain('BigInt');expect(source).toContain('100n');expect(source).not.toContain('toFixed(');});
 it('requires outbound funding and inbound returns',()=>{expect(source).toContain('Custody funding requires an outbound bank transaction');expect(source).toContain('Custody return requires an inbound bank transaction');});
 it('rejects reuse of already matched transactions',()=>expect(source).toContain('Bank transaction is already matched'));
 it('rejects document with an existing funding source',()=>expect(source).toContain('Document already has a funding source'));
 it('requires approved documents',()=>expect(source).toContain('Document must be approved with a total amount'));
 it('requires a custody-funded document to be fully funded in this single-source phase',()=>expect(source).toContain('Custody allocation must equal document total in this phase'));
 it('prevents allocation and return over the remaining amount',()=>{expect(source).toContain('Allocation exceeds custody remaining amount');expect(source).toContain('Return exceeds custody remaining amount');});
 it('does not hide a negative custody balance',()=>expect(source).toContain('Custody balances are inconsistent'));
 it('requires same currency for a bank return',()=>expect(source).toContain('Return currency must match custody funding currency'));
 it('locks custody, documents, and bank transactions during mutations',()=>expect((source.match(/FOR UPDATE/g)??[]).length).toBeGreaterThanOrEqual(3));
 it('requires zero remaining amount before close',()=>expect(source).toContain('Custody cannot close while a balance remains'));
 it('records create allocate remove return unlink close and reopen audits',()=>{for(const action of ['custody.create','custody.document.allocate','custody.document.remove','custody.return.link','custody.return.unlink','custody.close','custody.reopen'])expect(source).toContain(action);});
 it('requires reasons for allocation removal, return unlink, and reopen',()=>{expect(source).toMatch(/documents\/:allocationId'[\s\S]*reasonBody/);expect(source).toMatch(/returns\/:transactionId'[\s\S]*reasonBody/);expect(source).toMatch(/reopen'[\s\S]*reasonBody/);});
 it('uses same-origin and independent capability middleware on mutations',()=>{expect(source).toContain('requireSameOrigin');expect(source).toContain('requireCapability(MANAGE)');expect(source).toContain('requireCapability(CLOSE)');});
});
