import {describe,expect,it} from 'vitest';
import type{Pool}from'pg';
import{FixedAssetsService,FixedAssetConflictError,FixedAssetValidationError}from'../src/modules/fixed-assets/fixed-assets.router';
const COMPANY='11111111-1111-4111-8111-111111111111',USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',DOCUMENT='22222222-2222-4222-8222-222222222222',CATEGORY='33333333-3333-4333-8333-333333333333',ASSET='44444444-4444-4444-8444-444444444444';
const category={id:CATEGORY,company_id:COMPANY,depreciable:false,asset_account_id:null,accumulated_depreciation_account_id:null,depreciation_expense_account_id:null};
const document={id:DOCUMENT,total_amount:'100.00',document_date:'2026-01-15',reference_number:'PUR-1'};
class AssetPool{asset:any=null;connect=async()=>({query:this.query,release:()=>undefined});query=async(sql:string,args:unknown[]=[])=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return{rows:[],rowCount:0};if(sql.includes("SELECT id,total_amount::text,document_date::text,reference_number FROM documents"))return{rows:[document],rowCount:1};if(sql.includes('SELECT total_amount::text,document_date::text FROM documents'))return{rows:[document],rowCount:1};if(sql.includes('FROM asset_categories WHERE'))return{rows:[category],rowCount:1};if(sql.includes('FROM monthly_close_periods'))return{rows:[],rowCount:0};if(sql.includes('INSERT INTO fixed_assets')){this.asset={id:ASSET,company_id:COMPANY,asset_category_id:CATEGORY,asset_number:'FA-1',name:'Computer',description:null,source_type:'document',source_document_id:DOCUMENT,source_reference:'PUR-1',manual_reason:null,acquisition_cost:String(args[6]),acquisition_date:String(args[7]),placed_in_service_date:String(args[8]),depreciation_start_date:null,useful_life_months:null,residual_value:'0.00',opening_accumulated_depreciation:'0.00',depreciation_method:'straight_line',status:'draft',approved_by:null,approved_at:null,disposed_at:null,created_by:USER,created_at:new Date(),updated_at:new Date()};return{rows:[this.asset],rowCount:1}}if(sql.includes('SELECT *,acquisition_date::text,placed_in_service_date::text,depreciation_start_date::text FROM fixed_assets'))return{rows:this.asset?[this.asset]:[],rowCount:this.asset?1:0};if(sql.includes('SELECT a.*,a.acquisition_date::text'))return{rows:this.asset?[{...this.asset,...category}]:[],rowCount:this.asset?1:0};if(sql.includes('INSERT INTO audit_log'))return{rows:[{id:'audit'}],rowCount:1};throw Error(`Unexpected SQL: ${sql}`)};asPool(){return this as unknown as Pool}}
const input={asset_category_id:CATEGORY,name:'Computer',description:null,acquisition_cost:'100.00',acquisition_date:'2026-01-15',placed_in_service_date:'2026-01-15',depreciation_start_date:null,useful_life_months:null,residual_value:'0.00',opening_accumulated_depreciation:'0.00'};
async function created(){const db=new AssetPool(),service=new FixedAssetsService(db.asPool());await service.fromDocument(COMPANY,USER,{document_id:DOCUMENT,...input});return{db,service}}
describe('document-backed asset source integrity',()=>{
 it('rejects changing acquisition cost after creating the source-backed draft',async()=>{const{service}=await created();await expect(service.update(COMPANY,USER,ASSET,{acquisition_cost:'99.99'})).rejects.toBeInstanceOf(FixedAssetValidationError)});
 it('rejects changing acquisition date after creating the source-backed draft',async()=>{const{service}=await created();await expect(service.update(COMPANY,USER,ASSET,{acquisition_date:'2026-01-16'})).rejects.toBeInstanceOf(FixedAssetValidationError)});
 it('defensively rejects approval when persisted values diverge from the approved purchase',async()=>{const{db,service}=await created();db.asset.acquisition_cost='99.99';await expect(service.approve(COMPANY,USER,ASSET)).rejects.toBeInstanceOf(FixedAssetConflictError)});
 it('compares source amounts without Number or floating-point conversion',()=>{expect(FixedAssetsService.prototype.fromDocument.toString()).not.toContain('Number(');expect(FixedAssetsService.prototype.fromDocument.toString()).toContain('cents(')});
});
