import express,{NextFunction,Request,Response}from'express';
import request from'supertest';
import{beforeEach,describe,expect,it,vi}from'vitest';
import type{Pool,PoolClient}from'pg';

const COMPANY='11111111-1111-4111-8111-111111111111',OTHER='22222222-2222-4222-8222-222222222222',USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',FY='33333333-3333-4333-8333-333333333333',PERIOD='44444444-4444-4444-8444-444444444444';
const mocks=vi.hoisted(()=>({context:null as null|{user:{id:string};activeCompanyId:string;capabilities:string[]},pool:null as Pool|null,audit:vi.fn()}));
vi.mock('../src/db/pool',()=>({get default(){return mocks.pool}}));
vi.mock('../src/modules/audit-log/audit-log.repository',()=>({AuditLogRepository:class{logEvent=(event:unknown,client:unknown)=>mocks.audit(event,client)}}));
vi.mock('../src/modules/auth/origin.middleware',()=>({requireSameOrigin:(_q:Request,_s:Response,next:NextFunction)=>next()}));
vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:()=>mocks.context,requireAuth:(_q:Request,s:Response,n:NextFunction)=>mocks.context?n():void s.status(401).end(),requireActiveCompany:(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId?n():void s.status(403).end(),requireCapability:(capability:string)=>(_q:Request,s:Response,n:NextFunction)=>mocks.context?.capabilities.includes(capability)?n():void s.status(403).json({error:'Forbidden'})}));

const monthly=await import('../src/modules/monthly-close/monthly-close.router');
const{assertAccountingDateWritable}=await import('../src/modules/monthly-close/accounting-period.guard');
const{ObligationService}=await import('../src/modules/obligations/obligation.router');

type Result={rows:Record<string,unknown>[];rowCount:number};
const result=(rows:Record<string,unknown>[]=[]):Result=>({rows,rowCount:rows.length});
function poolFor(handler:(sql:string,args:unknown[])=>Result|Promise<Result>,assetCounts={pending:'0',drafts:'0'}){const query=vi.fn((sql:string,args:unknown[]=[])=>{const normalized=sql.replace(/\s+/g,' ');if(normalized.startsWith('SELECT d.id FROM asset_depreciation_entries')||normalized.startsWith('SELECT d.id FROM asset_disposals'))return result();if(normalized.startsWith('SELECT (SELECT COUNT(*) FROM asset_depreciation_entries'))return result([assetCounts]);if(normalized.startsWith('WITH material AS')||normalized.startsWith('WITH scoped AS'))return result();return handler(normalized,args)});const client={query,release:vi.fn()} as unknown as PoolClient;return{pool:{connect:vi.fn().mockResolvedValue(client),query}as unknown as Pool,client,query};}
const period=(status:'open'|'closed'='open',company=COMPANY)=>({id:PERIOD,company_id:company,fiscal_year_id:FY,period_start:'2026-01-01',period_end:'2026-01-31',status,created_at:new Date(),updated_at:new Date()});
const blockerRow=(documents=0,obligations=0,bank=0)=>({documents:String(documents),obligations:String(obligations),bank_transactions:String(bank)});
const vatBlockerRow=(unapproved=0,missing=0,pending=0)=>({unapproved_documents:String(unapproved),missing_reviews:String(missing),pending_reviews:String(pending)});
function createPool(options:{fiscalStart?:string;fiscalEnd?:string;overlap?:boolean}={}){return poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.includes('FROM fiscal_years'))return result([{start_date:options.fiscalStart??'2026-01-01',end_date:options.fiscalEnd??'2026-12-31'}]);if(sql.includes('SELECT 1 FROM monthly_close_periods'))return options.overlap?result([{one:1}]):result();if(sql.startsWith('INSERT INTO monthly_close_periods'))return result([period()]);throw new Error(sql);});}
type LedgerState={sourceCompany?:string;sourceDate?:string;sourceJournal?:'none'|'draft'|'posted';draftJournals?:number};
function transitionPool(status:'open'|'closed',blockers=blockerRow(),vatBlockers=vatBlockerRow(),ledger:LedgerState={}){const commands:string[]=[];const sourceId='55555555-5555-4555-8555-555555555555',sourceCompany=ledger.sourceCompany??COMPANY,sourceDate=ledger.sourceDate??'2026-01-15',sourceJournal=ledger.sourceJournal??'none';const built=poolFor((sql,args)=>{commands.push(sql);if(['BEGIN','COMMIT','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.includes('FROM monthly_close_periods WHERE id='))return args[1]===COMPANY?result([period(status)]):result();if(sql.includes('FROM monthly_close_periods WHERE company_id='))return args[0]===COMPANY?result([period(status)]):result();if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return sql.includes('unapproved_documents')?result([vatBlockers]):result([blockers]);if(sql.startsWith("SELECT id FROM obligations WHERE company_id=$1"))return args[0]===sourceCompany&&ledger.sourceCompany?result([{id:sourceId}]):result();if(sql.startsWith('SELECT d.id FROM asset_depreciation_entries')||sql.startsWith('SELECT d.id FROM asset_disposals'))return result();if(sql.startsWith('SELECT id FROM document_settlements')||sql.startsWith('SELECT id FROM obligation_settlements')||sql.startsWith('SELECT a.id FROM custody_document_allocations')||sql.startsWith('SELECT id FROM bank_transaction_matches'))return result();if(sql.startsWith("SELECT 'obligation' source_type"))return args[1]===sourceCompany?result([{source_type:'obligation',source_id:args[0],accounting_date:sourceDate,amount:'10.00',description:'Obligation',reference:null,context:{}}]):result();if(sql.includes("FROM journal_entries WHERE company_id=$1 AND source_type=$2")&&sql.includes("status='posted'"))return sourceJournal==='posted'?result([{one:1}]):result();if(sql.startsWith('SELECT COALESCE')&&sql.includes('asset_depreciation_entries'))return result([{pending:'0',drafts:'0'}]);if(sql.startsWith('SELECT source_type,source_id FROM journal_entries')&&sql.includes("status='draft'")){if(sourceJournal==='draft')return result([{source_type:'obligation',source_id:sourceId}]);return ledger.draftJournals?result(Array.from({length:ledger.draftJournals},()=>({source_type:null,source_id:null}))):result();}if(sql.startsWith('UPDATE monthly_close_periods'))return result([period(status==='open'?'closed':'open')]);throw new Error(sql);});return{...built,commands};}

beforeEach(()=>{mocks.context=null;mocks.pool=null;mocks.audit.mockReset().mockResolvedValue({});});

describe('MonthlyCloseService period creation',()=>{
 it('creates a valid calendar month inside the same-company fiscal year and audits atomically',async()=>{const built=createPool();const value=await new monthly.MonthlyCloseService(built.pool).create(COMPANY,USER,FY,'2026-01-01','2026-01-31');expect(value).toMatchObject({company_id:COMPANY,status:'open'});expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'monthly_close.create',company_id:COMPANY}),built.client);expect(built.query.mock.calls.map(c=>c[0])).toContain('COMMIT');});
 it('rejects a period outside its fiscal-year boundaries',async()=>{const built=createPool({fiscalStart:'2026-02-01'});await expect(new monthly.MonthlyCloseService(built.pool).create(COMPANY,USER,FY,'2026-01-01','2026-01-31')).rejects.toBeInstanceOf(monthly.MonthlyCloseValidationError);expect(built.query.mock.calls.map(c=>c[0])).toContain('ROLLBACK');});
 it('rejects an overlapping or duplicate period',async()=>{const built=createPool({overlap:true});await expect(new monthly.MonthlyCloseService(built.pool).create(COMPANY,USER,FY,'2026-01-01','2026-01-31')).rejects.toBeInstanceOf(monthly.MonthlyCloseConflictError);});
 it('rejects arbitrary multi-month ranges',async()=>{const built=createPool();await expect(new monthly.MonthlyCloseService(built.pool).create(COMPANY,USER,FY,'2026-01-15','2026-02-14')).rejects.toBeInstanceOf(monthly.MonthlyCloseValidationError);});
 it.each([
  ['truncated first month','2026-01-15','2026-12-31','2026-01-15','2026-01-31'],
  ['truncated last month','2026-01-01','2026-12-20','2026-12-01','2026-12-20'],
 ])('allows a %s at a fiscal-year boundary',async(_label,fiscalStart,fiscalEnd,start,end)=>{const built=createPool({fiscalStart,fiscalEnd});await expect(new monthly.MonthlyCloseService(built.pool).create(COMPANY,USER,FY,start,end)).resolves.toMatchObject({status:'open'});});
 it('rejects a non-boundary partial month',async()=>{const built=createPool();await expect(new monthly.MonthlyCloseService(built.pool).create(COMPANY,USER,FY,'2026-01-15','2026-01-31')).rejects.toBeInstanceOf(monthly.MonthlyCloseValidationError);});
});

describe('MonthlyCloseService blockers, isolation, audit, and state transitions',()=>{
 it.each([[1,0,0,'document'],[0,1,0,'obligation'],[0,0,1,'bank transaction']] as const)('rejects close for an unresolved %s blocker',async(documents,obligations,bank)=>{const built=transitionPool('open',blockerRow(documents,obligations,bank));await expect(new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD)).rejects.toBeInstanceOf(monthly.MonthlyCloseConflictError);expect(built.commands.some(sql=>sql.startsWith('UPDATE monthly_close_periods'))).toBe(false);expect(mocks.audit).not.toHaveBeenCalled();});
 it('blocks monthly close when VAT readiness is not ready',async()=>{const built=transitionPool('open',blockerRow(),vatBlockerRow(0,1,0));await expect(new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD)).rejects.toBeInstanceOf(monthly.MonthlyCloseConflictError);expect(built.commands.some(sql=>sql.startsWith('UPDATE monthly_close_periods'))).toBe(false);});
 it('removes the monthly close VAT blocker when VAT readiness becomes ready',async()=>{const built=transitionPool('open',blockerRow(),vatBlockerRow());await expect(new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD)).resolves.toMatchObject({status:'closed',ready:true,blockers:expect.objectContaining({vat:0})});});
 it('counts an eligible in-period operational source without a journal as one ledger blocker',async()=>{const built=transitionPool('open',blockerRow(),vatBlockerRow(),{sourceCompany:COMPANY,sourceJournal:'none'});await expect(new monthly.MonthlyCloseService(built.pool).list(COMPANY)).resolves.toMatchObject({periods:[{ready:false,blockers:{ledger:1}}]});});
 it('counts one incomplete approved material document once in the ledger blocker',async()=>{const query=vi.fn(async(sql:string)=>{const q=sql.replace(/\s+/g,' ');if(q.includes('FROM monthly_close_periods WHERE company_id='))return result([period()]);if(q.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return q.includes('unapproved_documents')?result([vatBlockerRow()]):result([blockerRow()]);if(q.startsWith('WITH material AS'))return result([{id:'44444444-4444-4444-8444-444444444444'}]);if(q.startsWith('WITH scoped AS'))return result();if(q.startsWith('SELECT d.id FROM asset_depreciation_entries')||q.startsWith('SELECT d.id FROM asset_disposals'))return result();if(q.startsWith('SELECT (SELECT COUNT(*) FROM asset_depreciation_entries'))return result([{pending:'0',drafts:'0'}]);if(q.startsWith('SELECT id FROM obligations')||q.startsWith('SELECT id FROM document_settlements')||q.startsWith('SELECT id FROM obligation_settlements')||q.startsWith('SELECT a.id FROM custody_document_allocations')||q.startsWith('SELECT id FROM bank_transaction_matches')||q.startsWith('SELECT source_type,source_id FROM journal_entries'))return result();throw new Error(q)});const db={query,connect:vi.fn()} as unknown as Pool;await expect(new monthly.MonthlyCloseService(db).list(COMPANY)).resolves.toMatchObject({periods:[{ready:false,blockers:{ledger:1}}]});});
 it('counts an eligible source bound only to a draft journal once',async()=>{const built=transitionPool('open',blockerRow(),vatBlockerRow(),{sourceCompany:COMPANY,sourceJournal:'draft'});await expect(new monthly.MonthlyCloseService(built.pool).list(COMPANY)).resolves.toMatchObject({periods:[{ready:false,blockers:{ledger:1}}]});});
 it('counts an independent in-period draft journal as one ledger blocker',async()=>{const built=transitionPool('open',blockerRow(),vatBlockerRow(),{draftJournals:1});await expect(new monthly.MonthlyCloseService(built.pool).list(COMPANY)).resolves.toMatchObject({periods:[{ready:false,blockers:{ledger:1}}]});});
 it('removes the ledger blocker after the source journal is posted',async()=>{const built=transitionPool('open',blockerRow(),vatBlockerRow(),{sourceCompany:COMPANY,sourceJournal:'posted'});await expect(new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD)).resolves.toMatchObject({status:'closed',ready:true,blockers:expect.objectContaining({ledger:0})});});
 it('ignores operational sources and draft journals belonging to another company',async()=>{const built=transitionPool('open',blockerRow(),vatBlockerRow(),{sourceCompany:OTHER,draftJournals:0});await expect(new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD)).resolves.toMatchObject({status:'closed',blockers:expect.objectContaining({ledger:0})});expect(built.commands.filter(sql=>sql.includes('journal_entries')).every((_,index)=>built.query.mock.calls.filter(call=>String(call[0]).includes('journal_entries'))[index]?.[1]?.[0]===COMPANY)).toBe(true);});
 it('ignores an eligible operational source outside the close period',async()=>{const built=transitionPool('open',blockerRow(),vatBlockerRow(),{sourceCompany:COMPANY,sourceDate:'2026-02-01',sourceJournal:'none'});await expect(new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD)).resolves.toMatchObject({status:'closed',blockers:expect.objectContaining({ledger:0})});});
 it('allows close when confirmed open/partial obligations and open custody are not blockers',async()=>{const built=transitionPool('open',blockerRow());await expect(new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD)).resolves.toMatchObject({status:'closed',ready:true});expect(built.commands.join(' ')).not.toContain('custody_advances');});
 it('writes successful close audit in the status transaction',async()=>{const built=transitionPool('open');await new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD);expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'monthly_close.close',before_data:{status:'open'},after_data:{status:'closed'}}),built.client);expect(built.commands.indexOf('COMMIT')).toBeGreaterThan(built.commands.findIndex(sql=>sql.startsWith('UPDATE monthly_close_periods')));});
 it('does not reveal or mutate a cross-company period id',async()=>{const built=transitionPool('open');await expect(new monthly.MonthlyCloseService(built.pool).close(OTHER,USER,PERIOD)).rejects.toBeInstanceOf(monthly.MonthlyCloseNotFoundError);expect(built.commands.some(sql=>sql.startsWith('UPDATE monthly_close_periods'))).toBe(false);});
 it('reopens with reason audit and then permits re-close',async()=>{const reopened=transitionPool('closed');await expect(new monthly.MonthlyCloseService(reopened.pool).reopen(COMPANY,USER,PERIOD,'Correct late invoice')).resolves.toMatchObject({status:'open'});expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'monthly_close.reopen',reason:'Correct late invoice'}),reopened.client);mocks.audit.mockClear();const reclose=transitionPool('open');await expect(new monthly.MonthlyCloseService(reclose.pool).close(COMPANY,USER,PERIOD)).resolves.toMatchObject({status:'closed'});expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'monthly_close.close'}),reclose.client);});
});


 it('blocks close for an unresolved document-backed Asset Draft',async()=>{const built=poolFor((sql)=>{if(sql.includes('FROM monthly_close_periods WHERE company_id='))return result([period()]);if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return sql.includes('unapproved_documents')?result([vatBlockerRow()]):result([blockerRow()]);if(sql.startsWith('SELECT id FROM obligations')||sql.startsWith('SELECT id FROM document_settlements')||sql.startsWith('SELECT id FROM obligation_settlements')||sql.startsWith('SELECT a.id FROM custody_document_allocations')||sql.startsWith('SELECT id FROM bank_transaction_matches')||sql.startsWith('SELECT source_type,source_id FROM journal_entries'))return result();throw Error(sql)},{pending:'0',drafts:'1'});await expect(new monthly.MonthlyCloseService(built.pool).list(COMPANY)).resolves.toMatchObject({periods:[{ready:false,blockers:expect.objectContaining({assets:1})}]});const query=String(built.query.mock.calls.find(call=>String(call[0]).includes('FROM fixed_assets'))?.[0]);expect(query).toContain("source_type='document'")});
 it('does not block close for a manual/opening Asset Draft',async()=>{const built=transitionPool('open');await expect(new monthly.MonthlyCloseService(built.pool).close(COMPANY,USER,PERIOD)).resolves.toMatchObject({ready:true,blockers:expect.objectContaining({assets:0})})});
 it('does not make an ordinary purchase without an Asset Draft an asset blocker',async()=>{const built=transitionPool('open');await expect(new monthly.MonthlyCloseService(built.pool).list(COMPANY)).resolves.toMatchObject({periods:[{blockers:expect.objectContaining({assets:0})}]})});

describe('monthly close HTTP authorization and validation',()=>{
 const app=express();app.use(express.json());app.use('/api',monthly.monthlyCloseRouter);app.use((error:unknown,_q:Request,res:Response,_n:NextFunction)=>res.status(500).json({error:error instanceof Error?error.message:'error'}));
 it('lists an empty set of monthly close periods',async()=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:['fiscal_year.view']};mocks.pool=poolFor((sql,args)=>{if(sql.includes('FROM monthly_close_periods WHERE company_id=')){expect(args).toEqual([COMPANY]);return result();}throw new Error(sql);}).pool;const response=await request(app).get('/api/monthly-close-periods');expect(response.status).toBe(200);expect(response.body).toEqual({periods:[]});});
 it('lists an existing period with string date bounds',async()=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:['fiscal_year.view']};mocks.pool=poolFor((sql,args)=>{if(sql.includes('FROM monthly_close_periods WHERE company_id=')){expect(args).toEqual([COMPANY]);return result([period()]);}if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents')){expect(args[0]).toBe(COMPANY);return sql.includes('unapproved_documents')?result([vatBlockerRow()]):result([blockerRow()]);}if(sql.startsWith('SELECT id FROM obligations')||sql.startsWith('SELECT id FROM document_settlements')||sql.startsWith('SELECT id FROM obligation_settlements')||sql.startsWith('SELECT a.id FROM custody_document_allocations')||sql.startsWith('SELECT id FROM bank_transaction_matches'))return result();if(sql.startsWith('SELECT COALESCE')&&sql.includes('asset_depreciation_entries'))return result([{pending:'0',drafts:'0'}]);if(sql.startsWith('SELECT source_type,source_id FROM journal_entries'))return result();throw new Error(sql);}).pool;const response=await request(app).get('/api/monthly-close-periods');expect(response.status).toBe(200);expect(response.body.periods).toEqual([expect.objectContaining({company_id:COMPANY,period_start:'2026-01-01',period_end:'2026-01-31',blockers:expect.objectContaining({vat:0,ledger:0})})]);});
 it('scopes listed periods to the active tenant',async()=>{mocks.context={user:{id:USER},activeCompanyId:OTHER,capabilities:['fiscal_year.view']};mocks.pool=poolFor((sql,args)=>{if(sql.includes('FROM monthly_close_periods WHERE company_id='))return args[0]===OTHER?result():result([period('open',COMPANY)]);throw new Error(sql);}).pool;const response=await request(app).get('/api/monthly-close-periods');expect(response.status).toBe(200);expect(response.body).toEqual({periods:[]});});
 it('requires monthly_close.close to close',async()=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:['fiscal_year.view']};expect((await request(app).post(`/api/monthly-close-periods/${PERIOD}/close`).send({})).status).toBe(403);});
 it('denies reopen to a user with close capability only',async()=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:['monthly_close.close']};expect((await request(app).post(`/api/monthly-close-periods/${PERIOD}/reopen`).send({reason:'x'})).status).toBe(403);});
 it.each([{reason:''},{reason:' '.repeat(3)},{reason:'x'.repeat(501)}])('rejects an invalid reopen reason %#',async body=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:['monthly_close.reopen']};expect((await request(app).post(`/api/monthly-close-periods/${PERIOD}/reopen`).send(body)).status).toBe(400);});
});

describe('closed-period write guard and shared advisory lock',()=>{
 function obligationPool(closed:boolean){return poolFor((sql,args)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.includes("FROM monthly_close_periods")&&sql.includes("status='closed'"))return closed&&String(args[1]).startsWith('2026-01')?result([{one:1}]):result();if(sql.includes('FROM counterparties'))return result([{one:1}]);if(sql.startsWith('INSERT INTO obligations'))return result([{id:'55555555-5555-4555-8555-555555555555',company_id:COMPANY,recognized_on:String(args[5]),status:'unconfirmed'}]);throw new Error(sql);});}
 const input={direction:'payable',counterparty_id:'66666666-6666-4666-8666-666666666666',document_id:null,original_amount:'10.00',recognized_on:'2026-01-20',due_on:null,verification_status:'unconfirmed',source_type:'manual',source_note:null};
 it('rejects an actual obligation create dated inside a closed period',async()=>{const built=obligationPool(true);await expect(new ObligationService(built.pool).createObligation(COMPANY,USER,input)).rejects.toThrow('Accounting period is closed');expect(built.query.mock.calls.some(call=>String(call[0]).startsWith('INSERT INTO obligations'))).toBe(false);});
 it('allows the equivalent obligation create outside a closed period',async()=>{const built=obligationPool(true);await expect(new ObligationService(built.pool).createObligation(COMPANY,USER,{...input,recognized_on:'2026-02-01'})).resolves.toMatchObject({company_id:COMPANY});expect(built.query.mock.calls.map(call=>call[0])).toContain('COMMIT');});
 it('uses the same company/month advisory key and orders it before close blockers and write checks',async()=>{const close=transitionPool('open');await new monthly.MonthlyCloseService(close.pool).close(COMPANY,USER,PERIOD);const closeLock=close.query.mock.calls.find(call=>String(call[0]).includes('pg_advisory_xact_lock'));const writeQueries:unknown[][]=[];const client={query:vi.fn(async(sql:string,args?:unknown[])=>{writeQueries.push([sql,args]);return result();})}as unknown as PoolClient;await assertAccountingDateWritable(COMPANY,'2026-01-20',client);const writeLock=writeQueries.find(call=>String(call[0]).includes('pg_advisory_xact_lock'));expect(closeLock?.[1]).toEqual(writeLock?.[1]);expect(close.commands.findIndex(sql=>sql.includes('pg_advisory_xact_lock'))).toBeLessThan(close.commands.findIndex(sql=>sql.startsWith('SELECT (SELECT COUNT(*)')));expect(String(writeQueries[0]![0])).toContain('pg_advisory_xact_lock');expect(String(writeQueries[1]![0])).toContain('monthly_close_periods');});
});
