import express,{NextFunction,Request,Response}from'express';import request from'supertest';import{beforeEach,describe,expect,it,vi}from'vitest';
const USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',COMPANY='11111111-1111-4111-8111-111111111111',O='22222222-2222-4222-8222-222222222222',BANK='33333333-3333-4333-8333-333333333333';
const mocks=vi.hoisted(()=>({context:null as any,audit:vi.fn(),pool:null as any}));
vi.mock('../src/db/pool',()=>({get default(){return mocks.pool}}));vi.mock('../src/modules/audit-log/audit-log.repository',()=>({AuditLogRepository:class{logEvent=async(e:unknown,c:unknown)=>mocks.audit(e,c)}}));vi.mock('../src/modules/auth/origin.middleware',()=>({requireSameOrigin:(_q:Request,_s:Response,n:NextFunction)=>n()}));vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:()=>mocks.context,requireAuth:(_q:Request,s:Response,n:NextFunction)=>mocks.context?n():void s.status(401).end(),requireActiveCompany:(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId?n():void s.status(403).end(),requireCapability:(c:string)=>(_q:Request,s:Response,n:NextFunction)=>mocks.context?.capabilities.includes(c)?n():void s.status(403).end()}));
const mod=await import('../src/modules/obligations/obligation.router');const app=express();app.use(express.json());app.use('/api',mod.obligationRouter);app.use((_e:unknown,_q:Request,s:Response,_n:NextFunction)=>s.status(500).end());
const ctx=(caps:string[])=>mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:caps};
function poolFor(handler:(sql:string,args:unknown[])=>any){let gate=Promise.resolve();return{query:vi.fn((s:string,a:unknown[]=[])=>handler(s.replace(/\s+/g,' '),a)),connect:vi.fn(async()=>{const prior=gate;let release!:()=>void;gate=new Promise(r=>release=r);await prior;return{query:async(s:string,a:unknown[]=[])=>{const r=await handler(s.replace(/\s+/g,' '),a);if(s==='COMMIT'||s==='ROLLBACK')release();return r},release:vi.fn()}})}};
beforeEach(()=>{mocks.context=null;mocks.audit.mockReset();mocks.pool=null});
describe('Phase 4B authorization',()=>{
 it('requires view on both read endpoints',async()=>{ctx([]);expect((await request(app).get('/api/obligations')).status).toBe(403);expect((await request(app).get('/api/counterparties')).status).toBe(403)});
 it('requires manage for counterparty and obligation writes',async()=>{ctx(['obligation.view']);expect((await request(app).post('/api/counterparties').send({name:'A',type:'customer'})).status).toBe(403);expect((await request(app).post('/api/obligations').send({})).status).toBe(403)});
 it('requires settle for settlement create and removal',async()=>{ctx(['obligation.manage']);expect((await request(app).post(`/api/obligations/${O}/settlements`).send({})).status).toBe(403);expect((await request(app).delete(`/api/obligations/${O}/settlements/${BANK}`).send({reason:'x'})).status).toBe(403)});
});
describe('Phase 4B completion behavior',()=>{
 it('rejects document-backed amount drift before mutation',async()=>{const queries:string[]=[];mocks.pool=poolFor((sql)=>{queries.push(sql);if(['BEGIN','ROLLBACK','COMMIT'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('SELECT *,original_amount'))return{rows:[{id:O,company_id:COMPANY,source_type:'document',document_id:BANK,original_amount:'100.00',verification_status:'confirmed',version:1}],rowCount:1};throw Error(sql)});const service=new mod.ObligationService(mocks.pool);await expect(service.updateObligation(COMPANY,USER,O,{version:1,original_amount:'99.00',reason:'x'})).rejects.toThrow();expect(queries.some(q=>q.startsWith('UPDATE obligations'))).toBe(false)});
 it('rejects a direct settlement when a bank match already explains the transaction',async()=>{mocks.pool=poolFor((sql)=>{if(['BEGIN','ROLLBACK','COMMIT'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{id:O,company_id:COMPANY,source_type:'manual',original_amount:'100.00',is_cancelled:false}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{id:BANK}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return{rows:[{one:1}],rowCount:1};throw Error(sql)});await expect(new mod.ObligationService(mocks.pool).settle(COMPANY,USER,O,BANK,'10.00',null)).rejects.toThrow()});
 it('locks the parent and allows exact full settlement with audit in the transaction',async()=>{const commands:string[]=[];const client={};mocks.pool=poolFor((sql)=>{commands.push(sql);if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{id:O,company_id:COMPANY,source_type:'manual',original_amount:'100.00',is_cancelled:false}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{id:BANK}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return{rows:[],rowCount:0};if(sql.includes('COALESCE(SUM(amount)'))return{rows:[{x:'40.00'}],rowCount:1};if(sql.startsWith('INSERT INTO obligation_settlements'))return{rows:[{id:BANK,amount:'60.00'}],rowCount:1};throw Error(sql)});await new mod.ObligationService(mocks.pool).settle(COMPANY,USER,O,BANK,'60.00',null);expect(commands.some(q=>q.includes('FOR UPDATE'))).toBe(true);expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'obligation_settlement.create'}),expect.anything())});

 it('returns eligible approved documents and real document settlement history without changing settled totals',async()=>{const queries:string[]=[];const db={query:vi.fn(async(sql:string)=>{const q=sql.replace(/\s+/g,' ');queries.push(q);if(q.includes('FROM obligations o JOIN counterparties'))return{rows:[{id:O,company_id:COMPANY,direction:'receivable',counterparty_id:'c1',document_id:'d1',original_amount:'100.00',recognized_on:'2026-01-01',due_on:null,verification_status:'confirmed',source_type:'document',source_note:null,is_cancelled:false,version:1,settled_amount:'25.00'}],rowCount:1};if(q.includes('FROM obligation_settlements s JOIN'))return{rows:[],rowCount:0};if(q.includes('FROM document_settlements s JOIN'))return{rows:[{id:'ds1',document_id:'d1',amount:'25.00',transaction_date:'2026-01-02',description:'Transfer'}],rowCount:1};if(q.includes("d.status='approved'"))return{rows:[{id:'d2',original_filename:'eligible.pdf',total_amount:'40.00'}],rowCount:1};throw Error(q)}),connect:vi.fn()};const result=await new mod.ObligationService(db as any).list(COMPANY);expect(result.eligible_documents).toEqual([{id:'d2',original_filename:'eligible.pdf',total_amount:'40.00'}]);expect(result.obligations[0]).toMatchObject({settled_amount:'25.00',remaining_amount:'75.00',settlement_history:[{id:'ds1',amount:'25.00'}]});expect(result.obligations[0].settlement_history).toHaveLength(1);expect(queries.some(q=>q.includes("status='approved'")&&q.includes('NOT EXISTS'))).toBe(true)});
 it('serializes concurrent attempts and never permits cumulative overpayment',async()=>{let settled=0;const db=poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{id:O,company_id:COMPANY,source_type:'manual',original_amount:'100.00',is_cancelled:false}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{id:BANK}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return{rows:[],rowCount:0};if(sql.includes('COALESCE(SUM(amount)'))return{rows:[{x:`${settled}.00`}],rowCount:1};if(sql.startsWith('INSERT INTO obligation_settlements')){settled+=60;return{rows:[{id:BANK,amount:'60.00'}],rowCount:1};}throw Error(sql)});const service=new mod.ObligationService(db as any);const results=await Promise.allSettled([service.settle(COMPANY,USER,O,BANK,'60.00',null),service.settle(COMPANY,USER,O,BANK,'60.00',null)]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);expect(settled).toBe(60)});
});
