import express,{NextFunction,Request,Response}from'express';import request from'supertest';import{beforeEach,describe,expect,it,vi}from'vitest';
const USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',COMPANY='11111111-1111-4111-8111-111111111111',O='22222222-2222-4222-8222-222222222222',BANK='33333333-3333-4333-8333-333333333333';
const mocks=vi.hoisted(()=>({context:null as any,audit:vi.fn(),pool:null as any}));
vi.mock('../src/db/pool',()=>({get default(){return mocks.pool}}));vi.mock('../src/modules/audit-log/audit-log.repository',()=>({AuditLogRepository:class{logEvent=async(e:unknown,c:unknown)=>mocks.audit(e,c)}}));vi.mock('../src/modules/auth/origin.middleware',()=>({requireSameOrigin:(_q:Request,_s:Response,n:NextFunction)=>n()}));vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:()=>mocks.context,requireAuth:(_q:Request,s:Response,n:NextFunction)=>mocks.context?n():void s.status(401).end(),requireActiveCompany:(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId?n():void s.status(403).end(),requireCapability:(c:string)=>(_q:Request,s:Response,n:NextFunction)=>mocks.context?.capabilities.includes(c)?n():void s.status(403).end()}));
vi.mock('../src/modules/monthly-close/accounting-period.guard',()=>({AccountingPeriodClosedError:class extends Error{},assertAccountingDateWritable:vi.fn().mockResolvedValue(undefined),lockAccountingRange:vi.fn().mockResolvedValue(undefined)}));
const mod=await import('../src/modules/obligations/obligation.router');const app=express();app.use(express.json());app.use('/api',mod.obligationRouter);app.use((_e:unknown,_q:Request,s:Response,_n:NextFunction)=>s.status(500).end());
const ctx=(caps:string[])=>mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:caps};
function poolFor(handler:(sql:string,args:unknown[])=>any){let gate=Promise.resolve();return{query:vi.fn((s:string,a:unknown[]=[])=>handler(s.replace(/\s+/g,' '),a)),connect:vi.fn(async()=>{const prior=gate;let release!:()=>void;gate=new Promise(r=>release=r);await prior;return{query:async(s:string,a:unknown[]=[])=>{const r=await handler(s.replace(/\s+/g,' '),a);if(s==='COMMIT'||s==='ROLLBACK')release();return r},release:vi.fn()}})}};
beforeEach(()=>{mocks.context=null;mocks.audit.mockReset();mocks.pool=null});
describe('Phase 4B authorization',()=>{
 it('requires view on both read endpoints',async()=>{ctx([]);expect((await request(app).get('/api/obligations')).status).toBe(403);expect((await request(app).get('/api/counterparties')).status).toBe(403)});
 it('requires manage for counterparty and obligation writes',async()=>{ctx(['obligation.view']);expect((await request(app).post('/api/counterparties').send({name:'A',type:'customer'})).status).toBe(403);expect((await request(app).post('/api/obligations').send({})).status).toBe(403)});
 it('requires settle for settlement create and removal',async()=>{ctx(['obligation.manage']);expect((await request(app).post(`/api/obligations/${O}/settlements`).send({})).status).toBe(403);expect((await request(app).delete(`/api/obligations/${O}/settlements/${BANK}`).send({reason:'x'})).status).toBe(403)});
});
describe('Phase 4B completion behavior',()=>{
 it('rejects document-backed amount drift before mutation',async()=>{const queries:string[]=[];mocks.pool=poolFor((sql)=>{queries.push(sql);if(['BEGIN','ROLLBACK','COMMIT'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('SELECT *,original_amount'))return{rows:[{id:O,company_id:COMPANY,source_type:'document',document_id:BANK,original_amount:'100.00',verification_status:'confirmed',version:1}],rowCount:1};throw Error(sql)});const service=new mod.ObligationService(mocks.pool);await expect(service.updateObligation(COMPANY,USER,O,{version:1,original_amount:'99.00',reason:'x'})).rejects.toThrow();expect(queries.some(q=>q.startsWith('UPDATE obligations'))).toBe(false)});
 it('rejects a direct settlement when a bank match already explains the transaction',async()=>{mocks.pool=poolFor((sql)=>{if(['BEGIN','ROLLBACK','COMMIT'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{id:O,company_id:COMPANY,source_type:'manual',direction:'receivable',original_amount:'100.00',is_cancelled:false}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{id:BANK,amount:'60.00'}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return{rows:[{one:1}],rowCount:1};throw Error(sql)});await expect(new mod.ObligationService(mocks.pool).settle(COMPANY,USER,O,BANK,'10.00',null)).rejects.toThrow()});
 it('locks the parent and allows exact full settlement with audit in the transaction',async()=>{const commands:string[]=[];const client={};mocks.pool=poolFor((sql)=>{commands.push(sql);if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{id:O,company_id:COMPANY,source_type:'manual',direction:'receivable',original_amount:'100.00',is_cancelled:false}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{id:BANK,amount:'60.00'}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return{rows:[],rowCount:0};if(sql.includes('COALESCE(SUM(amount)'))return{rows:[{x:'40.00'}],rowCount:1};if(sql.startsWith('INSERT INTO obligation_settlements'))return{rows:[{id:BANK,amount:'60.00'}],rowCount:1};throw Error(sql)});await new mod.ObligationService(mocks.pool).settle(COMPANY,USER,O,BANK,'60.00',null);expect(commands.some(q=>q.includes('FOR UPDATE'))).toBe(true);expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'obligation_settlement.create'}),expect.anything())});

 it('returns eligible approved documents and real document settlement history without changing settled totals',async()=>{const queries:string[]=[];const db={query:vi.fn(async(sql:string)=>{const q=sql.replace(/\s+/g,' ');queries.push(q);if(q.includes('FROM obligations o JOIN counterparties'))return{rows:[{id:O,company_id:COMPANY,direction:'receivable',counterparty_id:'c1',document_id:'d1',original_amount:'100.00',recognized_on:'2026-01-01',due_on:null,verification_status:'confirmed',source_type:'document',source_note:null,is_cancelled:false,version:1,settled_amount:'25.00'}],rowCount:1};if(q.includes('FROM obligation_settlements s JOIN'))return{rows:[],rowCount:0};if(q.includes('FROM document_settlements s JOIN'))return{rows:[{id:'ds1',document_id:'d1',amount:'25.00',transaction_date:'2026-01-02',description:'Transfer'}],rowCount:1};if(q.includes("d.status='approved'"))return{rows:[{id:'d2',original_filename:'eligible.pdf',total_amount:'40.00'}],rowCount:1};throw Error(q)}),connect:vi.fn()};const result=await new mod.ObligationService(db as any).list(COMPANY);expect(result.eligible_documents).toEqual([{id:'d2',original_filename:'eligible.pdf',total_amount:'40.00'}]);expect(result.obligations[0]).toMatchObject({settled_amount:'25.00',remaining_amount:'75.00',settlement_history:[{id:'ds1',amount:'25.00'}]});expect(result.obligations[0].settlement_history).toHaveLength(1);expect(result.summary).toMatchObject({open_receivables:'75.00',unconfirmed_receivables:'0.00',unconfirmed_count:0});expect(queries.some(q=>q.includes("status='approved'")&&q.includes('NOT EXISTS'))).toBe(true)});
 it('serializes concurrent attempts and never permits cumulative overpayment',async()=>{let settled=0;const db=poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{id:O,company_id:COMPANY,source_type:'manual',direction:'receivable',original_amount:'100.00',is_cancelled:false}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{id:BANK,amount:'60.00'}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return{rows:[],rowCount:0};if(sql.includes('COALESCE(SUM(amount)'))return{rows:[{x:`${settled}.00`}],rowCount:1};if(sql.startsWith('INSERT INTO obligation_settlements')){settled+=60;return{rows:[{id:BANK,amount:'60.00'}],rowCount:1};}throw Error(sql)});const service=new mod.ObligationService(db as any);const results=await Promise.allSettled([service.settle(COMPANY,USER,O,BANK,'60.00',null),service.settle(COMPANY,USER,O,BANK,'60.00',null)]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected')).toHaveLength(1);expect(settled).toBe(60)});
});

describe('Phase 4C hardening',()=>{
 const valid={direction:'receivable',counterparty_id:O,document_id:null,original_amount:'10.00',recognized_on:'2026-01-01',due_on:null,verification_status:'confirmed',source_type:'manual',source_note:null};
 it('requires manage and independent confirm for direct confirmed creation',async()=>{ctx(['obligation.manage']);expect((await request(app).post('/api/obligations').send(valid)).status).toBe(403);ctx(['obligation.confirm']);expect((await request(app).post('/api/obligations').send(valid)).status).toBe(403)});
 it('enforces confirmation capability and unconfirm reason while preserving audit before/after',async()=>{const base={id:O,company_id:COMPANY,source_type:'manual',document_id:null,original_amount:'100.00',verification_status:'confirmed',version:1,is_cancelled:false};const queries:string[]=[];mocks.pool=poolFor((sql)=>{queries.push(sql);if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('SELECT *,original_amount'))return{rows:[base],rowCount:1};if(sql.includes('COALESCE(SUM(amount)'))return{rows:[{x:'0.00'}],rowCount:1};if(sql.startsWith('UPDATE obligations'))return{rows:[{...base,verification_status:'unconfirmed',version:2}],rowCount:1};throw Error(sql)});const service=new mod.ObligationService(mocks.pool);await expect(service.updateObligation(COMPANY,USER,O,{version:1,verification_status:'unconfirmed'},false)).rejects.toThrow();await expect(service.updateObligation(COMPANY,USER,O,{version:1,verification_status:'unconfirmed'},true)).rejects.toThrow();await service.updateObligation(COMPANY,USER,O,{version:1,verification_status:'unconfirmed',reason:'correction'},true);expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({before_data:expect.objectContaining({verification_status:'confirmed'}),after_data:expect.objectContaining({verification_status:'unconfirmed'}),reason:'correction'}),expect.anything())});
 it('validates tenant fiscal-year starts and document counterparties before insert',async()=>{const base={direction:'receivable',counterparty_id:O,document_id:null,original_amount:'10.00',recognized_on:'2026-01-01',due_on:null,verification_status:'unconfirmed',source_type:'opening_balance',source_note:null};const db=poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM counterparties'))return{rows:[{one:1}],rowCount:1};if(sql.includes('FROM fiscal_years'))return{rows:[],rowCount:0};throw Error(sql)});await expect(new mod.ObligationService(db as any).createObligation(COMPANY,USER,base)).rejects.toThrow();const docDb=poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM counterparties'))return{rows:[{one:1}],rowCount:1};if(sql.includes('FROM documents'))return{rows:[{status:'approved',total_amount:'10.00',counterparty_id:BANK}],rowCount:1};throw Error(sql)});await expect(new mod.ObligationService(docDb as any).createObligation(COMPANY,USER,{...base,source_type:'document',document_id:BANK})).rejects.toThrow()});
 it('requires settlement direction and exact bank amount, while allowing unconfirmed obligations',async()=>{const make=(direction:string,bankAmount:string)=>poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{id:O,company_id:COMPANY,source_type:'manual',direction,verification_status:'unconfirmed',original_amount:'100.00',is_cancelled:false}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{amount:bankAmount}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return{rows:[],rowCount:0};if(sql.includes('COALESCE(SUM(amount)'))return{rows:[{x:'0.00'}],rowCount:1};if(sql.startsWith('INSERT INTO obligation_settlements'))return{rows:[{id:BANK,amount:bankAmount.replace('-','')}],rowCount:1};throw Error(sql)});await new mod.ObligationService(make('receivable','40.00') as any).settle(COMPANY,USER,O,BANK,'40.00',null);await new mod.ObligationService(make('payable','-40.00') as any).settle(COMPANY,USER,O,BANK,'40.00',null);await expect(new mod.ObligationService(make('receivable','-40.00') as any).settle(COMPANY,USER,O,BANK,'40.00',null)).rejects.toThrow();await expect(new mod.ObligationService(make('receivable','41.00') as any).settle(COMPANY,USER,O,BANK,'40.00',null)).rejects.toThrow()});
});

describe('Phase 4C approved validation contract',()=>{
 const base={direction:'receivable',counterparty_id:O,document_id:null,original_amount:'100.00',recognized_on:'2026-01-01',due_on:null,verification_status:'unconfirmed',source_type:'opening_balance',source_note:null};
 const created={...base,id:O,company_id:COMPANY,version:1,is_cancelled:false};
 const createDb=(options:{fiscal?:boolean;documentCounterparty?:string|null;counterparty?:boolean}={})=>poolFor((sql,args)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM counterparties'))return options.counterparty===false?{rows:[],rowCount:0}:{rows:[{one:1}],rowCount:1};if(sql.includes('FROM fiscal_years'))return options.fiscal?{rows:[{one:1}],rowCount:1}:{rows:[],rowCount:0};if(sql.includes('FROM documents'))return{rows:[{status:'approved',total_amount:'100.00',counterparty_id:options.documentCounterparty??null}],rowCount:1};if(sql.startsWith('INSERT INTO obligations'))return{rows:[created],rowCount:1};throw Error(`${sql} ${args}`)});
 it('allows an opening balance exactly on a same-company fiscal-year start and rejects a non-qualifying company lookup',async()=>{await expect(new mod.ObligationService(createDb({fiscal:true}) as any).createObligation(COMPANY,USER,base)).resolves.toMatchObject({id:O});await expect(new mod.ObligationService(createDb() as any).createObligation(COMPANY,USER,base)).rejects.toThrow()});
 it.each([{name:'matching',counterparty:O},{name:'null',counterparty:null}])('allows a document with $name counterparty',async({counterparty})=>{const body={...base,source_type:'document',document_id:BANK};await expect(new mod.ObligationService(createDb({documentCounterparty:counterparty}) as any).createObligation(COMPANY,USER,body)).resolves.toMatchObject({id:O})});
 it('rejects cross-company counterparties/documents without fallback',async()=>{await expect(new mod.ObligationService(createDb({counterparty:false}) as any).createObligation(COMPANY,USER,{...base,source_type:'document',document_id:BANK})).rejects.toThrow();const queries:string[]=[];const db=poolFor((sql)=>{queries.push(sql);if(['BEGIN','ROLLBACK','COMMIT'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM counterparties'))return{rows:[{one:1}],rowCount:1};if(sql.includes('FROM documents'))return{rows:[],rowCount:0};throw Error(sql)});await expect(new mod.ObligationService(db as any).createObligation(COMPANY,USER,{...base,source_type:'document',document_id:BANK})).rejects.toThrow();expect(queries.find(q=>q.includes('FROM documents'))).toContain('company_id=$2')});
 it('separates confirmed and unconfirmed remaining totals and excludes cancelled obligations',async()=>{const rows=[
  {...created,id:'confirmed',direction:'receivable',verification_status:'confirmed',original_amount:'100.00',settled_amount:'40.00'},
  {...created,id:'ur',direction:'receivable',verification_status:'unconfirmed',original_amount:'80.00',settled_amount:'20.00'},
  {...created,id:'up',direction:'payable',verification_status:'unconfirmed',original_amount:'50.00',settled_amount:'0.00'},
  {...created,id:'cancelled',direction:'payable',verification_status:'confirmed',original_amount:'90.00',settled_amount:'0.00',is_cancelled:true}
 ];const db={query:vi.fn(async(sql:string)=>{const q=sql.replace(/\s+/g,' ');if(q.includes('FROM obligations o JOIN counterparties'))return{rows,rowCount:rows.length};if(q.includes('FROM obligation_settlements s JOIN')||q.includes('FROM document_settlements s JOIN')||q.includes("d.status='approved'"))return{rows:[],rowCount:0};throw Error(q)}),connect:vi.fn()};const result=await new mod.ObligationService(db as any).list(COMPANY);expect(result.summary).toMatchObject({open_receivables:'60.00',open_payables:'0.00',unconfirmed_receivables:'60.00',unconfirmed_payables:'50.00',unconfirmed_count:2});expect(result.obligations.find(x=>x.id==='confirmed')).toMatchObject({remaining_amount:'60.00',state:'partial'})});
 const settlementDb=(options:{direction?:'receivable'|'payable';bankAmount?:string;used?:boolean;missingBank?:boolean;prior?:string}={})=>poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{...created,source_type:'manual',direction:options.direction??'receivable',verification_status:'unconfirmed'}],rowCount:1};if(sql.includes('FROM bank_transactions'))return options.missingBank?{rows:[],rowCount:0}:{rows:[{amount:options.bankAmount??'40.00'}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return options.used?{rows:[{one:1}],rowCount:1}:{rows:[],rowCount:0};if(sql.includes('COALESCE(SUM(amount)'))return{rows:[{x:options.prior??'0.00'}],rowCount:1};if(sql.startsWith('INSERT INTO obligation_settlements'))return{rows:[{id:BANK,amount:(options.bankAmount??'40.00').replace('-','')}],rowCount:1};throw Error(sql)});
 it('accepts correct signs, rejects opposite signs, and requires the absolute transaction amount',async()=>{await expect(new mod.ObligationService(settlementDb() as any).settle(COMPANY,USER,O,BANK,'40.00',null)).resolves.toBeTruthy();await expect(new mod.ObligationService(settlementDb({direction:'payable',bankAmount:'-40.00'}) as any).settle(COMPANY,USER,O,BANK,'40.00',null)).resolves.toBeTruthy();await expect(new mod.ObligationService(settlementDb({bankAmount:'-40.00'}) as any).settle(COMPANY,USER,O,BANK,'40.00',null)).rejects.toThrow();await expect(new mod.ObligationService(settlementDb({direction:'payable'}) as any).settle(COMPANY,USER,O,BANK,'40.00',null)).rejects.toThrow();await expect(new mod.ObligationService(settlementDb({bankAmount:'41.00'}) as any).settle(COMPANY,USER,O,BANK,'40.00',null)).rejects.toThrow()});
 it('allows independent transactions to move an unconfirmed obligation from partial to settled without changing verification',async()=>{let prior='0.00';const seen:string[]=[];const db=poolFor((sql,args)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{...created,source_type:'manual',direction:'receivable',verification_status:'unconfirmed'}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{amount:args[0]===BANK?'40.00':'60.00'}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return{rows:[],rowCount:0};if(sql.includes('COALESCE(SUM(amount)'))return{rows:[{x:prior}],rowCount:1};if(sql.startsWith('INSERT INTO obligation_settlements')){seen.push(String(args[2]));prior=String(Number(prior)+Number(args[3]));return{rows:[{id:args[2],amount:args[3]}],rowCount:1};}throw Error(sql)});const service=new mod.ObligationService(db as any),other='44444444-4444-4444-8444-444444444444';await service.settle(COMPANY,USER,O,BANK,'40.00',null);expect(prior).toBe('40');await service.settle(COMPANY,USER,O,other,'60.00',null);expect(prior).toBe('100');expect(seen).toEqual([BANK,other]);expect(mocks.audit).toHaveBeenLastCalledWith(expect.objectContaining({after_data:expect.not.objectContaining({verification_status:'confirmed'})}),expect.anything())});
 it('rejects reused, matched or document-settled transactions and cross-company bank transactions',async()=>{await expect(new mod.ObligationService(settlementDb({used:true}) as any).settle(COMPANY,USER,O,BANK,'40.00',null)).rejects.toThrow();await expect(new mod.ObligationService(settlementDb({missingBank:true}) as any).settle(COMPANY,USER,O,BANK,'40.00',null)).rejects.toThrow();for(const relation of ['bank_transaction_matches','document_settlements','obligation_settlements']){const db=poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql))return{rows:[],rowCount:0};if(sql.includes('FROM obligations WHERE'))return{rows:[{...created,source_type:'manual',direction:'receivable'}],rowCount:1};if(sql.includes('FROM bank_transactions'))return{rows:[{amount:'40.00'}],rowCount:1};if(sql.includes('FROM bank_transaction_matches'))return sql.includes(`FROM ${relation}`)?{rows:[{one:1}],rowCount:1}:{rows:[],rowCount:0};throw Error(sql)});await expect(new mod.ObligationService(db as any).settle(COMPANY,USER,O,BANK,'40.00',null)).rejects.toThrow()}});
});
