import express,{NextFunction,Request,Response} from 'express';
import request from 'supertest';
import {beforeEach,describe,expect,it,vi} from 'vitest';

const USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
const PA='33333333-3333-4333-8333-333333333333',PB='44444444-4444-4444-8444-444444444444',P2='55555555-5555-4555-8555-555555555555';
const OA='66666666-6666-4666-8666-666666666666',DA='77777777-7777-4777-8777-777777777777',DB='88888888-8888-4888-8888-888888888888';
type P={id:string;company_id:string;name:string;is_active:boolean;version:number;created_at:Date;updated_at:Date};
type O={id:string;company_id:string;partner_id:string;ownership_percentage:string|null;effective_from:string|null;effective_to:string|null;verification_status:'unconfirmed'|'confirmed';source_document_id:string|null;note:string|null;version:number;created_at:Date;updated_at:Date;created_by_user_id:string};
const mocks=vi.hoisted(()=>({context:null as null|{user:{id:string;email:string};activeCompanyId:string|null;capabilities:string[];allowedCompanies:never[]},audit:vi.fn()}));
class MemoryDb{partners:P[]=[];ownership:O[]=[];documents=[{id:DA,company_id:A},{id:DB,company_id:B}];seq=0;commands:string[]=[];private locked=Promise.resolve();private txGate=Promise.resolve();
 connect=vi.fn(async()=>{const previous=this.txGate;let unlock!:()=>void;this.txGate=new Promise<void>(r=>unlock=r);await previous;return{query:async(sql:string,args?:unknown[])=>{const result=await this.query(sql,args);if(sql==='COMMIT'||sql==='ROLLBACK')unlock();return result;},release:vi.fn()};});
 query=vi.fn(async(sql:string,args:unknown[]=[]):Promise<{rows:any[];rowCount:number}>=>{this.commands.push(sql.trim().split(/\s+/).slice(0,3).join(' '));const s=sql.replace(/\s+/g,' ').trim();
  if(['BEGIN','COMMIT','ROLLBACK'].includes(s))return{rows:[],rowCount:0};
  if(s.includes('pg_advisory_xact_lock')){const previous=this.locked;let release!:()=>void;this.locked=new Promise<void>(r=>release=r);await previous;queueMicrotask(release);return{rows:[],rowCount:1};}
  if(s.startsWith('SELECT p.*')){const company=args[0];const rows=this.partners.filter(p=>p.company_id===company).map(p=>{const current=this.ownership.filter(o=>o.partner_id===p.id&&o.company_id===company&&o.verification_status==='confirmed'&&o.effective_from!&&o.effective_from<='2026-08-17'&&(!o.effective_to||o.effective_to>='2026-08-17')).sort((x,y)=>y.effective_from!.localeCompare(x.effective_from!))[0];return{...p,current_ownership_percentage:current?.ownership_percentage??null,current_effective_from:current?.effective_from??null,has_unconfirmed_ownership:this.ownership.some(o=>o.partner_id===p.id&&o.verification_status==='unconfirmed')}});return{rows,rowCount:rows.length};}
  if(s.startsWith('INSERT INTO partners')){const p:P={id:[PA,P2,PB][this.partners.length]!,company_id:String(args[0]),name:String(args[1]),is_active:true,version:1,created_at:new Date(),updated_at:new Date()};if(this.partners.some(x=>x.id===p.id))p.id=P2;this.partners.push(p);return{rows:[p],rowCount:1};}
  if(s.startsWith('SELECT * FROM partners')){const p=this.partners.find(x=>x.id===args[0]&&x.company_id===args[1]);return{rows:p?[{...p}]:[],rowCount:p?1:0};}
  if(s.startsWith('SELECT 1 FROM partners')){const p=this.partners.find(x=>x.id===args[0]&&x.company_id===args[1]);return{rows:p?[{one:1}]:[],rowCount:p?1:0};}
  if(s.startsWith('UPDATE partners')){const p=this.partners.find(x=>x.id===args[0]&&x.company_id===args[1])!;p.name=String(args[2]);p.is_active=Boolean(args[3]);p.version++;p.updated_at=new Date();return{rows:[p],rowCount:1};}
  if(s.startsWith('SELECT 1 FROM documents')){const d=this.documents.find(x=>x.id===args[0]&&x.company_id===args[1]);return{rows:d?[{one:1}]:[],rowCount:d?1:0};}
  if(s.startsWith('SELECT 1 FROM partner_ownership_periods')){const [company,partner,exclude,from,to]=args as [string,string,string|null,string,string|null];const hit=this.ownership.find(o=>o.company_id===company&&o.partner_id===partner&&o.verification_status==='confirmed'&&o.id!==exclude&&o.effective_from!<=(to??'9999-12-31')&&(o.effective_to??'9999-12-31')>=from);return{rows:hit?[{one:1}]:[],rowCount:hit?1:0};}
  if(s.startsWith('INSERT INTO partner_ownership_periods')){const o:O={id:[OA,'99999999-9999-4999-8999-999999999999','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'][this.seq++]!,company_id:String(args[0]),partner_id:String(args[1]),ownership_percentage:args[2] as string|null,effective_from:args[3] as string|null,effective_to:args[4] as string|null,verification_status:args[5] as O['verification_status'],source_document_id:args[6] as string|null,note:args[7] as string|null,created_by_user_id:String(args[8]),version:1,created_at:new Date(),updated_at:new Date()};this.ownership.push(o);return{rows:[o],rowCount:1};}
  if(s.startsWith('SELECT *,ownership_percentage::text')&&s.includes('WHERE id=')){const o=this.ownership.find(x=>x.id===args[0]&&x.partner_id===args[1]&&x.company_id===args[2]);return{rows:o?[{...o}]:[],rowCount:o?1:0};}
  if(s.startsWith('SELECT *,ownership_percentage::text')){const rows=this.ownership.filter(x=>x.partner_id===args[0]&&x.company_id===args[1]);return{rows,rowCount:rows.length};}
  if(s.startsWith('UPDATE partner_ownership_periods')){const o=this.ownership.find(x=>x.id===args[0]&&x.partner_id===args[1]&&x.company_id===args[2])!;Object.assign(o,{ownership_percentage:args[3],effective_from:args[4],effective_to:args[5],verification_status:args[6],source_document_id:args[7],note:args[8],version:o.version+1,updated_at:new Date()});return{rows:[{...o}],rowCount:1};}
  throw new Error(`Unhandled SQL: ${s}`);});}
const db=new MemoryDb();
vi.mock('../src/db/pool',()=>({default:db}));
vi.mock('../src/modules/audit-log/audit-log.repository',()=>({AuditLogRepository:class{logEvent=async(event:unknown)=>{mocks.audit(event,db.commands.at(-1));return event;}}}));
vi.mock('../src/modules/auth/origin.middleware',()=>({requireSameOrigin:(_q:Request,_s:Response,n:NextFunction)=>n()}));
vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:()=>mocks.context,requireAuth:(_q:Request,s:Response,n:NextFunction)=>mocks.context?n():void s.status(401).json({error:'Unauthenticated'}),requireActiveCompany:(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId?n():void s.status(403).json({error:'No active company'}),requireCapability:(cap:string)=>(_q:Request,s:Response,n:NextFunction)=>mocks.context?.capabilities.includes(cap)?n():void s.status(403).json({error:'Forbidden'})}));
const {partnerRouter}=await import('../src/modules/partners/partner.router');
const app=express();app.use(express.json());app.use('/api',partnerRouter);app.use((e:unknown,_q:Request,s:Response,_n:NextFunction)=>s.status(500).json({error:e instanceof Error?e.message:'error'}));
const WRITES=['partner.create','partner.edit','partner.disable','partner.ownership.create','partner.ownership.edit','partner.ownership.confirm'];
function context(company=A,caps=['partner.view',...WRITES]){mocks.context={user:{id:USER,email:'u@x.test'},activeCompanyId:company,capabilities:caps,allowedCompanies:[]};}
const ownership=(extra:Record<string,unknown>={})=>({ownership_percentage:null,effective_from:null,effective_to:null,verification_status:'unconfirmed',source_document_id:null,note:null,...extra});
beforeEach(()=>{db.partners=[];db.ownership=[];db.seq=0;db.commands=[];db.query.mockClear();db.connect.mockClear();mocks.audit.mockReset();mocks.context=null;});

describe('Partners executable authorization and behavior',()=>{
 it('requires view for reads and has no legacy manage fallback for writes',async()=>{context(A,[]);expect((await request(app).get('/api/partners')).status).toBe(403);context(A,['partner.view','partner.manage']);expect((await request(app).post('/api/partners').send({name:'A'})).status).toBe(403)});
 it('isolates partner create, edit, disable, and combined patch capabilities',async()=>{context(A,['partner.create']);expect((await request(app).post('/api/partners').send({name:'A'})).status).toBe(201);context(A,['partner.edit']);expect((await request(app).patch(`/api/partners/${PA}`).send({name:'B',version:1})).status).toBe(200);expect((await request(app).patch(`/api/partners/${PA}`).send({is_active:false,version:2})).status).toBe(403);context(A,['partner.disable']);expect((await request(app).patch(`/api/partners/${PA}`).send({is_active:false,version:2})).status).toBe(200);expect((await request(app).patch(`/api/partners/${PA}`).send({is_active:true,version:3})).status).toBe(403);context(A,['partner.edit']);expect((await request(app).patch(`/api/partners/${PA}`).send({name:'C',is_active:false,version:3})).status).toBe(403);context(A,['partner.edit','partner.disable']);expect((await request(app).patch(`/api/partners/${PA}`).send({name:'C',is_active:false,version:3})).status).toBe(200)});
 it('isolates ownership create and confirmation capabilities',async()=>{db.partners.push({id:PA,company_id:A,name:'A',is_active:true,version:1,created_at:new Date(),updated_at:new Date()});context(A,['partner.ownership.create']);expect((await request(app).post(`/api/partners/${PA}/ownership`).send(ownership())).status).toBe(201);expect((await request(app).post(`/api/partners/${PA}/ownership`).send(ownership({ownership_percentage:'25',effective_from:'2026-01-01',verification_status:'confirmed'}))).status).toBe(403);context(A,['partner.ownership.confirm']);expect((await request(app).post(`/api/partners/${PA}/ownership`).send(ownership())).status).toBe(403)});
 it('requires all applicable ownership patch capabilities',async()=>{db.partners.push({id:PA,company_id:A,name:'A',is_active:true,version:1,created_at:new Date(),updated_at:new Date()});db.ownership.push({id:OA,company_id:A,partner_id:PA,ownership_percentage:'25',effective_from:'2026-01-01',effective_to:null,verification_status:'unconfirmed',source_document_id:null,note:null,version:1,created_at:new Date(),updated_at:new Date(),created_by_user_id:USER});const confirmed={...ownership({ownership_percentage:'25',effective_from:'2026-01-01',verification_status:'confirmed'}),version:1};context(A,['partner.ownership.confirm']);expect((await request(app).patch(`/api/partners/${PA}/ownership/${OA}`).send(confirmed)).status).toBe(200);db.ownership[0]!.verification_status='unconfirmed';db.ownership[0]!.version=1;context(A,['partner.ownership.edit']);expect((await request(app).patch(`/api/partners/${PA}/ownership/${OA}`).send({...confirmed,note:'changed'})).status).toBe(403);context(A,['partner.ownership.confirm']);expect((await request(app).patch(`/api/partners/${PA}/ownership/${OA}`).send({...confirmed,note:'changed'})).status).toBe(403);context(A,['partner.ownership.edit','partner.ownership.confirm']);expect((await request(app).patch(`/api/partners/${PA}/ownership/${OA}`).send({...confirmed,note:'changed'})).status).toBe(200)});
 it('creates lists updates and disables without deleting, with transactional audits',async()=>{context();let r=await request(app).post('/api/partners').send({name:' Partner A '});expect(r.status).toBe(201);expect(mocks.audit.mock.calls[0][0].action).toBe('partner.create');expect(mocks.audit.mock.calls[0][1]).not.toBe('COMMIT');r=await request(app).get('/api/partners');expect(r.body.partners[0].name).toBe('Partner A');r=await request(app).patch(`/api/partners/${PA}`).send({name:'Renamed',version:1});expect(r.status).toBe(200);expect(mocks.audit.mock.calls[1][0].action).toBe('partner.update');r=await request(app).patch(`/api/partners/${PA}`).send({is_active:false,version:2});expect(r.status).toBe(200);expect(db.partners).toHaveLength(1);expect(db.partners[0].is_active).toBe(false);expect(mocks.audit.mock.calls[2][0].action).toBe('partner.disable')});
 it('returns safe not found cross-company and rejects stale partner versions',async()=>{db.partners.push({id:PB,company_id:B,name:'Secret',is_active:true,version:1,created_at:new Date(),updated_at:new Date()});context(A);expect((await request(app).get(`/api/partners/${PB}/ownership`)).status).toBe(404);expect((await request(app).patch(`/api/partners/${PB}`).send({name:'X',version:1})).status).toBe(404);db.partners.push({id:PA,company_id:A,name:'A',is_active:true,version:2,created_at:new Date(),updated_at:new Date()});expect((await request(app).patch(`/api/partners/${PA}`).send({name:'X',version:1})).status).toBe(409)});
 it('keeps unknown unconfirmed values null and audits ownership create',async()=>{db.partners.push({id:PA,company_id:A,name:'A',is_active:true,version:1,created_at:new Date(),updated_at:new Date()});context();const r=await request(app).post(`/api/partners/${PA}/ownership`).send(ownership());expect(r.status).toBe(201);expect(r.body.ownership_percentage).toBeNull();expect(r.body.effective_from).toBeNull();expect(mocks.audit.mock.calls[0][0].action).toBe('partner_ownership.create')});
 it.each([{ownership_percentage:null,effective_from:'2026-01-01'}, {ownership_percentage:'25',effective_from:null}, {ownership_percentage:'0',effective_from:'2026-01-01'}, {ownership_percentage:'101',effective_from:'2026-01-01'}, {ownership_percentage:'25',effective_from:'2026-02-01',effective_to:'2026-01-01'}])('rejects invalid confirmed ownership %#',async invalid=>{db.partners.push({id:PA,company_id:A,name:'A',is_active:true,version:1,created_at:new Date(),updated_at:new Date()});context();expect((await request(app).post(`/api/partners/${PA}/ownership`).send(ownership({...invalid,verification_status:'confirmed'}))).status).toBe(400)});
 it('allows non-overlap and different partners, but rejects same-partner overlap',async()=>{db.partners.push(...[PA,P2].map((id,i)=>({id,company_id:A,name:`P${i}`,is_active:true,version:1,created_at:new Date(),updated_at:new Date()})));context();const first=ownership({ownership_percentage:'20',effective_from:'2026-01-01',effective_to:'2026-03-31',verification_status:'confirmed'});expect((await request(app).post(`/api/partners/${PA}/ownership`).send(first)).status).toBe(201);expect((await request(app).post(`/api/partners/${PA}/ownership`).send(ownership({...first,effective_from:'2026-04-01',effective_to:null}))).status).toBe(201);expect((await request(app).post(`/api/partners/${PA}/ownership`).send(ownership({...first,effective_from:'2026-03-01'}))).status).toBe(409);expect((await request(app).post(`/api/partners/${P2}/ownership`).send(first)).status).toBe(201)});
 it('accepts same-company evidence and safely rejects cross-company evidence',async()=>{db.partners.push({id:PA,company_id:A,name:'A',is_active:true,version:1,created_at:new Date(),updated_at:new Date()});context();expect((await request(app).post(`/api/partners/${PA}/ownership`).send(ownership({source_document_id:DA}))).status).toBe(201);expect((await request(app).post(`/api/partners/${PA}/ownership`).send(ownership({source_document_id:DB}))).status).toBe(404)});
 it('requires reason for confirmed correction and rejects stale ownership version',async()=>{db.partners.push({id:PA,company_id:A,name:'A',is_active:true,version:1,created_at:new Date(),updated_at:new Date()});db.ownership.push({id:OA,company_id:A,partner_id:PA,ownership_percentage:'20',effective_from:'2026-01-01',effective_to:null,verification_status:'confirmed',source_document_id:null,note:null,version:2,created_at:new Date(),updated_at:new Date(),created_by_user_id:USER});context();const body={...ownership({ownership_percentage:'21',effective_from:'2026-01-01',verification_status:'confirmed'}),version:2};expect((await request(app).patch(`/api/partners/${PA}/ownership/${OA}`).send(body)).status).toBe(400);expect((await request(app).patch(`/api/partners/${PA}/ownership/${OA}`).send({...body,version:1,reason:'Correction'})).status).toBe(409);expect((await request(app).patch(`/api/partners/${PA}/ownership/${OA}`).send({...body,reason:'Correction'})).status).toBe(200);expect(mocks.audit.mock.calls[0][0]).toMatchObject({action:'partner_ownership.update',reason:'Correction'})});
 it('writes confirmation audit and serializes concurrent overlapping confirmations',async()=>{db.partners.push({id:PA,company_id:A,name:'A',is_active:true,version:1,created_at:new Date(),updated_at:new Date()});db.ownership.push({id:OA,company_id:A,partner_id:PA,ownership_percentage:null,effective_from:null,effective_to:null,verification_status:'unconfirmed',source_document_id:null,note:null,version:1,created_at:new Date(),updated_at:new Date(),created_by_user_id:USER});context();const confirmed={...ownership({ownership_percentage:'40',effective_from:'2026-01-01',effective_to:'2026-12-31',verification_status:'confirmed'}),version:1};const a=await request(app).patch(`/api/partners/${PA}/ownership/${OA}`).send(confirmed);expect(a.status).toBe(200);expect(mocks.audit.mock.calls[0][0].action).toBe('partner_ownership.confirm');const [one,two]=await Promise.all([request(app).post(`/api/partners/${PA}/ownership`).send(ownership({ownership_percentage:'40',effective_from:'2027-01-01',effective_to:'2027-12-31',verification_status:'confirmed'})),request(app).post(`/api/partners/${PA}/ownership`).send(ownership({ownership_percentage:'40',effective_from:'2027-06-01',effective_to:null,verification_status:'confirmed'}))]);expect([one.status,two.status].sort()).toEqual([201,409]);expect(db.commands.some(x=>x.includes('pg_advisory_xact_lock'))).toBe(true)});
});
