import express,{NextFunction,Request,Response}from'express';import request from'supertest';import{beforeEach,describe,expect,it,vi}from'vitest';
const COMPANY='11111111-1111-4111-8111-111111111111';
const mocks=vi.hoisted(()=>({context:null as any,pool:null as any}));
vi.mock('../src/db/pool',()=>({get default(){return mocks.pool}}));
vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:()=>mocks.context,requireAuth:(_q:Request,s:Response,n:NextFunction)=>mocks.context?n():void s.status(401).end(),requireActiveCompany:(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId?n():void s.status(403).end(),requireCapability:(c:string)=>(_q:Request,s:Response,n:NextFunction)=>mocks.context?.capabilities.includes(c)?n():void s.status(403).end()}));
const mod=await import('../src/modules/purchases/purchases.router');const app=express();app.use('/api',mod.purchasesRouter);app.use((_e:unknown,_q:Request,s:Response,_n:NextFunction)=>s.status(500).end());
const row=(x:Record<string,unknown>={})=>({id:'purchase-1',document_type:'purchase',original_filename:'purchase.pdf',status:'approved',document_date:'2026-08-01',reference_number:'INV-1',total_amount:'100.00',counterparty_id:'supplier-1',supplier_name:'Supplier',payable_id:'rec-1',payable_original_amount:'100.00',due_on:null,verification_status:'confirmed',is_cancelled:false,vat_review_status:null,tax_date:null,vat_treatment:null,taxable_amount:null,vat_amount:null,...x});
function db(rows:any[],settlements:any[]=[]){return{query:vi.fn(async(sql:string,args:unknown[])=>sql.includes('FROM documents d')?{rows,rowCount:rows.length}:{rows:settlements,rowCount:settlements.length})}}
beforeEach(()=>{mocks.context={user:{id:'u'},activeCompanyId:COMPANY,capabilities:['document.view','obligation.view']};mocks.pool=null});
describe('purchases projection',()=>{
 it('requires both existing read capabilities',async()=>{mocks.context.capabilities=['document.view'];expect((await request(app).get('/api/purchases')).status).toBe(403);mocks.context.capabilities=['obligation.view'];expect((await request(app).get('/api/purchases')).status).toBe(403)});
 it('server-scopes the purchase-only query and preserves the supplier relationship',async()=>{mocks.pool=db([row()]);const response=await request(app).get('/api/purchases');expect(response.status).toBe(200);expect(response.body.purchases[0]).toMatchObject({supplier_name:'Supplier',counterparty_id:'supplier-1',payable_relationship:'linked_active'});const [sql,args]=mocks.pool.query.mock.calls[0];expect(sql).toContain("d.company_id=$1 AND d.document_type IN ('purchase','expense')");expect(args).toEqual([COMPANY])});
 it.each([{settled:[],due:null,state:'open'},{settled:[{id:'s',document_id:'purchase-1',amount:'25.00'}],due:null,state:'partial'},{settled:[{id:'s',document_id:'purchase-1',amount:'100.00'}],due:null,state:'paid'},{settled:[],due:'2020-01-01',state:'overdue'}])('derives $state for an active payable',async({settled,due,state})=>{const result=await new mod.PurchasesService(db([row({due_on:due})],settled) as any).list(COMPANY);expect(result.purchases[0]).toMatchObject({financial_state:state,payable_cancelled:false});});
 it('projects purchase and expense types and excludes sales in the tenant-scoped SQL',async()=>{mocks.pool=db([row(),row({id:'expense-1',document_type:'expense'})]);const response=await request(app).get('/api/purchases');expect(response.body.purchases.map((x:any)=>x.document_type)).toEqual(['purchase','expense']);const sql=mocks.pool.query.mock.calls[0][0];expect(sql).toContain("d.document_type IN ('purchase','expense')");expect(sql).not.toContain("d.document_type='sale'");expect(sql).toContain('d.company_id=$1')});
 it('exposes not-created payables and existing VAT review states',async()=>{const result=await new mod.PurchasesService(db([row({payable_id:null,payable_original_amount:null}),row({id:'pending',vat_review_status:'pending'}),row({id:'reviewed',vat_review_status:'reviewed',tax_date:'2026-08-01',vat_treatment:'standard',taxable_amount:'100.00',vat_amount:'15.00'})]) as any).list(COMPANY);expect(result.purchases[0]).toMatchObject({payable_relationship:'not_created',financial_state:null,vat_review_status:'missing'});expect(result.purchases[1].vat_review_status).toBe('pending');expect(result.purchases[2]).toMatchObject({vat_review_status:'reviewed',vat_amount:'15.00'})});
 it('clamps an over-settled active payable remaining balance to zero',async()=>{const result=await new mod.PurchasesService(db([row()],[{id:'s',document_id:'purchase-1',amount:'125.00'}]) as any).list(COMPANY);expect(result.purchases[0]).toMatchObject({remaining_amount:'0.00',financial_state:'paid'})});
 it('keeps cancelled history but exposes no active financial state or balance',async()=>{const history=[{id:'s',document_id:'purchase-1',amount:'20.00',transaction_date:'2026-08-02'}];const result=await new mod.PurchasesService(db([row({is_cancelled:true,due_on:'2020-01-01'})],history) as any).list(COMPANY);expect(result.purchases[0]).toMatchObject({payable_cancelled:true,payable_relationship:'linked_cancelled',financial_state:null,remaining_amount:null,paid_amount:'20.00',settlement_history:history})});
});
