import express,{NextFunction,Request,Response}from'express';import request from'supertest';import{beforeEach,describe,expect,it,vi}from'vitest';
const COMPANY='11111111-1111-4111-8111-111111111111';
const mocks=vi.hoisted(()=>({context:null as any,pool:null as any}));
vi.mock('../src/db/pool',()=>({get default(){return mocks.pool}}));
vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:()=>mocks.context,requireAuth:(_q:Request,s:Response,n:NextFunction)=>mocks.context?n():void s.status(401).end(),requireActiveCompany:(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId?n():void s.status(403).end(),requireCapability:(c:string)=>(_q:Request,s:Response,n:NextFunction)=>mocks.context?.capabilities.includes(c)?n():void s.status(403).end()}));
const mod=await import('../src/modules/sales/sales.router');const app=express();app.use('/api',mod.salesRouter);app.use((_e:unknown,_q:Request,s:Response,_n:NextFunction)=>s.status(500).end());
const row=(x:Record<string,unknown>={})=>({id:'sale-1',original_filename:'sale.pdf',status:'approved',document_date:'2026-08-01',reference_number:'INV-1',total_amount:'100.00',intake_note:'Sales note',counterparty_id:'customer-1',customer_name:'Customer',counterparty_type:'customer',receivable_id:'rec-1',receivable_original_amount:'100.00',due_on:null,verification_status:'confirmed',is_cancelled:false,...x});
function db(rows:any[],settlements:any[]=[]){return{query:vi.fn(async(sql:string,args:unknown[])=>sql.includes('FROM documents d')?{rows,rowCount:rows.length}:{rows:settlements,rowCount:settlements.length})}}
beforeEach(()=>{mocks.context={user:{id:'u'},activeCompanyId:COMPANY,capabilities:['document.view','obligation.view']};mocks.pool=null});
describe('sales projection',()=>{
 it('requires both existing read capabilities',async()=>{mocks.context.capabilities=['document.view'];expect((await request(app).get('/api/sales')).status).toBe(403);mocks.context.capabilities=['obligation.view'];expect((await request(app).get('/api/sales')).status).toBe(403)});
 it('server-scopes the sale-only query and exposes intake plus actual counterparty role',async()=>{mocks.pool=db([row()]);const response=await request(app).get('/api/sales');expect(response.status).toBe(200);expect(response.body.sales[0]).toMatchObject({customer_name:'Customer',counterparty_id:'customer-1',counterparty_type:'customer',intake_note:'Sales note',receivable_relationship:'linked_active'});const [sql,args]=mocks.pool.query.mock.calls[0];expect(sql).toContain("d.company_id=$1 AND d.document_type='sale'");expect(sql).toContain('d.intake_note');expect(sql).toContain('c.type counterparty_type');expect(args).toEqual([COMPANY])});
 it.each([{settled:[],due:null,state:'open'},{settled:[{id:'s',document_id:'sale-1',amount:'25.00'}],due:null,state:'partial'},{settled:[{id:'s',document_id:'sale-1',amount:'100.00'}],due:null,state:'paid'},{settled:[],due:'2020-01-01',state:'overdue'}])('derives $state for an active receivable',async({settled,due,state})=>{const result=await new mod.SalesService(db([row({due_on:due})],settled) as any).list(COMPANY);expect(result.sales[0]).toMatchObject({financial_state:state,receivable_cancelled:false});});
 it('keeps cancelled history but exposes no active financial state or balance',async()=>{const history=[{id:'s',document_id:'sale-1',amount:'20.00',transaction_date:'2026-08-02'}];const result=await new mod.SalesService(db([row({is_cancelled:true,due_on:'2020-01-01'})],history) as any).list(COMPANY);expect(result.sales[0]).toMatchObject({receivable_cancelled:true,receivable_relationship:'linked_cancelled',financial_state:null,remaining_amount:null,collected_amount:'20.00',settlement_history:history})});
});
