import { readFileSync } from 'node:fs';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { Pool, PoolClient } from 'pg';

const COMPANY='11111111-1111-4111-8111-111111111111',USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',FY='33333333-3333-4333-8333-333333333333',PERIOD='44444444-4444-4444-8444-444444444444',DOC='55555555-5555-4555-8555-555555555555',REVIEW='66666666-6666-4666-8666-666666666666';
const mocks=vi.hoisted(()=>({pool:null as Pool|null,audit:vi.fn()}));
vi.mock('../src/db/pool',()=>({get default(){return mocks.pool}}));
vi.mock('../src/modules/audit-log/audit-log.repository',()=>({AuditLogRepository:class{logEvent=(event:unknown,client:unknown)=>mocks.audit(event,client)}}));
const vat=await import('../src/modules/vat/vat.router');
type Result={rows:Record<string,unknown>[];rowCount:number};
const result=(rows:Record<string,unknown>[]=[]):Result=>({rows,rowCount:rows.length});
function poolFor(handler:(sql:string,args:unknown[])=>Result|Promise<Result>){const query=vi.fn((sql:string,args:unknown[]=[])=>handler(sql.replace(/\s+/g,' '),args));const client={query,release:vi.fn()}as unknown as PoolClient;return{pool:{connect:vi.fn().mockResolvedValue(client),query}as unknown as Pool,client,query};}
const period=(status:'open'|'closed'='open')=>({id:PERIOD,company_id:COMPANY,fiscal_year_id:FY,period_start:'2026-01-01',period_end:'2026-03-31',status,created_at:new Date(),updated_at:new Date()});
const review=(version=1)=>({id:REVIEW,company_id:COMPANY,document_id:DOC,tax_date:'2026-02-10',treatment:'standard',taxable_amount:'100.00',vat_amount:'15.00',review_status:'reviewed',reviewed_by_user_id:USER,reviewed_at:new Date(),review_note:null,created_at:new Date(),updated_at:new Date(),version});
beforeEach(()=>mocks.audit.mockReset().mockResolvedValue({}));

describe('Phase 6A acceptance coverage',()=>{
 it('rejects a VAT period outside its tenant fiscal year',async()=>{const built=poolFor(sql=>{if(['BEGIN','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.includes('FROM fiscal_years'))return result([{start_date:'2026-04-01',end_date:'2027-03-31'}]);throw new Error(sql)});await expect(new vat.VatService(built.pool).create(COMPANY,USER,FY,'2026-01-01','2026-03-31')).rejects.toBeInstanceOf(vat.VatValidationError)});
 it('rejects an overlapping VAT period',async()=>{const built=poolFor(sql=>{if(['BEGIN','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.includes('FROM fiscal_years'))return result([{start_date:'2026-01-01',end_date:'2026-12-31'}]);if(sql.includes('SELECT 1 FROM vat_periods WHERE company_id='))return result([{one:1}]);throw new Error(sql)});await expect(new vat.VatService(built.pool).create(COMPANY,USER,FY,'2026-01-01','2026-03-31')).rejects.toBeInstanceOf(vat.VatConflictError)});
 it('audits an existing VAT review update with before/after data',async()=>{const existing=review(1);const built=poolFor(sql=>{if(['BEGIN','COMMIT'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.startsWith('SELECT id,status,document_type FROM documents'))return result([{id:DOC,status:'approved',document_type:'purchase'}]);if(sql.startsWith('SELECT *,tax_date::text'))return result([existing]);if(sql.includes("FROM vat_periods WHERE company_id=")&&sql.includes("status='closed'"))return result();if(sql.startsWith('UPDATE document_vat_reviews'))return result([review(2)]);throw new Error(sql)});await new vat.VatService(built.pool).saveReview(COMPANY,USER,DOC,{taxDate:'2026-02-10',status:'reviewed',treatment:'standard',taxable:'100.00',vat:'15.00',note:'checked',version:1});expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'document_vat_review.update',before_data:existing,after_data:expect.objectContaining({version:2})}),built.client)});
 it('uses the same VAT company/month advisory key for close and review writes',async()=>{const close=poolFor(sql=>{if(['BEGIN','COMMIT'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.includes('FROM vat_periods WHERE id='))return result([period('open')]);if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return result([{unapproved_documents:'0',missing_reviews:'0',pending_reviews:'0'}]);if(sql.startsWith('UPDATE vat_periods'))return result([period('closed')]);throw new Error(sql)});await new vat.VatService(close.pool).close(COMPANY,USER,PERIOD);const closeLocks=close.query.mock.calls.filter(c=>String(c[0]).includes('pg_advisory_xact_lock')).map(c=>c[1]);const write=poolFor(sql=>{if(['BEGIN','COMMIT'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.startsWith('SELECT id,status,document_type FROM documents'))return result([{id:DOC,status:'approved',document_type:'purchase'}]);if(sql.startsWith('SELECT *,tax_date::text'))return result();if(sql.includes("FROM vat_periods WHERE company_id=")&&sql.includes("status='closed'"))return result();if(sql.startsWith('INSERT INTO document_vat_reviews'))return result([review()]);throw new Error(sql)});await new vat.VatService(write.pool).saveReview(COMPANY,USER,DOC,{taxDate:'2026-02-10',status:'reviewed',treatment:'standard',taxable:'100.00',vat:'15.00',note:null});const writeLock=write.query.mock.calls.find(c=>String(c[0]).includes('pg_advisory_xact_lock'))?.[1];expect(closeLocks).toContainEqual(writeLock)});
 it('wires same-origin protection on every VAT mutation route',()=>{const source=readFileSync(new URL('../src/modules/vat/vat.router.ts',import.meta.url),'utf8');for(const path of ["vatRouter.post('/vat-periods'","vatRouter.post('/vat-periods/:id/close'","vatRouter.post('/vat-periods/:id/reopen'","vatRouter.put('/documents/:id/vat-review'"]) {const line=source.split('\n').find(x=>x.includes(path));expect(line).toContain('requireSameOrigin')}});
});
