import express,{NextFunction,Request,Response}from'express';
import request from'supertest';
import{beforeEach,describe,expect,it,vi}from'vitest';
import type{Pool,PoolClient}from'pg';

const COMPANY='11111111-1111-4111-8111-111111111111',OTHER='22222222-2222-4222-8222-222222222222',USER='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',FY='33333333-3333-4333-8333-333333333333',PERIOD='44444444-4444-4444-8444-444444444444',DOC='55555555-5555-4555-8555-555555555555',REVIEW='66666666-6666-4666-8666-666666666666';
const mocks=vi.hoisted(()=>({context:null as null|{user:{id:string};activeCompanyId:string;capabilities:string[]},pool:null as Pool|null,audit:vi.fn()}));
vi.mock('../src/db/pool',()=>({get default(){return mocks.pool}}));
vi.mock('../src/modules/audit-log/audit-log.repository',()=>({AuditLogRepository:class{logEvent=(event:unknown,client:unknown)=>mocks.audit(event,client)}}));
vi.mock('../src/modules/auth/origin.middleware',()=>({requireSameOrigin:(_q:Request,_s:Response,next:NextFunction)=>next()}));
vi.mock('../src/modules/auth/auth.middleware',()=>({getAuthenticatedContext:()=>mocks.context,requireAuth:(_q:Request,s:Response,n:NextFunction)=>mocks.context?n():void s.status(401).end(),requireActiveCompany:(_q:Request,s:Response,n:NextFunction)=>mocks.context?.activeCompanyId?n():void s.status(403).end(),requireCapability:(capability:string)=>(_q:Request,s:Response,n:NextFunction)=>mocks.context?.capabilities.includes(capability)?n():void s.status(403).json({error:'Forbidden'})}));
const vat=await import('../src/modules/vat/vat.router');
type Result={rows:Record<string,unknown>[];rowCount:number};const result=(rows:Record<string,unknown>[]=[]):Result=>({rows,rowCount:rows.length});
function poolFor(handler:(sql:string,args:unknown[])=>Result|Promise<Result>){const query=vi.fn((sql:string,args:unknown[]=[])=>handler(sql.replace(/\s+/g,' '),args));const client={query,release:vi.fn()}as unknown as PoolClient;return{pool:{connect:vi.fn().mockResolvedValue(client),query}as unknown as Pool,client,query};}
const period=(status:'open'|'closed'='open')=>({id:PERIOD,company_id:COMPANY,fiscal_year_id:FY,period_start:'2026-01-01',period_end:'2026-03-31',status,created_at:new Date(),updated_at:new Date()});
const profile=(overrides:Record<string,unknown>={})=>({id:'77777777-7777-4777-8777-777777777777',company_id:COMPANY,version_no:1,workflow_status:'approved',vat_status:'registered',vat_registered_from:'2025-01-01',vat_deregistered_from:null,vat_filing_frequency:'quarterly',...overrides});
const blockers=(u=0,m=0,p=0)=>({unapproved_documents:String(u),missing_reviews:String(m),pending_reviews:String(p),vat_recoverability_pending:'0'});
const review=(version=1)=>({id:REVIEW,company_id:COMPANY,document_id:DOC,tax_date:'2026-02-10',treatment:'standard',taxable_amount:'100.00',vat_amount:'15.00',review_status:'reviewed',reviewed_by_user_id:USER,reviewed_at:new Date(),review_note:null,created_at:new Date(),updated_at:new Date(),version});
beforeEach(()=>{mocks.context=null;mocks.pool=null;mocks.audit.mockReset().mockResolvedValue({})});

describe('VAT period service',()=>{
 it('creates a tenant-scoped period inside its fiscal year and audits it',async()=>{const built=poolFor((sql)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.includes('FROM fiscal_years'))return result([{start_date:'2026-01-01',end_date:'2026-12-31'}]);if(sql.includes('FROM company_accounting_profiles'))return result([profile()]);if(sql.includes('SELECT 1 FROM vat_periods WHERE company_id='))return result();if(sql.startsWith('INSERT INTO vat_periods'))return result([period()]);throw new Error(sql)});await expect(new vat.VatService(built.pool).create(COMPANY,USER,FY,'2026-01-01','2026-03-31')).resolves.toMatchObject({company_id:COMPANY});expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'vat_period.create',company_id:COMPANY}),built.client)});
 it('rejects a cross-company or missing period on close',async()=>{const built=poolFor((sql)=>{if(['BEGIN','ROLLBACK'].includes(sql))return result();if(sql.includes('FROM vat_periods WHERE id='))return result();throw new Error(sql)});await expect(new vat.VatService(built.pool).close(OTHER,USER,PERIOD)).rejects.toBeInstanceOf(vat.VatNotFoundError)});
 it('blocks close when runtime readiness has blockers',async()=>{const built=poolFor((sql)=>{if(['BEGIN','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock')||sql.startsWith('WITH scoped AS'))return result();if(sql.includes('FROM vat_periods WHERE id='))return result([period('open')]);if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return result([blockers(0,1,0)]);throw new Error(sql)});await expect(new vat.VatService(built.pool).close(COMPANY,USER,PERIOD)).rejects.toBeInstanceOf(vat.VatConflictError);expect(built.query.mock.calls.some(c=>String(c[0]).startsWith('UPDATE vat_periods'))).toBe(false)});
 it('blocks close when a positive reviewed VAT ledger mismatch exists',async()=>{const built=poolFor((sql)=>{if(['BEGIN','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.includes('FROM vat_periods WHERE id='))return result([period('open')]);if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return result([blockers()]);if(sql.startsWith('WITH scoped AS'))return result([{reviewed_vat_amount:'15.00',document_type:'sale',reconciliation_status:'missing_posted_journal'}]);throw new Error(sql)});await expect(new vat.VatService(built.pool).close(COMPANY,USER,PERIOD)).rejects.toThrow('VAT period has blockers')});
 it('does not count a zero VAT reconciled document as a ledger blocker',async()=>{const built=poolFor((sql)=>{if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return result([blockers()]);if(sql.startsWith('WITH scoped AS'))return result([{reviewed_vat_amount:'0.00',document_type:'purchase',reconciliation_status:'reconciled'}]);throw new Error(sql)});await expect(new vat.VatService(built.pool).readiness(COMPANY,'2026-01-01','2026-03-31')).resolves.toEqual({blockers:{unapproved_documents:0,missing_reviews:0,pending_reviews:0,vat_recoverability_pending:0,vat_ledger_mismatches:0,total:0},ready:true})});
 it('closes a ready period and audits atomically',async()=>{const built=poolFor((sql)=>{if(['BEGIN','COMMIT'].includes(sql)||sql.includes('pg_advisory_xact_lock')||sql.startsWith('WITH scoped AS'))return result();if(sql.includes('FROM vat_periods WHERE id='))return result([period('open')]);if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return result([blockers()]);if(sql.startsWith('UPDATE vat_periods'))return result([period('closed')]);throw new Error(sql)});await expect(new vat.VatService(built.pool).close(COMPANY,USER,PERIOD)).resolves.toMatchObject({status:'closed',ready:true,blockers:{vat_ledger_mismatches:0}});expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'vat_period.close'}),built.client)});
 it('returns reconciliation details with a VAT period',async()=>{let reconciliationCalls=0;const built=poolFor((sql)=>{if(sql.includes('FROM vat_periods WHERE id='))return result([period('open')]);if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return result([blockers()]);if(sql.startsWith('WITH scoped AS')){reconciliationCalls++;return result(reconciliationCalls===2?[{document_id:DOC,obligation_id:'88888888-8888-4888-8888-888888888888',document_type:'sale',tax_date:'2026-02-10',treatment:'standard',reviewed_vat_amount:'15.00',expected_memo:'VAT_OUTPUT',journal_entry_id:null,journal_status:null,ledger_vat_amount:null,reconciliation_status:'missing_posted_journal'}]:[])}if(sql.startsWith('SELECT d.id,d.status'))return result();throw new Error(sql)});const value=await new vat.VatService(built.pool).get(COMPANY,PERIOD);expect(value.reconciliation).toMatchObject({counts:{total_in_scope:1,reconciled:0,unreconciled:1},documents:[{document_id:DOC}]})});
});

describe('manual document VAT review',()=>{
 it('creates a reviewed VAT record only for an approved same-company document',async()=>{const built=poolFor((sql)=>{if(['BEGIN','COMMIT'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.startsWith('SELECT id,status,document_type FROM documents'))return result([{id:DOC,status:'approved',document_type:'purchase'}]);if(sql.startsWith('SELECT *,tax_date::text'))return result();if(sql.startsWith('SELECT 1 FROM monthly_close_periods'))return result();if(sql.includes("FROM vat_periods WHERE company_id=")&&sql.includes("status='closed'"))return result();if(sql.startsWith('INSERT INTO document_vat_reviews'))return result([review()]);throw new Error(sql)});await expect(new vat.VatService(built.pool).saveReview(COMPANY,USER,DOC,{taxDate:'2026-02-10',status:'reviewed',treatment:'standard',taxable:'100.00',vat:'15.00',note:null})).resolves.toMatchObject({document_id:DOC,vat_amount:'15.00'});expect(mocks.audit).toHaveBeenCalledWith(expect.objectContaining({action:'document_vat_review.create'}),built.client)});
 it('rejects review writes into a closed VAT period',async()=>{const built=poolFor((sql)=>{if(['BEGIN','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.startsWith('SELECT id,status,document_type FROM documents'))return result([{id:DOC,status:'approved',document_type:'sale'}]);if(sql.startsWith('SELECT *,tax_date::text'))return result();if(sql.startsWith('SELECT 1 FROM monthly_close_periods'))return result();if(sql.includes("FROM vat_periods WHERE company_id=")&&sql.includes("status='closed'"))return result([{one:1}]);throw new Error(sql)});await expect(new vat.VatService(built.pool).saveReview(COMPANY,USER,DOC,{taxDate:'2026-02-10',status:'reviewed',treatment:'standard',taxable:'100.00',vat:'15.00',note:null})).rejects.toBeInstanceOf(vat.VatConflictError)});
 it('requires the current version when updating an existing review',async()=>{const built=poolFor((sql)=>{if(['BEGIN','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.startsWith('SELECT id,status,document_type FROM documents'))return result([{id:DOC,status:'approved',document_type:'expense'}]);if(sql.startsWith('SELECT *,tax_date::text'))return result([review(2)]);if(sql.startsWith('SELECT 1 FROM monthly_close_periods'))return result();if(sql.includes("FROM vat_periods WHERE company_id=")&&sql.includes("status='closed'"))return result();throw new Error(sql)});await expect(new vat.VatService(built.pool).saveReview(COMPANY,USER,DOC,{taxDate:'2026-02-10',status:'reviewed',treatment:'standard',taxable:'100.00',vat:'15.00',note:null,version:1})).rejects.toBeInstanceOf(vat.VatConflictError)});
});

describe('VAT HTTP authorization and validation',()=>{
 const app=express();app.use(express.json());app.use('/api',vat.vatRouter);app.use((error:unknown,_q:Request,res:Response,_n:NextFunction)=>res.status(500).json({error:error instanceof Error?error.message:'error'}));
 it('requires vat.view to list periods',async()=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:[]};expect((await request(app).get('/api/vat-periods')).status).toBe(403)});
 it('requires vat.review for review writes',async()=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:['vat.view']};expect((await request(app).put(`/api/documents/${DOC}/vat-review`).send({tax_date:'2026-02-10',review_status:'pending',treatment:null,taxable_amount:null,vat_amount:null})).status).toBe(403)});
 it('requires vat.reopen independently and a non-empty reason',async()=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:['vat.close']};expect((await request(app).post(`/api/vat-periods/${PERIOD}/reopen`).send({reason:'fix'})).status).toBe(403);mocks.context.capabilities=['vat.reopen'];expect((await request(app).post(`/api/vat-periods/${PERIOD}/reopen`).send({reason:' '})).status).toBe(400)});
 it('rejects negative, excessive, and unknown recoverability payload values before SQL',async()=>{mocks.context={user:{id:USER},activeCompanyId:COMPANY,capabilities:['vat.review']};for(const payload of [{recoverability_status:'partially_recoverable',recoverable_vat_amount:'-1.00'},{recoverability_status:'automatic',recoverable_vat_amount:'1.00'}]){const response=await request(app).put(`/api/documents/${DOC}/vat-review`).send({tax_date:'2026-02-10',review_status:'reviewed',treatment:'standard',taxable_amount:'100.00',vat_amount:'15.00',...payload});expect(response.status).toBe(400)}});

});

describe('Phase 6B2 recoverability controls',()=>{
 async function save(type:'sale'|'purchase'|'expense',recoverability?:string,recoverable?:string|null,vatAmount='15.00'){
  let values:unknown[]=[];const built=poolFor((sql,args)=>{if(['BEGIN','COMMIT','ROLLBACK'].includes(sql)||sql.includes('pg_advisory_xact_lock'))return result();if(sql.startsWith('SELECT id,status,document_type FROM documents'))return result([{id:DOC,status:'approved',document_type:type}]);if(sql.startsWith('SELECT *,tax_date::text'))return result();if(sql.startsWith('SELECT 1 FROM monthly_close_periods')||sql.includes("FROM vat_periods WHERE company_id="))return result();if(sql.startsWith('INSERT INTO document_vat_reviews')){values=args;return result([review()])}throw new Error(sql)});
  const input:any={taxDate:'2026-02-10',status:'reviewed',treatment:'standard',taxable:'100.00',vat:vatAmount,note:null};if(recoverability!==undefined)input.recoverability=recoverability;if(recoverable!==undefined)input.recoverable=recoverable;
  await new vat.VatService(built.pool).saveReview(COMPANY,USER,DOC,input);return values;
 }
 it('defaults sales to not applicable and positive purchases and expenses to needs review',async()=>{expect(await save('sale')).toEqual(expect.arrayContaining(['not_applicable']));for(const type of ['purchase','expense'] as const){const values=await save(type);expect(values[10]).toBe('needs_review');expect(values[11]).toBeNull()}});
 it.each([
  ['fully_recoverable','15.00'],['non_recoverable','0.00'],['partially_recoverable','9.00'],['needs_review',null],
 ] as const)('accepts valid %s decisions',async(status,amount)=>{const values=await save('purchase',status,amount);expect(values[10]).toBe(status);expect(values[11]).toBe(amount)});
 it.each([
  ['fully_recoverable','14.99'],['fully_recoverable','15.01'],['non_recoverable','0.01'],['partially_recoverable','0.00'],['partially_recoverable','15.00'],['needs_review','1.00'],['not_applicable',null],
 ] as const)('rejects invalid purchase %s / %s',async(status,amount)=>{await expect(save('purchase',status,amount)).rejects.toBeInstanceOf(vat.VatValidationError)});
 it('rejects a recoverability decision on a sale and resolves zero input VAT without a blocker',async()=>{await expect(save('sale','fully_recoverable','15.00')).rejects.toBeInstanceOf(vat.VatValidationError);const values=await save('expense',undefined,undefined,'0.00');expect(values[10]).toBe('fully_recoverable');expect(values[11]).toBe('0.00')});
 it('counts unresolved reviewed input VAT by tax_date as a close blocker',async()=>{const built=poolFor(sql=>{if(sql.startsWith('SELECT (SELECT COUNT(*) FROM documents'))return result([{...blockers(),vat_recoverability_pending:'1'}]);if(sql.startsWith('WITH scoped AS'))return result();throw new Error(sql)});const value=await new vat.VatService(built.pool).readiness(COMPANY,'2026-01-01','2026-03-31');expect(value).toMatchObject({ready:false,blockers:{vat_recoverability_pending:1,total:1}});const sql=built.query.mock.calls[0]![0] as string;expect(sql).toContain('r.tax_date BETWEEN $2 AND $3')});
});
