import {Pool,PoolClient} from 'pg';
import {AuditLogRepository} from '../audit-log/audit-log.repository';
import {WhtReview,WhtReviewValues,WhtStatus} from './wht-review.types';
export class WhtReviewNotFoundError extends Error{} export class WhtReviewConflictError extends Error{} export class WhtReviewValidationError extends Error{}
const SELECT=`r.*,r.prepared_at::text,r.reviewed_at::text,r.created_at::text,r.updated_at::text,c.name counterparty_name`;
export class WhtReviewService{
 constructor(private db:Pool){ }
 async list(companyId:string,yearId:string){return (await this.db.query<WhtReview>(`SELECT ${SELECT} FROM wht_reviews r LEFT JOIN counterparties c ON c.id=r.counterparty_id AND c.company_id=r.company_id WHERE r.company_id=$1 AND r.fiscal_year_id=$2 ORDER BY r.created_at`,[companyId,yearId])).rows;}
 private async source(company:string,type:string,id:string,c:PoolClient){const tables:{[key:string]:string}={document:'documents',obligation:'obligations',bank_transaction:'bank_transactions'};const table=tables[type];if(!table)return false;return Boolean((await c.query(`SELECT 1 FROM ${table} WHERE id=$1 AND company_id=$2`,[id,company])).rowCount);}
 private async tx<T>(fn:(c:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const result=await fn(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
 private async audit(c:PoolClient,company:string,actor:string,action:string,id:string,before:WhtReview|null,after:WhtReview){await new AuditLogRepository().logEvent({company_id:company,actor_user_id:actor,action,entity_type:'wht_review',entity_id:id,before_data:before as unknown as Record<string,unknown>,after_data:after as unknown as Record<string,unknown>},c);}
 async create(company:string,year:string,actor:string,v:WhtReviewValues){return this.tx(async c=>{if(!(await c.query('SELECT 1 FROM fiscal_years WHERE id=$1 AND company_id=$2',[year,company])).rowCount||!await this.source(company,v.source_type,v.source_id,c))throw new WhtReviewValidationError('Invalid company source or fiscal year');if(v.counterparty_id&&!(await c.query('SELECT 1 FROM counterparties WHERE id=$1 AND company_id=$2',[v.counterparty_id,company])).rowCount)throw new WhtReviewValidationError('Invalid counterparty');try{const row=(await c.query<WhtReview>(`INSERT INTO wht_reviews(company_id,fiscal_year_id,prepared_by_user_id,source_type,source_id,counterparty_id,non_resident_assessment,payment_service_category,basis_reference,reviewer_note,professional_review_required) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *,prepared_at::text,reviewed_at::text,created_at::text,updated_at::text`,[company,year,actor,v.source_type,v.source_id,v.counterparty_id??null,v.non_resident_assessment,v.payment_service_category,v.basis_reference,v.reviewer_note??null,v.professional_review_required])).rows[0]!;await this.audit(c,company,actor,'wht_review.created',row.id,null,row);return row;}catch(e){if((e as {code?:string}).code==='23505')throw new WhtReviewConflictError('Source already has a review');throw e;}});}
 async update(company:string,year:string,id:string,actor:string,v:Partial<WhtReviewValues>&{version:number}){return this.tx(async c=>{const before=(await c.query<WhtReview>('SELECT * FROM wht_reviews WHERE id=$1 AND company_id=$2 AND fiscal_year_id=$3 FOR UPDATE',[id,company,year])).rows[0];if(!before)throw new WhtReviewNotFoundError();const sourceType=v.source_type??before.source_type,sourceId=v.source_id??before.source_id;if((v.source_type!==undefined||v.source_id!==undefined)&&!await this.source(company,sourceType,sourceId,c))throw new WhtReviewValidationError('Invalid company source');if(v.counterparty_id&&!(await c.query('SELECT 1 FROM counterparties WHERE id=$1 AND company_id=$2',[v.counterparty_id,company])).rowCount)throw new WhtReviewValidationError('Invalid counterparty');const keys=Object.keys(v).filter(k=>k!=='version') as (keyof WhtReviewValues)[];if(!keys.length)throw new WhtReviewValidationError('No changes');const material=keys.some(k=>k!=='reviewer_note');const set=keys.map((k,i)=>`${k}=$${i+1}`);if(material)set.push("workflow_status='needs_review'","assessment_result=NULL","reviewed_by_user_id=NULL","reviewed_at=NULL");const row=(await c.query<WhtReview>(`UPDATE wht_reviews SET ${set.join(',')},version=version+1,updated_at=NOW() WHERE id=$${keys.length+1} AND company_id=$${keys.length+2} AND fiscal_year_id=$${keys.length+3} AND version=$${keys.length+4} RETURNING *,prepared_at::text,reviewed_at::text,created_at::text,updated_at::text`,[...keys.map(k=>v[k]),id,company,year,v.version])).rows[0];if(!row)throw new WhtReviewConflictError('Version conflict');await this.audit(c,company,actor,material?'wht_review.materially_changed':'wht_review.updated',id,before,row);return row;});}
 async transition(company:string,year:string,id:string,actor:string,version:number,action:'submit'|'review',result?:'not_applicable'|'applicable',note?:string|null){return this.tx(async c=>{const before=(await c.query<WhtReview>('SELECT * FROM wht_reviews WHERE id=$1 AND company_id=$2 AND fiscal_year_id=$3 FOR UPDATE',[id,company,year])).rows[0];if(!before)throw new WhtReviewNotFoundError();const allowed=action==='submit'?before.workflow_status==='needs_review':['submitted','needs_review'].includes(before.workflow_status);if(!allowed)throw new WhtReviewConflictError('Invalid workflow transition');const status:WhtStatus=action==='submit'?'submitted':'reviewed';const row=(await c.query<WhtReview>(`UPDATE wht_reviews SET workflow_status=$1,assessment_result=$2,reviewer_note=COALESCE($3,reviewer_note),professional_review_required=$4,reviewed_by_user_id=$5,reviewed_at=$6,version=version+1,updated_at=NOW() WHERE id=$7 AND company_id=$8 AND fiscal_year_id=$9 AND version=$10 RETURNING *,prepared_at::text,reviewed_at::text,created_at::text,updated_at::text`,[status,action==='review'?result:null,note,action==='submit'?before.professional_review_required:false,action==='review'?actor:null,action==='review'?new Date():null,id,company,year,version])).rows[0];if(!row)throw new WhtReviewConflictError('Version conflict');await this.audit(c,company,actor,`wht_review.${action}`,id,before,row);return row;});}
}
