import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { PageHeader, StatusBadge, WorkspaceState } from './SharedUI';

type Account={id:string;code:string;name:string;account_type:'asset'|'liability'|'equity'|'revenue'|'expense';parent_account_id:string|null;is_active:boolean};
type Year={id:string;name:string;start_date:string;end_date:string};
type Journal={id:string;fiscal_year_id:string;accounting_date:string;description:string;reference:string|null;entry_type:'standard'|'opening_balance';status:'draft'|'posted'};
type Line={account_id:string;debit:string;credit:string;memo:string};
type TrialRow=Account&{debit_movement:string;credit_movement:string;debit_balance:string;credit_balance:string};
type LedgerRow={accounting_date:string;journal_id:string;reference:string|null;description:string;debit:string;credit:string;running_balance:string};
type Tab='accounts'|'journals'|'trial'|'ledger';
interface Props{canView:boolean;canManageChart:boolean;canManageJournals:boolean;canPost:boolean;onUnauthorized:()=>void}
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const response=await fetch(url,{credentials:'same-origin',...options});if(response.status===401)onUnauthorized();if(!response.ok)throw new Error(String(response.status));return response;}
const json=(method:string,body:unknown):RequestInit=>({method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});
const emptyLine=():Line=>({account_id:'',debit:'0.00',credit:'0.00',memo:''});

export function Accounting({canView,canManageChart,canManageJournals,canPost,onUnauthorized}:Props){
 const {t}=useTranslation();const [tab,setTab]=useState<Tab>('accounts');const [accounts,setAccounts]=useState<Account[]>([]);const [years,setYears]=useState<Year[]>([]);const [journals,setJournals]=useState<Journal[]>([]);const [selected,setSelected]=useState<Journal|null>(null);const [lines,setLines]=useState<Line[]>([emptyLine(),emptyLine()]);const [trial,setTrial]=useState<TrialRow[]>([]);const [ledger,setLedger]=useState<LedgerRow[]>([]);const [loading,setLoading]=useState(canView);const [error,setError]=useState(false);const [saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);setError(false);try{const [a,y,j]=await Promise.all([api('/api/accounts',{},onUnauthorized),api('/api/fiscal-years',{},onUnauthorized),api('/api/journals',{},onUnauthorized)]);setAccounts(((await a.json())as{accounts:Account[]}).accounts);setYears(((await y.json())as{fiscalYears:Year[]}).fiscalYears);setJournals(((await j.json())as{journals:Journal[]}).journals);}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{if(canView)void load();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);
 const totals=useMemo(()=>lines.reduce((v,l)=>({debit:v.debit+Number(l.debit||0),credit:v.credit+Number(l.credit||0)}),{debit:0,credit:0}),[lines]);
 if(!canView)return <section className="panel"><WorkspaceState>{t('accounting.noAccess')}</WorkspaceState></section>;
 const createAccount=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setSaving(true);try{await api('/api/accounts',json('POST',{code:d.get('code'),name:d.get('name'),account_type:d.get('account_type'),parent_account_id:d.get('parent_account_id')||null}),onUnauthorized);e.currentTarget.reset();await load()}catch{setError(true)}finally{setSaving(false)}};
 const toggleAccount=async(a:Account)=>{setSaving(true);try{await api(`/api/accounts/${a.id}`,json('PATCH',{is_active:!a.is_active}),onUnauthorized);await load()}catch{setError(true)}finally{setSaving(false)}};
 const createJournal=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setSaving(true);try{const response=await api('/api/journals',json('POST',{fiscal_year_id:d.get('fiscal_year_id'),accounting_date:d.get('accounting_date'),description:d.get('description'),reference:d.get('reference')||null,entry_type:d.get('entry_type')}),onUnauthorized);const journal=await response.json() as Journal;setSelected(journal);setLines([emptyLine(),emptyLine()]);await load()}catch{setError(true)}finally{setSaving(false)}};
 const openJournal=async(j:Journal)=>{setSelected(j);try{const response=await api(`/api/journals/${j.id}`,{},onUnauthorized);const value=await response.json() as Journal&{lines:Array<{account_id:string;debit:string;credit:string;memo:string|null}>};setLines(value.lines.length?value.lines.map(l=>({...l,memo:l.memo??''})):[emptyLine(),emptyLine()])}catch{setError(true)}};
 const saveLines=async()=>{if(!selected)return;setSaving(true);try{await api(`/api/journals/${selected.id}/lines`,json('PUT',{lines:lines.map(l=>({...l,memo:l.memo||null}))}),onUnauthorized);await openJournal(selected)}catch{setError(true)}finally{setSaving(false)}};
 const post=async()=>{if(!selected)return;setSaving(true);try{await api(`/api/journals/${selected.id}/post`,json('POST',{}),onUnauthorized);setSelected(null);await load()}catch{setError(true)}finally{setSaving(false)}};
 const report=async(kind:'trial'|'ledger',e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);const year=String(d.get('fiscal_year_id'));try{if(kind==='trial'){const r=await api(`/api/trial-balance?fiscal_year_id=${encodeURIComponent(year)}`,{},onUnauthorized);setTrial(((await r.json())as{accounts:TrialRow[]}).accounts)}else{const account=String(d.get('account_id'));const r=await api(`/api/general-ledger?fiscal_year_id=${encodeURIComponent(year)}&account_id=${encodeURIComponent(account)}`,{},onUnauthorized);setLedger(((await r.json())as{activity:LedgerRow[]}).activity)}}catch{setError(true)}};
 return <section className="panel" aria-labelledby="accounting-title"><PageHeader titleId="accounting-title" eyebrow={t('accounting.title')} title={t('accounting.title')} description={t('accounting.description')}/>
  <div className="workspace-tabs" role="tablist">{(['accounts','journals','trial','ledger']as Tab[]).map(x=><button role="tab" aria-selected={tab===x} className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{t(`accounting.tabs.${x}`)}</button>)}</div>
  {error&&<WorkspaceState tone="error" action={<button onClick={()=>void load()}>{t('common.retry')}</button>}>{t('accounting.error')}</WorkspaceState>}{loading&&<WorkspaceState>{t('accounting.loading')}</WorkspaceState>}
  {!loading&&tab==='accounts'&&<><h2>{t('accounting.accounts')}</h2>{canManageChart&&<form className="form-grid compact-form" onSubmit={createAccount}><label>{t('accounting.code')}<input name="code" required maxLength={50}/></label><label>{t('accounting.name')}<input name="name" required maxLength={200}/></label><label>{t('accounting.type')}<select name="account_type">{(['asset','liability','equity','revenue','expense']as const).map(x=><option value={x} key={x}>{t(`accounting.types.${x}`)}</option>)}</select></label><label>{t('accounting.parent')}<select name="parent_account_id"><option value="">—</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.code} — {a.name}</option>)}</select></label><button className="primary" disabled={saving}>{t('accounting.addAccount')}</button></form>}<div className="table-wrap"><table><thead><tr><th>{t('accounting.code')}</th><th>{t('accounting.name')}</th><th>{t('accounting.type')}</th><th>{t('accounting.status')}</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td>{a.code}</td><td>{a.name}</td><td>{t(`accounting.types.${a.account_type}`)}</td><td>{canManageChart?<button disabled={saving} onClick={()=>void toggleAccount(a)}>{t(a.is_active?'accounting.active':'accounting.inactive')}</button>:t(a.is_active?'accounting.active':'accounting.inactive')}</td></tr>)}</tbody></table></div></>}
  {!loading&&tab==='journals'&&<><h2>{t('accounting.journals')}</h2>{canManageJournals&&<form className="form-grid compact-form" onSubmit={createJournal}><label>{t('accounting.fiscalYear')}<select name="fiscal_year_id" required>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>{t('accounting.date')}<input name="accounting_date" type="date" required/></label><label>{t('accounting.descriptionLabel')}<input name="description" required maxLength={500}/></label><label>{t('accounting.reference')}<input name="reference" maxLength={200}/></label><label>{t('accounting.entryType')}<select name="entry_type"><option value="standard">{t('accounting.standard')}</option><option value="opening_balance">{t('accounting.opening')}</option></select></label><button className="primary" disabled={saving}>{t('accounting.createJournal')}</button></form>}<div className="accounting-journal-list">{journals.map(j=><button key={j.id} onClick={()=>void openJournal(j)}><span>{j.accounting_date} · {j.description}</span><StatusBadge status={j.status}>{t(`accounting.${j.status}`)}</StatusBadge></button>)}</div>{selected&&<div className="accounting-editor"><h3>{selected.description}</h3>{lines.map((l,i)=><div className="journal-line" key={i}><select value={l.account_id} disabled={selected.status==='posted'} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,account_id:e.target.value}:x))}><option value="">{t('accounting.account')}</option>{accounts.map(a=><option disabled={!a.is_active} key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select><input aria-label={t('accounting.debit')} type="number" min="0" step="0.01" value={l.debit} disabled={selected.status==='posted'} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,debit:e.target.value}:x))}/><input aria-label={t('accounting.credit')} type="number" min="0" step="0.01" value={l.credit} disabled={selected.status==='posted'} onChange={e=>setLines(v=>v.map((x,n)=>n===i?{...x,credit:e.target.value}:x))}/></div>)}<p className={totals.debit===totals.credit&&totals.debit>0?'balanced':'unbalanced'}>{t('accounting.totals',{debit:totals.debit.toFixed(2),credit:totals.credit.toFixed(2)})} · {t(totals.debit===totals.credit&&totals.debit>0?'accounting.balanced':'accounting.unbalanced')}</p>{selected.status==='draft'&&canManageJournals&&<><button onClick={()=>setLines(v=>[...v,emptyLine()])}>{t('accounting.addLine')}</button><button className="primary" disabled={saving} onClick={()=>void saveLines()}>{t('common.save')}</button></>}{selected.status==='draft'&&canPost&&<button className="primary" disabled={saving||totals.debit!==totals.credit||totals.debit===0||lines.length<2} onClick={()=>void post()}>{t('accounting.post')}</button>}</div>}</>}
  {!loading&&tab==='trial'&&<><form className="compact-form" onSubmit={e=>void report('trial',e)}><select name="fiscal_year_id" required>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select><button className="primary">{t('accounting.run')}</button></form><div className="table-wrap"><table><thead><tr><th>{t('accounting.account')}</th><th>{t('accounting.debitMovement')}</th><th>{t('accounting.creditMovement')}</th><th>{t('accounting.balance')}</th></tr></thead><tbody>{trial.map(r=><tr key={r.id}><td>{r.code} — {r.name}</td><td>{r.debit_movement}</td><td>{r.credit_movement}</td><td>{Number(r.debit_balance)>0?`${r.debit_balance} ${t('accounting.debit')}`:`${r.credit_balance} ${t('accounting.credit')}`}</td></tr>)}</tbody></table></div></>}
  {!loading&&tab==='ledger'&&<><form className="compact-form" onSubmit={e=>void report('ledger',e)}><select name="fiscal_year_id" required>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select><select name="account_id" required>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select><button className="primary">{t('accounting.run')}</button></form><div className="table-wrap"><table><thead><tr><th>{t('accounting.date')}</th><th>{t('accounting.reference')}</th><th>{t('accounting.descriptionLabel')}</th><th>{t('accounting.debit')}</th><th>{t('accounting.credit')}</th><th>{t('accounting.balance')}</th></tr></thead><tbody>{ledger.map(r=><tr key={`${r.journal_id}-${r.accounting_date}-${r.running_balance}`}><td>{r.accounting_date}</td><td>{r.reference??r.journal_id.slice(0,8)}</td><td>{r.description}</td><td>{r.debit}</td><td>{r.credit}</td><td>{r.running_balance}</td></tr>)}</tbody></table></div></>}
 </section>;
}
