import {FormEvent,useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {StatusBadge,WorkspaceState} from './SharedUI';
import './FixedAssets.css';

type Category={id:string;name_ar:string;name_en:string;depreciable:boolean};
type Account={id:string;code:string;name:string;account_type:string;is_active:boolean};
type Asset={id:string;asset_category_id:string;asset_number:string;name:string;status:string;depreciation_policy_version_id:string|null;useful_life_months:number|null;residual_value:string};
type Policy={id:string;asset_category_id:string;version_number:number;effective_from:string|null;depreciation_method:'straight_line'|null;useful_life_mode:'fixed'|'asset_specific'|'not_applicable';useful_life_months:number|null;residual_value_policy:'zero'|'asset_specific'|'not_applicable';depreciation_start_basis:'placed_in_service'|'explicit_date'|'not_applicable';asset_account_id:string|null;accumulated_depreciation_account_id:string|null;depreciation_expense_account_id:string|null;status:'draft'|'approved'|'superseded';is_legacy_migrated:boolean;reviewed_at:string|null;approved_at:string|null};
type EstimateChange={id:string;effective_from:string;old_useful_life_months:number|null;new_remaining_useful_life_months:number|null;old_residual_value:string;new_residual_value:string|null;reason:string;policy_exception:boolean;policy_exception_reason:string|null;status:'draft'|'reviewed'|'approved';reviewed_at:string|null;approved_at:string|null};

type Props={canView:boolean;canManagePolicy:boolean;canCreateEstimate:boolean;canReviewEstimate:boolean;canApproveEstimate:boolean;onUnauthorized:()=>void;onBack?:()=>void};

export function AssetPolicyOperations({canView,canManagePolicy,canCreateEstimate,canReviewEstimate,canApproveEstimate,onUnauthorized,onBack}:Props){
 const{t,i18n}=useTranslation();
 const ar=i18n.language==='ar';
 const label=(arText:string,enText:string)=>ar?arText:enText;
 const statusText=(v:string)=>ar?({approved:'معتمد',draft:'مسودة',superseded:'مستبدلة',reviewed:'تمت المراجعة'} as Record<string,string>)[v]??v:v;
 const[categories,setCategories]=useState<Category[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[assets,setAssets]=useState<Asset[]>([]);
 const[categoryId,setCategoryId]=useState(''),[policies,setPolicies]=useState<Policy[]>([]),[assetId,setAssetId]=useState(''),[changes,setChanges]=useState<EstimateChange[]>([]);
 const[policyForm,setPolicyForm]=useState(false),[editingPolicy,setEditingPolicy]=useState<Policy|null>(null),[estimateForm,setEstimateForm]=useState(false),[error,setError]=useState(''),[loadError,setLoadError]=useState(false),[loading,setLoading]=useState(true);
 const request=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init);if(r.status===401){onUnauthorized();throw Error()}if(!r.ok){const body=await r.json().catch(()=>({}));throw Error(body.error||label('تعذر تنفيذ العملية','Operation failed'))}return r};
 const loadBase=async()=>{setLoading(true);try{const reqs=[request('/api/asset-categories'),request('/api/assets'),...(canManagePolicy?[request('/api/accounts')]:[])];const responses=await Promise.all(reqs);const cats=(await responses[0]!.json()).categories as Category[],nextAssets=(await responses[1]!.json()).assets as Asset[];setCategories(cats);setAssets(nextAssets);if(canManagePolicy)setAccounts((await responses[2]!.json()).accounts);setCategoryId(v=>v||cats[0]?.id||'');setAssetId(v=>v||nextAssets[0]?.id||'')}catch(e){setError((e as Error).message);setLoadError(true)}finally{setLoading(false)}};
 useEffect(()=>{if(canView)void loadBase()},[canView,canManagePolicy]);
 useEffect(()=>{if(!categoryId){setPolicies([]);return}void request(`/api/asset-categories/${categoryId}/policies`).then(r=>r.json()).then(x=>setPolicies(x.policies)).catch(e=>{setError(e.message);setLoadError(true)})},[categoryId]);
 useEffect(()=>{if(!assetId){setChanges([]);return}void request(`/api/assets/${assetId}/estimate-changes`).then(r=>r.json()).then(x=>setChanges(x.changes)).catch(e=>{setError(e.message);setLoadError(true)})},[assetId]);
 const selectedCategory=categories.find(c=>c.id===categoryId),selectedAsset=assets.find(a=>a.id===assetId);
 const currentPolicy=policies.find(p=>p.status==='approved')??null;
 const activeAccounts=(type:string)=>accounts.filter(a=>a.is_active&&a.account_type===type);
 const accountLabel=(a:Account)=>`${a.code} — ${a.name}`;
 const nextMonthStart=()=>{const d=new Date();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+1);return d.toISOString().slice(0,10)};
 const reloadPolicies=async()=>{if(!categoryId)return;setPolicies((await(await request(`/api/asset-categories/${categoryId}/policies`)).json()).policies)};
 const reloadChanges=async()=>{if(!assetId)return;setChanges((await(await request(`/api/assets/${assetId}/estimate-changes`)).json()).changes);const a=(await(await request(`/api/assets/${assetId}`)).json()) as Asset;setAssets(list=>list.map(x=>x.id===a.id?{...x,...a}:x))};
 const policyPayload=(d:FormData)=>{const depreciable=selectedCategory?.depreciable!==false;return{effective_from:String(d.get('effectiveFrom')),depreciation_method:depreciable?'straight_line':null,useful_life_mode:depreciable?String(d.get('lifeMode')):'not_applicable',useful_life_months:depreciable&&d.get('lifeMode')==='fixed'?Number(d.get('life')):null,residual_value_policy:depreciable?String(d.get('residualPolicy')):'not_applicable',depreciation_start_basis:depreciable?String(d.get('startBasis')):'not_applicable',asset_account_id:d.get('assetAccount')||null,accumulated_depreciation_account_id:depreciable?(d.get('accumulatedAccount')||null):null,depreciation_expense_account_id:depreciable?(d.get('expenseAccount')||null):null}};
 const submitPolicy=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!categoryId)return;setError('');try{const payload=policyPayload(new FormData(e.currentTarget));if(editingPolicy)await request(`/api/asset-policies/${editingPolicy.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});else await request(`/api/asset-categories/${categoryId}/policies`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});await reloadPolicies();setPolicyForm(false);setEditingPolicy(null)}catch(e){setError((e as Error).message)}};
 const actPolicy=async(id:string,action:'review'|'approve')=>{setError('');try{await request(`/api/asset-policies/${id}/${action}`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});await reloadPolicies();await loadBase()}catch(e){setError((e as Error).message)}};
 const submitEstimate=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!assetId)return;const d=new FormData(e.currentTarget);setError('');try{await request(`/api/assets/${assetId}/estimate-changes`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({effective_from:d.get('effectiveFrom'),remaining_useful_life_months:d.get('remainingLife')?Number(d.get('remainingLife')):null,residual_value:d.get('residual')?String(d.get('residual')):null,reason:d.get('reason'),policy_exception_reason:d.get('exceptionReason')||null})});await reloadChanges();setEstimateForm(false)}catch(e){setError((e as Error).message)}};
 const actEstimate=async(id:string,action:'review'|'approve')=>{setError('');try{await request(`/api/asset-estimate-changes/${id}/${action}`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});await reloadChanges()}catch(e){setError((e as Error).message)}};
 const editPolicy=(p:Policy)=>{setEditingPolicy(p);setPolicyForm(true)};
 const canStartEstimate=Boolean(canCreateEstimate&&selectedAsset&&selectedAsset.status==='active');
 if(!canView)return null;
 return <section className="panel fa-view" aria-labelledby="asset-policy-title" data-workspace-size="operational">
  <header className="fa-header"><div><h2 id="asset-policy-title">{label('حوكمة سياسة إهلاك الأصول','Asset depreciation policy governance')}</h2><p>{label('إدارة السياسة الفعالة وتاريخها وتغييرات التقديرات المستقبلية دون تعديل الإهلاك المنشور.','Manage effective policies, history, and prospective estimate changes without altering posted depreciation.')}</p></div></header>
  {onBack&&<div className="fa-subbar"><button type="button" className="fa-link" onClick={onBack}>{t('assets.title')}</button></div>}
  {error&&(loadError?<div role="alert" className="fa-error"><strong>{label('تعذر تحميل بيانات حوكمة سياسة الإهلاك','Unable to load depreciation policy governance data')}</strong><span>{label('حدث خطأ في الخادم. يمكنك المحاولة مرة أخرى لاحقًا.','A server error occurred. You can try again later.')}</span></div>:<WorkspaceState tone="error">{error}</WorkspaceState>)}
  {loading?<WorkspaceState>{t('common.loading')}</WorkspaceState>:<>
   <div className="fa-card fa-grid2">
    <label>{label('فئة الأصل','Asset category')}<select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setEditingPolicy(null);setPolicyForm(false)}}>{categories.map(c=><option key={c.id} value={c.id}>{ar?c.name_ar:c.name_en}</option>)}</select></label>
    <label>{label('الأصل','Asset')}<select value={assetId} onChange={e=>{setAssetId(e.target.value);setEstimateForm(false)}}><option value="">—</option>{assets.map(a=><option key={a.id} value={a.id}>{a.asset_number} — {a.name}</option>)}</select></label>
   </div>
   <section className="fa-card"><div className="fa-card__head"><h3>{label('السياسة الحالية والتاريخ','Current policy and history')}</h3>{canManagePolicy&&<button className="fa-primary" onClick={()=>{setEditingPolicy(null);setPolicyForm(v=>!v)}}>{label('سياسة جديدة','New policy')}</button>}</div>
    {currentPolicy?<dl className="fa-summary"><div className="fa-field"><dt>{label('الحالة الحالية','Current status')}</dt><dd><StatusBadge status={currentPolicy.status}>{statusText(currentPolicy.status)}</StatusBadge></dd></div><div className="fa-field"><dt>{label('نسخة السياسة','Policy version')}</dt><dd><strong>v{currentPolicy.version_number}</strong></dd></div><div className="fa-field"><dt>{label('تاريخ السريان','Effective from')}</dt><dd>{currentPolicy.effective_from??'—'}</dd></div><div className="fa-field"><dt>{label('العمر الإنتاجي','Useful life')}</dt><dd><strong>{currentPolicy.useful_life_mode==='fixed'?`${currentPolicy.useful_life_months} ${label('شهرًا','months')}`:currentPolicy.useful_life_mode}</strong></dd></div><div className="fa-field"><dt>{label('طريقة القيمة المتبقية','Residual-value method')}</dt><dd><strong>{currentPolicy.residual_value_policy}</strong></dd></div></dl>:<p className="fa-muted">{label('لا توجد سياسة معتمدة حاليًا لهذه الفئة.','No approved policy currently exists for this category.')}</p>}
    {policyForm&&canManagePolicy&&<form className="form-grid fa-form" onSubmit={submitPolicy}>
      <label>{label('تاريخ السريان','Effective from')}<input name="effectiveFrom" type="date" required defaultValue={editingPolicy?.effective_from??nextMonthStart()}/></label>
      {selectedCategory?.depreciable!==false&&<><label>{label('نمط العمر الإنتاجي','Useful-life mode')}<select name="lifeMode" defaultValue={editingPolicy?.useful_life_mode??'fixed'}><option value="fixed">fixed</option><option value="asset_specific">asset_specific</option></select></label><label>{label('العمر الإنتاجي بالأشهر','Useful life months')}<input name="life" type="number" min="1" max="1200" defaultValue={editingPolicy?.useful_life_months??''}/></label><label>{label('سياسة القيمة المتبقية','Residual-value policy')}<select name="residualPolicy" defaultValue={editingPolicy?.residual_value_policy??'zero'}><option value="zero">zero</option><option value="asset_specific">asset_specific</option></select></label><label>{label('بداية الإهلاك','Depreciation start basis')}<select name="startBasis" defaultValue={editingPolicy?.depreciation_start_basis??'placed_in_service'}><option value="placed_in_service">placed_in_service</option><option value="explicit_date">explicit_date</option></select></label></>}
      <label>{label('حساب الأصل','Asset account')}<select name="assetAccount" defaultValue={editingPolicy?.asset_account_id??''}><option value="">—</option>{activeAccounts('asset').map(a=><option key={a.id} value={a.id}>{accountLabel(a)}</option>)}</select></label>
      {selectedCategory?.depreciable!==false&&<><label>{label('مجمع الإهلاك','Accumulated depreciation')}<select name="accumulatedAccount" defaultValue={editingPolicy?.accumulated_depreciation_account_id??''}><option value="">—</option>{activeAccounts('asset').map(a=><option key={a.id} value={a.id}>{accountLabel(a)}</option>)}</select></label><label>{label('مصروف الإهلاك','Depreciation expense')}<select name="expenseAccount" defaultValue={editingPolicy?.depreciation_expense_account_id??''}><option value="">—</option>{activeAccounts('expense').map(a=><option key={a.id} value={a.id}>{accountLabel(a)}</option>)}</select></label></>}
      <div className="modal-actions"><button className="fa-primary">{editingPolicy?label('حفظ المسودة','Save draft'):label('إنشاء المسودة','Create draft')}</button><button type="button" onClick={()=>{setPolicyForm(false);setEditingPolicy(null)}}>{t('common.cancel')}</button></div>
    </form>}
    {policies.length?<div className="fa-table shared-data-workspace"><table><thead><tr><th>v</th><th>{label('السريان','Effective')}</th><th>{label('الحالة','Status')}</th><th>{label('المراجعة','Review')}</th><th>{label('الاعتماد','Approval')}</th><th>{label('الإجراءات','Actions')}</th></tr></thead><tbody>{policies.map(p=><tr key={p.id}><td>{p.version_number}{p.is_legacy_migrated?' · legacy':''}</td><td>{p.effective_from??'—'}</td><td><StatusBadge status={p.status}>{statusText(p.status)}</StatusBadge></td><td>{p.reviewed_at?'✓':'—'}</td><td>{p.approved_at?'✓':'—'}</td><td>{canManagePolicy&&!p.is_legacy_migrated&&p.status==='draft'&&<><button onClick={()=>editPolicy(p)}>{label('تعديل','Edit')}</button>{!p.reviewed_at&&<button onClick={()=>void actPolicy(p.id,'review')}>{label('مراجعة','Review')}</button>}{p.reviewed_at&&!p.approved_at&&<button className="fa-primary" onClick={()=>void actPolicy(p.id,'approve')}>{label('اعتماد','Approve')}</button>}</>}</td></tr>)}</tbody></table></div>:<p>{label('لا يوجد تاريخ سياسات لهذه الفئة.','No policy history for this category.')}</p>}
   </section>
   <section className="fa-card"><div className="fa-card__head"><div><h3>{label('تغييرات التقديرات للأصل','Asset estimate changes')}</h3>{selectedAsset&&<p>{selectedAsset.asset_number} — {selectedAsset.name} · {label('نسخة السياسة','Policy version')}: <strong>{selectedAsset.depreciation_policy_version_id??'—'}</strong></p>}</div>{canStartEstimate&&<button className="fa-primary" onClick={()=>setEstimateForm(v=>!v)}>{label('طلب تغيير تقدير','Request estimate change')}</button>}</div>
    {estimateForm&&canStartEstimate&&<form className="form-grid fa-form" onSubmit={submitEstimate}><label>{label('السريان من أول الشهر','Effective first day of month')}<input name="effectiveFrom" type="date" required defaultValue={nextMonthStart()}/></label><label>{label('العمر المتبقي الجديد بالأشهر','New remaining useful life (months)')}<input name="remainingLife" type="number" min="1" max="1200"/></label><label>{label('القيمة المتبقية الجديدة','New residual value')}<input name="residual" inputMode="decimal"/></label><label>{label('سبب التغيير','Reason')}<textarea name="reason" required maxLength={1000}/></label><label>{label('سبب الاستثناء من السياسة عند الحاجة','Policy exception reason when applicable')}<textarea name="exceptionReason" maxLength={1000}/></label><div className="modal-actions"><button className="fa-primary">{label('إنشاء الطلب','Create request')}</button><button type="button" onClick={()=>setEstimateForm(false)}>{t('common.cancel')}</button></div></form>}
    {!selectedAsset?<p className="fa-empty">{label('اختر أصلًا لعرض سجل تغييرات التقدير.','Select an asset to view estimate-change history.')}</p>:changes.length?<div className="fa-table shared-data-workspace"><table><thead><tr><th>{label('السريان','Effective')}</th><th>{label('العمر السابق / الجديد','Old / new life')}</th><th>{label('القيمة السابقة / الجديدة','Old / new residual')}</th><th>{label('الحالة','Status')}</th><th>{label('استثناء','Exception')}</th><th>{label('الإجراءات','Actions')}</th></tr></thead><tbody>{changes.map(ch=><tr key={ch.id}><td>{ch.effective_from}</td><td>{ch.old_useful_life_months??'—'} / {ch.new_remaining_useful_life_months??'—'}</td><td>{ch.old_residual_value} / {ch.new_residual_value??'—'}</td><td><StatusBadge status={ch.status}>{statusText(ch.status)}</StatusBadge></td><td>{ch.policy_exception?`${label('نعم','Yes')}: ${ch.policy_exception_reason??'—'}`:label('لا','No')}</td><td>{ch.status==='draft'&&canReviewEstimate&&<button onClick={()=>void actEstimate(ch.id,'review')}>{label('مراجعة','Review')}</button>}{ch.status==='reviewed'&&canApproveEstimate&&<button className="fa-primary" onClick={()=>void actEstimate(ch.id,'approve')}>{label('اعتماد','Approve')}</button>}</td></tr>)}</tbody></table></div>:<p className="fa-empty">{label('لا توجد تغييرات تقدير مسجلة لهذا الأصل.','No estimate changes recorded for this asset.')}</p>}
   <p className="fa-note">{label('تغييرات التقديرات مستقبلية؛ لا تعدّل الإهلاك المنشور.','Estimate changes are prospective; they do not alter posted depreciation.')}</p>
   </section>
  </>}
 </section>;
}
