import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Alert, Badge, Button, Card, Group, Select, Stack, Table, Text, TextInput, Title } from '@mantine/core';
import { useTranslation } from 'react-i18next';
import { Dialog } from './Dialog';

type Account = { id:string; display_name:string; bank_name:string|null; currency_code:string; is_active:boolean };
type Batch = { id:string; bank_account_id:string; original_filename:string; status:string; total_rows:number; valid_rows:number; duplicate_rows:number; invalid_rows:number; created_at:string };
type ReconciliationStatus = 'unmatched'|'matched'|'reconciled';
type Transaction = { id:string; transaction_date:string; description:string|null; bank_reference:string|null; amount:string; running_balance:string|null; currency_code:string; reconciliation_status:ReconciliationStatus };
type Match = { id:string; document_id:string; note:string|null };
type CandidateDocument = { id:string; status:'needs_review'|'approved'; document_type:string|null; counterparty_name:string|null; document_date:string|null; reference_number:string|null; total_amount:string|null; original_filename:string };
type CandidateResponse = { transaction:{id:string;reconciliation_status:ReconciliationStatus}; match:Match|null; documents:CandidateDocument[] };
type PreviewRow = { source_row_number:number; transaction_date:string; description:string|null; bank_reference:string|null; amount:string; running_balance:string|null; status:'valid'|'duplicate'|'possible_duplicate'|'invalid'; error:string|null };
type Preview = { totalRows:number; validRows:number; duplicateRows:number; possibleDuplicateRows:number; invalidRows:number; rows:PreviewRow[] };
export type BankConfirmResult = { importedRows:number; duplicateRows:number; idempotent:boolean };

type Props = { canView:boolean; canImport:boolean; canManage:boolean; canMatch:boolean; canReconcile:boolean; onUnauthorized:()=>void };

async function api<T>(url:string, init?:RequestInit, onUnauthorized?:()=>void):Promise<T>{
  const response=await fetch(url,init);
  if(response.status===401){onUnauthorized?.();throw new Error('unauthorized');}
  const body=await response.json().catch(()=>({}));
  if(!response.ok) throw new Error(typeof body.error==='string'?body.error:`HTTP ${response.status}`);
  return body as T;
}

export function BankConfirmSummary({result}:{result:BankConfirmResult}){
  const {t}=useTranslation();
  return <Alert color="green" role="status">{t('banks.batchStatus.confirmed')} · {t('banks.valid')}: {result.importedRows} · {t('banks.duplicates')}: {result.duplicateRows}{result.idempotent?` · ${t('banks.batchStatus.confirmed')}`:''}</Alert>;
}

export function Banking({canView,canImport,canManage,canMatch,canReconcile,onUnauthorized}:Props){
  const {t}=useTranslation();
  const [accounts,setAccounts]=useState<Account[]>([]); const [batches,setBatches]=useState<Batch[]>([]); const [transactions,setTransactions]=useState<Transaction[]>([]);
  const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [confirmResult,setConfirmResult]=useState<BankConfirmResult|null>(null);
  const [selectedAccount,setSelectedAccount]=useState<string|null>(null); const [file,setFile]=useState<File|null>(null); const [columns,setColumns]=useState<string[]>([]); const [batchId,setBatchId]=useState<string|null>(null);
  const [mode,setMode]=useState<'signed'|'debit_credit'>('signed'); const [dateFormat,setDateFormat]=useState('YYYY-MM-DD');
  const [dateCol,setDateCol]=useState<string|null>(null); const [amountCol,setAmountCol]=useState<string|null>(null); const [debitCol,setDebitCol]=useState<string|null>(null); const [creditCol,setCreditCol]=useState<string|null>(null);
  const [valueDateCol,setValueDateCol]=useState<string|null>(null); const [descriptionCol,setDescriptionCol]=useState<string|null>(null); const [referenceCol,setReferenceCol]=useState<string|null>(null); const [balanceCol,setBalanceCol]=useState<string|null>(null); const [preview,setPreview]=useState<Preview|null>(null);
  const [matchTransaction,setMatchTransaction]=useState<Transaction|null>(null); const [candidateData,setCandidateData]=useState<CandidateResponse|null>(null); const [candidateSearch,setCandidateSearch]=useState(''); const [selectedDocument,setSelectedDocument]=useState<string|null>(null); const [matchNote,setMatchNote]=useState(''); const [matchBusy,setMatchBusy]=useState(false);

  const options=useMemo(()=>columns.map((label,index)=>({value:String(index),label:`${label} (${index+1})`})),[columns]);
  const refresh=async()=>{if(!canView)return;setLoading(true);setError('');try{const [a,b,x]=await Promise.all([api<{accounts:Account[]}>('/api/bank-accounts',undefined,onUnauthorized),api<{batches:Batch[]}>('/api/bank-import-batches',undefined,onUnauthorized),api<{transactions:Transaction[]}>('/api/bank-transactions',undefined,onUnauthorized)]);setAccounts(a.accounts);setBatches(b.batches);setTransactions(x.transactions);if(!selectedAccount&&a.accounts.length)setSelectedAccount(a.accounts[0]!.id);}catch(e){setError(e instanceof Error?e.message:t('banks.error'));}finally{setLoading(false);}};
  useEffect(()=>{void refresh();},[canView]);

  const createAccount=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError('');const form=event.currentTarget;const data=new FormData(form);try{await api('/api/bank-accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:String(data.get('display_name')||''),bank_name:String(data.get('bank_name')||'')||null,currency_code:String(data.get('currency_code')||'SAR')})},onUnauthorized);form.reset();await refresh();}catch(e){setError(e instanceof Error?e.message:t('banks.error'));}};

  const upload=async()=>{if(!file||!selectedAccount)return;setError('');setConfirmResult(null);setPreview(null);const ext=file.name.toLowerCase().endsWith('.xlsx');try{const body=await api<{batch:Batch;columns:string[]}>('/api/bank-import-batches',{method:'POST',headers:{'Content-Type':ext?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'text/csv','X-File-Name':encodeURIComponent(file.name),'X-Bank-Account-Id':selectedAccount},body:file},onUnauthorized);setBatchId(body.batch.id);setColumns(body.columns);setDateCol(null);setAmountCol(null);setDebitCol(null);setCreditCol(null);await refresh();}catch(e){setError(e instanceof Error?e.message:t('banks.error'));}};

  const ref=(value:string|null)=>value===null?undefined:{index:Number(value),label:columns[Number(value)]};
  const saveMapping=async()=>{if(!batchId||dateCol===null)return;const mapping:any={amount_mode:mode,date_format:dateFormat,transaction_date:ref(dateCol),value_date:ref(valueDateCol),description:ref(descriptionCol),bank_reference:ref(referenceCol),running_balance:ref(balanceCol)};if(mode==='signed')mapping.amount=ref(amountCol);else{mapping.debit=ref(debitCol);mapping.credit=ref(creditCol);}Object.keys(mapping).forEach((k)=>mapping[k]===undefined&&delete mapping[k]);setError('');try{const result=await api<{preview:Preview}>(`/api/bank-import-batches/${batchId}/mapping`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(mapping)},onUnauthorized);setPreview(result.preview);await refresh();}catch(e){setError(e instanceof Error?e.message:t('banks.error'));}};
  const confirm=async()=>{if(!batchId||!preview||preview.invalidRows>0)return;setError('');try{const result=await api<BankConfirmResult>(`/api/bank-import-batches/${batchId}/confirm`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'},onUnauthorized);setConfirmResult(result);setBatchId(null);setColumns([]);setPreview(null);setFile(null);await refresh();}catch(e){setError(e instanceof Error?e.message:t('banks.error'));}};

  const loadCandidates=async(transaction:Transaction,search='')=>{setMatchTransaction(transaction);setMatchBusy(true);setError('');try{const data=await api<CandidateResponse>(`/api/bank-transactions/${transaction.id}/match-candidates${search?`?search=${encodeURIComponent(search)}`:''}`,undefined,onUnauthorized);setCandidateData(data);setSelectedDocument(data.match?.document_id??null);}catch(e){setError(e instanceof Error?e.message:t('banks.reconciliationError'));setMatchTransaction(null);}finally{setMatchBusy(false);}};
  const closeMatch=()=>{if(matchBusy)return;setMatchTransaction(null);setCandidateData(null);setCandidateSearch('');setSelectedDocument(null);setMatchNote('');};
  const createMatch=async()=>{if(!matchTransaction||!selectedDocument)return;setMatchBusy(true);setError('');try{await api(`/api/bank-transactions/${matchTransaction.id}/match`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_id:selectedDocument,note:matchNote||undefined})},onUnauthorized);closeMatch();await refresh();}catch(e){setError(e instanceof Error?e.message:t('banks.reconciliationError'));setMatchBusy(false);}};
  const unmatch=async(transaction:Transaction)=>{setError('');try{await api(`/api/bank-transactions/${transaction.id}/match`,{method:'DELETE'},onUnauthorized);await refresh();}catch(e){setError(e instanceof Error?e.message:t('banks.reconciliationError'));}};
  const setReconciliation=async(transaction:Transaction,status:'matched'|'reconciled')=>{setError('');try{await api(`/api/bank-transactions/${transaction.id}/reconciliation`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})},onUnauthorized);await refresh();}catch(e){setError(e instanceof Error?e.message:t('banks.reconciliationError'));}};

  if(!canView)return <section className="panel"><Text role="status">{t('banks.noAccess')}</Text></section>;
  return <Stack gap="lg">
    <Group justify="space-between" align="end"><div><Title order={1}>{t('banks.title')}</Title><Text c="dimmed">{t('banks.description')}</Text></div><Button variant="light" onClick={()=>void refresh()} loading={loading}>{t('common.retry')}</Button></Group>
    {error&&<Alert color="red" role="alert">{error}</Alert>}
    {confirmResult&&<BankConfirmSummary result={confirmResult}/>} 

    <Card withBorder padding="lg"><Stack gap="md"><Title order={2} size="h3">{t('banks.accounts')}</Title>
      {canManage&&<form onSubmit={createAccount}><Group align="end"><TextInput name="display_name" label={t('banks.accountName')} required/><TextInput name="bank_name" label={t('banks.bankName')}/><TextInput name="currency_code" label={t('banks.currency')} defaultValue="SAR" maxLength={3} required/><Button type="submit">{t('banks.createAccount')}</Button></Group></form>}
      {accounts.length===0?<Text c="dimmed">{t('banks.noAccounts')}</Text>:<Table.ScrollContainer minWidth={620}><Table striped highlightOnHover><Table.Thead><Table.Tr><Table.Th>{t('banks.accountName')}</Table.Th><Table.Th>{t('banks.bankName')}</Table.Th><Table.Th>{t('banks.currency')}</Table.Th><Table.Th>{t('banks.status')}</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{accounts.map(a=><Table.Tr key={a.id}><Table.Td>{a.display_name}</Table.Td><Table.Td>{a.bank_name||'—'}</Table.Td><Table.Td>{a.currency_code}</Table.Td><Table.Td><Badge>{a.is_active?t('banks.active'):t('banks.inactive')}</Badge></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}
    </Stack></Card>

    {canImport&&<Card withBorder padding="lg"><Stack gap="md"><Title order={2} size="h3">{t('banks.import')}</Title><Text c="dimmed">{t('banks.accepted')}</Text>
      <Group align="end"><Select label={t('banks.account')} data={accounts.map(a=>({value:a.id,label:a.display_name}))} value={selectedAccount} onChange={setSelectedAccount}/><label><Text size="sm" fw={500}>{t('banks.file')}</Text><input aria-label={t('banks.file')} type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><Button onClick={()=>void upload()} disabled={!file||!selectedAccount}>{t('banks.upload')}</Button></Group>
      {columns.length>0&&<Stack gap="sm"><Title order={3} size="h4">{t('banks.mapping')}</Title><Group grow><Select label={t('banks.amountMode')} data={[{value:'signed',label:t('banks.signed')},{value:'debit_credit',label:t('banks.debitCredit')}]} value={mode} onChange={v=>setMode((v as any)||'signed')}/><Select label={t('banks.dateFormat')} data={['YYYY-MM-DD','DD/MM/YYYY','DD-MM-YYYY']} value={dateFormat} onChange={v=>setDateFormat(v||'YYYY-MM-DD')}/><Select label={t('banks.transactionDate')} data={options} value={dateCol} onChange={setDateCol} required/></Group><Group grow>{mode==='signed'?<Select label={t('banks.amount')} data={options} value={amountCol} onChange={setAmountCol} required/>:<><Select label={t('banks.debit')} data={options} value={debitCol} onChange={setDebitCol} required/><Select label={t('banks.credit')} data={options} value={creditCol} onChange={setCreditCol} required/></>}<Select label={t('banks.descriptionField')} data={options} value={descriptionCol} onChange={setDescriptionCol} clearable/><Select label={t('banks.reference')} data={options} value={referenceCol} onChange={setReferenceCol} clearable/></Group><Group grow><Select label={t('banks.valueDate')} data={options} value={valueDateCol} onChange={setValueDateCol} clearable/><Select label={t('banks.balance')} data={options} value={balanceCol} onChange={setBalanceCol} clearable/></Group><Button onClick={()=>void saveMapping()} disabled={dateCol===null||(mode==='signed'?amountCol===null:debitCol===null||creditCol===null)}>{t('banks.preview')}</Button></Stack>}
      {preview&&<Stack gap="sm"><Group><Badge>{t('banks.total')}: {preview.totalRows}</Badge><Badge color="green">{t('banks.valid')}: {preview.validRows}</Badge><Badge color="yellow">{t('banks.duplicates')}: {preview.duplicateRows}</Badge><Badge color="orange">{t('banks.possibleDuplicates')}: {preview.possibleDuplicateRows}</Badge><Badge color={preview.invalidRows?'red':'gray'}>{t('banks.invalid')}: {preview.invalidRows}</Badge></Group><Table.ScrollContainer minWidth={760}><Table striped><Table.Thead><Table.Tr><Table.Th>{t('banks.transactionDate')}</Table.Th><Table.Th>{t('banks.descriptionField')}</Table.Th><Table.Th>{t('banks.reference')}</Table.Th><Table.Th>{t('banks.amount')}</Table.Th><Table.Th>{t('banks.balance')}</Table.Th><Table.Th>{t('banks.status')}</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{preview.rows.map(r=><Table.Tr key={r.source_row_number}><Table.Td>{r.transaction_date||'—'}</Table.Td><Table.Td>{r.description||'—'}</Table.Td><Table.Td>{r.bank_reference||'—'}</Table.Td><Table.Td>{r.amount||'—'}</Table.Td><Table.Td>{r.running_balance||'—'}</Table.Td><Table.Td><Badge color={r.status==='invalid'?'red':r.status==='duplicate'?'yellow':r.status==='possible_duplicate'?'orange':'green'}>{r.error||t(`banks.rowStatus.${r.status}`)}</Badge></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer><Button onClick={()=>void confirm()} disabled={preview.invalidRows>0}>{t('banks.confirm')}</Button></Stack>}
    </Stack></Card>}

    <Card withBorder padding="lg"><Stack gap="md"><Title order={2} size="h3">{t('banks.importHistory')}</Title>{batches.length===0?<Text c="dimmed">{t('banks.noImports')}</Text>:<Table.ScrollContainer minWidth={700}><Table><Table.Thead><Table.Tr><Table.Th>{t('banks.file')}</Table.Th><Table.Th>{t('banks.status')}</Table.Th><Table.Th>{t('banks.total')}</Table.Th><Table.Th>{t('banks.valid')}</Table.Th><Table.Th>{t('banks.duplicates')}</Table.Th><Table.Th>{t('banks.invalid')}</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{batches.map(b=><Table.Tr key={b.id}><Table.Td>{b.original_filename}</Table.Td><Table.Td><Badge>{t(`banks.batchStatus.${b.status}`)}</Badge></Table.Td><Table.Td>{b.total_rows}</Table.Td><Table.Td>{b.valid_rows}</Table.Td><Table.Td>{b.duplicate_rows}</Table.Td><Table.Td>{b.invalid_rows}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}</Stack></Card>

    <Card withBorder padding="lg"><Stack gap="md"><Title order={2} size="h3">{t('banks.transactions')}</Title>{transactions.length===0?<Text c="dimmed">{t('banks.noTransactions')}</Text>:<Table.ScrollContainer minWidth={980}><Table striped><Table.Thead><Table.Tr><Table.Th>{t('banks.transactionDate')}</Table.Th><Table.Th>{t('banks.descriptionField')}</Table.Th><Table.Th>{t('banks.reference')}</Table.Th><Table.Th>{t('banks.amount')}</Table.Th><Table.Th>{t('banks.balance')}</Table.Th><Table.Th>{t('banks.reconciliationStatus')}</Table.Th><Table.Th>{t('banks.actions')}</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{transactions.map(x=><Table.Tr key={x.id}><Table.Td>{x.transaction_date}</Table.Td><Table.Td>{x.description||'—'}</Table.Td><Table.Td>{x.bank_reference||'—'}</Table.Td><Table.Td>{x.amount} {x.currency_code}</Table.Td><Table.Td>{x.running_balance??'—'}</Table.Td><Table.Td><Badge color={x.reconciliation_status==='reconciled'?'green':x.reconciliation_status==='matched'?'blue':'gray'}>{t(`banks.reconciliation.${x.reconciliation_status}`)}</Badge></Table.Td><Table.Td><Group gap="xs">{x.reconciliation_status==='unmatched'&&canMatch&&<Button size="xs" variant="light" onClick={()=>void loadCandidates(x)}>{t('banks.match')}</Button>}{x.reconciliation_status==='matched'&&<><Button size="xs" variant="subtle" onClick={()=>void loadCandidates(x)}>{t('banks.viewMatch')}</Button>{canReconcile&&<Button size="xs" onClick={()=>void setReconciliation(x,'reconciled')}>{t('banks.reconcile')}</Button>}{canMatch&&<Button size="xs" color="red" variant="subtle" onClick={()=>void unmatch(x)}>{t('banks.unmatch')}</Button>}</>}{x.reconciliation_status==='reconciled'&&canReconcile&&<Button size="xs" variant="light" onClick={()=>void setReconciliation(x,'matched')}>{t('banks.reopen')}</Button>}</Group></Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}</Stack></Card>

    {matchTransaction&&<Dialog title={t('banks.matchDialog')} busy={matchBusy} onClose={closeMatch}><Stack gap="md"><Text>{matchTransaction.transaction_date} · {matchTransaction.amount} {matchTransaction.currency_code} · {matchTransaction.description||'—'}</Text><Group align="end"><TextInput label={t('banks.searchDocuments')} value={candidateSearch} onChange={e=>setCandidateSearch(e.currentTarget.value)}/><Button variant="light" loading={matchBusy} onClick={()=>void loadCandidates(matchTransaction,candidateSearch)}>{t('banks.search')}</Button></Group>{candidateData?.match&&<Alert>{t('banks.currentMatch')}: {candidateData.match.document_id}</Alert>}<Select label={t('banks.document')} searchable data={(candidateData?.documents??[]).map(d=>({value:d.id,label:`${d.original_filename} · ${d.counterparty_name||'—'} · ${d.total_amount||'—'} · ${t(`documents.statuses.${d.status}`)}`}))} value={selectedDocument} onChange={setSelectedDocument} disabled={Boolean(candidateData?.match)}/><TextInput label={t('banks.matchNote')} value={matchNote} onChange={e=>setMatchNote(e.currentTarget.value)} maxLength={500} disabled={Boolean(candidateData?.match)}/><Group justify="flex-end"><Button variant="default" onClick={closeMatch} disabled={matchBusy}>{t('common.close')}</Button>{canMatch&&!candidateData?.match&&<Button onClick={()=>void createMatch()} loading={matchBusy} disabled={!selectedDocument}>{t('banks.confirmMatch')}</Button>}</Group></Stack></Dialog>}
  </Stack>;
}