import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Alert, Badge, Button, Card, Group, NativeSelect, NumberInput, Stack, Table, Text, TextInput, Title } from '@mantine/core';
import { useTranslation } from 'react-i18next';

type Tx={id:string;transaction_date:string;description:string|null;bank_reference:string|null;amount:string;currency_code:string;reconciliation_status:'unmatched'|'matched'|'reconciled'};
type Allocation={id:string;document_id:string;amount:string;original_filename?:string;note:string|null};
type ReturnItem={bank_transaction_id:string;amount:string;transaction_date:string;description:string|null;bank_reference:string|null;reconciliation_status:string};
type Summary={custody:{id:string;purpose:string|null;status:'open'|'closed';holder_user_id:string};funding_transaction:Tx;funded_amount:string;allocated_amount:string;returned_amount:string;remaining_amount:string;derived_status:string;allocations:Allocation[];returns:ReturnItem[]};
type Props={canView:boolean;canManage:boolean;canClose:boolean;onUnauthorized:()=>void};
async function api<T>(url:string,init?:RequestInit,onUnauthorized?:()=>void):Promise<T>{const r=await fetch(url,init);if(r.status===401){onUnauthorized?.();throw new Error('unauthorized');}const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(typeof b.error==='string'?b.error:`HTTP ${r.status}`);return b as T;}
const strings={en:{title:'Custody & advances',desc:'Track company funds advanced to you, supporting documents, returns, and closure.',new:'New custody',funding:'Outbound funding transaction',purpose:'Purpose',create:'Create custody',select:'Select custody',funded:'Funded',allocated:'Documents',returned:'Returned',remaining:'Remaining',status:'Status',document:'Approved document ID',amount:'Amount',note:'Note',allocate:'Add document',returnTx:'Inbound return transaction',addReturn:'Link return',close:'Close custody',reopen:'Reopen custody',reason:'Reason',remove:'Remove',none:'No custody records',error:'Unable to load custody records',current:'Selected custody',supporting:'Supporting documents',returns:'Returns',emptyAllocations:'No supporting documents linked yet',emptyReturns:'No returned funds linked yet'},ar:{title:'العهد والسلف',desc:'متابعة المبالغ المحولة من الشركة للعهدة، مستنداتها، المبالغ المرتجعة، ثم الإغلاق.',new:'عهدة جديدة',funding:'حركة الصرف البنكية',purpose:'الغرض',create:'إنشاء العهدة',select:'اختر العهدة',funded:'المبلغ الأصلي',allocated:'المستندات',returned:'المرتجع',remaining:'المتبقي',status:'الحالة',document:'معرف المستند المعتمد',amount:'المبلغ',note:'ملاحظة',allocate:'إضافة مستند',returnTx:'حركة الإرجاع البنكية',addReturn:'ربط المرتجع',close:'إغلاق العهدة',reopen:'إعادة فتح العهدة',reason:'السبب',remove:'إزالة',none:'لا توجد عهد',error:'تعذر تحميل العهد',current:'العهدة المحددة',supporting:'المستندات المرتبطة',returns:'المبالغ المرتجعة',emptyAllocations:'لا توجد مستندات مرتبطة بعد',emptyReturns:'لا توجد مبالغ مرتجعة مرتبطة بعد'}};
export function CustodyPanel({canView,canManage,canClose,onUnauthorized}:Props){const{i18n}=useTranslation();const s=i18n.language==='ar'?strings.ar:strings.en;const[list,setList]=useState<Summary[]>([]);const[txs,setTxs]=useState<Tx[]>([]);const[selected,setSelected]=useState('');const[purpose,setPurpose]=useState('');const[funding,setFunding]=useState('');const[doc,setDoc]=useState('');const[allocationAmount,setAllocationAmount]=useState<number|string>('');const[returnTx,setReturnTx]=useState('');const[note,setNote]=useState('');const[reason,setReason]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const load=async()=>{if(!canView)return;try{const[c,t]=await Promise.all([api<{custodies:Summary[]}>('/api/custodies',undefined,onUnauthorized),api<{transactions:Tx[]}>('/api/bank-transactions',undefined,onUnauthorized)]);setList(c.custodies);setTxs(t.transactions);if(!selected&&c.custodies[0])setSelected(c.custodies[0].custody.id);}catch(e){setError(e instanceof Error?e.message:s.error);}};
 useEffect(()=>{void load();},[canView]);const current=useMemo(()=>list.find(x=>x.custody.id===selected)??null,[list,selected]);const outbound=txs.filter(x=>x.reconciliation_status==='unmatched'&&x.amount.startsWith('-'));const inbound=txs.filter(x=>x.reconciliation_status==='unmatched'&&!x.amount.startsWith('-')&&Number(x.amount)>0);const request=async(url:string,init:RequestInit)=>{setBusy(true);setError('');try{await api(url,init,onUnauthorized);await load();}catch(e){setError(e instanceof Error?e.message:s.error);}finally{setBusy(false);}};const json=(method:string,body:unknown):RequestInit=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 const create=async(e:FormEvent)=>{e.preventDefault();if(funding)await request('/api/custodies',json('POST',{bank_transaction_id:funding,purpose:purpose||undefined}));setPurpose('');setFunding('');};const allocate=async(e:FormEvent)=>{e.preventDefault();if(current&&doc&&allocationAmount)await request(`/api/custodies/${current.custody.id}/documents`,json('POST',{document_id:doc,amount:String(allocationAmount),note:note||undefined}));setDoc('');setAllocationAmount('');setNote('');};const addReturn=async()=>{if(current&&returnTx)await request(`/api/custodies/${current.custody.id}/returns`,json('POST',{bank_transaction_id:returnTx,note:note||undefined}));setReturnTx('');setNote('');};if(!canView)return null;return <Card withBorder padding="lg" className="banking-custody-panel"><Stack gap="lg"><div className="banking-section-heading"><Title order={2} size="h3">{s.title}</Title><Text c="dimmed">{s.desc}</Text></div>{error&&<Alert color="red" role="alert">{error}</Alert>}
 {canManage&&<div className="banking-operation-card"><Text fw={700} mb="sm">{s.new}</Text><form onSubmit={create}><Group align="end" grow><NativeSelect label={s.funding} value={funding} onChange={e=>setFunding(e.currentTarget.value)} data={[{value:'',label:'—'},...outbound.map(x=>({value:x.id,label:`${x.transaction_date} · ${x.description||x.bank_reference||x.id} · ${x.amount}`}))]}/><TextInput label={s.purpose} value={purpose} onChange={e=>setPurpose(e.currentTarget.value)} maxLength={500}/><Button type="submit" disabled={!funding} loading={busy}>{s.create}</Button></Group></form></div>}
 <div className="banking-operation-card"><NativeSelect label={s.select} value={selected} onChange={e=>setSelected(e.currentTarget.value)} data={[{value:'',label:s.none},...list.map(x=>({value:x.custody.id,label:`${x.custody.purpose||x.custody.id} · ${x.remaining_amount}`}))]}/></div>
 {current&&<div className="banking-selected-operation"><Stack gap="lg"><div><Text fw={700}>{s.current}</Text><Text size="sm" c="dimmed" dir="auto">{current.custody.purpose||current.custody.id}</Text></div><div className="banking-metrics-grid banking-metrics-grid--five"><div><span>{s.funded}</span><strong dir="ltr">{current.funded_amount}</strong></div><div><span>{s.allocated}</span><strong dir="ltr">{current.allocated_amount}</strong></div><div><span>{s.returned}</span><strong dir="ltr">{current.returned_amount}</strong></div><div><span>{s.remaining}</span><strong dir="ltr">{current.remaining_amount}</strong></div><div><span>{s.status}</span><strong>{current.derived_status}</strong></div></div>
 {canManage&&current.custody.status==='open'&&<div className="banking-two-column-operations"><div className="banking-subsection"><Text fw={700} mb="sm">{s.supporting}</Text><form onSubmit={allocate}><Stack gap="sm"><TextInput label={s.document} value={doc} onChange={e=>setDoc(e.currentTarget.value)} required/><NumberInput label={s.amount} value={allocationAmount} onChange={setAllocationAmount} min={0.01} decimalScale={2} required/><TextInput label={s.note} value={note} onChange={e=>setNote(e.currentTarget.value)} maxLength={500}/><Button type="submit" loading={busy}>{s.allocate}</Button></Stack></form></div><div className="banking-subsection"><Text fw={700} mb="sm">{s.returns}</Text><Stack gap="sm"><NativeSelect label={s.returnTx} value={returnTx} onChange={e=>setReturnTx(e.currentTarget.value)} data={[{value:'',label:'—'},...inbound.map(x=>({value:x.id,label:`${x.transaction_date} · ${x.description||x.bank_reference||x.id} · ${x.amount}`}))]}/><TextInput label={s.note} value={note} onChange={e=>setNote(e.currentTarget.value)} maxLength={500}/><Button onClick={()=>void addReturn()} disabled={!returnTx} loading={busy}>{s.addReturn}</Button></Stack></div></div>}
 {canClose&&<div className="banking-subsection"><Group align="end"><TextInput label={s.reason} value={reason} onChange={e=>setReason(e.currentTarget.value)} maxLength={500}/>{current.custody.status==='open'?<Button onClick={()=>void request(`/api/custodies/${current.custody.id}/close`,json('POST',{}))} disabled={current.remaining_amount!=='0.00'} loading={busy}>{s.close}</Button>:<Button onClick={()=>void request(`/api/custodies/${current.custody.id}/reopen`,json('POST',{reason}))} disabled={!reason.trim()} loading={busy}>{s.reopen}</Button>}</Group></div>}
 <div className="banking-subsection"><Title order={3} size="h4" mb="sm">{s.supporting}</Title>{current.allocations.length===0?<Text c="dimmed">{s.emptyAllocations}</Text>:<Table.ScrollContainer minWidth={640}><Table><Table.Thead><Table.Tr><Table.Th>{s.document}</Table.Th><Table.Th>{s.amount}</Table.Th>{canManage&&current.custody.status==='open'&&<Table.Th>{s.remove}</Table.Th>}</Table.Tr></Table.Thead><Table.Tbody>{current.allocations.map(a=><Table.Tr key={a.id}><Table.Td>{a.original_filename||a.document_id}</Table.Td><Table.Td>{a.amount}</Table.Td>{canManage&&current.custody.status==='open'&&<Table.Td><Button size="xs" color="red" variant="light" disabled={!reason.trim()} onClick={()=>void request(`/api/custodies/${current.custody.id}/documents/${a.id}`,json('DELETE',{reason}))}>{s.remove}</Button></Table.Td>}</Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}</div>
 <div className="banking-subsection"><Title order={3} size="h4" mb="sm">{s.returns}</Title>{current.returns.length===0?<Text c="dimmed">{s.emptyReturns}</Text>:<Table.ScrollContainer minWidth={640}><Table><Table.Thead><Table.Tr><Table.Th>{s.returnTx}</Table.Th><Table.Th>{s.amount}</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{current.returns.map(r=><Table.Tr key={r.bank_transaction_id}><Table.Td>{r.transaction_date} · {r.description||r.bank_reference||r.bank_transaction_id}</Table.Td><Table.Td>{r.amount}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>}</div>
 </Stack></div>}</Stack></Card>}
