import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatDisplayDate, formatDisplayDateTime } from '../date-format';
import { Dialog } from './Dialog';
import { PageHeader, StatusBadge, WorkspaceState } from './SharedUI';

type DocumentItem={id:string;original_filename:string;mime_type:string;size_bytes:number;status:string;review_note:string|null;reviewed_at:string|null;created_at:string;document_type:'purchase'|'expense'|'sale'|'other'|null;counterparty_id:string|null;counterparty_name:string|null;relational_counterparty_name?:string|null;document_date:string|null;reference_number:string|null;total_amount:string|null;intake_note:string|null};
type Counterparty={id:string;name:string;is_active:boolean};
type DocumentEntryType='purchase'|'expense';
const intakeFields=['document_type','counterparty_id','document_date','reference_number','total_amount','intake_note'] as const;
const displayFields=['document_type','counterparty_name','document_date','reference_number','total_amount','intake_note'] as const;
const size=(bytes:number)=>bytes>=1024*1024?`${(bytes/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;

function IntakeEditor({document,counterparties,canManageCounterparties=false,onCounterpartyCreated,onSaved,onUnauthorized}:{document:DocumentItem;counterparties:Counterparty[];canManageCounterparties?:boolean;onCounterpartyCreated?:(counterparty:Counterparty)=>void;onSaved:()=>Promise<void>;onUnauthorized:()=>void}){
 const {t}=useTranslation();const [saving,setSaving]=useState(false),[error,setError]=useState(false),[counterpartyId,setCounterpartyId]=useState(document.counterparty_id??''),[counterpartyOpen,setCounterpartyOpen]=useState(false),[creatingCounterparty,setCreatingCounterparty]=useState(false),[counterpartyError,setCounterpartyError]=useState(false);const selectable=counterparties.filter(counterparty=>counterparty.is_active||counterparty.id===document.counterparty_id||counterparty.id===counterpartyId);
 const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError(false);const data=new FormData(event.currentTarget);const body=Object.fromEntries(intakeFields.map(field=>{const value=String(data.get(field)??'');return[field,value===''?null:field==='total_amount'?Number(value):value]}));try{const response=await fetch(`/api/documents/${document.id}/intake`,{method:'PATCH',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(response.status===401){onUnauthorized();return}if(!response.ok){setError(true);return}await onSaved()}catch{setError(true)}finally{setSaving(false)}};
 const createCounterparty=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setCreatingCounterparty(true);setCounterpartyError(false);const name=String(new FormData(event.currentTarget).get('name')??'').trim();try{const response=await fetch('/api/counterparties',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({name,type:'supplier'})});if(response.status===401){onUnauthorized();return}if(!response.ok){setCounterpartyError(true);return}const created=await response.json() as Counterparty;onCounterpartyCreated?.(created);setCounterpartyId(created.id);setCounterpartyOpen(false)}catch{setCounterpartyError(true)}finally{setCreatingCounterparty(false)}};
 return <><form className="document-intake" onSubmit={save}><label>{t('documents.intake.documentType')}<select name="document_type" defaultValue={document.document_type??''}><option value="">{t('documents.intake.none')}</option>{(['purchase','expense','sale','other'] as const).map(type=><option key={type} value={type}>{t(`documents.intake.types.${type}`)}</option>)}</select></label><label>{t('documents.intake.counterparty')}<select name="counterparty_id" value={counterpartyId} onChange={e=>setCounterpartyId(e.target.value)}><option value="">{t('documents.intake.none')}</option>{selectable.map(counterparty=><option key={counterparty.id} value={counterparty.id} disabled={!counterparty.is_active}>{counterparty.name}</option>)}</select></label>{canManageCounterparties&&<button type="button" onClick={()=>{setCounterpartyError(false);setCounterpartyOpen(true)}}>{t('obligations.createCounterparty')}</button>}<label>{t('documents.intake.documentDate')}<input name="document_date" type="date" defaultValue={document.document_date?.slice(0,10)??''}/></label><label>{t('documents.intake.reference')}<input name="reference_number" maxLength={100} defaultValue={document.reference_number??''}/></label><label>{t('documents.intake.totalAmount')}<input name="total_amount" type="number" min="0.01" step="0.01" defaultValue={document.total_amount??''}/></label><label>{t('documents.intake.note')}<textarea name="intake_note" maxLength={500} defaultValue={document.intake_note??''}/></label>{error&&<WorkspaceState tone="error">{t('documents.intake.error')}</WorkspaceState>}<button className="primary" disabled={saving}>{saving?t('documents.intake.saving'):t('documents.intake.save')}</button></form>{counterpartyOpen&&<Dialog title={t('obligations.createCounterparty')} busy={creatingCounterparty} onClose={()=>setCounterpartyOpen(false)}><form onSubmit={e=>void createCounterparty(e)}><label>{t('obligations.counterparty')}<input name="name" required maxLength={200}/></label><label>{t('obligations.type')}<input value={t('obligations.supplier')} readOnly/></label>{counterpartyError&&<WorkspaceState tone="error">{t('obligations.error')}</WorkspaceState>}<div className="modal-actions"><button type="button" disabled={creatingCounterparty} onClick={()=>setCounterpartyOpen(false)}>{t('common.cancel')}</button><button className="primary" disabled={creatingCounterparty}>{t('common.save')}</button></div></form></Dialog>}</>}

interface DocumentsProps{canView:boolean;canUpload:boolean;canReview:boolean;canApprove:boolean;canManageCounterparties?:boolean;entryDocumentType?:DocumentEntryType;onEntryComplete?:()=>void;onEntryCancel?:()=>void;onUnauthorized:()=>void} type Decision='approved'|'incomplete'|'rejected';
export function Documents({canView,canUpload,canReview,canApprove,canManageCounterparties=false,entryDocumentType,onEntryComplete,onEntryCancel,onUnauthorized}:DocumentsProps){
 const {t,i18n}=useTranslation();const [documents,setDocuments]=useState<DocumentItem[]>([]);const [counterparties,setCounterparties]=useState<Counterparty[]>([]);const [loading,setLoading]=useState(canView);const [uploading,setUploading]=useState(false);const [error,setError]=useState<string|null>(null);const [selectedId,setSelectedId]=useState<string|null>(null);const [uploadOpen,setUploadOpen]=useState(false);const [file,setFile]=useState<File|null>(null);const [reviewingId,setReviewingId]=useState<string|null>(null);const [decision,setDecision]=useState<Decision|null>(null);const [reasonError,setReasonError]=useState(false);
 const load=useCallback(async(preferredId?:string)=>{if(!canView)return;setLoading(true);setError(null);try{const response=await fetch('/api/documents',{credentials:'same-origin'});if(response.status===401){onUnauthorized();return}if(!response.ok)throw new Error();const body=await response.json() as {documents:DocumentItem[];counterparties?:Counterparty[]};setDocuments(body.documents);setCounterparties(body.counterparties??[]);setSelectedId(current=>preferredId&&body.documents.some(d=>d.id===preferredId)?preferredId:body.documents.some(d=>d.id===current)?current:(body.documents[0]?.id??null))}catch{setError(t('documents.error'))}finally{setLoading(false)}},[canView,onUnauthorized,t]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(entryDocumentType&&canUpload)setUploadOpen(true)},[entryDocumentType,canUpload]);
 const selected=documents.find(d=>d.id===selectedId)??null;
 const upload=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!file)return;setUploading(true);setError(null);try{const response=await fetch('/api/documents',{method:'POST',credentials:'same-origin',headers:{'content-type':file.type||'application/octet-stream','x-file-name':encodeURIComponent(file.name)},body:file});if(response.status===401){onUnauthorized();return}if(!response.ok){setError(response.status===413?t('documents.tooLarge'):t('documents.invalid'));return}const body=await response.json() as {document:DocumentItem};if(entryDocumentType){const preset=await fetch(`/api/documents/${body.document.id}/intake`,{method:'PATCH',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({document_type:entryDocumentType})});if(preset.status===401){onUnauthorized();return}if(!preset.ok){setError(t('documents.intake.error'));setFile(null);setUploadOpen(false);if(canView)await load(body.document.id);return}}setFile(null);setUploadOpen(false);if(canView)await load(body.document.id)}catch{setError(t('documents.error'))}finally{setUploading(false)}};
 const mutateReview=async(documentId:string,path:'submit-review'|'review',body?:object)=>{setReviewingId(documentId);setError(null);try{const response=await fetch(`/api/documents/${documentId}/${path}`,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(body??{})});if(response.status===401){onUnauthorized();return}if(!response.ok){setError(response.status===409?t('documents.reviewConflict'):t('documents.reviewError'));return}setDecision(null);await load()}catch{setError(t('documents.reviewError'))}finally{setReviewingId(null)}};
 const confirmDecision=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected||!decision)return;const note=String(new FormData(event.currentTarget).get('reason')??'').trim();if(decision!=='approved'&&!note){setReasonError(true);return}void mutateReview(selected.id,'review',{decision,...(note?{note}:{})})};
 const closeUpload=()=>{setUploadOpen(false);setFile(null);if(entryDocumentType)onEntryCancel?.()};
 if(!canView&&!canUpload&&!canReview&&!canApprove)return null;
 return <section className="panel documents-page" aria-labelledby="documents-title">
  <PageHeader titleId="documents-title" eyebrow={t('documents.workspace')} title={t('documents.title')} description={t('documents.description')} action={canUpload?<button className="primary" onClick={()=>setUploadOpen(true)}>{t('documents.upload')}</button>:undefined}/>
  {entryDocumentType&&<WorkspaceState action={onEntryCancel?<button onClick={onEntryCancel}>{t('nav.purchases')}</button>:undefined}>{t(`purchases.${entryDocumentType}`)} · {t('documents.intake.title')}</WorkspaceState>}
  {error&&<WorkspaceState tone="error" action={canView?<button onClick={()=>void load()}>{t('common.retry')}</button>:undefined}>{error}</WorkspaceState>}
  {canView&&loading&&<WorkspaceState>{t('documents.loading')}</WorkspaceState>}{canView&&!loading&&documents.length===0&&<WorkspaceState>{t('documents.empty')}</WorkspaceState>}
  {canView&&!loading&&documents.length>0&&<div className="documents-workspace"><div className="document-list" aria-label={t('documents.list')}>{documents.map(doc=><button key={doc.id} className={`document-row ${doc.id===selectedId?'selected':''}`} onClick={()=>setSelectedId(doc.id)}><span className="document-row-main"><strong>{doc.original_filename}</strong><span>{doc.document_type?t(`documents.intake.types.${doc.document_type}`):t('documents.intake.none')} · {doc.relational_counterparty_name??doc.counterparty_name??'—'}</span><span>{formatDisplayDate(doc.document_date,i18n.language)} {doc.total_amount?` · ${doc.total_amount}`:''}</span></span><span><StatusBadge status={doc.status}>{t(`documents.statuses.${doc.status}`)}</StatusBadge><small>{size(doc.size_bytes)}</small></span></button>)}</div>
  {selected&&<article className="document-detail"><div className="detail-header"><div><h3>{selected.original_filename}</h3><StatusBadge status={selected.status}>{t(`documents.statuses.${selected.status}`)}</StatusBadge></div><a className="button-link" href={`/api/documents/${selected.id}/file`} target="_blank" rel="noreferrer">{t('documents.open')}</a></div><dl className="metadata"><div><dt>{t('documents.size')}</dt><dd>{size(selected.size_bytes)}</dd></div>{displayFields.map(field=><div key={field}><dt>{t(`documents.intake.${field}`)}</dt><dd>{field==='counterparty_name'?(selected.relational_counterparty_name??selected.counterparty_name??'—'):selected[field]!=null?(field==='document_type'?t(`documents.intake.types.${selected[field]}`):field==='document_date'?formatDisplayDate(String(selected[field]),i18n.language):selected[field]):'—'}</dd></div>)}{selected.review_note&&<div><dt>{t('documents.reviewNote')}</dt><dd>{selected.review_note}</dd></div>}{selected.reviewed_at&&<div><dt>{t('documents.reviewedAt')}</dt><dd>{formatDisplayDateTime(selected.reviewed_at,i18n.language)}</dd></div>}</dl><section className="detail-section"><h4>{t('documents.intake.title')}</h4>{canUpload&&selected.status==='uploaded'?<IntakeEditor key={selected.id} document={selected} counterparties={counterparties} canManageCounterparties={canManageCounterparties} onCounterpartyCreated={counterparty=>setCounterparties(current=>[...current.filter(item=>item.id!==counterparty.id),counterparty])} onSaved={async()=>{await load(selected.id);if(entryDocumentType)onEntryComplete?.()}} onUnauthorized={onUnauthorized}/>:<p className="muted">{t('documents.intake.readOnly')}</p>}</section>{((canUpload&&selected.status==='uploaded')||((canReview||canApprove)&&selected.status==='needs_review'))&&<section className="detail-section"><h4>{t('documents.workflow')}</h4><div className="document-review-actions">{canUpload&&selected.status==='uploaded'&&<button className="primary" disabled={reviewingId===selected.id} onClick={()=>void mutateReview(selected.id,'submit-review')}>{t('documents.reviewActions.submit')}</button>}{canReview&&selected.status==='needs_review'&&<><button disabled={reviewingId===selected.id} onClick={()=>{setReasonError(false);setDecision('incomplete')}}>{t('documents.reviewActions.incomplete')}</button><button className="danger" disabled={reviewingId===selected.id} onClick={()=>{setReasonError(false);setDecision('rejected')}}>{t('documents.reviewActions.rejected')}</button></>}{canApprove&&selected.status==='needs_review'&&<button className="primary" disabled={reviewingId===selected.id} onClick={()=>setDecision('approved')}>{t('documents.reviewActions.approved')}</button>}</div></section>}</article>}</div>}
  {uploadOpen&&<Dialog title={`${t('documents.uploadTitle')}${entryDocumentType?` — ${t(`purchases.${entryDocumentType}`)}`:''}`} busy={uploading} onClose={closeUpload}><form onSubmit={upload} className="upload-form"><label className="file-drop">{t('documents.chooseFile')}<input name="document" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" required onChange={e=>setFile(e.target.files?.[0]??null)}/><span>{t('documents.accepted')}</span></label>{file&&<div className="selected-file"><strong>{file.name}</strong><span>{size(file.size)}</span></div>}{error&&<WorkspaceState tone="error">{error}</WorkspaceState>}<div className="modal-actions"><button type="button" disabled={uploading} onClick={closeUpload}>{t('common.cancel')}</button><button className="primary" disabled={uploading||!file}>{uploading?t('documents.uploading'):t('documents.upload')}</button></div></form></Dialog>}
  {decision&&selected&&<Dialog title={t(`documents.dialogs.${decision}Title`)} busy={reviewingId===selected.id} onClose={()=>setDecision(null)}><form className="form-grid" onSubmit={confirmDecision}><p>{t(`documents.dialogs.${decision}Confirmation`)}</p><label>{decision==='approved'?t('documents.approvalNote'):t('documents.reviewReason')}<textarea name="reason" required={decision!=='approved'} aria-describedby={reasonError?'reason-error':undefined}/></label>{reasonError&&<WorkspaceState tone="error">{t('documents.reasonRequired')}</WorkspaceState>}<div className="modal-actions"><button type="button" onClick={()=>setDecision(null)}>{t('common.cancel')}</button><button className={decision==='rejected'?'danger':'primary'} disabled={reviewingId===selected.id}>{t('common.confirm')}</button></div></form></Dialog>}
 </section>
}
