import { FormEvent, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { ApiError, apiErrorMessage, findingMessage, isAbortError, parseApiError, toApiError } from '../api/apiError';
import { formatDisplayDate } from '../date-format';
import { Dialog } from './Dialog';
import { StatusBadge, WorkspaceState } from './SharedUI';
import './FiscalYears.css';

export interface FiscalYear { id:string; name:string; start_date:string; end_date:string; status:'open'|'closed' }
interface Props { canView:boolean; canCreate:boolean; canEdit:boolean; canClose:boolean; onUnauthorized:()=>void }
type FormMode={kind:'create'}|{kind:'edit';fiscalYear:FiscalYear};
type ErrorKey='error'|'invalidRequest'|'forbidden'|'notFound'|'conflict'|'invalidRange';
async function request(url:string,options:RequestInit,onUnauthorized:()=>void){let response:Response;try{response=await fetch(url,{credentials:'same-origin',...options})}catch(reason){if(isAbortError(reason))throw reason;throw toApiError(reason)}if(response.status===401){onUnauthorized();throw await parseApiError(response)}if(!response.ok)throw await parseApiError(response);return response}
function errorKeyFor(reason:unknown):ErrorKey{if(!(reason instanceof ApiError)||reason.network)return'error';if(reason.status===400)return'invalidRequest';if(reason.status===403)return'forbidden';if(reason.status===404)return'notFound';if(reason.status===409)return'conflict';return'error'}

const PlusIcon=()=><svg className="fy-icon" viewBox="0 0 16 16" aria-hidden="true" focusable="false"><path d="M8 3v10M3 8h10" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>;
const LockIcon=()=><svg className="fy-icon" viewBox="0 0 16 16" aria-hidden="true" focusable="false"><rect x="3" y="7" width="10" height="7" rx="1.6" fill="none" stroke="currentColor" strokeWidth="1.5"/><path d="M5.5 7V5.2a2.5 2.5 0 0 1 5 0V7" fill="none" stroke="currentColor" strokeWidth="1.5"/><circle cx="8" cy="10.5" r="1" fill="currentColor"/></svg>;

export function FiscalYears({canView,canCreate,canEdit,canClose,onUnauthorized}:Props){
 const {t,i18n}=useTranslation(); const [years,setYears]=useState<FiscalYear[]>([]); const [loading,setLoading]=useState(canView); const [errorKey,setErrorKeyState]=useState<ErrorKey|null>(null); const [failure,setFailure]=useState<ApiError|null>(null); const setErrorKey=(key:ErrorKey|null,cause:unknown=null)=>{setErrorKeyState(key);setFailure(cause instanceof ApiError?cause:null)}; const [form,setForm]=useState<FormMode|null>(null); const [saving,setSaving]=useState(false); const [closeTarget,setCloseTarget]=useState<FiscalYear|null>(null); const [loaded,setLoaded]=useState(false);
 const load=async(signal?:AbortSignal)=>{setLoading(true);setErrorKey(null);try{const response=await request('/api/fiscal-years',{signal},onUnauthorized);const body=await response.json() as {fiscalYears:FiscalYear[]};setYears(body.fiscalYears);setLoaded(true)}catch(reason){const aborted=isAbortError(reason);const unauthorized=reason instanceof ApiError&&reason.status===401;if(!aborted&&!unauthorized)setErrorKey(errorKeyFor(reason),reason)}finally{if(!signal?.aborted)setLoading(false)}};
 useEffect(()=>{if(!canView)return;const controller=new AbortController();void load(controller.signal);return()=>controller.abort();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);
 if(!canView)return <section className="panel"><WorkspaceState>{t('fiscalYears.noAccess')}</WorkspaceState></section>;
 const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!form)return;const data=new FormData(event.currentTarget);const payload={name:String(data.get('name')),start_date:String(data.get('start_date')),end_date:String(data.get('end_date'))};if(payload.start_date>=payload.end_date){setErrorKey('invalidRange');return}setSaving(true);setErrorKey(null);try{const url=form.kind==='create'?'/api/fiscal-years':`/api/fiscal-years/${form.fiscalYear.id}`;await request(url,{method:form.kind==='create'?'POST':'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)},onUnauthorized);setForm(null);await load()}catch(reason){if(!(reason instanceof ApiError&&reason.status===401))setErrorKey(errorKeyFor(reason),reason)}finally{setSaving(false)}};
 const close=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!closeTarget)return;const reason=String(new FormData(event.currentTarget).get('reason')??'').trim();setSaving(true);setErrorKey(null);try{await request(`/api/fiscal-years/${closeTarget.id}/close`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(reason?{reason}:{})},onUnauthorized);setCloseTarget(null);await load()}catch(reason){if(!(reason instanceof ApiError&&reason.status===401))setErrorKey(errorKeyFor(reason),reason)}finally{setSaving(false)}};
 const counts={total:years.length,open:years.filter(year=>year.status==='open').length,closed:years.filter(year=>year.status==='closed').length};
 const rangeInvalid=errorKey==='invalidRange';
 const blocked=failure?.code==='FISCAL_YEAR_CLOSE_BLOCKED'?failure:null;
 const errorText=errorKey?((failure&&apiErrorMessage(failure,t))||t(`fiscalYears.${errorKey}`)):'';
 return <section className="panel fy-view" aria-labelledby="fiscal-years-title">
  <header className="fy-header"><div><h2 id="fiscal-years-title">{t('fiscalYears.title')}</h2><p>{t('fiscalYears.description')}</p></div>{canCreate&&<button className="fy-primary" onClick={()=>setForm({kind:'create'})}><PlusIcon/>{t('fiscalYears.create')}</button>}</header>
  {errorKey&&!form&&!closeTarget&&<WorkspaceState tone="error" action={errorKey!=='invalidRange'?<button onClick={()=>void load()}>{t('fiscalYears.retry')}</button>:undefined}>{errorText}</WorkspaceState>}
  {loading&&!loaded?<WorkspaceState>{t('fiscalYears.loading')}</WorkspaceState>:loaded&&<>
   <dl className="fy-summary" aria-label={t('fiscalYears.summary')}><div><dt>{t('fiscalYears.totalCount')}</dt><dd>{counts.total}</dd></div><div className="is-open"><dt>{t('fiscalYears.openCount')}</dt><dd>{counts.open}</dd></div><div><dt>{t('fiscalYears.closedCount')}</dt><dd>{counts.closed}</dd></div></dl>
   <section className="fy-card" aria-labelledby="fiscal-years-register-title"><div className="fy-card__head"><h3 id="fiscal-years-register-title">{t('fiscalYears.register')}</h3><span className="fy-muted">{t('fiscalYears.registerMeta',{count:counts.total})}</span></div>
    <div className="fy-table"><table><thead><tr><th>{t('fiscalYears.fiscalYear')}</th><th>{t('fiscalYears.start')}</th><th>{t('fiscalYears.end')}</th><th>{t('fiscalYears.status')}</th><th>{t('fiscalYears.actions')}</th></tr></thead>
     <tbody>{years.length===0?<tr><td colSpan={5} className="fy-empty"><strong>{t('fiscalYears.emptyTitle')}</strong><span>{t('fiscalYears.empty')}</span></td></tr>:years.map(year=><tr key={year.id} className={year.status}><td className="fy-name">{year.name}</td><td>{formatDisplayDate(year.start_date,i18n.language)}</td><td>{formatDisplayDate(year.end_date,i18n.language)}</td><td><StatusBadge status={year.status}>{t(`fiscalYears.${year.status}`)}</StatusBadge></td><td>{year.status==='open'&&(canEdit||canClose)&&<div className="fy-actions">{canEdit&&<button className="fy-ghost" onClick={()=>setForm({kind:'edit',fiscalYear:year})}>{t('fiscalYears.edit')}</button>}{canClose&&<button className="fy-dark" onClick={()=>setCloseTarget(year)}><LockIcon/>{t('fiscalYears.close')}</button>}</div>}</td></tr>)}</tbody></table></div>
   </section>
  </>}
  {form&&<Dialog title={t(form.kind==='create'?'fiscalYears.createTitle':'fiscalYears.editTitle')} busy={saving} onClose={()=>setForm(null)}>{errorKey&&<div role="alert" className="fy-alert">{errorText}</div>}<form onSubmit={save} className="fy-form"><label>{t('fiscalYears.name')}<input name="name" required maxLength={120} defaultValue={form.kind==='edit'?form.fiscalYear.name:''}/></label><div className="fy-date-fields"><label>{t('fiscalYears.start')}<input name="start_date" type="date" required aria-invalid={rangeInvalid||undefined} defaultValue={form.kind==='edit'?form.fiscalYear.start_date:''}/></label><label>{t('fiscalYears.end')}<input name="end_date" type="date" required aria-invalid={rangeInvalid||undefined} defaultValue={form.kind==='edit'?form.fiscalYear.end_date:''}/></label></div><div className="modal-actions"><button type="button" className="fy-ghost" onClick={()=>setForm(null)}>{t('common.cancel')}</button><button className="fy-primary" type="submit" disabled={saving}>{saving&&<span className="fy-spinner" aria-hidden="true"/>}{saving?t('fiscalYears.saving'):t('common.save')}</button></div></form></Dialog>}
  {closeTarget&&<Dialog title={t('fiscalYears.closeTitle')} busy={saving} onClose={()=>setCloseTarget(null)}><p className="fy-close-text">{t('fiscalYears.closeConfirmation',{name:closeTarget.name})}</p>{errorKey&&<div role="alert" className="fy-alert">{errorText}{blocked&&blocked.blockers.length>0&&<><strong>{t('errors.blockersTitle')}</strong><ul className="fy-findings">{blocked.blockers.map(item=><li key={item.code}>{findingMessage('blockers',item,t)}</li>)}</ul></>}{blocked&&blocked.warnings.length>0&&<><strong>{t('errors.warningsTitle')}</strong><ul className="fy-findings fy-findings--warning">{blocked.warnings.map(item=><li key={item.code}>{findingMessage('warnings',item,t)}</li>)}</ul></>}</div>}<form onSubmit={close} className="fy-form"><label>{t('fiscalYears.reason')}<textarea name="reason" maxLength={500}/></label><div className="modal-actions"><button type="button" className="fy-ghost" onClick={()=>setCloseTarget(null)}>{t('common.cancel')}</button><button className="fy-dark" type="submit" disabled={saving}>{saving?<span className="fy-spinner" aria-hidden="true"/>:<LockIcon/>}{t('fiscalYears.confirmClose')}</button></div></form></Dialog>}
 </section>
}
