import {FormEvent,useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {readQueryParameter} from '../navigation/queryState';
import {DetailPane,PageHeader,SectionCard,StatusBadge,WorkspacePage,WorkspaceState} from './SharedUI';

type Category={id:string;name_ar:string;name_en:string;default_useful_life_months:number|null;asset_account_id:string|null;accumulated_depreciation_account_id:string|null;depreciation_expense_account_id:string|null};
type Account={id:string;code:string;name:string;account_type:'asset'|'expense'|string;is_active:boolean};
type Sale={id:string;status:string;reference_number:string|null;original_filename:string;document_date:string|null;total_amount:string|null};
type Asset={id:string;asset_category_id:string;asset_number:string;name:string;description:string|null;source_type:string;source_document_id:string|null;source_reference:string|null;category_name_ar:string;category_name_en:string;acquisition_cost:string;acquisition_date:string;placed_in_service_date:string;depreciation_start_date:string|null;residual_value:string;opening_accumulated_depreciation:string;posted_depreciation:string;net_book_value:string;useful_life_months:number|null;status:string;disposal_id?:string|null;disposal_type?:string|null;disposal_date?:string|null;disposal_proceeds?:string|null;nbv_at_disposal?:string|null;calculated_gain_loss?:string|null;disposal_reason?:string|null;source_sale_document_id?:string|null};
type Entry={id:string;period_start:string;period_end:string;depreciation_amount:string;closing_nbv:string;status:string};

const trimMoney=(value:FormDataEntryValue|null,fallback='')=>typeof value==='string'?(value.trim()||fallback):fallback;
const datePattern=/^\d{4}-(0[1-9]|1[0-2])-([0-2]\d|3[01])$/;
const validDate=(value:string|null)=>value&&datePattern.test(value)&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value?value:'';
const readClosePeriod=()=>{const from=validDate(readQueryParameter('assetFrom')),to=validDate(readQueryParameter('assetTo'));return from&&to&&from<=to?{from,to}:null};
const today=()=>new Date().toISOString().slice(0,10);

export function FixedAssets({canView,canCreate,canEdit,canCancel,canManagePolicy,canApprove,canDispose,onUnauthorized}:{canView:boolean;canCreate:boolean;canEdit:boolean;canCancel:boolean;canManagePolicy:boolean;canApprove:boolean;canDispose:boolean;onUnauthorized:()=>void}){
 const{t,i18n}=useTranslation();
 const[assets,setAssets]=useState<Asset[]|null>(null),[discoveryEntries,setDiscoveryEntries]=useState<Record<string,Entry[]>>({}),[categories,setCategories]=useState<Category[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[sales,setSales]=useState<Sale[]>([]),[selected,setSelected]=useState<Asset|null>(null),[entries,setEntries]=useState<Entry[]>([]),[form,setForm]=useState(false),[editForm,setEditForm]=useState(false),[categoryForm,setCategoryForm]=useState(false),[disposalForm,setDisposalForm]=useState(false),[disposalType,setDisposalType]=useState('scrap_write_off'),[error,setError]=useState('');
 const documentId=new URLSearchParams(location.search).get('assetDocument');
 const request=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init);if(r.status===401){onUnauthorized();throw Error()}if(!r.ok){const body=await r.json().catch(()=>({}));throw Error(body.error||t('assets.error'))}return r};
 const load=async()=>{const requests=[request('/api/assets'),request('/api/asset-categories'),...(canManagePolicy?[request('/api/accounts')]:[]),...(canDispose?[request('/api/sales')]:[])];const responses=await Promise.all(requests),nextAssets=(await responses[0]!.json()).assets as Asset[];setAssets(nextAssets);const closePeriod=readClosePeriod();if(closePeriod){const schedules=await Promise.all(nextAssets.map(async asset=>[asset.id,((await(await request(`/api/assets/${asset.id}/depreciation`)).json()) as {entries:Entry[]}).entries] as const));setDiscoveryEntries(Object.fromEntries(schedules))}else setDiscoveryEntries({});setCategories((await responses[1]!.json()).categories);let index=2;if(canManagePolicy)setAccounts((await responses[index++]!.json()).accounts);if(canDispose)setSales((await responses[index]!.json()).sales);return nextAssets};
 useEffect(()=>{if(canView)void load().catch(e=>setError(e.message))},[canView,canManagePolicy,canDispose]);
 const readAsset=async(id:string)=>await(await request(`/api/assets/${id}`)).json() as Asset;
 const choose=async(a:Asset)=>{setEditForm(false);setDisposalForm(false);setSelected(await readAsset(a.id));setEntries((await(await request(`/api/assets/${a.id}/depreciation`)).json()).entries)};
 const refreshSelected=async(id:string)=>{await load();setSelected(await readAsset(id));setEntries((await(await request(`/api/assets/${id}/depreciation`)).json()).entries)};
 const mutate=async(url:string,body:unknown={})=>{setError('');try{const id=selected?.id;await request(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(id)await refreshSelected(id);else await load();return true}catch(e){const message=(e as Error).message;setError(message==='Asset category accounting is incomplete'?t('assets.accountingIncomplete'):message);return false}};
 const draftPayload=(d:FormData)=>({asset_category_id:d.get('category'),name:d.get('name'),description:d.get('description')||null,acquisition_cost:trimMoney(d.get('cost')),acquisition_date:d.get('acquisitionDate'),placed_in_service_date:d.get('serviceDate'),depreciation_start_date:d.get('startDate')||null,useful_life_months:d.get('life')?Number(d.get('life')):null,residual_value:trimMoney(d.get('residual'),'0'),opening_accumulated_depreciation:trimMoney(d.get('opening'),'0')});
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),payload=draftPayload(d);try{if(documentId){const p=await request('/api/purchases'),doc=(await p.json()).purchases.find((x:{id:string})=>x.id===documentId);if(!doc)throw Error(t('assets.sourceUnavailable'));if(await mutate('/api/assets/from-document',{...payload,document_id:documentId,acquisition_cost:String(doc.total_amount).trim(),acquisition_date:doc.document_date}))setForm(false)}else if(await mutate('/api/assets/manual',{...payload,manual_reason:d.get('reason'),source_reference:d.get('reference')}))setForm(false)}catch(x){setError((x as Error).message)}};
 const submitEdit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;setError('');try{await request(`/api/assets/${selected.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(draftPayload(new FormData(e.currentTarget)))});await refreshSelected(selected.id);setEditForm(false)}catch(x){setError((x as Error).message)}};
 const saveCategory=async(e:FormEvent<HTMLFormElement>,id:string)=>{e.preventDefault();const d=new FormData(e.currentTarget);setError('');try{await request(`/api/asset-categories/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({asset_account_id:d.get('assetAccount')||null,accumulated_depreciation_account_id:d.get('accumulatedAccount')||null,depreciation_expense_account_id:d.get('expenseAccount')||null,default_useful_life_months:d.get('defaultLife')?Number(d.get('defaultLife')):null})});await load()}catch(x){setError((x as Error).message)}};
 const submitDisposal=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const d=new FormData(e.currentTarget);if(await mutate(`/api/assets/${selected.id}/dispose`,{disposal_type:d.get('disposalType'),disposal_date:d.get('disposalDate'),disposal_proceeds:trimMoney(d.get('disposalProceeds'),'0'),source_sale_document_id:d.get('saleDocument')||null,reason:d.get('disposalReason')}))setDisposalForm(false)};
 if(!canView)return <WorkspacePage><WorkspaceState>{t('assets.noAccess')}</WorkspaceState></WorkspacePage>;
 const closePeriod=readClosePeriod();
 const visibleAssets=closePeriod?(assets??[]).filter(asset=>(asset.source_type==='document'&&asset.status==='draft'&&asset.acquisition_date>=closePeriod.from&&asset.acquisition_date<=closePeriod.to)||(discoveryEntries[asset.id]??[]).some(entry=>entry.status==='pending'&&entry.period_end>=closePeriod.from&&entry.period_end<=closePeriod.to)):(assets??[]);
 const categoryName=(c:Category)=>i18n.language==='ar'?c.name_ar:c.name_en,accountName=(a:Account)=>`${a.code} — ${a.name}`,activeAccounts=(type:string)=>accounts.filter(a=>a.is_active&&a.account_type===type),approvedSales=sales.filter(s=>s.status==='approved');
 const accountSelect=(name:string,value:string|null,type:string)=><select name={name} defaultValue={value??''}><option value="">—</option>{activeAccounts(type).map(a=><option key={a.id} value={a.id}>{accountName(a)}</option>)}</select>;
 return <WorkspacePage size="operational" labelledBy="assets-title"><PageHeader titleId="assets-title" eyebrow={t('assets.title')} title={t('assets.title')} description={t('assets.description')} action={(canCreate||canManagePolicy)?<>{canManagePolicy&&<button onClick={()=>setCategoryForm(v=>!v)}>{t('assets.categoryAccounting')}</button>}{canCreate&&<button className="primary" onClick={()=>setForm(v=>!v)}>{documentId?t('assets.capitalise'):t('assets.addManual')}</button>}</>:undefined}/>
 {error&&<WorkspaceState tone="error">{error}</WorkspaceState>}
 {categoryForm&&canManagePolicy&&<SectionCard><h2>{t('assets.categoryAccounting')}</h2>{categories.map(c=><form className="form-grid" key={c.id} onSubmit={e=>void saveCategory(e,c.id)}><h3>{categoryName(c)}</h3><label>{t('assets.assetAccount')}{accountSelect('assetAccount',c.asset_account_id,'asset')}</label><label>{t('assets.accumulatedAccount')}{accountSelect('accumulatedAccount',c.accumulated_depreciation_account_id,'asset')}</label><label>{t('assets.expenseAccount')}{accountSelect('expenseAccount',c.depreciation_expense_account_id,'expense')}</label><label>{t('assets.defaultLife')}<input name="defaultLife" type="number" min="1" max="1200" defaultValue={c.default_useful_life_months??''}/></label><button className="primary">{t('common.save')}</button></form>)}</SectionCard>}
 {form&&<SectionCard><form className="form-grid" onSubmit={submit}><label>{t('assets.category')}<select name="category" required>{categories.map(c=><option value={c.id} key={c.id}>{categoryName(c)}</option>)}</select></label><label>{t('assets.name')}<input name="name" required/></label><label>{t('assets.descriptionField')}<input name="description"/></label>{!documentId&&<><label>{t('assets.reference')}<input name="reference" required/></label><label>{t('assets.reason')}<input name="reason" required/></label><label>{t('assets.cost')}<input name="cost" required/></label><label>{t('assets.acquisitionDate')}<input name="acquisitionDate" type="date" required/></label></>}<label>{t('assets.serviceDate')}<input name="serviceDate" type="date" required/></label><label>{t('assets.startDate')}<input name="startDate" type="date"/></label><label>{t('assets.life')}<input name="life" type="number" min="1" max="1200"/></label><label>{t('assets.residual')}<input name="residual" defaultValue="0"/></label>{!documentId&&<label>{t('assets.opening')}<input name="opening" defaultValue="0"/></label>}<div className="modal-actions"><button className="primary">{t('common.save')}</button><button type="button" onClick={()=>setForm(false)}>{t('common.cancel')}</button></div></form></SectionCard>}
 {!assets?<WorkspaceState>{t('common.loading')}</WorkspaceState>:visibleAssets.length===0?<WorkspaceState kind="empty">{t('assets.empty')}</WorkspaceState>:<div className="shared-workspace-page__content"><div className="shared-data-workspace"><table><thead><tr>{['reference','name','category','acquisitionDate','cost','accumulated','nbv','status'].map(k=><th key={k}>{t(`assets.${k}`)}</th>)}</tr></thead><tbody>{visibleAssets.map(a=><tr key={a.id} tabIndex={0} onClick={()=>void choose(a)}><td>{a.asset_number}</td><td>{a.name}</td><td>{i18n.language==='ar'?a.category_name_ar:a.category_name_en}</td><td>{a.acquisition_date}</td><td>{a.acquisition_cost}</td><td>{Number(a.opening_accumulated_depreciation)+Number(a.posted_depreciation)}</td><td>{a.net_book_value}</td><td><StatusBadge status={a.status}>{t(`assets.statuses.${a.status}`)}</StatusBadge></td></tr>)}</tbody></table></div>
 {selected&&<DetailPane label={t('assets.detail')}><h2>{selected.asset_number} — {selected.name}</h2>
 {editForm&&<SectionCard><form className="form-grid" onSubmit={submitEdit}><label>{t('assets.category')}<select name="category" required defaultValue={selected.asset_category_id}>{categories.map(c=><option value={c.id} key={c.id}>{categoryName(c)}</option>)}</select></label><label>{t('assets.name')}<input name="name" required defaultValue={selected.name}/></label><label>{t('assets.descriptionField')}<input name="description" defaultValue={selected.description??''}/></label><label>{t('assets.cost')}<input name="cost" required defaultValue={selected.acquisition_cost} readOnly={selected.source_type==='document'}/></label><label>{t('assets.acquisitionDate')}<input name="acquisitionDate" type="date" required defaultValue={selected.acquisition_date} readOnly={selected.source_type==='document'}/></label><label>{t('assets.serviceDate')}<input name="serviceDate" type="date" required defaultValue={selected.placed_in_service_date}/></label><label>{t('assets.startDate')}<input name="startDate" type="date" defaultValue={selected.depreciation_start_date??''}/></label><label>{t('assets.life')}<input name="life" type="number" min="1" max="1200" defaultValue={selected.useful_life_months??''}/></label><label>{t('assets.residual')}<input name="residual" defaultValue={selected.residual_value}/></label><label>{t('assets.opening')}<input name="opening" defaultValue={selected.opening_accumulated_depreciation}/></label><div className="modal-actions"><button className="primary">{t('common.save')}</button><button type="button" onClick={()=>setEditForm(false)}>{t('common.cancel')}</button></div></form></SectionCard>}
 <SectionCard><dl><dt>{t('assets.assetNumber')}</dt><dd>{selected.asset_number}</dd><dt>{t('assets.name')}</dt><dd>{selected.name}</dd><dt>{t('assets.category')}</dt><dd>{i18n.language==='ar'?selected.category_name_ar:selected.category_name_en}</dd><dt>{t('assets.source')}</dt><dd>{selected.source_type==='document'?selected.source_document_id:selected.source_reference}</dd><dt>{t('assets.cost')}</dt><dd>{selected.acquisition_cost}</dd><dt>{t('assets.acquisitionDate')}</dt><dd>{selected.acquisition_date}</dd><dt>{t('assets.serviceDate')}</dt><dd>{selected.placed_in_service_date}</dd><dt>{t('assets.startDate')}</dt><dd>{selected.depreciation_start_date??'—'}</dd><dt>{t('assets.life')}</dt><dd>{selected.useful_life_months??'—'}</dd><dt>{t('assets.residual')}</dt><dd>{selected.residual_value}</dd><dt>{t('assets.opening')}</dt><dd>{selected.opening_accumulated_depreciation}</dd><dt>{t('assets.postedAccumulated')}</dt><dd>{selected.posted_depreciation}</dd><dt>{t('assets.nbv')}</dt><dd>{selected.net_book_value}</dd><dt>{t('assets.status')}</dt><dd>{t(`assets.statuses.${selected.status}`)}</dd>{selected.status==='disposed'&&<><dt>{t('assets.disposalType')}</dt><dd>{t(`assets.disposalTypes.${selected.disposal_type}`)}</dd><dt>{t('assets.disposalDate')}</dt><dd>{selected.disposal_date}</dd><dt>{t('assets.disposalProceeds')}</dt><dd>{selected.disposal_proceeds}</dd><dt>{t('assets.nbvAtDisposal')}</dt><dd>{selected.nbv_at_disposal}</dd><dt>{t('assets.gainLoss')}</dt><dd>{selected.calculated_gain_loss}</dd><dt>{t('assets.reason')}</dt><dd>{selected.disposal_reason}</dd>{selected.source_sale_document_id&&<><dt>{t('assets.sourceSale')}</dt><dd>{sales.find(s=>s.id===selected.source_sale_document_id)?.reference_number??selected.source_sale_document_id}</dd></>}</>}</dl></SectionCard>
 <SectionCard><h3>{t('assets.schedule')}</h3>{entries.length?<table><thead><tr><th>{t('assets.period')}</th><th>{t('assets.depreciation')}</th><th>{t('assets.closingNbv')}</th><th>{t('assets.status')}</th></tr></thead><tbody>{entries.map(x=><tr key={x.id}><td>{x.period_start} – {x.period_end}</td><td>{x.depreciation_amount}</td><td>{x.closing_nbv}</td><td>{t(`assets.depreciationStatuses.${x.status}`)}</td></tr>)}</tbody></table>:<p>{t('assets.noSchedule')}</p>}</SectionCard>
 {disposalForm&&<SectionCard><form className="form-grid" onSubmit={submitDisposal}><label>{t('assets.disposalType')}<select name="disposalType" value={disposalType} onChange={e=>setDisposalType(e.target.value)}><option value="sale">{t('assets.disposalTypes.sale')}</option><option value="scrap_write_off">{t('assets.disposalTypes.scrap_write_off')}</option><option value="other">{t('assets.disposalTypes.other')}</option></select></label><label>{t('assets.disposalDate')}<input name="disposalDate" type="date" required defaultValue={today()}/></label><label>{t('assets.disposalProceeds')}<input name="disposalProceeds" required defaultValue={disposalType==='scrap_write_off'?'0':''}/></label><label>{t('assets.reason')}<input name="disposalReason" required/></label><label>{t('assets.sourceSale')}<select name="saleDocument" required={disposalType==='sale'}><option value="">—</option>{approvedSales.map(s=><option key={s.id} value={s.id}>{s.reference_number??s.original_filename} — {s.document_date??'—'} — {s.total_amount??'—'}</option>)}</select></label><div className="modal-actions"><button className="primary">{t('assets.dispose')}</button><button type="button" onClick={()=>setDisposalForm(false)}>{t('common.cancel')}</button></div></form></SectionCard>}
 <div className="shared-detail-pane__actions">{canApprove&&selected.status==='draft'&&<button className="primary" onClick={()=>void mutate(`/api/assets/${selected.id}/approve`)}>{t('assets.approve')}</button>}{canEdit&&selected.status==='draft'&&<button onClick={()=>setEditForm(true)}>{t('assets.edit')}</button>}{canCancel&&selected.status==='draft'&&<button onClick={()=>{const reason=prompt(t('assets.reason'));if(reason)void mutate(`/api/assets/${selected.id}/cancel`,{reason})}}>{t('assets.cancelDraft')}</button>}{canDispose&&['active','fully_depreciated'].includes(selected.status)&&<button onClick={()=>setDisposalForm(true)}>{t('assets.dispose')}</button>}</div></DetailPane>}</div>}
 </WorkspacePage>
}
