import {FormEvent,ReactNode,useEffect,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {readQueryParameter,writeQueryParameters} from '../navigation/queryState';
import {DetailPane,SectionCard,StatusBadge,WorkspacePage,WorkspaceState} from './SharedUI';
import {ExportButtons} from './ExportButtons';
import {useActiveCompanyName} from '../context/CompanyContext';
import {fixedAssetsExport,generatedStamp} from '../export/reportExport';
import './FixedAssets.css';

type Category={id:string;name_ar:string;name_en:string;default_useful_life_months:number|null;asset_account_id:string|null;accumulated_depreciation_account_id:string|null;depreciation_expense_account_id:string|null};
type Account={id:string;code:string;name:string;account_type:'asset'|'expense'|string;is_active:boolean};
type Sale={id:string;status:string;reference_number:string|null;original_filename:string;document_date:string|null;total_amount:string|null};
type Asset={id:string;asset_category_id:string;asset_number:string;name:string;description:string|null;source_type:string;source_document_id:string|null;source_reference:string|null;category_name_ar:string;category_name_en:string;acquisition_cost:string;acquisition_date:string;placed_in_service_date:string;depreciation_start_date:string|null;residual_value:string;opening_accumulated_depreciation:string;posted_depreciation:string;net_book_value:string;useful_life_months:number|null;status:string;disposal_id?:string|null;disposal_type?:string|null;disposal_date?:string|null;disposal_proceeds?:string|null;nbv_at_disposal?:string|null;calculated_gain_loss?:string|null;disposal_reason?:string|null;source_sale_document_id?:string|null};
type Entry={id:string;period_start:string;period_end:string;depreciation_amount:string;closing_nbv:string;status:string};

const trimMoney=(value:FormDataEntryValue|null,fallback='')=>typeof value==='string'?(value.trim()||fallback):fallback;
const datePattern=/^\d{4}-(0[1-9]|1[0-2])-([0-2]\d|3[01])$/;
const validDate=(value:string|null)=>value&&datePattern.test(value)&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value?value:'';
const readClosePeriod=()=>{const from=validDate(readQueryParameter('assetFrom')),to=validDate(readQueryParameter('assetTo'));return from&&to&&from<=to?{from,to}:null};
const today=()=>new Date().toISOString().slice(0,10);

export function FixedAssets({canView,canCreate,canEdit,canCancel,canManagePolicy,canApprove,canDispose,onUnauthorized,view='main',onOpenPolicy,onOpenCategories,onBack}:{canView:boolean;canCreate:boolean;canEdit:boolean;canCancel:boolean;canManagePolicy:boolean;canApprove:boolean;canDispose:boolean;onUnauthorized:()=>void;view?:'main'|'categories';onOpenPolicy?:()=>void;onOpenCategories?:()=>void;onBack?:()=>void}){
 const{t,i18n}=useTranslation();
 const[assets,setAssets]=useState<Asset[]|null>(null),[discoveryEntries,setDiscoveryEntries]=useState<Record<string,Entry[]>>({}),[categories,setCategories]=useState<Category[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[sales,setSales]=useState<Sale[]>([]),[selected,setSelected]=useState<Asset|null>(null),[entries,setEntries]=useState<Entry[]>([]),[form,setForm]=useState(false),[editForm,setEditForm]=useState(false),[categoryForm,setCategoryForm]=useState(false),[disposalForm,setDisposalForm]=useState(false),[disposalType,setDisposalType]=useState('scrap_write_off'),[error,setError]=useState('');
 const[,setReload]=useState(0);
 const company=useActiveCompanyName()??'';
 const documentId=new URLSearchParams(location.search).get('assetDocument');
 const request=async(url:string,init?:RequestInit)=>{const r=await fetch(url,init);if(r.status===401){onUnauthorized();throw Error()}if(!r.ok){const body=await r.json().catch(()=>({}));throw Error(body.error||t('assets.error'))}return r};
 const load=async()=>{const requests=[request('/api/assets'),request('/api/asset-categories'),...(canManagePolicy?[request('/api/accounts')]:[]),...(canDispose?[request('/api/sales')]:[])];const responses=await Promise.all(requests),nextAssets=(await responses[0]!.json()).assets as Asset[];setAssets(nextAssets);const closePeriod=readClosePeriod();if(closePeriod){const schedules=await Promise.all(nextAssets.map(async asset=>[asset.id,((await(await request(`/api/assets/${asset.id}/depreciation`)).json()) as {entries:Entry[]}).entries] as const));setDiscoveryEntries(Object.fromEntries(schedules))}else setDiscoveryEntries({});setCategories((await responses[1]!.json()).categories);let index=2;if(canManagePolicy)setAccounts((await responses[index++]!.json()).accounts);if(canDispose)setSales((await responses[index]!.json()).sales);return nextAssets};
 useEffect(()=>{if(canView)void load().catch(e=>setError(e.message))},[canView,canManagePolicy,canDispose]);
 const readAsset=async(id:string)=>await(await request(`/api/assets/${id}`)).json() as Asset;
 const choose=async(a:Asset)=>{setEditForm(false);setDisposalForm(false);setSelected(await readAsset(a.id));setEntries((await(await request(`/api/assets/${a.id}/depreciation`)).json()).entries)};
 const pick=async(a:Asset)=>{setError('');try{await choose(a)}catch(e){const message=(e as Error).message;if(message)setError(message)}};
 const refreshSelected=async(id:string)=>{await load();setSelected(await readAsset(id));setEntries((await(await request(`/api/assets/${id}/depreciation`)).json()).entries)};
 const mutate=async(url:string,body:unknown={})=>{setError('');try{const id=selected?.id;await request(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(id)await refreshSelected(id);else await load();return true}catch(e){const message=(e as Error).message;setError(message==='Asset category accounting is incomplete'?t('assets.accountingIncomplete'):message);return false}};
 const draftPayload=(d:FormData)=>({asset_category_id:d.get('category'),name:d.get('name'),description:d.get('description')||null,acquisition_cost:trimMoney(d.get('cost')),acquisition_date:d.get('acquisitionDate'),placed_in_service_date:d.get('serviceDate'),depreciation_start_date:d.get('startDate')||null,useful_life_months:d.get('life')?Number(d.get('life')):null,residual_value:trimMoney(d.get('residual'),'0'),opening_accumulated_depreciation:trimMoney(d.get('opening'),'0')});
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget),payload=draftPayload(d);try{if(documentId){const p=await request('/api/purchases'),doc=(await p.json()).purchases.find((x:{id:string})=>x.id===documentId);if(!doc)throw Error(t('assets.sourceUnavailable'));if(await mutate('/api/assets/from-document',{...payload,document_id:documentId,acquisition_cost:String(doc.total_amount).trim(),acquisition_date:doc.document_date}))setForm(false)}else if(await mutate('/api/assets/manual',{...payload,manual_reason:d.get('reason'),source_reference:d.get('reference')}))setForm(false)}catch(x){setError((x as Error).message)}};
 const submitEdit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;setError('');try{await request(`/api/assets/${selected.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(draftPayload(new FormData(e.currentTarget)))});await refreshSelected(selected.id);setEditForm(false)}catch(x){setError((x as Error).message)}};
 const saveCategory=async(e:FormEvent<HTMLFormElement>,id:string)=>{e.preventDefault();const d=new FormData(e.currentTarget);setError('');try{await request(`/api/asset-categories/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({asset_account_id:d.get('assetAccount')||null,accumulated_depreciation_account_id:d.get('accumulatedAccount')||null,depreciation_expense_account_id:d.get('expenseAccount')||null,default_useful_life_months:d.get('defaultLife')?Number(d.get('defaultLife')):null})});await load()}catch(x){setError((x as Error).message)}};
 const submitDisposal=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const d=new FormData(e.currentTarget);if(await mutate(`/api/assets/${selected.id}/dispose`,{disposal_type:d.get('disposalType'),disposal_date:d.get('disposalDate'),disposal_proceeds:trimMoney(d.get('disposalProceeds'),'0'),source_sale_document_id:d.get('saleDocument')||null,reason:d.get('disposalReason')}))setDisposalForm(false)};
 if(!canView)return <WorkspacePage><WorkspaceState>{t('assets.noAccess')}</WorkspaceState></WorkspacePage>;
 const closePeriod=readClosePeriod();
 const visibleAssets=closePeriod?(assets??[]).filter(asset=>(asset.source_type==='document'&&asset.status==='draft'&&asset.acquisition_date>=closePeriod.from&&asset.acquisition_date<=closePeriod.to)||(discoveryEntries[asset.id]??[]).some(entry=>entry.status==='pending'&&entry.period_end>=closePeriod.from&&entry.period_end<=closePeriod.to)):(assets??[]);
 const categoryName=(c:Category)=>i18n.language==='ar'?c.name_ar:c.name_en,accountName=(a:Account)=>`${a.code} — ${a.name}`,activeAccounts=(type:string)=>accounts.filter(a=>a.is_active&&a.account_type===type),approvedSales=sales.filter(s=>s.status==='approved');
 const accountSelect=(name:string,value:string|null,type:string)=><select name={name} defaultValue={value??''}><option value="">—</option>{activeAccounts(type).map(a=><option key={a.id} value={a.id}>{accountName(a)}</option>)}</select>;
 const ar=i18n.language==='ar',currency=ar?'ر.س':'SAR';
 const fmt=(v:string|number|null|undefined)=>{if(v===null||v===undefined||v==='')return '—';const n=Number(v);return Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):String(v)};
 const sum=(values:string[])=>values.reduce((total,v)=>total+Math.round(Number(v)*100),0)/100;
 const accumulatedOf=(a:Asset)=>Number(a.opening_accumulated_depreciation)+Number(a.posted_depreciation);
 const kpis={count:visibleAssets.length,active:visibleAssets.filter(a=>a.status==='active').length,cost:sum(visibleAssets.map(a=>a.acquisition_cost)),accumulated:Math.round(visibleAssets.reduce((total,a)=>total+accumulatedOf(a)*100,0))/100,nbv:sum(visibleAssets.map(a=>a.net_book_value))};
 const exportDoc=assets&&!error&&visibleAssets.length>0?(()=>{const stamp=generatedStamp();return fixedAssetsExport({ar,company,generatedAt:stamp,asOf:stamp.slice(0,10),from:closePeriod?.from,to:closePeriod?.to,rows:visibleAssets.map(a=>({asset_number:a.asset_number,name:a.name,category:ar?a.category_name_ar:a.category_name_en,acquisition_date:a.acquisition_date,placed_in_service_date:a.placed_in_service_date,acquisition_cost:a.acquisition_cost,accumulated:accumulatedOf(a).toFixed(2),net_book_value:a.net_book_value,status:a.status})),statusLabel:s=>t(`assets.statuses.${s}`)})})():null;
 const amount=(v:string|number|null|undefined)=><span className="fa-amount" dir="ltr"><span>{fmt(v)}</span></span>;
 const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
 const sourceValue=(a:Asset)=>{const raw=a.source_type==='document'?a.source_document_id:a.source_reference,human=a.source_reference&&!uuidPattern.test(a.source_reference)?a.source_reference:null;if(human)return <span dir="ltr" className="fa-range">{human}</span>;if(!raw)return '—';return uuidPattern.test(raw)?<span className="fa-source" dir="ltr" title={raw}>{raw.slice(0,8)}…</span>:<span dir="ltr" className="fa-range">{raw}</span>};
 const field=(label:string,value:ReactNode)=><div className="fa-field"><dt>{label}</dt><dd>{value}</dd></div>;
 const backLink=<button type="button" className="fa-link" onClick={onBack}>{t('assets.title')}</button>;
 const categoryCards=categories.map(c=><form className="fa-card fa-category" key={`${c.id}:${accounts.length}`} onSubmit={e=>void saveCategory(e,c.id)}><div className="fa-card__head"><h3>{categoryName(c)}</h3><button className="fa-primary">{t('common.save')}</button></div><div className="fa-grid2"><label>{t('assets.assetAccount')}{accountSelect('assetAccount',c.asset_account_id,'asset')}</label><label>{t('assets.accumulatedAccount')}{accountSelect('accumulatedAccount',c.accumulated_depreciation_account_id,'asset')}</label><label>{t('assets.expenseAccount')}{accountSelect('expenseAccount',c.depreciation_expense_account_id,'expense')}</label><label>{t('assets.defaultLife')}<input name="defaultLife" type="number" min="1" max="1200" defaultValue={c.default_useful_life_months??''}/></label></div></form>);
 if(view==='categories'){
  if(!canManagePolicy)return <WorkspacePage><WorkspaceState>{t('assets.noAccess')}</WorkspaceState></WorkspacePage>;
  return <section className="panel fa-view" aria-labelledby="assets-categories-title" data-workspace-size="operational">
   <header className="fa-header"><div><h2 id="assets-categories-title">{t('assets.categoryAccounting')}</h2></div></header>
   <div className="fa-subbar">{backLink}<span className="fa-muted">{t('assets.categoryCount',{count:categories.length})}</span></div>
   {error&&<WorkspaceState tone="error">{error}</WorkspaceState>}
   {categoryCards}
  </section>;
 }
 const legacyCategoryToggle=!onOpenCategories;
 return <section className="panel fa-view" aria-labelledby="assets-title" data-workspace-size="operational">
 <header className="fa-header"><div><h2 id="assets-title">{t('assets.title')}</h2><p>{t('assets.description')}</p></div>{canCreate&&<button className="fa-primary" onClick={()=>setForm(v=>!v)}>{documentId?t('assets.capitalise'):t('assets.addManual')}</button>}</header>
 <div className="fa-subbar"><div className="fa-subbar__actions">{canManagePolicy&&<button className="fa-ghost" onClick={()=>legacyCategoryToggle?setCategoryForm(v=>!v):onOpenCategories!()}>{t('assets.categoryAccounting')}</button>}{onOpenPolicy&&canView&&<button type="button" className="fa-link" onClick={onOpenPolicy}>{t('assets.policyGovernance')}</button>}</div>{assets&&<span className="fa-muted">{t('assets.summaryNote',{count:kpis.active})}</span>}</div>
 {error&&<WorkspaceState tone="error">{error}</WorkspaceState>}
 {assets&&<ExportButtons language={i18n.language} document={exportDoc} landscape/>}
 {closePeriod&&<div className="fa-card fa-period-note" role="status" data-testid="assets-period-filter"><span>{t('assets.periodFilter',{from:closePeriod.from,to:closePeriod.to})}</span> <button type="button" className="fa-link" onClick={()=>{writeQueryParameters({assetFrom:null,assetTo:null});setReload(n=>n+1)}}>{t('assets.clearPeriodFilter')}</button></div>}
 {legacyCategoryToggle&&categoryForm&&canManagePolicy&&<div className="fa-card"><h3>{t('assets.categoryAccounting')}</h3>{categoryCards}</div>}
 {form&&<section className="fa-card"><form className="form-grid fa-form" onSubmit={submit}><label>{t('assets.category')}<select name="category" required>{categories.map(c=><option value={c.id} key={c.id}>{categoryName(c)}</option>)}</select></label><label>{t('assets.name')}<input name="name" required/></label><label>{t('assets.descriptionField')}<input name="description"/></label>{!documentId&&<><label>{t('assets.reference')}<input name="reference" required/></label><label>{t('assets.reason')}<input name="reason" required/></label><label>{t('assets.cost')}<input name="cost" required/></label><label>{t('assets.acquisitionDate')}<input name="acquisitionDate" type="date" required/></label></>}<label>{t('assets.serviceDate')}<input name="serviceDate" type="date" required/></label><label>{t('assets.startDate')}<input name="startDate" type="date"/></label><label>{t('assets.life')}<input name="life" type="number" min="1" max="1200"/></label><label>{t('assets.residual')}<input name="residual" defaultValue="0"/></label>{!documentId&&<label>{t('assets.opening')}<input name="opening" defaultValue="0"/></label>}<div className="modal-actions"><button className="fa-primary">{t('common.save')}</button><button type="button" className="fa-ghost" onClick={()=>setForm(false)}>{t('common.cancel')}</button></div></form></section>}
 {!assets?(error?null:<WorkspaceState>{t('common.loading')}</WorkspaceState>):visibleAssets.length===0?<WorkspaceState kind="empty">{closePeriod?t('assets.emptyForPeriod'):t('assets.empty')}</WorkspaceState>:<>
 <div className="fa-kpis">
  <div className="fa-kpi"><span>{t('assets.kpiCount')}</span><strong>{kpis.count}</strong><em className="fa-kpi__badge">{t('assets.kpiActive',{count:kpis.active})}</em></div>
  <div className="fa-kpi"><span>{t('assets.cost')}</span><strong dir="ltr"><small>{currency}</small>{fmt(kpis.cost)}</strong></div>
  <div className="fa-kpi fa-kpi--warn"><span>{t('assets.accumulated')}</span><strong dir="ltr"><small>{currency}</small>{fmt(kpis.accumulated)}</strong></div>
  <div className="fa-kpi fa-kpi--good"><span>{t('assets.nbv')}</span><strong dir="ltr"><small>{currency}</small>{fmt(kpis.nbv)}</strong></div>
 </div>
 <div className="shared-workspace-page__content">
 <section className="fa-card" aria-labelledby="assets-register-title"><div className="fa-card__head"><h3 id="assets-register-title">{t('assets.register')}</h3><span className="fa-muted">{t('assets.registerMeta',{count:visibleAssets.length,currency})}</span></div>
 <div className="fa-table shared-data-workspace"><table><thead><tr>{['reference','name','category','acquisitionDate','cost','accumulated','nbv','status'].map(k=><th key={k}>{t(`assets.${k}`)}</th>)}</tr></thead><tbody>{visibleAssets.map(a=><tr key={a.id} tabIndex={0} className={selected?.id===a.id?'is-selected':undefined} onClick={()=>void pick(a)} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();void pick(a)}}}><td className="fa-ref">{a.asset_number}</td><td>{a.name}</td><td>{i18n.language==='ar'?a.category_name_ar:a.category_name_en}</td><td>{a.acquisition_date}</td><td>{fmt(a.acquisition_cost)}</td><td>{fmt(accumulatedOf(a))}</td><td><strong>{fmt(a.net_book_value)}</strong></td><td><StatusBadge status={a.status}>{t(`assets.statuses.${a.status}`)}</StatusBadge></td></tr>)}</tbody></table></div>
 <p className="fa-muted fa-foot">{selected?t('assets.selectedOf',{number:selected.asset_number,shown:1,total:visibleAssets.length}):t('assets.selectHint')}</p></section>
 {selected&&<DetailPane label={t('assets.detail')}><div className="fa-card fa-detail"><div className="fa-card__head"><h2>{selected.name} — {selected.asset_number}</h2><StatusBadge status={selected.status}>{t(`assets.statuses.${selected.status}`)}</StatusBadge></div>
 {editForm&&<SectionCard><form className="form-grid fa-form" onSubmit={submitEdit}><label>{t('assets.category')}<select name="category" required defaultValue={selected.asset_category_id}>{categories.map(c=><option value={c.id} key={c.id}>{categoryName(c)}</option>)}</select></label><label>{t('assets.name')}<input name="name" required defaultValue={selected.name}/></label><label>{t('assets.descriptionField')}<input name="description" defaultValue={selected.description??''}/></label><label>{t('assets.cost')}<input name="cost" required defaultValue={selected.acquisition_cost} readOnly={selected.source_type==='document'}/></label><label>{t('assets.acquisitionDate')}<input name="acquisitionDate" type="date" required defaultValue={selected.acquisition_date} readOnly={selected.source_type==='document'}/></label><label>{t('assets.serviceDate')}<input name="serviceDate" type="date" required defaultValue={selected.placed_in_service_date}/></label><label>{t('assets.startDate')}<input name="startDate" type="date" defaultValue={selected.depreciation_start_date??''}/></label><label>{t('assets.life')}<input name="life" type="number" min="1" max="1200" defaultValue={selected.useful_life_months??''}/></label><label>{t('assets.residual')}<input name="residual" defaultValue={selected.residual_value}/></label><label>{t('assets.opening')}<input name="opening" defaultValue={selected.opening_accumulated_depreciation}/></label><div className="modal-actions"><button className="fa-primary">{t('common.save')}</button><button type="button" className="fa-ghost" onClick={()=>setEditForm(false)}>{t('common.cancel')}</button></div></form></SectionCard>}
 <div className="fa-groups">
  <section><h4>{t('assets.groupIdentity')}</h4><dl>{field(t('assets.assetNumber'),selected.asset_number)}{field(t('assets.name'),selected.name)}{field(t('assets.category'),i18n.language==='ar'?selected.category_name_ar:selected.category_name_en)}{field(t('assets.source'),sourceValue(selected))}</dl></section>
  <section><h4>{t('assets.groupValues',{currency})}</h4><dl>{field(t('assets.cost'),amount(selected.acquisition_cost))}{field(t('assets.residual'),amount(selected.residual_value))}{field(t('assets.opening'),amount(selected.opening_accumulated_depreciation))}{field(t('assets.postedAccumulated'),amount(selected.posted_depreciation))}{field(t('assets.nbv'),<strong>{amount(selected.net_book_value)}</strong>)}</dl></section>
  <section><h4>{t('assets.groupDates')}</h4><dl>{field(t('assets.acquisitionDate'),<span className="fa-amount" dir="ltr">{selected.acquisition_date}</span>)}{field(t('assets.serviceDate'),<span className="fa-amount" dir="ltr">{selected.placed_in_service_date}</span>)}{field(t('assets.startDate'),<span className="fa-amount" dir="ltr">{selected.depreciation_start_date??'—'}</span>)}{field(t('assets.life'),selected.useful_life_months===null?'—':t('assets.months',{count:selected.useful_life_months}))}{field(t('assets.status'),t(`assets.statuses.${selected.status}`))}</dl></section>
  {selected.status==='disposed'&&<section><h4>{t('assets.dispose')}</h4><dl>{field(t('assets.disposalType'),t(`assets.disposalTypes.${selected.disposal_type}`))}{field(t('assets.disposalDate'),selected.disposal_date)}{field(t('assets.disposalProceeds'),amount(selected.disposal_proceeds))}{field(t('assets.nbvAtDisposal'),amount(selected.nbv_at_disposal))}{field(t('assets.gainLoss'),amount(selected.calculated_gain_loss))}{field(t('assets.reason'),selected.disposal_reason)}{selected.source_sale_document_id&&field(t('assets.sourceSale'),sales.find(s=>s.id===selected.source_sale_document_id)?.reference_number??selected.source_sale_document_id)}</dl></section>}
 </div></div>
 <div className="fa-card"><div className="fa-card__head"><h3>{t('assets.schedule')}</h3><span className="fa-muted">{t('assets.scheduleMeta',{count:entries.length,currency})}</span></div>{entries.length?<div className="fa-table fa-schedule shared-data-workspace" tabIndex={0} role="region" aria-label={t('assets.schedule')}><table><thead><tr><th>{t('assets.period')}</th><th>{t('assets.depreciation')}</th><th>{t('assets.closingNbv')}</th><th>{t('assets.status')}</th></tr></thead><tbody>{entries.map(x=><tr key={x.id}><td><span dir="ltr" className="fa-range">{x.period_start} – {x.period_end}</span></td><td>{fmt(x.depreciation_amount)}</td><td>{fmt(x.closing_nbv)}</td><td><StatusBadge status={x.status}>{t(`assets.depreciationStatuses.${x.status}`)}</StatusBadge></td></tr>)}</tbody></table></div>:<p>{t('assets.noSchedule')}</p>}
 {disposalForm&&<SectionCard><form className="form-grid fa-form" onSubmit={submitDisposal}><label>{t('assets.disposalType')}<select name="disposalType" value={disposalType} onChange={e=>setDisposalType(e.target.value)}><option value="sale">{t('assets.disposalTypes.sale')}</option><option value="scrap_write_off">{t('assets.disposalTypes.scrap_write_off')}</option><option value="other">{t('assets.disposalTypes.other')}</option></select></label><label>{t('assets.disposalDate')}<input name="disposalDate" type="date" required defaultValue={today()}/></label><label>{t('assets.disposalProceeds')}<input name="disposalProceeds" required defaultValue={disposalType==='scrap_write_off'?'0':''}/></label><label>{t('assets.reason')}<input name="disposalReason" required/></label><label>{t('assets.sourceSale')}<select name="saleDocument" required={disposalType==='sale'}><option value="">—</option>{approvedSales.map(s=><option key={s.id} value={s.id}>{s.reference_number??s.original_filename} — {s.document_date??'—'} — {s.total_amount??'—'}</option>)}</select></label><div className="modal-actions"><button className="fa-primary">{t('assets.dispose')}</button><button type="button" className="fa-ghost" onClick={()=>setDisposalForm(false)}>{t('common.cancel')}</button></div></form></SectionCard>}
 <div className="fa-foot fa-foot--actions"><span className="fa-muted">{entries.length>4?t('assets.scrollHint',{count:entries.length}):t('assets.lifecycleActions')}</span><div className="shared-detail-pane__actions">{canApprove&&selected.status==='draft'&&<button className="fa-primary" onClick={()=>void mutate(`/api/assets/${selected.id}/approve`)}>{t('assets.approve')}</button>}{canEdit&&selected.status==='draft'&&<button className="fa-ghost" onClick={()=>setEditForm(true)}>{t('assets.edit')}</button>}{canCancel&&selected.status==='draft'&&<button className="fa-ghost" onClick={()=>{const reason=prompt(t('assets.reason'));if(reason)void mutate(`/api/assets/${selected.id}/cancel`,{reason})}}>{t('assets.cancelDraft')}</button>}{canDispose&&['active','fully_depreciated'].includes(selected.status)&&<button className="fa-ghost" onClick={()=>setDisposalForm(true)}>{t('assets.dispose')}</button>}</div></div></div></DetailPane>}</div></>}
 </section>
}
