import { FormEvent, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatDisplayDate } from '../date-format';
import { Dialog } from './Dialog';
import { PageHeader, StatusBadge, WorkspaceState } from './SharedUI';

type Period={id:string;fiscal_year_id:string;period_start:string;period_end:string;status:'open'|'closed';ready:boolean;blockers:{documents:number;obligations:number;bank_transactions:number;total:number}};
type FiscalYear={id:string;name:string;start_date:string;end_date:string};
interface Props{canView:boolean;canClose:boolean;canReopen:boolean;onUnauthorized:()=>void}
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const response=await fetch(url,{credentials:'same-origin',...options});if(response.status===401)onUnauthorized();if(!response.ok)throw new Error(String(response.status));return response;}

export function MonthlyClose({canView,canClose,canReopen,onUnauthorized}:Props){
 const {t,i18n}=useTranslation();const [periods,setPeriods]=useState<Period[]>([]);const [years,setYears]=useState<FiscalYear[]>([]);const [loading,setLoading]=useState(canView);const [error,setError]=useState(false);const [creating,setCreating]=useState(false);const [reopen,setReopen]=useState<Period|null>(null);const [saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);setError(false);try{const [p,y]=await Promise.all([api('/api/monthly-close-periods',{},onUnauthorized),api('/api/fiscal-years',{},onUnauthorized)]);setPeriods(((await p.json()) as {periods:Period[]}).periods);setYears(((await y.json()) as {fiscalYears:FiscalYear[]}).fiscalYears);}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{if(canView)void load();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);
 if(!canView)return <section className="panel"><WorkspaceState>{t('monthlyClose.noAccess')}</WorkspaceState></section>;
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setSaving(true);try{await api('/api/monthly-close-periods',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fiscal_year_id:data.get('fiscal_year_id'),period_start:data.get('period_start'),period_end:data.get('period_end')})},onUnauthorized);setCreating(false);await load()}catch{setError(true)}finally{setSaving(false)}};
 const close=async(period:Period)=>{setSaving(true);try{await api(`/api/monthly-close-periods/${period.id}/close`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'},onUnauthorized);await load()}catch{setError(true)}finally{setSaving(false)}};
 const submitReopen=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!reopen)return;const reason=String(new FormData(event.currentTarget).get('reason')??'').trim();if(!reason)return;setSaving(true);try{await api(`/api/monthly-close-periods/${reopen.id}/reopen`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason})},onUnauthorized);setReopen(null);await load()}catch{setError(true)}finally{setSaving(false)}};
 return <section className="panel" aria-labelledby="monthly-close-title">
  <PageHeader titleId="monthly-close-title" eyebrow={t('monthlyClose.title')} title={t('monthlyClose.title')} description={t('monthlyClose.description')} action={canClose?<button className="primary" onClick={()=>setCreating(true)}>{t('monthlyClose.create')}</button>:undefined}/>
  {error&&<WorkspaceState tone="error" action={<button onClick={()=>void load()}>{t('common.retry')}</button>}>{t('monthlyClose.error')}</WorkspaceState>}
  {loading?<WorkspaceState>{t('monthlyClose.loading')}</WorkspaceState>:periods.length===0?<WorkspaceState>{t('monthlyClose.empty')}</WorkspaceState>:<div className="fiscal-years-grid">{periods.map(period=><article className={`fiscal-year-card ${period.status}`} key={period.id}><div className="fiscal-year-card-header"><h3>{formatDisplayDate(period.period_start,i18n.language)} — {formatDisplayDate(period.period_end,i18n.language)}</h3><StatusBadge status={period.status}>{t(`monthlyClose.${period.status}`)}</StatusBadge></div><p>{period.ready?t('monthlyClose.ready'):t('monthlyClose.blocked',{count:period.blockers.total})}</p>{!period.ready&&<ul><li>{t('monthlyClose.documents',{count:period.blockers.documents})}</li><li>{t('monthlyClose.obligations',{count:period.blockers.obligations})}</li><li>{t('monthlyClose.transactions',{count:period.blockers.bank_transactions})}</li></ul>}<div className="fiscal-year-actions">{canClose&&period.status==='open'&&<button className="danger" disabled={!period.ready||saving} onClick={()=>void close(period)}>{t('monthlyClose.close')}</button>}{canReopen&&period.status==='closed'&&<button disabled={saving} onClick={()=>setReopen(period)}>{t('monthlyClose.reopen')}</button>}</div></article>)}</div>}
  {creating&&<Dialog title={t('monthlyClose.create')} busy={saving} onClose={()=>setCreating(false)}><form className="form-grid" onSubmit={create}><label>{t('monthlyClose.fiscalYear')}<select name="fiscal_year_id" required>{years.map(year=><option key={year.id} value={year.id}>{year.name}</option>)}</select></label><label>{t('monthlyClose.start')}<input name="period_start" type="date" required/></label><label>{t('monthlyClose.end')}<input name="period_end" type="date" required/></label><div className="modal-actions"><button type="button" onClick={()=>setCreating(false)}>{t('common.cancel')}</button><button className="primary" disabled={saving}>{t('common.save')}</button></div></form></Dialog>}
  {reopen&&<Dialog title={t('monthlyClose.reopen')} busy={saving} onClose={()=>setReopen(null)}><form className="form-grid" onSubmit={submitReopen}><label>{t('monthlyClose.reason')}<textarea name="reason" required maxLength={500}/></label><div className="modal-actions"><button type="button" onClick={()=>setReopen(null)}>{t('common.cancel')}</button><button className="primary" disabled={saving}>{t('monthlyClose.reopen')}</button></div></form></Dialog>}
 </section>;
}
