import { FormEvent, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatDisplayDate } from '../date-format';
import { readQueryParameter, writeQueryParameters } from '../navigation/queryState';
import { Dialog } from './Dialog';
import { PageHeader, SectionCard, StatusBadge, WorkspacePage, WorkspaceState, WorkspaceToolbar } from './SharedUI';

type Blockers={documents:number;obligations:number;bank_transactions:number;vat:number;ledger:number;assets:number;opening_balances:number;periodic_adjustments:number};
type Period={id:string;fiscal_year_id:string;period_start:string;period_end:string;status:'open'|'closed';ready:boolean;blockers:Partial<Blockers>;disclosed_total:number;has_hidden_blockers:boolean};
type FiscalYear={id:string;name:string;start_date:string;end_date:string};
type DestinationPage='documents'|'banks'|'obligations'|'vat'|'accounting'|'assets'|'openingBalances'|'periodicAdjustments';
interface Props{canView:boolean;canViewFiscalYears:boolean;canCreate:boolean;canClose:boolean;canReopen:boolean;viewCapabilities:{documents:boolean;obligations:boolean;bank:boolean;vat:boolean;accounting:boolean;assets:boolean;openingBalances:boolean;periodicAdjustments:boolean};onNavigate?:(page:DestinationPage,parameters:Record<string,string>)=>void;onUnauthorized:()=>void}
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const response=await fetch(url,{credentials:'same-origin',...options});if(response.status===401)onUnauthorized();if(!response.ok)throw new Error(String(response.status));return response;}

export function MonthlyClose({canView,canViewFiscalYears,canCreate,canClose,canReopen,viewCapabilities,onNavigate=()=>undefined,onUnauthorized}:Props){
 const {t,i18n}=useTranslation();
 const [periods,setPeriods]=useState<Period[]>([]),[years,setYears]=useState<FiscalYear[]>([]);
 const [selectedId,setSelectedId]=useState<string|null>(null),[yearFilter,setYearFilter]=useState('');
 const [loading,setLoading]=useState(canView),[error,setError]=useState(false),[creating,setCreating]=useState(false),[reopen,setReopen]=useState<Period|null>(null),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);setError(false);try{const p=await api('/api/monthly-close-periods',{},onUnauthorized);const next=((await p.json()) as {periods:Period[]}).periods;const fiscalYearsUrl=canViewFiscalYears?'/api/fiscal-years':canCreate?'/api/monthly-close-fiscal-years':null;const nextYears=fiscalYearsUrl?((await (await api(fiscalYearsUrl,{},onUnauthorized)).json()) as {fiscalYears:FiscalYear[]}).fiscalYears:[];const requestedYear=readQueryParameter('closeYear');const requestedPeriod=readQueryParameter('closePeriod');const validYear=requestedYear&&(nextYears.some(year=>year.id===requestedYear)||(!canViewFiscalYears&&next.some(period=>period.fiscal_year_id===requestedYear)))?requestedYear:'';const available=validYear?next.filter(period=>period.fiscal_year_id===validYear):next;const restored=requestedPeriod&&available.some(period=>period.id===requestedPeriod)?requestedPeriod:(available[0]?.id??null);setPeriods(next);setYears(nextYears);setYearFilter(validYear);setSelectedId(restored);writeQueryParameters({closeYear:validYear||null,closePeriod:restored},'replace');}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{if(canView)void load();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);
 if(!canView)return <WorkspacePage><WorkspaceState>{t('monthlyClose.noAccess')}</WorkspaceState></WorkspacePage>;
 const availablePeriods=yearFilter?periods.filter(period=>period.fiscal_year_id===yearFilter):periods,selected=periods.find(period=>period.id===selectedId)??null;
 const selectPeriod=(id:string)=>{setSelectedId(id);writeQueryParameters({closePeriod:id});};
 const selectYear=(value:string)=>{const next=(value?periods.find(period=>period.fiscal_year_id===value):periods[0])?.id??null;setYearFilter(value);setSelectedId(next);writeQueryParameters({closeYear:value||null,closePeriod:next});};
 const drill=(page:DestinationPage,parameters:Record<string,string>)=>selected&&onNavigate(page,parameters);
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setSaving(true);try{await api('/api/monthly-close-periods',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fiscal_year_id:data.get('fiscal_year_id'),period_start:data.get('period_start'),period_end:data.get('period_end')})},onUnauthorized);setCreating(false);await load()}catch{setError(true)}finally{setSaving(false)}};
 const close=async(period:Period)=>{setSaving(true);try{await api(`/api/monthly-close-periods/${period.id}/close`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'},onUnauthorized);await load()}catch{setError(true)}finally{setSaving(false)}};
 const submitReopen=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!reopen)return;const reason=String(new FormData(event.currentTarget).get('reason')??'').trim();if(!reason)return;setSaving(true);try{await api(`/api/monthly-close-periods/${reopen.id}/reopen`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason})},onUnauthorized);setReopen(null);await load()}catch{setError(true)}finally{setSaving(false)}};
 const blocker=(allowed:boolean,label:string,count:number|undefined,action:()=>void)=>allowed&&count!==undefined?<li>{count>0?<button type="button" className="monthly-close-blocker-action" onClick={action}><span>{label}</span><span className="monthly-close-blocker-count">{count}</span></button>:<span>{label}: {count}</span>}</li>:null;
 return <WorkspacePage labelledBy="monthly-close-title">
  <PageHeader titleId="monthly-close-title" eyebrow={t('monthlyClose.title')} title={t('monthlyClose.title')} description={t('monthlyClose.description')} action={canCreate?<button className="primary" onClick={()=>setCreating(true)}>{t('monthlyClose.create')}</button>:undefined}/>
  {error&&<WorkspaceState tone="error" action={<button onClick={()=>void load()}>{t('common.retry')}</button>}>{t('monthlyClose.error')}</WorkspaceState>}
  {loading?<WorkspaceState>{t('monthlyClose.loading')}</WorkspaceState>:periods.length===0?<WorkspaceState>{t('monthlyClose.empty')}</WorkspaceState>:<div className="shared-workspace-page__content"><WorkspaceToolbar filters={canViewFiscalYears?<label>{t('monthlyClose.fiscalYear')}<select value={yearFilter} onChange={e=>selectYear(e.target.value)}><option value="">{t('monthlyClose.allYears')}</option>{years.map(year=><option key={year.id} value={year.id}>{year.name}</option>)}</select></label>:undefined}/><div className="shared-compact-periods" aria-label={t('monthlyClose.selectPeriod')}>{availablePeriods.map(period=><button key={period.id} aria-pressed={selectedId===period.id} onClick={()=>selectPeriod(period.id)}>{formatDisplayDate(period.period_start,i18n.language)} — {formatDisplayDate(period.period_end,i18n.language)}</button>)}</div>{selected&&<SectionCard className={`monthly-close-selected ${selected.status}`}><div className="fiscal-year-card-header"><h3>{formatDisplayDate(selected.period_start,i18n.language)} — {formatDisplayDate(selected.period_end,i18n.language)}</h3><StatusBadge status={selected.status}>{t(`monthlyClose.${selected.status}`)}</StatusBadge></div><p><strong>{selected.ready?t('monthlyClose.ready'):selected.has_hidden_blockers?t('monthlyClose.blockedHidden'):t('monthlyClose.blocked',{count:selected.disclosed_total})}</strong></p>{!selected.ready&&<ul className="monthly-close-blockers">
   {blocker(viewCapabilities.documents,t('monthlyClose.documents',{count:selected.blockers.documents}).replace(/:\s*\d+$/,''),selected.blockers.documents,()=>drill('documents',{from:selected.period_start,to:selected.period_end}))}
   {blocker(viewCapabilities.obligations,t('monthlyClose.obligations',{count:selected.blockers.obligations}).replace(/:\s*\d+$/,''),selected.blockers.obligations,()=>drill('obligations',{confirmation:'unconfirmed',recognizedFrom:selected.period_start,recognizedTo:selected.period_end}))}
   {blocker(viewCapabilities.bank,t('monthlyClose.transactions',{count:selected.blockers.bank_transactions}).replace(/:\s*\d+$/,''),selected.blockers.bank_transactions,()=>drill('banks',{section:'transactions',from:selected.period_start,to:selected.period_end}))}
   {blocker(viewCapabilities.vat,t('nav.vat'),selected.blockers.vat,()=>drill('vat',{vatFrom:selected.period_start,vatTo:selected.period_end}))}
   {blocker(viewCapabilities.assets,t('assets.title'),selected.blockers.assets,()=>drill('assets',{assetFrom:selected.period_start,assetTo:selected.period_end}))}
   {blocker(viewCapabilities.openingBalances,t('monthlyClose.openingBalances'),selected.blockers.opening_balances,()=>drill('openingBalances',{fiscalYear:selected.fiscal_year_id}))}
   {blocker(viewCapabilities.periodicAdjustments,t('monthlyClose.periodicAdjustments'),selected.blockers.periodic_adjustments,()=>drill('periodicAdjustments',{adjustmentFrom:selected.period_start,adjustmentTo:selected.period_end}))}
   {blocker(viewCapabilities.accounting,`${t('accounting.title')} / ${t('accounting.tabs.ledger')}`,selected.blockers.ledger,()=>drill('accounting',{accountingTab:'sources',sourceFrom:selected.period_start,sourceTo:selected.period_end}))}
  </ul>}<div className="fiscal-year-actions">{canClose&&selected.status==='open'&&<button className="danger" disabled={!selected.ready||saving} onClick={()=>void close(selected)}>{t('monthlyClose.close')}</button>}{canReopen&&selected.status==='closed'&&<button disabled={saving} onClick={()=>setReopen(selected)}>{t('monthlyClose.reopen')}</button>}</div></SectionCard>}</div>}
  {creating&&<Dialog title={t('monthlyClose.create')} busy={saving} onClose={()=>setCreating(false)}><form className="form-grid" onSubmit={create}><label>{t('monthlyClose.fiscalYear')}<select name="fiscal_year_id" required>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>{t('monthlyClose.start')}<input name="period_start" type="date" required/></label><label>{t('monthlyClose.end')}<input name="period_end" type="date" required/></label><div className="modal-actions"><button type="button" onClick={()=>setCreating(false)}>{t('common.cancel')}</button><button className="primary" disabled={saving}>{t('common.save')}</button></div></form></Dialog>}
  {reopen&&<Dialog title={t('monthlyClose.reopen')} busy={saving} onClose={()=>setReopen(null)}><form className="form-grid" onSubmit={submitReopen}><label>{t('monthlyClose.reason')}<textarea name="reason" required maxLength={500}/></label><div className="modal-actions"><button type="button" onClick={()=>setReopen(null)}>{t('common.cancel')}</button><button className="primary" disabled={saving}>{t('monthlyClose.reopen')}</button></div></form></Dialog>}
 </WorkspacePage>;
}
