import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {Dialog} from './Dialog';

type Counterparty={id:string;name:string;type:string;is_active:boolean;version:number};
type Settlement={id:string;bank_transaction_id:string;amount:string;note:string|null;transaction_date:string;description:string|null};
type Obligation={id:string;direction:'receivable'|'payable';counterparty_id:string;counterparty_name:string;source_type:'document'|'opening_balance'|'manual';original_amount:string;settled_amount:string;remaining_amount:string;recognized_on:string;due_on:string|null;verification_status:'unconfirmed'|'confirmed';state:'open'|'partial'|'settled';is_overdue:boolean;is_cancelled:boolean;document_id:string|null;source_note:string|null;version:number;settlement_history:Settlement[]};
type EligibleDocument={id:string;original_filename:string;total_amount:string};
type Data={obligations:Obligation[];eligible_documents:EligibleDocument[];summary:{open_receivables:string;open_payables:string;unconfirmed_receivables:string;unconfirmed_payables:string;unconfirmed_count:number;partially_settled_count:number;overdue_count:number}};
type BankTransaction={id:string;transaction_date:string;description:string|null;bank_reference:string|null;amount:string;reconciliation_status:string};
type Modal='counterparty'|'obligation'|'settlement'|null;
export function Obligations({canView,canManage,canSettle,canConfirm=false,onUnauthorized}:{canView:boolean;canManage:boolean;canSettle:boolean;canConfirm?:boolean;onUnauthorized:()=>void}){
 const{t}=useTranslation();const[data,setData]=useState<Data|null>(null),[counterparties,setCounterparties]=useState<Counterparty[]>([]),[selected,setSelected]=useState<Obligation|null>(null),[editingParty,setEditingParty]=useState<Counterparty|null>(null),[modal,setModal]=useState<Modal>(null),[creationSource,setCreationSource]=useState<'manual'|'opening_balance'|'document'>('manual'),[direction,setDirection]=useState(''),[state,setState]=useState(''),[party,setParty]=useState(''),[error,setError]=useState(false),[bankTransactions,setBankTransactions]=useState<BankTransaction[]>([]);
 const load=async()=>{const[a,b]=await Promise.all([fetch('/api/obligations'),fetch('/api/counterparties')]);if(a.status===401||b.status===401){onUnauthorized();return;}if(!a.ok||!b.ok)throw Error();const next=await a.json() as Data;setData(next);setCounterparties((await b.json()).counterparties);setSelected(old=>old?next.obligations.find(x=>x.id===old.id)??null:null);};
 useEffect(()=>{if(canView)void load().catch(()=>setError(true));},[canView]);
 const rows=useMemo(()=>(data?.obligations??[]).filter(o=>(!direction||o.direction===direction)&&(!state||o.state===state)&&(!party||o.counterparty_id===party)),[data,direction,state,party]);
 if(!canView)return <section className="panel"><h1>{t('obligations.title')}</h1><p>{t('obligations.noAccess')}</p></section>;
 const send=async(url:string,method:string,body:unknown)=>{const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok){setError(true);return false;}setError(false);setModal(null);await load();return true;};
 const saveCounterparty=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);return send(editingParty?`/api/counterparties/${editingParty.id}`:'/api/counterparties',editingParty?'PATCH':'POST',{name:f.get('name'),type:f.get('type'),...(editingParty?{version:editingParty.version}:{})});};
 const saveObligation=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(selected)return send(`/api/obligations/${selected.id}`,'PATCH',{due_on:f.get('due_on')||null,source_note:f.get('source_note')||null,version:selected.version});const source=String(f.get('source_type'));const documentId=source==='document'?String(f.get('document_id')):null;const document=source==='document'?data?.eligible_documents.find(d=>d.id===documentId):null;return send('/api/obligations','POST',{direction:f.get('direction'),counterparty_id:f.get('counterparty_id'),document_id:documentId,original_amount:document?.total_amount??f.get('original_amount'),recognized_on:f.get('recognized_on'),due_on:f.get('due_on')||null,verification_status:'unconfirmed',source_type:source,source_note:f.get('source_note')||null});};
 const changeVerification=async()=>{if(!selected||!canManage||!canConfirm)return;const next=selected.verification_status==='confirmed'?'unconfirmed':'confirmed';const reason=next==='unconfirmed'?window.prompt(t('obligations.unconfirmReason')):null;if(next==='unconfirmed'&&!reason?.trim())return;await send(`/api/obligations/${selected.id}`,'PATCH',{verification_status:next,version:selected.version,...(reason?{reason:reason.trim()}:{})});};
 const openSettlement=async()=>{if(!selected)return;setError(false);const r=await fetch('/api/bank-transactions');if(r.status===401){onUnauthorized();return;}if(!r.ok){setError(true);return;}const x=await r.json() as {transactions:BankTransaction[]};const used=new Set((data?.obligations??[]).filter(o=>o.source_type!=='document').flatMap(o=>o.settlement_history.map(s=>s.bank_transaction_id)));setBankTransactions(x.transactions.filter(tx=>!used.has(tx.id)&&tx.reconciliation_status==='unmatched'&&(selected.direction==='receivable'?!tx.amount.startsWith('-'):tx.amount.startsWith('-'))));setModal('settlement');};
 const saveSettlement=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);return send(`/api/obligations/${selected!.id}/settlements`,'POST',{bank_transaction_id:f.get('bank_transaction_id'),amount:String(f.get('bank_transaction_id_amount')??''),note:f.get('note')||null});};
 const toggleCounterparty=async(c:Counterparty)=>{await send(`/api/counterparties/${c.id}`,'PATCH',{is_active:!c.is_active,version:c.version});};
 const cancelObligation=async()=>{const reason=window.prompt(t('obligations.reason'));if(reason?.trim()&&selected)await send(`/api/obligations/${selected.id}`,'PATCH',{is_cancelled:true,reason,version:selected.version});};
 const removeSettlement=async(s:Settlement)=>{const reason=window.prompt(t('obligations.reason'));if(reason?.trim()&&selected)await send(`/api/obligations/${selected.id}/settlements/${s.id}`,'DELETE',{reason});};
 return <section className="panel obligations-workspace"><header className="workspace-heading"><div><h1>{t('obligations.title')}</h1><p>{t('obligations.description')}</p></div>{canManage&&<div><button className="primary" onClick={()=>{setEditingParty(null);setModal('counterparty')}}>{t('obligations.createCounterparty')}</button> <button onClick={()=>{setSelected(null);setModal('obligation')}}>{t('obligations.createObligation')}</button></div>}</header>
 {error&&<p role="alert">{t('obligations.error')}</p>}{data&&<><div className="summary-grid"><article><span>{t('obligations.openReceivables')}</span><strong>{data.summary.open_receivables}</strong></article><article><span>{t('obligations.openPayables')}</span><strong>{data.summary.open_payables}</strong></article><article><span>{t('obligations.unconfirmedReceivables')}</span><strong>{data.summary.unconfirmed_receivables}</strong></article><article><span>{t('obligations.unconfirmedPayables')}</span><strong>{data.summary.unconfirmed_payables}</strong></article><article><span>{t('obligations.unconfirmedCount')}</span><strong>{data.summary.unconfirmed_count}</strong></article><article><span>{t('obligations.partialCount')}</span><strong>{data.summary.partially_settled_count}</strong></article><article><span>{t('obligations.overdueCount')}</span><strong>{data.summary.overdue_count}</strong></article></div>
 <div className="filter-row"><label>{t('obligations.direction')}<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="">{t('obligations.all')}</option><option value="receivable">{t('obligations.receivable')}</option><option value="payable">{t('obligations.payable')}</option></select></label><label>{t('obligations.state')}<select value={state} onChange={e=>setState(e.target.value)}><option value="">{t('obligations.all')}</option>{['open','partial','settled'].map(x=><option key={x} value={x}>{t(`obligations.${x}`)}</option>)}</select></label><label>{t('obligations.counterparty')}<select value={party} onChange={e=>setParty(e.target.value)}><option value="">{t('obligations.all')}</option>{counterparties.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
 <div className="responsive-table"><table><thead><tr>{['counterparty','direction','source','original','settledAmount','remaining','due','verification','state'].map(x=><th key={x}>{t(`obligations.${x}`)}</th>)}</tr></thead><tbody>{rows.map(o=><tr key={o.id} onClick={()=>setSelected(o)} tabIndex={0}><td>{o.counterparty_name}</td><td>{t(`obligations.${o.direction}`)}</td><td>{t(`obligations.${o.source_type}`)}</td><td>{o.original_amount}</td><td>{o.settled_amount}</td><td>{o.remaining_amount}</td><td>{o.due_on??t('obligations.unknown')}</td><td>{t(`obligations.${o.verification_status}`)}</td><td>{t(`obligations.${o.state}`)} {o.is_overdue&&<strong>{t('obligations.overdue')}</strong>}</td></tr>)}</tbody></table></div></>}
 {selected&&<aside className="detail-card"><button onClick={()=>setSelected(null)} aria-label={t('common.close')}>×</button><h2>{selected.counterparty_name}</h2><dl><dt>{t('obligations.source')}</dt><dd>{t(`obligations.${selected.source_type}`)}</dd><dt>{t('obligations.recognized')}</dt><dd>{selected.recognized_on}</dd><dt>{t('obligations.due')}</dt><dd>{selected.due_on??t('obligations.unknown')}</dd><dt>{t('obligations.verification')}</dt><dd>{t(`obligations.${selected.verification_status}`)}</dd></dl><h3>{t('obligations.settlementHistory')}</h3>{selected.settlement_history.length===0?<p>{t('obligations.none')}</p>:<ul>{selected.settlement_history.map(s=><li key={s.id}>{s.transaction_date} — {s.amount} {s.description}{canSettle&&<button onClick={()=>void removeSettlement(s)}>{t('obligations.removeSettlement')}</button>}</li>)}</ul>}{canManage&&<button onClick={()=>setModal('obligation')}>{t('obligations.edit')}</button>}{canManage&&canConfirm&&<button onClick={()=>void changeVerification()}>{t(`obligations.${selected.verification_status==='confirmed'?'markUnconfirmed':'confirmAction'}`)}</button>}{canManage&&!selected.is_cancelled&&<button onClick={()=>void cancelObligation()}>{t('obligations.cancel')}</button>}{canSettle&&selected.source_type!=='document'&&!selected.is_cancelled&&<button onClick={()=>void openSettlement()}>{t('obligations.addSettlement')}</button>}</aside>}
 {modal==='counterparty'&&<Dialog title={editingParty?t('obligations.editCounterparty'):t('obligations.createCounterparty')} onClose={()=>setModal(null)}><form onSubmit={e=>void saveCounterparty(e)}><label>{t('obligations.counterparty')}<input name="name" defaultValue={editingParty?.name} required maxLength={200}/></label><label>{t('obligations.type')}<select name="type" defaultValue={editingParty?.type}>{['customer','supplier','government','other'].map(x=><option key={x} value={x}>{t(`obligations.${x}`)}</option>)}</select></label><button type="submit">{t('common.save')}</button></form></Dialog>}
 {modal==='obligation'&&<Dialog title={selected?t('obligations.edit'):t('obligations.createObligation')} onClose={()=>setModal(null)}><form onSubmit={e=>void saveObligation(e)}>{!selected&&<><label>{t('obligations.direction')}<select name="direction"><option value="receivable">{t('obligations.receivable')}</option><option value="payable">{t('obligations.payable')}</option></select></label><label>{t('obligations.counterparty')}<select name="counterparty_id" required>{counterparties.filter(c=>c.is_active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{t('obligations.source')}<select name="source_type" value={creationSource} onChange={e=>setCreationSource(e.target.value as typeof creationSource)}><option value="manual">{t('obligations.manual')}</option><option value="opening_balance">{t('obligations.opening_balance')}</option><option value="document">{t('obligations.document')}</option></select></label>{creationSource==='document'?<label>{t('obligations.eligibleDocument')}<select name="document_id" required>{data?.eligible_documents.map(d=><option key={d.id} value={d.id}>{d.original_filename} — {d.total_amount}</option>)}</select></label>:<label>{t('obligations.original')}<input name="original_amount" inputMode="decimal" required/></label>}<label>{t('obligations.recognized')}<input name="recognized_on" type="date" required/></label></>}<label>{t('obligations.due')}<input name="due_on" type="date" defaultValue={selected?.due_on??''}/></label>{!selected&&<p>{t('obligations.createdUnconfirmed')}</p>}<label>{t('obligations.note')}<textarea name="source_note" maxLength={1000} defaultValue={selected?.source_note??''}/></label><button type="submit">{t('common.save')}</button></form></Dialog>}
 {modal==='settlement'&&selected&&<Dialog title={t('obligations.addSettlement')} onClose={()=>setModal(null)}><form onSubmit={e=>void saveSettlement(e)}><label>{t('obligations.bankTransaction')}<select name="bank_transaction_id" required onChange={e=>{const tx=bankTransactions.find(x=>x.id===e.currentTarget.value);const hidden=e.currentTarget.form?.elements.namedItem('bank_transaction_id_amount') as HTMLInputElement|null;if(hidden)hidden.value=tx?tx.amount.replace('-',''):''}}><option value="">{t('obligations.selectBankTransaction')}</option>{bankTransactions.map(tx=><option key={tx.id} value={tx.id}>{tx.transaction_date} — {tx.description||tx.bank_reference||t('obligations.unknown')} — {tx.amount}</option>)}</select></label><input type="hidden" name="bank_transaction_id_amount"/><label>{t('obligations.note')}<textarea name="note" maxLength={500}/></label><button type="submit">{t('common.save')}</button></form></Dialog>}
 {canManage&&counterparties.length>0&&<div><h2>{t('obligations.counterparties')}</h2>{counterparties.map(c=><button key={c.id} onClick={()=>{setEditingParty(c);setModal('counterparty')}}>{t('obligations.editCounterparty')}: {c.name}</button>)}{counterparties.map(c=><button key={`toggle-${c.id}`} onClick={()=>void toggleCounterparty(c)}>{c.is_active?t('obligations.disableCounterparty'):t('obligations.reactivateCounterparty')}: {c.name}</button>)}</div>}
 </section>;
}
