import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {Dialog} from './Dialog';
import {DataWorkspace,DetailPane,Metric,MetricStrip,PageHeader,StatusBadge,WorkspacePage,WorkspaceState,WorkspaceToolbar} from './SharedUI';
import {clearQueryParameters,readQueryParameter,writeQueryParameters} from '../navigation/queryState';

type Counterparty={id:string;name:string;type:string;is_active:boolean;version:number};
type Settlement={id:string;bank_transaction_id:string;amount:string;note:string|null;transaction_date:string;description:string|null};
type Obligation={id:string;direction:'receivable'|'payable';counterparty_id:string;counterparty_name:string;source_type:'document'|'opening_balance'|'manual';original_amount:string;settled_amount:string;remaining_amount:string;recognized_on:string;due_on:string|null;verification_status:'unconfirmed'|'confirmed';state:'open'|'partial'|'settled';is_overdue:boolean;is_cancelled:boolean;document_id:string|null;original_filename?:string|null;source_note:string|null;version:number;settlement_history:Settlement[]};
type EligibleDocument={id:string;original_filename:string;total_amount:string;counterparty_id:string|null};
type Data={obligations:Obligation[];eligible_documents:EligibleDocument[];summary:{open_receivables:string;open_payables:string;unconfirmed_receivables:string;unconfirmed_payables:string;unconfirmed_count:number;partially_settled_count:number;overdue_count:number}};
type BankTransaction={id:string;transaction_date:string;description:string|null;bank_reference:string|null;amount:string;reconciliation_status:string};
type Modal='counterparties'|'counterparty'|'obligation'|'settlement'|null;
const directions=['receivable','payable'] as const,states=['open','partial','settled'] as const,confirmations=['confirmed','unconfirmed'] as const,sources=['document','non_document'] as const;
const discoveryParameters=['search','direction','state','confirmation','overdue','dueFrom','dueTo','source','counterparty'] as const;
const datePattern=/^\d{4}-(0[1-9]|1[0-2])-([0-2]\d|3[01])$/;
type DiscoveryFilters={search:string;direction:string;state:string;confirmation:string;overdue:string;dueFrom:string;dueTo:string;source:string;counterparty:string};
const validDate=(value:string|null)=>value&&datePattern.test(value)&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value?value:'';
const readFilters=():DiscoveryFilters=>({search:readQueryParameter('search')??'',direction:readQueryParameter('direction',{allowedValues:directions})??'',state:readQueryParameter('state',{allowedValues:states})??'',confirmation:readQueryParameter('confirmation',{allowedValues:confirmations})??'',overdue:readQueryParameter('overdue',{allowedValues:['1']})??'',dueFrom:validDate(readQueryParameter('dueFrom')),dueTo:validDate(readQueryParameter('dueTo')),source:readQueryParameter('source',{allowedValues:sources})??'',counterparty:readQueryParameter('counterparty')??''});
export function Obligations({canView,canManage,canSettle,canConfirm=false,onUnauthorized}:{canView:boolean;canManage:boolean;canSettle:boolean;canConfirm?:boolean;onUnauthorized:()=>void}){
 const{t}=useTranslation();const[data,setData]=useState<Data|null>(null),[counterparties,setCounterparties]=useState<Counterparty[]>([]),[selected,setSelected]=useState<Obligation|null>(null),[editingParty,setEditingParty]=useState<Counterparty|null>(null),[modal,setModal]=useState<Modal>(null),[creationSource,setCreationSource]=useState<'manual'|'opening_balance'|'document'>('manual'),[creationDocumentId,setCreationDocumentId]=useState(''),[filters,setFilters]=useState<DiscoveryFilters>(readFilters),[error,setError]=useState(false),[bankTransactions,setBankTransactions]=useState<BankTransaction[]>([]);
 const load=async()=>{const[a,b]=await Promise.all([fetch('/api/obligations'),fetch('/api/counterparties')]);if(a.status===401||b.status===401){onUnauthorized();return;}if(!a.ok||!b.ok)throw Error();const next=await a.json() as Data;setData(next);setCounterparties((await b.json()).counterparties);setSelected(old=>old?next.obligations.find(x=>x.id===old.id)??null:null);};
 useEffect(()=>{if(canView)void load().catch(()=>setError(true));},[canView]);
 useEffect(()=>{const restore=()=>setFilters(readFilters());window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore)},[]);
 const updateFilter=(name:keyof DiscoveryFilters,value:string)=>{setFilters(current=>({...current,[name]:value}));writeQueryParameters({[name]:value||null},name==='search'?'replace':'push')};
 const clearFilters=()=>{setFilters({search:'',direction:'',state:'',confirmation:'',overdue:'',dueFrom:'',dueTo:'',source:'',counterparty:''});clearQueryParameters(discoveryParameters)};
 const rows=useMemo(()=>{const query=filters.search.trim().toLocaleLowerCase();return(data?.obligations??[]).filter(o=>(!query||[o.counterparty_name,o.id,o.document_id,o.original_filename,o.source_note,o.source_type].some(value=>value?.toLocaleLowerCase().includes(query)))&&(!filters.direction||o.direction===filters.direction)&&(!filters.state||o.state===filters.state)&&(!filters.confirmation||o.verification_status===filters.confirmation)&&(!filters.overdue||(o.is_overdue&&o.due_on!==null&&Number(o.remaining_amount)>0&&o.state!=='settled'&&!o.is_cancelled))&&(!filters.dueFrom||(o.due_on!==null&&o.due_on>=filters.dueFrom))&&(!filters.dueTo||(o.due_on!==null&&o.due_on<=filters.dueTo))&&(!filters.source||(filters.source==='document'?o.source_type==='document':o.source_type!=='document'))&&(!filters.counterparty||!counterparties.some(c=>c.id===filters.counterparty)||o.counterparty_id===filters.counterparty))},[counterparties,data,filters]);const creationDocument=data?.eligible_documents.find(d=>d.id===creationDocumentId&&d.counterparty_id!==null);const creationCounterparty=counterparties.find(c=>c.id===creationDocument?.counterparty_id);
 if(!canView)return <WorkspacePage><WorkspaceState>{t('obligations.noAccess')}</WorkspaceState></WorkspacePage>;
 const send=async(url:string,method:string,body:unknown)=>{const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok){setError(true);return false;}setError(false);setModal(null);await load();return true;};
 const saveCounterparty=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);return send(editingParty?`/api/counterparties/${editingParty.id}`:'/api/counterparties',editingParty?'PATCH':'POST',{name:f.get('name'),type:f.get('type'),...(editingParty?{version:editingParty.version}:{})});};
 const saveObligation=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);if(selected)return send(`/api/obligations/${selected.id}`,'PATCH',{due_on:f.get('due_on')||null,source_note:f.get('source_note')||null,version:selected.version});const source=String(f.get('source_type'));const documentId=source==='document'?String(f.get('document_id')):null;const document=source==='document'?data?.eligible_documents.find(d=>d.id===documentId):null;return send('/api/obligations','POST',{direction:f.get('direction'),counterparty_id:f.get('counterparty_id'),document_id:documentId,original_amount:document?.total_amount??f.get('original_amount'),recognized_on:f.get('recognized_on'),due_on:f.get('due_on')||null,verification_status:'unconfirmed',source_type:source,source_note:f.get('source_note')||null});};
 const changeVerification=async()=>{if(!selected||!canManage||!canConfirm)return;const next=selected.verification_status==='confirmed'?'unconfirmed':'confirmed';const reason=next==='unconfirmed'?window.prompt(t('obligations.unconfirmReason')):null;if(next==='unconfirmed'&&!reason?.trim())return;await send(`/api/obligations/${selected.id}`,'PATCH',{verification_status:next,version:selected.version,...(reason?{reason:reason.trim()}:{})});};
 const openSettlement=async()=>{if(!selected)return;setError(false);const r=await fetch('/api/bank-transactions');if(r.status===401){onUnauthorized();return;}if(!r.ok){setError(true);return;}const x=await r.json() as {transactions:BankTransaction[]};const used=new Set((data?.obligations??[]).filter(o=>o.source_type!=='document').flatMap(o=>o.settlement_history.map(s=>s.bank_transaction_id)));setBankTransactions(x.transactions.filter(tx=>!used.has(tx.id)&&tx.reconciliation_status==='unmatched'&&(selected.direction==='receivable'?!tx.amount.startsWith('-'):tx.amount.startsWith('-'))));setModal('settlement');};
 const saveSettlement=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);return send(`/api/obligations/${selected!.id}/settlements`,'POST',{bank_transaction_id:f.get('bank_transaction_id'),amount:String(f.get('bank_transaction_id_amount')??''),note:f.get('note')||null});};
 const toggleCounterparty=async(c:Counterparty)=>{await send(`/api/counterparties/${c.id}`,'PATCH',{is_active:!c.is_active,version:c.version});};
 const cancelObligation=async()=>{const reason=window.prompt(t('obligations.reason'));if(reason?.trim()&&selected)await send(`/api/obligations/${selected.id}`,'PATCH',{is_cancelled:true,reason,version:selected.version});};
 const removeSettlement=async(s:Settlement)=>{const reason=window.prompt(t('obligations.reason'));if(reason?.trim()&&selected)await send(`/api/obligations/${selected.id}/settlements/${s.id}`,'DELETE',{reason});};
 return <WorkspacePage className="obligations-workspace" labelledBy="obligations-title"><PageHeader titleId="obligations-title" eyebrow={t('obligations.title')} title={t('obligations.title')} description={t('obligations.description')} action={canManage?<button className="primary" onClick={()=>{setSelected(null);setModal('obligation')}}>{t('obligations.createObligation')}</button>:undefined}/>
 {error&&<WorkspaceState tone="error" action={<button onClick={()=>void load()}>{t('common.retry')}</button>}>{t('obligations.error')}</WorkspaceState>}
 {!data?<WorkspaceState>{t('common.loading')}</WorkspaceState>:<div className="shared-workspace-page__content">
  <MetricStrip><Metric label={t('obligations.openReceivables')} value={data.summary.open_receivables}/><Metric label={t('obligations.openPayables')} value={data.summary.open_payables}/><Metric label={t('obligations.unconfirmedCount')} value={data.summary.unconfirmed_count}/><Metric label={t('obligations.overdueCount')} value={data.summary.overdue_count}/><Metric label={t('obligations.partialCount')} value={data.summary.partially_settled_count}/></MetricStrip>
  <WorkspaceToolbar ariaLabel={t('obligations.discoveryToolbar')} search={<label>{t('obligations.search')}<input type="search" value={filters.search} placeholder={t('obligations.searchPlaceholder')} onChange={e=>updateFilter('search',e.target.value)}/></label>} filters={<><label>{t('obligations.direction')}<select value={filters.direction} onChange={e=>updateFilter('direction',e.target.value)}><option value="">{t('obligations.all')}</option>{directions.map(x=><option key={x} value={x}>{t(`obligations.${x}`)}</option>)}</select></label><label>{t('obligations.state')}<select value={filters.state} onChange={e=>updateFilter('state',e.target.value)}><option value="">{t('obligations.all')}</option>{states.map(x=><option key={x} value={x}>{t(`obligations.${x}`)}</option>)}</select></label><label>{t('obligations.confirmation')}<select value={filters.confirmation} onChange={e=>updateFilter('confirmation',e.target.value)}><option value="">{t('obligations.all')}</option>{confirmations.map(x=><option key={x} value={x}>{t(`obligations.${x}`)}</option>)}</select></label><label>{t('obligations.overdueFilter')}<select value={filters.overdue} onChange={e=>updateFilter('overdue',e.target.value)}><option value="">{t('obligations.all')}</option><option value="1">{t('obligations.overdueOnly')}</option></select></label><label>{t('obligations.dueFrom')}<input type="date" value={filters.dueFrom} onChange={e=>updateFilter('dueFrom',e.target.value)}/></label><label>{t('obligations.dueTo')}<input type="date" value={filters.dueTo} onChange={e=>updateFilter('dueTo',e.target.value)}/></label><label>{t('obligations.source')}<select value={filters.source} onChange={e=>updateFilter('source',e.target.value)}><option value="">{t('obligations.allSources')}</option><option value="document">{t('obligations.documentBacked')}</option><option value="non_document">{t('obligations.nonDocument')}</option></select></label><label>{t('obligations.counterparty')}<select value={filters.counterparty} onChange={e=>updateFilter('counterparty',e.target.value)}><option value="">{t('obligations.all')}</option>{counterparties.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>} resultCount={t('obligations.resultCount',{count:rows.length})} clearAction={Object.values(filters).some(Boolean)?<button type="button" onClick={clearFilters}>{t('obligations.clearFilters')}</button>:undefined}/>
  {canManage&&<div className="obligations-secondary-action"><button onClick={()=>setModal('counterparties')}>{t('obligations.manageCounterparties')}</button></div>}
  {data.obligations.length===0?<WorkspaceState kind="empty">{t('obligations.empty')}</WorkspaceState>:rows.length===0?<WorkspaceState kind="no-results" action={<button type="button" onClick={clearFilters}>{t('obligations.clearFilters')}</button>}>{t('obligations.noResults')}</WorkspaceState>:<DataWorkspace withDetail={Boolean(selected)}><div className="responsive-table"><table><thead><tr>{['counterparty','direction','source','original','settledAmount','remaining','due','verification','state'].map(x=><th key={x}>{t(`obligations.${x}`)}</th>)}</tr></thead><tbody>{rows.map(o=><tr key={o.id} onClick={()=>setSelected(o)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(o)}}} tabIndex={0} aria-selected={selected?.id===o.id}><td>{o.counterparty_name}</td><td>{t(`obligations.${o.direction}`)}</td><td>{t(`obligations.${o.source_type}`)}</td><td>{o.original_amount}</td><td>{o.settled_amount}</td><td>{o.remaining_amount}</td><td>{o.due_on??t('obligations.unknown')}</td><td><StatusBadge status={o.verification_status}>{t(`obligations.${o.verification_status}`)}</StatusBadge></td><td>{t(`obligations.${o.state}`)} {o.is_overdue&&<strong>{t('obligations.overdue')}</strong>}</td></tr>)}</tbody></table></div>
  {selected&&<DetailPane label={t('obligations.detail')}><div className="shared-detail-pane__header"><h2>{selected.counterparty_name}</h2><button onClick={()=>setSelected(null)} aria-label={t('common.close')}>×</button></div><dl><dt>{t('obligations.source')}</dt><dd>{t(`obligations.${selected.source_type}`)}</dd><dt>{t('obligations.recognized')}</dt><dd>{selected.recognized_on}</dd><dt>{t('obligations.due')}</dt><dd>{selected.due_on??t('obligations.unknown')}</dd><dt>{t('obligations.verification')}</dt><dd>{t(`obligations.${selected.verification_status}`)}</dd></dl><h3>{t('obligations.settlementHistory')}</h3>{selected.settlement_history.length===0?<p>{t('obligations.none')}</p>:<ul>{selected.settlement_history.map(s=><li key={s.id}>{s.transaction_date} — {s.amount} {s.description}{canSettle&&<button onClick={()=>void removeSettlement(s)}>{t('obligations.removeSettlement')}</button>}</li>)}</ul>}<div className="shared-detail-pane__actions">{canManage&&<button onClick={()=>setModal('obligation')}>{t('obligations.edit')}</button>}{canManage&&canConfirm&&<button onClick={()=>void changeVerification()}>{t(`obligations.${selected.verification_status==='confirmed'?'markUnconfirmed':'confirmAction'}`)}</button>}{canManage&&!selected.is_cancelled&&<button onClick={()=>void cancelObligation()}>{t('obligations.cancel')}</button>}{canSettle&&selected.source_type!=='document'&&!selected.is_cancelled&&<button onClick={()=>void openSettlement()}>{t('obligations.addSettlement')}</button>}</div></DetailPane>}
  </DataWorkspace>}
 </div>}
 {modal==='counterparty'&&<Dialog title={editingParty?t('obligations.editCounterparty'):t('obligations.createCounterparty')} onClose={()=>setModal(null)}><form onSubmit={e=>void saveCounterparty(e)}><label>{t('obligations.counterparty')}<input name="name" defaultValue={editingParty?.name} required maxLength={200}/></label><label>{t('obligations.type')}<select name="type" defaultValue={editingParty?.type}>{['customer','supplier','government','other'].map(x=><option key={x} value={x}>{t(`obligations.${x}`)}</option>)}</select></label><button type="submit">{t('common.save')}</button></form></Dialog>}
 {modal==='obligation'&&<Dialog title={selected?t('obligations.edit'):t('obligations.createObligation')} onClose={()=>setModal(null)}><form onSubmit={e=>void saveObligation(e)}>{!selected&&<><label>{t('obligations.direction')}<select name="direction"><option value="receivable">{t('obligations.receivable')}</option><option value="payable">{t('obligations.payable')}</option></select></label><label>{t('obligations.source')}<select name="source_type" value={creationSource} onChange={e=>{const source=e.target.value as typeof creationSource;setCreationSource(source);if(source!=='document')setCreationDocumentId('')}}><option value="manual">{t('obligations.manual')}</option><option value="opening_balance">{t('obligations.opening_balance')}</option><option value="document">{t('obligations.document')}</option></select></label>{creationSource==='document'?<><label>{t('obligations.eligibleDocument')}<select name="document_id" value={creationDocumentId} onChange={e=>setCreationDocumentId(e.target.value)} required><option value="">{t('obligations.eligibleDocument')}</option>{data?.eligible_documents.filter(d=>d.counterparty_id!==null).map(d=><option key={d.id} value={d.id}>{d.original_filename} — {d.total_amount}</option>)}</select></label><label>{t('obligations.counterparty')}<input value={creationCounterparty?.name??''} readOnly/></label><input type="hidden" name="counterparty_id" value={creationDocument?.counterparty_id??''}/></>:<><label>{t('obligations.counterparty')}<select name="counterparty_id" required>{counterparties.filter(c=>c.is_active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>{t('obligations.original')}<input name="original_amount" inputMode="decimal" required/></label></>}<label>{t('obligations.recognized')}<input name="recognized_on" type="date" required/></label></>}<label>{t('obligations.due')}<input name="due_on" type="date" min={selected?.recognized_on} defaultValue={selected?.due_on??''}/></label>{!selected&&<p>{t('obligations.createdUnconfirmed')}</p>}<label>{t('obligations.note')}<textarea name="source_note" maxLength={1000} defaultValue={selected?.source_note??''}/></label><button type="submit">{t('common.save')}</button></form></Dialog>}
 {modal==='settlement'&&selected&&<Dialog title={t('obligations.addSettlement')} onClose={()=>setModal(null)}><form onSubmit={e=>void saveSettlement(e)}><label>{t('obligations.bankTransaction')}<select name="bank_transaction_id" required onChange={e=>{const tx=bankTransactions.find(x=>x.id===e.currentTarget.value);const hidden=e.currentTarget.form?.elements.namedItem('bank_transaction_id_amount') as HTMLInputElement|null;if(hidden)hidden.value=tx?tx.amount.replace('-',''):''}}><option value="">{t('obligations.selectBankTransaction')}</option>{bankTransactions.map(tx=><option key={tx.id} value={tx.id}>{tx.transaction_date} — {tx.description||tx.bank_reference||t('obligations.unknown')} — {tx.amount}</option>)}</select></label><input type="hidden" name="bank_transaction_id_amount"/><label>{t('obligations.note')}<textarea name="note" maxLength={500}/></label><button type="submit">{t('common.save')}</button></form></Dialog>}
 {modal==='counterparties'&&canManage&&<Dialog title={t('obligations.manageCounterparties')} onClose={()=>setModal(null)}><div className="counterparty-manager"><button className="primary" onClick={()=>{setEditingParty(null);setModal('counterparty')}}>{t('obligations.createCounterparty')}</button>{counterparties.length===0?<WorkspaceState>{t('obligations.noCounterparties')}</WorkspaceState>:<ul>{counterparties.map(c=><li key={c.id}><span><strong>{c.name}</strong><small>{t(`obligations.${c.type}`)} · {c.is_active?t('obligations.active'):t('obligations.inactive')}</small></span><span><button onClick={()=>{setEditingParty(c);setModal('counterparty')}}>{t('obligations.editCounterparty')}</button><button onClick={()=>void toggleCounterparty(c)}>{c.is_active?t('obligations.disableCounterparty'):t('obligations.reactivateCounterparty')}</button></span></li>)}</ul>}</div></Dialog>}
 </WorkspacePage>;
}
