import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatDisplayDate } from '../date-format';
import { readQueryParameter } from '../navigation/queryState';
import { WorkspacePage, WorkspaceState } from './SharedUI';
import { useDateContext } from '../context/DateContext';
import './OpeningBalanceReview.css';

type FiscalYear={id:string;name:string;start_date:string;end_date:string;status:'open'|'closed'};
type Account={id:string;code:string;name:string;account_type:string;is_active:boolean};
type Review={id:string;status:'draft'|'in_review'|'approved';journal_entry_id:string|null};
type Item={id:string;category:string;account_id:string;amount:string;balance_side:'debit'|'credit';source_type:string;source_reference:string|null;confidence:'high'|'medium'|'low';note:string|null};
type Summary={debit:string;credit:string;difference:string;confidence:{high:number;medium:number;low:number}};
type Suggestion={source_id:string;category:string;amount:string;balance_side:'debit'|'credit';label:string;source_type:string;confidence:string;warning?:string};
interface Props{canView:boolean;canCreate:boolean;canEdit:boolean;canDelete:boolean;canSubmit:boolean;canReview:boolean;canApprove:boolean;onUnauthorized:()=>void}
class ApiError extends Error{constructor(readonly status:number,readonly messageText:string){super(messageText)}}
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const r=await fetch(url,{credentials:'same-origin',...options});if(r.status===401){onUnauthorized();throw new ApiError(401,'Unauthorized')}if(!r.ok){let message='Request failed';try{message=((await r.json()) as {error?:string}).error??message}catch{}throw new ApiError(r.status,message)}return r}

const en={title:'Opening Balance Review',description:'Prepare, review and approve the opening position before it becomes the official opening journal.',noAccess:'You do not have permission to view opening balances.',loading:'Loading opening balances…',error:'Unable to load or update opening balances.',fiscalYear:'Fiscal year',asOf:'As of',status:'Status',debit:'Debit',credit:'Credit',difference:'Difference',confidence:'Confidence',high:'High',medium:'Medium',low:'Low',draft:'Draft',in_review:'In review',approved:'Approved',items:'Opening balance items',empty:'No opening balance items yet.',category:'Category',account:'Account',amount:'Amount',side:'Side',source:'Source',reference:'Source reference',note:'Note',add:'Add item',remove:'Remove',submit:'Submit for review',returnDraft:'Return to draft',returnReason:'Reason for returning to draft',approve:'Approve opening balance',suggestions:'System suggestions',suggestionNote:'Suggestions are read-only evidence candidates. They are never added or approved automatically.',noSuggestions:'No system suggestions available.',blocked:'Approval is blocked until debit equals credit and at least two journal lines can be produced.',categories:{bank:'Bank',receivable:'Receivable',payable:'Payable',partner_capital:'Partner capital',partner_current:'Partner current account',partner_loan:'Partner loan',custody_advance:'Custody / advance',vat_tax:'VAT / tax',inventory:'Inventory',fixed_asset_cost:'Fixed asset cost',accumulated_depreciation:'Accumulated depreciation',other_asset:'Other asset',other_liability:'Other liability',equity:'Equity'},sources:{bank_statement:'Bank statement',customer_statement:'Customer statement',supplier_statement:'Supplier statement',official_filing:'Official filing',original_document:'Original document',internal_ledger:'Internal ledger',management_reconciliation:'Management reconciliation',manual_unverified:'Manual / unverified'},balanceState:'Balance state',balanced:'Balanced',unbalanced:'Unbalanced',reviewStatus:'Review status',itemCount:'Opening balance items',registerDesc:'Accounts, sources and confidence of the fiscal-year opening balance.',direction:'Side / direction',unverified:'Unverified',manualShort:'Manual',visibleItems:'Showing',of:'of',itemsWord:'items',confidenceLabel:'Source confidence levels',confidenceNote:'Balance does not mean the sources are reliable.',auditNote:'Source type, verification and confidence are independent fields.',readOnly:'Read-only',suggestedConfidence:'Confidence',suggestedValue:'Suggested value',suggestionScope:'This suggestion is not part of approved items and does not enter the balance totals or item count.',unknownAccount:'Unknown account',totalDebit:'Total debit',totalCredit:'Total credit',select:'Select…'} as const;
const ar={title:'الأرصدة الافتتاحية',description:'إعداد ومراجعة واعتماد الوضع الافتتاحي قبل أن يصبح قيد الافتتاح الرسمي.',noAccess:'ليس لديك صلاحية لعرض الأرصدة الافتتاحية.',loading:'جارٍ تحميل الأرصدة الافتتاحية…',error:'تعذر تحميل أو تحديث الأرصدة الافتتاحية.',fiscalYear:'السنة المالية',asOf:'كما في',status:'الحالة',debit:'مدين',credit:'دائن',difference:'الفرق',confidence:'الثقة',high:'عالية',medium:'متوسطة',low:'منخفضة',draft:'مسودة',in_review:'قيد المراجعة',approved:'معتمد',items:'بنود الرصيد الافتتاحي',empty:'لا توجد بنود أرصدة افتتاحية حتى الآن.',category:'التصنيف',account:'الحساب',amount:'المبلغ',side:'الطرف',source:'المصدر',reference:'مرجع المصدر',note:'ملاحظة',add:'إضافة بند',remove:'حذف',submit:'إرسال للمراجعة',returnDraft:'إرجاع إلى المسودة',returnReason:'سبب الإرجاع إلى المسودة',approve:'اعتماد الرصيد الافتتاحي',suggestions:'اقتراحات النظام',suggestionNote:'الاقتراحات أدلة مرشحة للقراءة فقط، ولا تضاف أو تعتمد تلقائياً.',noSuggestions:'لا توجد اقتراحات من النظام.',blocked:'الاعتماد متوقف حتى يتساوى المدين والدائن ويمكن إنتاج سطرين محاسبيين على الأقل.',categories:{bank:'البنوك',receivable:'الذمم المدينة',payable:'الذمم الدائنة',partner_capital:'رأس مال الشركاء',partner_current:'جاري الشركاء',partner_loan:'قروض الشركاء',custody_advance:'العهد والسلف',vat_tax:'الزكاة/الضريبة/القيمة المضافة',inventory:'المخزون',fixed_asset_cost:'تكلفة الأصول الثابتة',accumulated_depreciation:'مجمع الإهلاك',other_asset:'أصول أخرى',other_liability:'التزامات أخرى',equity:'حقوق الملكية'},sources:{bank_statement:'كشف بنكي',customer_statement:'كشف عميل',supplier_statement:'كشف مورد',official_filing:'إقرار/قائمة رسمية',original_document:'مستند أصلي',internal_ledger:'دفتر داخلي',management_reconciliation:'تسوية إدارية',manual_unverified:'يدوي / غير متحقق'},balanceState:'حالة التوازن',balanced:'متوازن',unbalanced:'غير متوازن',reviewStatus:'حالة المراجعة',itemCount:'عدد بنود الرصيد',registerDesc:'الحسابات والمصادر ومستوى الثقة للسنة المالية ومراجعها.',direction:'الطرف / الاتجاه',unverified:'غير متحقق',manualShort:'يدوي',visibleItems:'عرض',of:'من',itemsWord:'بند',confidenceLabel:'مستوى الثقة في مصادر البنود',confidenceNote:'التوازن لا يعني موثوقية المصدر.',auditNote:'نوع المصدر وحالة التحقق ومستوى الثقة حقول مستقلة.',readOnly:'للقراءة فقط',suggestedConfidence:'مستوى الثقة',suggestedValue:'القيمة المقترحة',suggestionScope:'هذا الاقتراح ليس ضمن البنود المعتمدة، ولا يدخل في إجمالي الرصيد أو عدد البنود.',unknownAccount:'حساب غير معروف',totalDebit:'إجمالي المدين',totalCredit:'إجمالي الدائن',select:'اختر…'} as const;
const groupThousands=(v:string)=>{const m=/^(-?)(\d+)(\.\d+)?$/.exec(v);return m?`${m[1]}${m[2].replace(/\B(?=(\d{3})+(?!\d))/g,',')}${m[3]??''}`:v};
const categories=Object.keys(en.categories) as Array<keyof typeof en.categories>;
const sources=Object.keys(en.sources) as Array<keyof typeof en.sources>;

export function OpeningBalanceReview({canView,canCreate,canDelete,canSubmit,canReview,canApprove,onUnauthorized}:Props){
 const {i18n}=useTranslation();const l=i18n.language==='ar'?ar:en;
 const { selectedFiscalYearId } = useDateContext();
 const [years,setYears]=useState<FiscalYear[]>([]);const [yearId,setYearId]=useState('');const [accounts,setAccounts]=useState<Account[]>([]);const [review,setReview]=useState<Review|null>(null);const [items,setItems]=useState<Item[]>([]);const [summary,setSummary]=useState<Summary>({debit:'0.00',credit:'0.00',difference:'0.00',confidence:{high:0,medium:0,low:0}});const [suggestions,setSuggestions]=useState<Suggestion[]>([]);const [loading,setLoading]=useState(canView);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [returnReason,setReturnReason]=useState('');
 const yearRequest=useRef(0);
 const activeAccounts=useMemo(()=>accounts.filter(x=>x.is_active),[accounts]);
 const loadBase=async()=>{setLoading(true);setError(null);try{const [fyRes,accRes]=await Promise.all([api('/api/fiscal-years',{},onUnauthorized),api('/api/accounts',{},onUnauthorized)]);const fy=(await fyRes.json()) as {fiscalYears:FiscalYear[]};const acc=(await accRes.json()) as {accounts:Account[]};const requestedYear=readQueryParameter('fiscalYear');setYears(fy.fiscalYears);setAccounts(acc.accounts);setYearId(current=>current||(requestedYear&&fy.fiscalYears.some(x=>x.id===requestedYear)?requestedYear:'')||selectedFiscalYearId||fy.fiscalYears.find(x=>x.status==='open')?.id||fy.fiscalYears[0]?.id||'')}catch(e){if(!(e instanceof ApiError&&e.status===401))setError(e instanceof Error?e.message:l.error)}finally{setLoading(false)}};
 const loadYear=async(id:string,keepError=false)=>{if(!id)return;const request=++yearRequest.current;const current=()=>request===yearRequest.current;setLoading(true);if(!keepError)setError(null);try{const [r,s]=await Promise.all([api(`/api/opening-balances/${id}`,{},onUnauthorized),api(`/api/opening-balances/${id}/suggestions`,{},onUnauthorized)]);const body=await r.json() as {review:Review|null;items:Item[];summary:Summary};const sug=await s.json() as {suggestions:Suggestion[]};if(!current())return;setReview(body.review);setItems(body.items);setSummary(body.summary);setSuggestions(sug.suggestions);if(body.review?.status!=='in_review')setReturnReason('')}catch(e){if(current()&&!(e instanceof ApiError&&e.status===401))setError(e instanceof Error?e.message:l.error)}finally{if(current())setLoading(false)}};
 const resetYear=()=>{yearRequest.current++;setReview(null);setItems([]);setSummary({debit:'0.00',credit:'0.00',difference:'0.00',confidence:{high:0,medium:0,low:0}});setSuggestions([]);setReturnReason('');setError(null)};
 useEffect(()=>{if(canView)void loadBase();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView, selectedFiscalYearId]);
 useEffect(()=>{if(yearId)void loadYear(yearId);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[yearId]);
 if(!canView)return <WorkspacePage><WorkspaceState>{l.noAccess}</WorkspaceState></WorkspacePage>;
 const selectedYear=years.find(x=>x.id===yearId);
 const mutate=async(url:string,method='POST',body?:unknown)=>{setBusy(true);setError(null);try{await api(url,{method,headers:body===undefined?undefined:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)},onUnauthorized);await loadYear(yearId);return true}catch(e){if(!(e instanceof ApiError&&e.status===401)){setError(e instanceof Error?e.message:l.error);if(!(e instanceof ApiError)||e.status===409)await loadYear(yearId,true)}return false}finally{setBusy(false)}};
 const add=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const d=new FormData(form);const ok=await mutate(`/api/opening-balances/${yearId}/items`,'POST',{category:String(d.get('category')),account_id:String(d.get('account_id')),amount:String(d.get('amount')),balance_side:String(d.get('balance_side')),source_type:String(d.get('source_type')),source_reference:String(d.get('source_reference')||'')||null,confidence:String(d.get('confidence')),note:String(d.get('note')||'')||null});if(ok)form.reset()};
 const status=review?.status??'draft';const balanced=/^-?0+(?:\.0+)?$/.test(summary.difference)&&items.length>=2;
 const bd=(v:string)=><bdi dir="ltr">{v}</bdi>;
 const money=(v:string)=>bd(groupThousands(v));
 const tone=(c:string)=>c==='high'?'ok':c==='medium'?'warn':'low';
 const statusTone=status==='approved'?'ok':status==='in_review'?'warn':'neutral';
 const accountLabel=(id:string)=>{const a=accounts.find(y=>y.id===id);return a?<><bdi dir="ltr">{a.code}</bdi> — {a.name}</>:l.unknownAccount};
 const canRemove=canDelete&&status==='draft';
 return <WorkspacePage className="opening-balance-view" labelledBy="opening-balance-title" size="operational">
  <header className="ob-header"><h2 id="opening-balance-title">{l.title}</h2><p>{l.description}</p></header>
  <section className="ob-card ob-context" aria-label={l.fiscalYear}>
   <div className="ob-context__year"><label className="ob-context__label" htmlFor="ob-year">{l.fiscalYear}</label><select id="ob-year" value={yearId} disabled={busy} onChange={e=>{resetYear();setYearId(e.target.value)}}>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select>{selectedYear&&<><span className="ob-divider" aria-hidden="true"/><span className="ob-context__asof"><span className="ob-muted">{l.asOf}</span> <bdi dir="rtl">{formatDisplayDate(selectedYear.start_date,i18n.language)}</bdi></span></>}</div>
   <div className="ob-context__status"><span className="ob-muted">{l.reviewStatus}</span><span className={`ob-badge ob-badge--${statusTone}`}>{l[status]}</span><span className="ob-sr">{l.status}</span></div>
  </section>
  <section className="ob-card ob-summary" aria-label={l.difference}>
   <dl>
    <div><dt>{l.totalDebit}</dt><dd className="ob-amount">{money(summary.debit)}</dd><span className="ob-sr">{l.debit}</span></div>
    <div><dt>{l.totalCredit}</dt><dd className="ob-amount">{money(summary.credit)}</dd><span className="ob-sr">{l.credit}</span></div>
    <div><dt>{l.difference}</dt><dd className={`ob-amount ${balanced?'ob-amount--ok':'ob-amount--warn'}`}>{money(summary.difference)}</dd></div>
    <div><dt>{l.balanceState}</dt><dd><span className={`ob-badge ob-badge--${balanced?'ok':'warn'}`}>{balanced?l.balanced:l.unbalanced}</span></dd></div>
   </dl>
  </section>
  <section className="ob-card ob-confidence" aria-label={l.confidenceLabel}>
   <strong>{l.confidenceLabel}</strong>
   <ul><li className="ob-conf--low"><bdi dir="ltr">{summary.confidence.low}</bdi> {l.low}</li><li><bdi dir="ltr">{summary.confidence.medium}</bdi> {l.medium}</li><li className="ob-conf--high"><bdi dir="ltr">{summary.confidence.high}</bdi> {l.high}</li></ul>
   <span className="ob-muted">{l.confidenceNote}</span>
  </section>
  {error&&<WorkspaceState tone="error" action={<button onClick={()=>void loadYear(yearId)}>{l.error}</button>}>{error}</WorkspaceState>}
  {loading?<WorkspaceState>{l.loading}</WorkspaceState>:<>
   <section className="ob-card ob-register" aria-labelledby="ob-register-title">
    <div className="ob-register__head"><div><h3 id="ob-register-title">{l.items}</h3><p className="ob-muted">{selectedYear?`${l.registerDesc} ${selectedYear.name}`:l.registerDesc}</p></div><span className="ob-muted">{l.itemCount}: <bdi dir="ltr">{items.length}</bdi></span></div>
    {items.length===0?<WorkspaceState kind="empty">{l.empty}</WorkspaceState>:<div className="table-wrap ob-table"><table><thead><tr><th>{l.category}</th><th>{l.account}</th><th>{l.amount}</th><th>{l.direction}</th><th>{l.source}</th><th>{l.confidence}</th><th>{l.reference}</th><th>{l.note}</th>{canRemove&&<th/>}</tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{l.categories[x.category as keyof typeof l.categories]??x.category}</td><td>{accountLabel(x.account_id)}</td><td className="ob-num">{money(x.amount)}</td><td>{x.balance_side==='debit'?l.debit:l.credit}</td><td><span>{x.source_type==='manual_unverified'?l.manualShort:l.sources[x.source_type as keyof typeof l.sources]??x.source_type}</span>{x.source_type==='manual_unverified'&&<span className="ob-badge ob-badge--warn">{l.unverified}</span>}</td><td><span className={`ob-badge ob-badge--${tone(x.confidence)}`}>{l[x.confidence]}</span></td><td>{x.source_reference?bd(x.source_reference):'—'}</td><td>{x.note??'—'}</td>{canRemove&&<td><button disabled={busy} onClick={()=>void mutate(`/api/opening-balances/${yearId}/items/${x.id}`,'DELETE')}>{l.remove}</button></td>}</tr>)}</tbody></table></div>}
    <div className="ob-register__foot ob-muted"><span>{l.auditNote}</span><span>{l.visibleItems} <bdi dir="ltr">{items.length}</bdi> {l.of} <bdi dir="ltr">{items.length}</bdi> {l.itemsWord}</span></div>
   </section>
   {canCreate&&status==='draft'&&<section className="ob-card ob-form"><h3>{l.add}</h3><form className="form-grid" onSubmit={add}><label>{l.category}<select name="category" required defaultValue=""><option value="" disabled>{l.select}</option>{categories.map(x=><option key={x} value={x}>{l.categories[x]}</option>)}</select></label><label>{l.account}<select name="account_id" required defaultValue=""><option value="" disabled>{l.select}</option>{activeAccounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>{l.amount}<input name="amount" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" required/></label><label>{l.side}<select name="balance_side" defaultValue="debit"><option value="debit">{l.debit}</option><option value="credit">{l.credit}</option></select></label><label>{l.source}<select name="source_type" defaultValue="manual_unverified">{sources.map(x=><option key={x} value={x}>{l.sources[x]}</option>)}</select></label><label>{l.confidence}<select name="confidence" defaultValue="low"><option value="high">{l.high}</option><option value="medium">{l.medium}</option><option value="low">{l.low}</option></select></label><label>{l.reference}<input name="source_reference" maxLength={500}/></label><label>{l.note}<textarea name="note" maxLength={1000}/></label><button className="primary" type="submit" disabled={busy}>{l.add}</button></form></section>}
   <section className="ob-card ob-suggestions" aria-labelledby="ob-sug-title">
    <div className="ob-sug__head"><h3 id="ob-sug-title">{l.suggestions}</h3><span className="ob-badge ob-badge--neutral">{l.readOnly}</span></div>
    <p className="ob-rule">{l.suggestionNote}</p>
    {suggestions.length===0?<WorkspaceState kind="empty">{l.noSuggestions}</WorkspaceState>:<ul className="ob-sug__list">{suggestions.map((s,i)=><li key={`${s.source_id}-${i}`}><div className="ob-sug__title"><strong>{s.label}</strong><span className="ob-muted">{l.categories[s.category as keyof typeof l.categories]??s.category}</span></div><div><span className="ob-muted">{l.suggestedValue}</span><span className="ob-amount ob-amount--sm">{money(s.amount)}</span></div><div><span className="ob-muted">{l.direction}</span><span>{s.balance_side==='debit'?l.debit:l.credit}</span></div><div><span className="ob-muted">{l.suggestedConfidence}</span><span className={`ob-badge ob-badge--${tone(s.confidence)}`}>{(l as Record<string,unknown>)[s.confidence] as string??s.confidence}</span></div>{s.warning&&<p className="ob-sug__warn">{s.warning}</p>}</li>)}</ul>}
    <p className="ob-muted">{l.suggestionScope}</p>
   </section>
   {!balanced&&status!=='approved'&&<WorkspaceState>{l.blocked}</WorkspaceState>}
   <div className="modal-actions ob-actions">{canSubmit&&status==='draft'&&items.length>0&&<button className="primary" disabled={busy} onClick={()=>void mutate(`/api/opening-balances/${yearId}/submit-review`)}>{l.submit}</button>}{canReview&&status==='in_review'&&<><label>{l.returnReason}<textarea aria-label={l.returnReason} value={returnReason} onChange={e=>setReturnReason(e.target.value)} maxLength={1000}/></label><button disabled={busy||!returnReason.trim()} onClick={()=>void mutate(`/api/opening-balances/${yearId}/return-to-draft`,'POST',{reason:returnReason.trim()})}>{l.returnDraft}</button></>}{canApprove&&status==='in_review'&&<button className="primary" disabled={busy||!balanced} onClick={()=>void mutate(`/api/opening-balances/${yearId}/approve`)}>{l.approve}</button>}</div>
  </>}
 </WorkspacePage>;
}
