import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatDisplayDate } from '../date-format';
import { readQueryParameter } from '../navigation/queryState';
import { Metric, MetricStrip, PageHeader, SectionCard, StatusBadge, WorkspacePage, WorkspaceState } from './SharedUI';

type FiscalYear={id:string;name:string;start_date:string;end_date:string;status:'open'|'closed'};
type Account={id:string;code:string;name:string;account_type:string;is_active:boolean};
type Review={id:string;status:'draft'|'in_review'|'approved';journal_entry_id:string|null};
type Item={id:string;category:string;account_id:string;amount:string;balance_side:'debit'|'credit';source_type:string;source_reference:string|null;confidence:'high'|'medium'|'low';note:string|null};
type Summary={debit:string;credit:string;difference:string;confidence:{high:number;medium:number;low:number}};
type Suggestion={source_id:string;category:string;amount:string;balance_side:'debit'|'credit';label:string;source_type:string;confidence:string;warning?:string};
interface Props{canView:boolean;canCreate:boolean;canEdit:boolean;canDelete:boolean;canSubmit:boolean;canReview:boolean;canApprove:boolean;onUnauthorized:()=>void}
class ApiError extends Error{constructor(readonly status:number,readonly messageText:string){super(messageText)}}
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const r=await fetch(url,{credentials:'same-origin',...options});if(r.status===401){onUnauthorized();throw new ApiError(401,'Unauthorized')}if(!r.ok){let message='Request failed';try{message=((await r.json()) as {error?:string}).error??message}catch{}throw new ApiError(r.status,message)}return r}

const en={title:'Opening Balance Review',description:'Prepare, review and approve the opening position before it becomes the official opening journal.',noAccess:'You do not have permission to view opening balances.',loading:'Loading opening balances…',error:'Unable to load or update opening balances.',fiscalYear:'Fiscal year',asOf:'As of',status:'Status',debit:'Debit',credit:'Credit',difference:'Difference',confidence:'Confidence',high:'High',medium:'Medium',low:'Low',draft:'Draft',in_review:'In review',approved:'Approved',items:'Opening balance items',empty:'No opening balance items yet.',category:'Category',account:'Account',amount:'Amount',side:'Side',source:'Source',reference:'Source reference',note:'Note',add:'Add item',remove:'Remove',submit:'Submit for review',returnDraft:'Return to draft',returnReason:'Reason for returning to draft',approve:'Approve opening balance',suggestions:'System suggestions',suggestionNote:'Suggestions are read-only evidence candidates. They are never added or approved automatically.',noSuggestions:'No system suggestions available.',blocked:'Approval is blocked until debit equals credit and at least two journal lines can be produced.',categories:{bank:'Bank',receivable:'Receivable',payable:'Payable',partner_capital:'Partner capital',partner_current:'Partner current account',partner_loan:'Partner loan',custody_advance:'Custody / advance',vat_tax:'VAT / tax',inventory:'Inventory',fixed_asset_cost:'Fixed asset cost',accumulated_depreciation:'Accumulated depreciation',other_asset:'Other asset',other_liability:'Other liability',equity:'Equity'},sources:{bank_statement:'Bank statement',customer_statement:'Customer statement',supplier_statement:'Supplier statement',official_filing:'Official filing',original_document:'Original document',internal_ledger:'Internal ledger',management_reconciliation:'Management reconciliation',manual_unverified:'Manual / unverified'},select:'Select…'} as const;
const ar={title:'مراجعة الأرصدة الافتتاحية',description:'إعداد ومراجعة واعتماد الوضع الافتتاحي قبل أن يصبح قيد الافتتاح الرسمي.',noAccess:'ليس لديك صلاحية لعرض الأرصدة الافتتاحية.',loading:'جارٍ تحميل الأرصدة الافتتاحية…',error:'تعذر تحميل أو تحديث الأرصدة الافتتاحية.',fiscalYear:'السنة المالية',asOf:'كما في',status:'الحالة',debit:'مدين',credit:'دائن',difference:'الفرق',confidence:'الثقة',high:'عالية',medium:'متوسطة',low:'منخفضة',draft:'مسودة',in_review:'قيد المراجعة',approved:'معتمد',items:'بنود الرصيد الافتتاحي',empty:'لا توجد بنود أرصدة افتتاحية حتى الآن.',category:'التصنيف',account:'الحساب',amount:'المبلغ',side:'الطرف',source:'المصدر',reference:'مرجع المصدر',note:'ملاحظة',add:'إضافة بند',remove:'حذف',submit:'إرسال للمراجعة',returnDraft:'إرجاع إلى المسودة',returnReason:'سبب الإرجاع إلى المسودة',approve:'اعتماد الرصيد الافتتاحي',suggestions:'اقتراحات النظام',suggestionNote:'الاقتراحات أدلة مرشحة للقراءة فقط، ولا تضاف أو تعتمد تلقائياً.',noSuggestions:'لا توجد اقتراحات من النظام.',blocked:'الاعتماد متوقف حتى يتساوى المدين والدائن ويمكن إنتاج سطرين محاسبيين على الأقل.',categories:{bank:'البنوك',receivable:'الذمم المدينة',payable:'الذمم الدائنة',partner_capital:'رأس مال الشركاء',partner_current:'جاري الشركاء',partner_loan:'قروض الشركاء',custody_advance:'العهد والسلف',vat_tax:'الزكاة/الضريبة/القيمة المضافة',inventory:'المخزون',fixed_asset_cost:'تكلفة الأصول الثابتة',accumulated_depreciation:'مجمع الإهلاك',other_asset:'أصول أخرى',other_liability:'التزامات أخرى',equity:'حقوق الملكية'},sources:{bank_statement:'كشف بنكي',customer_statement:'كشف عميل',supplier_statement:'كشف مورد',official_filing:'إقرار/قائمة رسمية',original_document:'مستند أصلي',internal_ledger:'دفتر داخلي',management_reconciliation:'تسوية إدارية',manual_unverified:'يدوي / غير متحقق'},select:'اختر…'} as const;
const categories=Object.keys(en.categories) as Array<keyof typeof en.categories>;
const sources=Object.keys(en.sources) as Array<keyof typeof en.sources>;

export function OpeningBalanceReview({canView,canCreate,canDelete,canSubmit,canReview,canApprove,onUnauthorized}:Props){
 const {i18n}=useTranslation();const l=i18n.language==='ar'?ar:en;
 const [years,setYears]=useState<FiscalYear[]>([]);const [yearId,setYearId]=useState('');const [accounts,setAccounts]=useState<Account[]>([]);const [review,setReview]=useState<Review|null>(null);const [items,setItems]=useState<Item[]>([]);const [summary,setSummary]=useState<Summary>({debit:'0.00',credit:'0.00',difference:'0.00',confidence:{high:0,medium:0,low:0}});const [suggestions,setSuggestions]=useState<Suggestion[]>([]);const [loading,setLoading]=useState(canView);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [returnReason,setReturnReason]=useState('');
 const activeAccounts=useMemo(()=>accounts.filter(x=>x.is_active),[accounts]);
 const loadBase=async()=>{setLoading(true);setError(null);try{const [fyRes,accRes]=await Promise.all([api('/api/fiscal-years',{},onUnauthorized),api('/api/accounts',{},onUnauthorized)]);const fy=(await fyRes.json()) as {fiscalYears:FiscalYear[]};const acc=(await accRes.json()) as {accounts:Account[]};const requestedYear=readQueryParameter('fiscalYear');setYears(fy.fiscalYears);setAccounts(acc.accounts);setYearId(current=>current||(requestedYear&&fy.fiscalYears.some(x=>x.id===requestedYear)?requestedYear:'')||fy.fiscalYears.find(x=>x.status==='open')?.id||fy.fiscalYears[0]?.id||'')}catch(e){if(!(e instanceof ApiError&&e.status===401))setError(e instanceof Error?e.message:l.error)}finally{setLoading(false)}};
 const loadYear=async(id:string)=>{if(!id)return;setLoading(true);setError(null);try{const [r,s]=await Promise.all([api(`/api/opening-balances/${id}`,{},onUnauthorized),api(`/api/opening-balances/${id}/suggestions`,{},onUnauthorized)]);const body=await r.json() as {review:Review|null;items:Item[];summary:Summary};const sug=await s.json() as {suggestions:Suggestion[]};setReview(body.review);setItems(body.items);setSummary(body.summary);setSuggestions(sug.suggestions);if(body.review?.status!=='in_review')setReturnReason('')}catch(e){if(!(e instanceof ApiError&&e.status===401))setError(e instanceof Error?e.message:l.error)}finally{setLoading(false)}};
 useEffect(()=>{if(canView)void loadBase();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);
 useEffect(()=>{if(yearId)void loadYear(yearId);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[yearId]);
 if(!canView)return <WorkspacePage><WorkspaceState>{l.noAccess}</WorkspaceState></WorkspacePage>;
 const selectedYear=years.find(x=>x.id===yearId);
 const mutate=async(url:string,method='POST',body?:unknown)=>{setBusy(true);setError(null);try{await api(url,{method,headers:body===undefined?undefined:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)},onUnauthorized);await loadYear(yearId);return true}catch(e){if(!(e instanceof ApiError&&e.status===401))setError(e instanceof Error?e.message:l.error);return false}finally{setBusy(false)}};
 const add=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const d=new FormData(form);const ok=await mutate(`/api/opening-balances/${yearId}/items`,'POST',{category:String(d.get('category')),account_id:String(d.get('account_id')),amount:String(d.get('amount')),balance_side:String(d.get('balance_side')),source_type:String(d.get('source_type')),source_reference:String(d.get('source_reference')||'')||null,confidence:String(d.get('confidence')),note:String(d.get('note')||'')||null});if(ok)form.reset()};
 const status=review?.status??'draft';const balanced=/^-?0+(?:\.0+)?$/.test(summary.difference)&&items.length>=2;
 return <WorkspacePage labelledBy="opening-balance-title" size="operational">
  <PageHeader titleId="opening-balance-title" eyebrow={l.title} title={l.title} description={l.description}/>
  <div className="form-grid"><label>{l.fiscalYear}<select value={yearId} onChange={e=>setYearId(e.target.value)}>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label>{selectedYear&&<p><strong>{l.asOf}:</strong> {formatDisplayDate(selectedYear.start_date,i18n.language)}</p>}<p><strong>{l.status}:</strong> <StatusBadge status={status}>{l[status]}</StatusBadge></p></div>
  <MetricStrip><Metric label={l.debit} value={summary.debit}/><Metric label={l.credit} value={summary.credit}/><Metric label={l.difference} value={summary.difference}/><Metric label={`${l.confidence} · ${l.high}/${l.medium}/${l.low}`} value={`${summary.confidence.high}/${summary.confidence.medium}/${summary.confidence.low}`}/></MetricStrip>
  {error&&<WorkspaceState tone="error" action={<button onClick={()=>void loadYear(yearId)}>{l.error}</button>}>{error}</WorkspaceState>}
  {loading?<WorkspaceState>{l.loading}</WorkspaceState>:<>
   <SectionCard><h3>{l.items}</h3>{items.length===0?<WorkspaceState kind="empty">{l.empty}</WorkspaceState>:<div className="table-wrap"><table><thead><tr><th>{l.category}</th><th>{l.account}</th><th>{l.amount}</th><th>{l.side}</th><th>{l.source}</th><th>{l.confidence}</th><th>{l.reference}</th><th>{l.note}</th>{canDelete&&status==='draft'&&<th/>}</tr></thead><tbody>{items.map(x=>{const a=accounts.find(y=>y.id===x.account_id);return <tr key={x.id}><td>{l.categories[x.category as keyof typeof l.categories]??x.category}</td><td>{a?`${a.code} — ${a.name}`:x.account_id}</td><td>{x.amount}</td><td>{x.balance_side==='debit'?l.debit:l.credit}</td><td>{l.sources[x.source_type as keyof typeof l.sources]??x.source_type}</td><td>{l[x.confidence]}</td><td>{x.source_reference??'—'}</td><td>{x.note??'—'}</td>{canDelete&&status==='draft'&&<td><button disabled={busy} onClick={()=>void mutate(`/api/opening-balances/${yearId}/items/${x.id}`,'DELETE')}>{l.remove}</button></td>}</tr>})}</tbody></table></div>}</SectionCard>
   {canCreate&&status==='draft'&&<SectionCard><h3>{l.add}</h3><form className="form-grid" onSubmit={add}><label>{l.category}<select name="category" required defaultValue=""><option value="" disabled>{l.select}</option>{categories.map(x=><option key={x} value={x}>{l.categories[x]}</option>)}</select></label><label>{l.account}<select name="account_id" required defaultValue=""><option value="" disabled>{l.select}</option>{activeAccounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label><label>{l.amount}<input name="amount" inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" required/></label><label>{l.side}<select name="balance_side" defaultValue="debit"><option value="debit">{l.debit}</option><option value="credit">{l.credit}</option></select></label><label>{l.source}<select name="source_type" defaultValue="manual_unverified">{sources.map(x=><option key={x} value={x}>{l.sources[x]}</option>)}</select></label><label>{l.confidence}<select name="confidence" defaultValue="low"><option value="high">{l.high}</option><option value="medium">{l.medium}</option><option value="low">{l.low}</option></select></label><label>{l.reference}<input name="source_reference" maxLength={500}/></label><label>{l.note}<textarea name="note" maxLength={1000}/></label><button className="primary" type="submit" disabled={busy}>{l.add}</button></form></SectionCard>}
   <SectionCard><h3>{l.suggestions}</h3><p>{l.suggestionNote}</p>{suggestions.length===0?<WorkspaceState kind="empty">{l.noSuggestions}</WorkspaceState>:<ul>{suggestions.map((s,i)=><li key={`${s.source_id}-${i}`}><strong>{s.label}</strong> — {s.category} — {s.amount} — {s.balance_side} — {s.confidence}{s.warning?` — ${s.warning}`:''}</li>)}</ul>}</SectionCard>
   {!balanced&&status!=='approved'&&<WorkspaceState>{l.blocked}</WorkspaceState>}
   <div className="modal-actions">{canSubmit&&status==='draft'&&items.length>0&&<button className="primary" disabled={busy} onClick={()=>void mutate(`/api/opening-balances/${yearId}/submit-review`)}>{l.submit}</button>}{canReview&&status==='in_review'&&<><label>{l.returnReason}<textarea aria-label={l.returnReason} value={returnReason} onChange={e=>setReturnReason(e.target.value)} maxLength={1000}/></label><button disabled={busy||!returnReason.trim()} onClick={()=>void mutate(`/api/opening-balances/${yearId}/return-to-draft`,'POST',{reason:returnReason.trim()})}>{l.returnDraft}</button></>}{canApprove&&status==='in_review'&&<button className="primary" disabled={busy||!balanced} onClick={()=>void mutate(`/api/opening-balances/${yearId}/approve`)}>{l.approve}</button>}</div>
  </>}
 </WorkspacePage>;
}
