import { FormEvent, useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Dialog } from './Dialog';
import { PageHeader, StatusBadge, WorkspaceState } from './SharedUI';
import './Partners.css';
type Partner={id:string;name:string;is_active:boolean;version:number;current_ownership_percentage:string|null;current_effective_from:string|null;has_unconfirmed_ownership:boolean};
type Ownership={id:string;ownership_percentage:string|null;effective_from:string|null;effective_to:string|null;verification_status:'unconfirmed'|'confirmed';source_document_id:string|null;note:string|null;version:number};
type Props={canView:boolean;canCreatePartner:boolean;canEditPartner:boolean;canDisablePartner:boolean;canCreateOwnership:boolean;canEditOwnership:boolean;canConfirmOwnership:boolean;onUnauthorized:()=>void;companyName?:string};
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const r=await fetch(url,{credentials:'same-origin',...options});if(r.status===401)onUnauthorized();if(!r.ok)throw new Error(String(r.status));return r.json();}
export function Partners({canView,canCreatePartner,canEditPartner,canDisablePartner,canCreateOwnership,canEditOwnership,canConfirmOwnership,onUnauthorized,companyName}:Props){const{t}=useTranslation();const[partners,setPartners]=useState<Partner[]>([]),[selected,setSelected]=useState<Partner|null>(null),[history,setHistory]=useState<Ownership[]>([]);const[loading,setLoading]=useState(canView),[error,setError]=useState(false),[partnerForm,setPartnerForm]=useState<Partner|null|undefined>(undefined),[ownershipForm,setOwnershipForm]=useState<Ownership|null|undefined>(undefined),[saving,setSaving]=useState(false),[historyFor,setHistoryFor]=useState<string|null>(null);const latestHistory=useRef<string|null>(null);
 const load=async()=>{setLoading(true);setError(false);try{const x=await api('/api/partners',{},onUnauthorized) as {partners:Partner[]};setPartners(x.partners);if(selected){const next=x.partners.find(p=>p.id===selected.id)??null;setSelected(next);}}catch{setError(true)}finally{setLoading(false)}};
 const loadHistory=async(p:Partner)=>{setSelected(p);setHistoryFor(null);latestHistory.current=p.id;try{const x=await api(`/api/partners/${p.id}/ownership`,{},onUnauthorized) as {ownership:Ownership[]};if(latestHistory.current!==p.id)return;setHistory(x.ownership);setHistoryFor(p.id)}catch{if(latestHistory.current===p.id)setError(true)}};
 useEffect(()=>{if(canView)void load();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);if(!canView)return <section className="panel"><WorkspaceState>{t('partners.noAccess')}</WorkspaceState></section>;
 const savePartner=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget),name=String(data.get('name'));let payload:Record<string,unknown>={name};if(partnerForm){payload={version:partnerForm.version};if(canEditPartner&&name!==partnerForm.name)payload.name=name;const isActive=data.get('is_active')==='on';if(isActive!==partnerForm.is_active)payload.is_active=isActive;}setSaving(true);try{await api(partnerForm?`/api/partners/${partnerForm.id}`:'/api/partners',{method:partnerForm?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)},onUnauthorized);setPartnerForm(undefined);await load()}catch{setError(true)}finally{setSaving(false)}};
 const saveOwnership=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected||saving)return;const d=new FormData(e.currentTarget),value=(n:string)=>String(d.get(n)||'').trim()||null,existing=(key:keyof Ownership)=>ownershipForm?.[key]??null;const editable=!ownershipForm||canEditOwnership;const payload={ownership_percentage:editable?value('ownership_percentage'):existing('ownership_percentage'),effective_from:editable?value('effective_from'):existing('effective_from'),effective_to:editable?value('effective_to'):existing('effective_to'),verification_status:String(d.get('verification_status')??existing('verification_status')??'unconfirmed'),source_document_id:editable?value('source_document_id'):existing('source_document_id'),note:editable?value('note'):existing('note')};setSaving(true);try{await api(ownershipForm?`/api/partners/${selected.id}/ownership/${ownershipForm.id}`:`/api/partners/${selected.id}/ownership`,{method:ownershipForm?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(ownershipForm?{...payload,version:ownershipForm.version,reason:value('reason')}:payload)},onUnauthorized);setOwnershipForm(undefined);await loadHistory(selected);await load()}catch{setError(true)}finally{setSaving(false)}};
 const counts={total:partners.length,active:partners.filter(p=>p.is_active).length,inactive:partners.filter(p=>!p.is_active).length};
 return <section className="panel pt-view" aria-labelledby="partners-title"><header className="pt-header"><div><h2 id="partners-title">{t('partners.title')}</h2><p>{t('partners.description')}</p></div>{canCreatePartner&&<button className="pt-primary" onClick={()=>setPartnerForm(null)}><svg className="pt-icon" viewBox="0 0 16 16" aria-hidden="true" focusable="false"><path d="M8 3v10M3 8h10" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/></svg>{t('partners.create')}</button>}</header>{error&&<WorkspaceState tone="error">{t('partners.error')}</WorkspaceState>}{loading?<WorkspaceState>{t('partners.loading')}</WorkspaceState>:<>
 <dl className="pt-summary" aria-label={t('partners.summary')}><div><dt>{t('partners.totalCount')}</dt><dd>{counts.total}</dd></div><div className="is-active"><dt>{t('partners.active')}</dt><dd>{counts.active}</dd></div><div><dt>{t('partners.inactive')}</dt><dd>{counts.inactive}</dd></div></dl>
 <section className="pt-card" aria-labelledby="partners-register-title"><div className="pt-card__head"><h3 id="partners-register-title">{t('partners.register')}</h3><span className="pt-muted">{t('partners.registerMeta',{count:counts.total})}</span></div><div className="pt-table"><table><thead><tr><th>{t('partners.name')}</th><th>{t('partners.statusColumn')}</th><th>{t('partners.ownership')}</th><th>{t('partners.effectiveFrom')}</th><th>{t('partners.actions')}</th></tr></thead><tbody>{partners.length===0?<tr><td colSpan={5} className="pt-empty"><span>{t('partners.empty')}</span></td></tr>:partners.map(p=><tr key={p.id}><td className="pt-name"><button className="link-button" onClick={()=>void loadHistory(p)}>{p.name}</button>{p.has_unconfirmed_ownership&&<span className="pt-note">{t('partners.unconfirmed')}</span>}</td><td><StatusBadge status={p.is_active?'open':'closed'}>{t(p.is_active?'partners.active':'partners.inactive')}</StatusBadge></td><td>{p.current_ownership_percentage!=null?`${p.current_ownership_percentage}%`:t('partners.unknown')}</td><td>{p.current_effective_from??t('partners.unknown')}</td><td>{(canEditPartner||(p.is_active&&canDisablePartner))&&<button className="pt-ghost" onClick={()=>setPartnerForm(p)}>{t('partners.edit')}</button>}</td></tr>)}</tbody></table></div></section></>}
 {selected&&<section className="subsection"><PageHeader eyebrow={t('partners.history')} title={selected.name} action={canCreateOwnership?<button onClick={()=>setOwnershipForm(null)}>{t('partners.addOwnership')}</button>:undefined}/>{historyFor!==selected.id?<WorkspaceState>{t('partners.loading')}</WorkspaceState>:history.length===0?<WorkspaceState>{t('partners.noHistory')}</WorkspaceState>:history.map(o=><article className="fiscal-year-card" key={o.id}><StatusBadge status={o.verification_status==='confirmed'?'open':'closed'}>{t(`partners.${o.verification_status}`)}</StatusBadge><dl className="fiscal-year-dates"><div><dt>{t('partners.ownership')}</dt><dd>{o.ownership_percentage?`${o.ownership_percentage}%`:t('partners.unknown')}</dd></div><div><dt>{t('partners.effectiveFrom')}</dt><dd>{o.effective_from??t('partners.unknown')}</dd></div><div><dt>{t('partners.effectiveTo')}</dt><dd>{o.effective_to??t('partners.openEnded')}</dd></div></dl>{o.source_document_id&&<p>{t('partners.source')}: {o.source_document_id}</p>}{o.note&&<p>{o.note}</p>}{(canEditOwnership||(o.verification_status==='unconfirmed'&&canConfirmOwnership))&&<button onClick={()=>setOwnershipForm(o)}>{o.verification_status==='unconfirmed'&&canConfirmOwnership?t('partners.editOrConfirm'):t('partners.edit')}</button>}</article>)}</section>}
 {partnerForm!==undefined&&<Dialog title={t(partnerForm?'partners.edit':'partners.create')} busy={saving} onClose={()=>setPartnerForm(undefined)}><form className="pt-form" onSubmit={savePartner}>{companyName&&<p className="pt-note" data-testid="partner-company-context">{t('partners.company',{name:companyName})}</p>}<label>{t('partners.name')}<input name="name" required maxLength={200} defaultValue={partnerForm?.name} disabled={!!partnerForm&&!canEditPartner}/></label>{partnerForm&&<label className="pt-check"><input name="is_active" type="checkbox" defaultChecked={partnerForm.is_active} disabled={partnerForm.is_active?!canDisablePartner:!canEditPartner}/>{t('partners.active')}</label>}<div className="modal-actions"><button type="button" className="pt-ghost" disabled={saving} onClick={()=>setPartnerForm(undefined)}>{t('common.cancel')}</button><button className="pt-primary" type="submit" disabled={saving}>{saving&&<span className="pt-spinner" aria-hidden="true"/>}{saving?t('partners.saving'):t('common.save')}</button></div></form></Dialog>}
 {ownershipForm!==undefined&&<Dialog title={t('partners.ownership')} busy={saving} onClose={()=>setOwnershipForm(undefined)}><form className="form-grid" onSubmit={saveOwnership}><label>{t('partners.ownership')}<input name="ownership_percentage" type="number" min="0.0001" max="100" step="0.0001" defaultValue={ownershipForm?.ownership_percentage??''} disabled={!!ownershipForm&&!canEditOwnership}/></label><label>{t('partners.effectiveFrom')}<input name="effective_from" type="date" defaultValue={ownershipForm?.effective_from??''} disabled={!!ownershipForm&&!canEditOwnership}/></label><label>{t('partners.effectiveTo')}<input name="effective_to" type="date" defaultValue={ownershipForm?.effective_to??''} disabled={!!ownershipForm&&!canEditOwnership}/></label><label>{t('partners.status')}<select name="verification_status" defaultValue={ownershipForm?.verification_status??'unconfirmed'} disabled={!!ownershipForm&&(ownershipForm.verification_status==='confirmed'?!canEditOwnership:!canConfirmOwnership&&!canEditOwnership)}><option value="unconfirmed">{t('partners.unconfirmed')}</option>{canConfirmOwnership&&<option value="confirmed">{t('partners.confirmed')}</option>}</select></label><label>{t('partners.source')}<input name="source_document_id" defaultValue={ownershipForm?.source_document_id??''} disabled={!!ownershipForm&&!canEditOwnership}/></label><label>{t('partners.note')}<textarea name="note" maxLength={1000} defaultValue={ownershipForm?.note??''} disabled={!!ownershipForm&&!canEditOwnership}/></label>{ownershipForm?.verification_status==='confirmed'&&<label>{t('partners.reason')}<textarea name="reason" required maxLength={500}/></label>}<div className="modal-actions"><button type="button" disabled={saving} onClick={()=>setOwnershipForm(undefined)}>{t('common.cancel')}</button><button className="primary" disabled={saving}>{t('common.save')}</button></div></form></Dialog>}</section>}
