import { FormEvent, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Dialog } from './Dialog';
import { PageHeader, StatusBadge, WorkspaceState } from './SharedUI';
type Partner={id:string;name:string;is_active:boolean;version:number;current_ownership_percentage:string|null;current_effective_from:string|null;has_unconfirmed_ownership:boolean};
type Ownership={id:string;ownership_percentage:string|null;effective_from:string|null;effective_to:string|null;verification_status:'unconfirmed'|'confirmed';source_document_id:string|null;note:string|null;version:number};
type Props={canView:boolean;canCreatePartner:boolean;canEditPartner:boolean;canDisablePartner:boolean;canCreateOwnership:boolean;canEditOwnership:boolean;canConfirmOwnership:boolean;onUnauthorized:()=>void};
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const r=await fetch(url,{credentials:'same-origin',...options});if(r.status===401)onUnauthorized();if(!r.ok)throw new Error(String(r.status));return r.json();}
export function Partners({canView,canCreatePartner,canEditPartner,canDisablePartner,canCreateOwnership,canEditOwnership,canConfirmOwnership,onUnauthorized}:Props){const{t}=useTranslation();const[partners,setPartners]=useState<Partner[]>([]),[selected,setSelected]=useState<Partner|null>(null),[history,setHistory]=useState<Ownership[]>([]);const[loading,setLoading]=useState(canView),[error,setError]=useState(false),[partnerForm,setPartnerForm]=useState<Partner|null|undefined>(undefined),[ownershipForm,setOwnershipForm]=useState<Ownership|null|undefined>(undefined);
 const load=async()=>{setLoading(true);setError(false);try{const x=await api('/api/partners',{},onUnauthorized) as {partners:Partner[]};setPartners(x.partners);if(selected){const next=x.partners.find(p=>p.id===selected.id)??null;setSelected(next);}}catch{setError(true)}finally{setLoading(false)}};
 const loadHistory=async(p:Partner)=>{setSelected(p);try{const x=await api(`/api/partners/${p.id}/ownership`,{},onUnauthorized) as {ownership:Ownership[]};setHistory(x.ownership)}catch{setError(true)}};
 useEffect(()=>{if(canView)void load();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);if(!canView)return <section className="panel"><WorkspaceState>{t('partners.noAccess')}</WorkspaceState></section>;
 const savePartner=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget),name=String(data.get('name'));let payload:Record<string,unknown>={name};if(partnerForm){payload={version:partnerForm.version};if(canEditPartner&&name!==partnerForm.name)payload.name=name;const isActive=data.get('is_active')==='on';if(isActive!==partnerForm.is_active)payload.is_active=isActive;}try{await api(partnerForm?`/api/partners/${partnerForm.id}`:'/api/partners',{method:partnerForm?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)},onUnauthorized);setPartnerForm(undefined);await load()}catch{setError(true)}};
 const saveOwnership=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const d=new FormData(e.currentTarget),value=(n:string)=>String(d.get(n)||'').trim()||null,existing=(key:keyof Ownership)=>ownershipForm?.[key]??null;const editable=!ownershipForm||canEditOwnership;const payload={ownership_percentage:editable?value('ownership_percentage'):existing('ownership_percentage'),effective_from:editable?value('effective_from'):existing('effective_from'),effective_to:editable?value('effective_to'):existing('effective_to'),verification_status:String(d.get('verification_status')??existing('verification_status')??'unconfirmed'),source_document_id:editable?value('source_document_id'):existing('source_document_id'),note:editable?value('note'):existing('note')};try{await api(ownershipForm?`/api/partners/${selected.id}/ownership/${ownershipForm.id}`:`/api/partners/${selected.id}/ownership`,{method:ownershipForm?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(ownershipForm?{...payload,version:ownershipForm.version,reason:value('reason')}:payload)},onUnauthorized);setOwnershipForm(undefined);await loadHistory(selected);await load()}catch{setError(true)}};
 return <section className="panel" aria-labelledby="partners-title"><PageHeader titleId="partners-title" eyebrow={t('partners.title')} title={t('partners.title')} description={t('partners.description')} action={canCreatePartner?<button className="primary" onClick={()=>setPartnerForm(null)}>{t('partners.create')}</button>:undefined}/>{error&&<WorkspaceState tone="error">{t('partners.error')}</WorkspaceState>}{loading?<WorkspaceState>{t('partners.loading')}</WorkspaceState>:partners.length===0?<WorkspaceState>{t('partners.empty')}</WorkspaceState>:<div className="fiscal-years-grid">{partners.map(p=><article className="fiscal-year-card" key={p.id}><h3><button className="link-button" onClick={()=>void loadHistory(p)}>{p.name}</button></h3><StatusBadge status={p.is_active?'open':'closed'}>{t(p.is_active?'partners.active':'partners.inactive')}</StatusBadge><dl className="fiscal-year-dates"><div><dt>{t('partners.ownership')}</dt><dd>{p.current_ownership_percentage!=null?`${p.current_ownership_percentage}%`:t('partners.unknown')}</dd></div><div><dt>{t('partners.effectiveFrom')}</dt><dd>{p.current_effective_from??t('partners.unknown')}</dd></div></dl>{p.has_unconfirmed_ownership&&<p>{t('partners.unconfirmed')}</p>}{(canEditPartner||(p.is_active&&canDisablePartner))&&<button onClick={()=>setPartnerForm(p)}>{t('partners.edit')}</button>}</article>)}</div>}
 {selected&&<section className="subsection"><PageHeader eyebrow={t('partners.history')} title={selected.name} action={canCreateOwnership?<button onClick={()=>setOwnershipForm(null)}>{t('partners.addOwnership')}</button>:undefined}/>{history.length===0?<WorkspaceState>{t('partners.noHistory')}</WorkspaceState>:history.map(o=><article className="fiscal-year-card" key={o.id}><StatusBadge status={o.verification_status==='confirmed'?'open':'closed'}>{t(`partners.${o.verification_status}`)}</StatusBadge><dl className="fiscal-year-dates"><div><dt>{t('partners.ownership')}</dt><dd>{o.ownership_percentage?`${o.ownership_percentage}%`:t('partners.unknown')}</dd></div><div><dt>{t('partners.effectiveFrom')}</dt><dd>{o.effective_from??t('partners.unknown')}</dd></div><div><dt>{t('partners.effectiveTo')}</dt><dd>{o.effective_to??t('partners.openEnded')}</dd></div></dl>{o.source_document_id&&<p>{t('partners.source')}: {o.source_document_id}</p>}{o.note&&<p>{o.note}</p>}{(canEditOwnership||(o.verification_status==='unconfirmed'&&canConfirmOwnership))&&<button onClick={()=>setOwnershipForm(o)}>{o.verification_status==='unconfirmed'&&canConfirmOwnership?t('partners.editOrConfirm'):t('partners.edit')}</button>}</article>)}</section>}
 {partnerForm!==undefined&&<Dialog title={t(partnerForm?'partners.edit':'partners.create')} onClose={()=>setPartnerForm(undefined)}><form className="form-grid" onSubmit={savePartner}><label>{t('partners.name')}<input name="name" required maxLength={200} defaultValue={partnerForm?.name} disabled={!!partnerForm&&!canEditPartner}/></label>{partnerForm&&<label><input name="is_active" type="checkbox" defaultChecked={partnerForm.is_active} disabled={partnerForm.is_active?!canDisablePartner:!canEditPartner}/>{t('partners.active')}</label>}<button className="primary">{t('common.save')}</button></form></Dialog>}
 {ownershipForm!==undefined&&<Dialog title={t('partners.ownership')} onClose={()=>setOwnershipForm(undefined)}><form className="form-grid" onSubmit={saveOwnership}><label>{t('partners.ownership')}<input name="ownership_percentage" type="number" min="0.0001" max="100" step="0.0001" defaultValue={ownershipForm?.ownership_percentage??''} disabled={!!ownershipForm&&!canEditOwnership}/></label><label>{t('partners.effectiveFrom')}<input name="effective_from" type="date" defaultValue={ownershipForm?.effective_from??''} disabled={!!ownershipForm&&!canEditOwnership}/></label><label>{t('partners.effectiveTo')}<input name="effective_to" type="date" defaultValue={ownershipForm?.effective_to??''} disabled={!!ownershipForm&&!canEditOwnership}/></label><label>{t('partners.status')}<select name="verification_status" defaultValue={ownershipForm?.verification_status??'unconfirmed'} disabled={!!ownershipForm&&(ownershipForm.verification_status==='confirmed'?!canEditOwnership:!canConfirmOwnership&&!canEditOwnership)}><option value="unconfirmed">{t('partners.unconfirmed')}</option>{canConfirmOwnership&&<option value="confirmed">{t('partners.confirmed')}</option>}</select></label><label>{t('partners.source')}<input name="source_document_id" defaultValue={ownershipForm?.source_document_id??''} disabled={!!ownershipForm&&!canEditOwnership}/></label><label>{t('partners.note')}<textarea name="note" maxLength={1000} defaultValue={ownershipForm?.note??''} disabled={!!ownershipForm&&!canEditOwnership}/></label>{ownershipForm?.verification_status==='confirmed'&&<label>{t('partners.reason')}<textarea name="reason" required maxLength={500}/></label>}<button className="primary">{t('common.save')}</button></form></Dialog>}</section>}
