import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {formatDisplayDate} from '../date-format';
import {readQueryParameter} from '../navigation/queryState';
import {Metric,MetricStrip,PageHeader,SectionCard,StatusBadge,WorkspacePage,WorkspaceState} from './SharedUI';

type AdjustmentType='accrued_expense'|'prepaid_expense'|'accrued_income'|'deferred_income';
type Status='draft'|'in_review'|'approved'|'completed';
type Schedule={id:string;period_start:string;period_end:string;recognition_date:string;amount:string;status:'pending'|'posted';journal_entry_id:string|null};
type Adjustment={id:string;adjustment_type:AdjustmentType;total_amount:string;recognition_start:string;recognition_end:string;document_id:string|null;obligation_id:string|null;document_name:string|null;description:string;reference:string|null;notes:string|null;balance_account_id:string;pnl_account_id:string;workflow_status:Status;review_note:string|null;version:number;schedule:Schedule[]};
type Account={id:string;code:string;name:string;account_type:'asset'|'liability'|'equity'|'revenue'|'expense';is_active:boolean};
type Document={id:string;original_filename:string;status:string};
type Obligation={id:string;direction:string;counterparty_name?:string;document_id:string|null;original_amount:string};
type Props={canView:boolean;canManage:boolean;canReview:boolean;canApprove:boolean;canPost:boolean;onUnauthorized:()=>void};

type FormState={type:AdjustmentType;amount:string;start:string;end:string;description:string;reference:string;notes:string;balanceAccountId:string;pnlAccountId:string;documentId:string;obligationId:string};
const initialForm:FormState={type:'accrued_expense',amount:'',start:'',end:'',description:'',reference:'',notes:'',balanceAccountId:'',pnlAccountId:'',documentId:'',obligationId:''};
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const response=await fetch(url,{credentials:'same-origin',...options});if(response.status===401)onUnauthorized();if(!response.ok)throw new Error(String(response.status));return response;}
const datePattern=/^\d{4}-(0[1-9]|1[0-2])-([0-2]\d|3[01])$/;
const validDate=(value:string|null)=>value&&datePattern.test(value)&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value?value:'';
const readClosePeriod=()=>{const from=validDate(readQueryParameter('adjustmentFrom')),to=validDate(readQueryParameter('adjustmentTo'));return from&&to&&from<=to?{from,to}:null};
const json=(method:string,body:unknown):RequestInit=>({method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});

export function PeriodicAdjustments({canView,canManage,canReview,canApprove,canPost,onUnauthorized}:Props){
 const {i18n}=useTranslation();const ar=i18n.language==='ar';
 const l=ar?{
  title:'الاستحقاقات والمقدمات',description:'إدارة المصروفات والإيرادات المستحقة والمقدمة مع جداول الاعتراف والترحيل.',newItem:'إضافة تعديل دوري',type:'النوع',amount:'إجمالي المبلغ',start:'بداية الاعتراف',end:'نهاية الاعتراف',descriptionLabel:'الوصف',reference:'المرجع',notes:'ملاحظات',balanceAccount:'حساب الميزانية',pnlAccount:'حساب الربح والخسارة',document:'المستند المرتبط (اختياري)',obligation:'الالتزام المرتبط (اختياري)',none:'بدون ربط',save:'حفظ',update:'تحديث',cancel:'إلغاء التعديل',items:'التعديلات الدورية',schedule:'جدول الاعتراف',period:'الفترة',recognitionDate:'تاريخ الاعتراف',journal:'القيد',post:'ترحيل الفترة',submit:'إرسال للمراجعة',approve:'اعتماد',returnDraft:'إرجاع إلى المسودة',returnReason:'سبب الإرجاع',loading:'جارٍ التحميل...',empty:'لا توجد تعديلات دورية بعد.',error:'تعذر تحميل أو حفظ البيانات.',noAccess:'ليس لديك صلاحية عرض التعديلات الدورية.',draft:'مسودة',in_review:'قيد المراجعة',approved:'معتمد',completed:'مكتمل',pending:'معلق',posted:'مرحل',accrued_expense:'مصروف مستحق',prepaid_expense:'مصروف مقدم',accrued_income:'إيراد مستحق',deferred_income:'إيراد مؤجل',total:'الإجمالي',pendingCount:'فترات معلقة',postedCount:'فترات مرحلة',accountHint:'اختيار الحسابات هو إعداد محاسبي؛ اتجاه المدين/الدائن يحدده النظام تلقائيًا.'
 }:{
  title:'Accruals & Prepayments',description:'Manage accrued and prepaid expenses/income with governed recognition schedules and posting.',newItem:'Add periodic adjustment',type:'Type',amount:'Total amount',start:'Recognition start',end:'Recognition end',descriptionLabel:'Description',reference:'Reference',notes:'Notes',balanceAccount:'Balance-sheet account',pnlAccount:'P&L account',document:'Linked document (optional)',obligation:'Linked obligation (optional)',none:'No link',save:'Save',update:'Update',cancel:'Cancel edit',items:'Periodic adjustments',schedule:'Recognition schedule',period:'Period',recognitionDate:'Recognition date',journal:'Journal',post:'Post period',submit:'Submit for review',approve:'Approve',returnDraft:'Return to draft',returnReason:'Return reason',loading:'Loading...',empty:'No periodic adjustments yet.',error:'Could not load or save data.',noAccess:'You do not have access to periodic adjustments.',draft:'Draft',in_review:'In review',approved:'Approved',completed:'Completed',pending:'Pending',posted:'Posted',accrued_expense:'Accrued expense',prepaid_expense:'Prepaid expense',accrued_income:'Accrued income',deferred_income:'Deferred income',total:'Total',pendingCount:'Pending periods',postedCount:'Posted periods',accountHint:'Account selection is accounting setup; the system determines debit/credit direction automatically.'
 };
 const types:AdjustmentType[]=['accrued_expense','prepaid_expense','accrued_income','deferred_income'];
 const [items,setItems]=useState<Adjustment[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[documents,setDocuments]=useState<Document[]>([]),[obligations,setObligations]=useState<Obligation[]>([]);
 const [form,setForm]=useState<FormState>(initialForm),[editing,setEditing]=useState<Adjustment|null>(null),[returnReasons,setReturnReasons]=useState<Record<string,string>>({});
 const [loading,setLoading]=useState(canView),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 const load=async()=>{setLoading(true);setError(false);try{const main=await api('/api/periodic-adjustments',{},onUnauthorized);setItems(((await main.json()) as {adjustments:Adjustment[]}).adjustments);const optional=await Promise.allSettled([api('/api/accounts',{},onUnauthorized),api('/api/documents',{},onUnauthorized),api('/api/obligations',{},onUnauthorized)]);if(optional[0].status==='fulfilled')setAccounts(((await optional[0].value.json()) as {accounts:Account[]}).accounts);if(optional[1].status==='fulfilled')setDocuments(((await optional[1].value.json()) as {documents:Document[]}).documents);if(optional[2].status==='fulfilled')setObligations(((await optional[2].value.json()) as {obligations:Obligation[]}).obligations);}catch{setError(true)}finally{setLoading(false)}};
 useEffect(()=>{if(canView)void load();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);
 const expected=useMemo(()=>{const balance=form.type==='accrued_expense'||form.type==='deferred_income'?'liability':'asset';const pnl=form.type==='accrued_expense'||form.type==='prepaid_expense'?'expense':'revenue';return{balance,pnl}},[form.type]);
 const balanceAccounts=accounts.filter(a=>a.is_active&&a.account_type===expected.balance),pnlAccounts=accounts.filter(a=>a.is_active&&a.account_type===expected.pnl);
 const reset=()=>{setEditing(null);setForm(initialForm)};
 const edit=(a:Adjustment)=>{setEditing(a);setForm({type:a.adjustment_type,amount:a.total_amount,start:a.recognition_start,end:a.recognition_end,description:a.description,reference:a.reference??'',notes:a.notes??'',balanceAccountId:a.balance_account_id,pnlAccountId:a.pnl_account_id,documentId:a.document_id??'',obligationId:a.obligation_id??''});};
 const payload=()=>({adjustment_type:form.type,total_amount:form.amount,recognition_start:form.start,recognition_end:form.end,description:form.description,reference:form.reference||null,notes:form.notes||null,balance_account_id:form.balanceAccountId,pnl_account_id:form.pnlAccountId,document_id:form.documentId||null,obligation_id:form.obligationId||null});
 const submitForm=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError(false);try{if(editing)await api(`/api/periodic-adjustments/${editing.id}`,json('PATCH',{...payload(),version:editing.version}),onUnauthorized);else await api('/api/periodic-adjustments',json('POST',payload()),onUnauthorized);reset();await load();}catch{setError(true)}finally{setBusy(false)}};
 const mutate=async(url:string,body?:unknown)=>{setBusy(true);setError(false);try{await api(url,body===undefined?{method:'POST'}:json('POST',body),onUnauthorized);await load();return true}catch{setError(true);return false}finally{setBusy(false)}};
 if(!canView)return <WorkspacePage><WorkspaceState>{l.noAccess}</WorkspaceState></WorkspacePage>;
 const closePeriod=readClosePeriod();
 const visibleItems=closePeriod?items.filter(a=>((a.workflow_status==='draft'||a.workflow_status==='in_review')&&a.recognition_start<=closePeriod.to&&a.recognition_end>=closePeriod.from)||(a.workflow_status==='approved'&&a.schedule.some(entry=>entry.status==='pending'&&entry.recognition_date>=closePeriod.from&&entry.recognition_date<=closePeriod.to))):items;
 const pending=items.flatMap(a=>a.schedule).filter(s=>s.status==='pending').length,posted=items.flatMap(a=>a.schedule).filter(s=>s.status==='posted').length;
 return <WorkspacePage labelledBy="periodic-adjustments-title" size="operational">
  <PageHeader titleId="periodic-adjustments-title" eyebrow={l.title} title={l.title} description={l.description}/>
  <MetricStrip><Metric label={l.total} value={items.length}/><Metric label={l.pendingCount} value={pending}/><Metric label={l.postedCount} value={posted}/></MetricStrip>
  {error&&<WorkspaceState tone="error">{l.error}</WorkspaceState>}
  {canManage&&<SectionCard><h3>{editing?l.update:l.newItem}</h3><p className="muted">{l.accountHint}</p><form className="form-grid" onSubmit={submitForm}>
   <label>{l.type}<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as AdjustmentType,balanceAccountId:'',pnlAccountId:''})}>{types.map(t=><option key={t} value={t}>{l[t]}</option>)}</select></label>
   <label>{l.amount}<input value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} inputMode="decimal" pattern="[0-9]+([.][0-9]{1,2})?" required/></label>
   <label>{l.start}<input type="date" value={form.start} onChange={e=>setForm({...form,start:e.target.value})} required/></label>
   <label>{l.end}<input type="date" value={form.end} onChange={e=>setForm({...form,end:e.target.value})} required/></label>
   <label>{l.descriptionLabel}<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} maxLength={500} required/></label>
   <label>{l.reference}<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} maxLength={200}/></label>
   <label>{l.balanceAccount}<select value={form.balanceAccountId} onChange={e=>setForm({...form,balanceAccountId:e.target.value})} required><option value="">—</option>{balanceAccounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label>
   <label>{l.pnlAccount}<select value={form.pnlAccountId} onChange={e=>setForm({...form,pnlAccountId:e.target.value})} required><option value="">—</option>{pnlAccounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label>
   {documents.length>0&&<label>{l.document}<select value={form.documentId} onChange={e=>setForm({...form,documentId:e.target.value})}><option value="">{l.none}</option>{documents.map(d=><option key={d.id} value={d.id}>{d.original_filename}</option>)}</select></label>}
   {obligations.length>0&&<label>{l.obligation}<select value={form.obligationId} onChange={e=>setForm({...form,obligationId:e.target.value})}><option value="">{l.none}</option>{obligations.map(o=><option key={o.id} value={o.id}>{o.counterparty_name??o.id} — {o.original_amount}</option>)}</select></label>}
   <label>{l.notes}<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} maxLength={1000}/></label>
   <div className="actions"><button className="primary" disabled={busy} type="submit">{editing?l.update:l.save}</button>{editing&&<button type="button" onClick={reset}>{l.cancel}</button>}</div>
  </form></SectionCard>}
  <SectionCard><h3>{l.items}</h3>{loading?<WorkspaceState>{l.loading}</WorkspaceState>:visibleItems.length===0?<WorkspaceState kind="empty">{l.empty}</WorkspaceState>:<div className="table-wrap"><table><thead><tr><th>{l.type}</th><th>{l.descriptionLabel}</th><th>{l.amount}</th><th>{l.start}</th><th>{l.end}</th><th>{l.schedule}</th><th/></tr></thead><tbody>{visibleItems.map(a=><tr key={a.id}><td><strong>{l[a.adjustment_type]}</strong><br/><StatusBadge status={a.workflow_status}>{l[a.workflow_status]}</StatusBadge></td><td>{a.description}{a.document_name&&<><br/><small>{a.document_name}</small></>}</td><td>{a.total_amount}</td><td>{formatDisplayDate(a.recognition_start,i18n.language)}</td><td>{formatDisplayDate(a.recognition_end,i18n.language)}</td><td>{a.schedule.length?`${a.schedule.filter(s=>s.status==='posted').length}/${a.schedule.length}`:'—'}</td><td><div className="actions">{canManage&&a.workflow_status==='draft'&&<button disabled={busy} onClick={()=>edit(a)}>{l.update}</button>}{canReview&&a.workflow_status==='draft'&&<button disabled={busy} onClick={()=>void mutate(`/api/periodic-adjustments/${a.id}/submit-review`)}>{l.submit}</button>}{canApprove&&a.workflow_status==='in_review'&&<button className="primary" disabled={busy} onClick={()=>void mutate(`/api/periodic-adjustments/${a.id}/approve`)}>{l.approve}</button>}</div>{canReview&&a.workflow_status==='in_review'&&<div><textarea aria-label={l.returnReason} placeholder={l.returnReason} value={returnReasons[a.id]??''} onChange={e=>setReturnReasons({...returnReasons,[a.id]:e.target.value})}/><button disabled={busy||!(returnReasons[a.id]??'').trim()} onClick={()=>void mutate(`/api/periodic-adjustments/${a.id}/return-to-draft`,{reason:(returnReasons[a.id]??'').trim()})}>{l.returnDraft}</button></div>}</td></tr>)}</tbody></table></div>}</SectionCard>
  {visibleItems.filter(a=>a.schedule.length>0).map(a=><SectionCard key={`${a.id}-schedule`}><h3>{l.schedule} — {a.description}</h3><div className="table-wrap"><table><thead><tr><th>{l.period}</th><th>{l.recognitionDate}</th><th>{l.amount}</th><th>{l.journal}</th><th/></tr></thead><tbody>{a.schedule.map(s=><tr key={s.id}><td>{formatDisplayDate(s.period_start,i18n.language)} — {formatDisplayDate(s.period_end,i18n.language)}</td><td>{formatDisplayDate(s.recognition_date,i18n.language)}</td><td>{s.amount}</td><td><StatusBadge status={s.status}>{l[s.status]}</StatusBadge>{s.journal_entry_id&&<><br/><small>{s.journal_entry_id}</small></>}</td><td>{canPost&&s.status==='pending'&&<button className="primary" disabled={busy} onClick={()=>void mutate(`/api/periodic-adjustments/${a.id}/schedule/${s.id}/post`)}>{l.post}</button>}</td></tr>)}</tbody></table></div></SectionCard>)}
 </WorkspacePage>;
}
