import {useEffect,useMemo,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {formatDisplayDate} from '../date-format';
import {clearQueryParameters,readQueryParameter,writeQueryParameters} from '../navigation/queryState';
import {DataWorkspace,DetailPane,MetricStrip,PageHeader,SectionCard,StatusBadge,WorkspacePage,WorkspaceState,WorkspaceToolbar} from './SharedUI';
import {Dialog} from './Dialog';
import {useDateContext} from '../context/DateContext';
import './PurchasesApproved.css';

type Settlement={id:string;amount:string;transaction_date:string;description:string|null;bank_reference:string|null};
type CounterpartyType='customer'|'supplier'|'government'|'other';
type Purchase={id:string;document_type:'purchase'|'expense';original_filename:string;status:string;document_date:string|null;reference_number:string|null;total_amount:string|null;intake_note:string|null;counterparty_id:string|null;supplier_name:string|null;counterparty_type:CounterpartyType|null;payable_id:string|null;payable_original_amount:string|null;due_on:string|null;verification_status:string|null;payable_cancelled:boolean;payable_relationship:'not_created'|'linked_active'|'linked_cancelled';paid_amount:string;remaining_amount:string|null;financial_state:'open'|'partial'|'paid'|'overdue'|null;settlement_history:Settlement[];vat_review_status:'missing'|'pending'|'reviewed';tax_date:string|null;vat_treatment:string|null;taxable_amount:string|null;vat_amount:string|null;asset_id:string|null};
type PurchaseEntryType='purchase'|'expense';
type DiscoveryFilters={search:string;supplier:string;financial:string;review:string;type:string;from:string;to:string;payable:string;verification:string;vatReview:string};
const financialValues=['open','partial','paid','overdue'] as const,reviewValues=['uploaded','needs_review','approved','incomplete','rejected'] as const,typeValues=['purchase','expense'] as const,payableValues=['not_created','linked_active','linked_cancelled'] as const,verificationValues=['confirmed','unconfirmed'] as const,vatReviewValues=['missing','pending','reviewed'] as const;
const filterParameters=['purchaseSearch','purchaseSupplier','purchaseFinancial','purchaseReview','purchaseType','purchaseFrom','purchaseTo','purchasePayable','purchaseVerification','purchaseVatReview'] as const;
const validDate=(value:string|null)=>value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`))&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value?value:'';
const sumAmounts=(values:(string|null)[])=>{const valid=values.flatMap(value=>{if(value===null||value.trim()==='')return[];const parsed=Number(value);return Number.isFinite(parsed)?[parsed]:[]});return valid.length?valid.reduce((sum,value)=>sum+value,0).toFixed(2):'—'};
const readFilters=():DiscoveryFilters=>({search:readQueryParameter('purchaseSearch')??'',supplier:readQueryParameter('purchaseSupplier')??'',financial:readQueryParameter('purchaseFinancial',{allowedValues:financialValues})??'',review:readQueryParameter('purchaseReview',{allowedValues:reviewValues})??'',type:readQueryParameter('purchaseType',{allowedValues:typeValues})??'',from:validDate(readQueryParameter('purchaseFrom')),to:validDate(readQueryParameter('purchaseTo')),payable:readQueryParameter('purchasePayable',{allowedValues:payableValues})??'',verification:readQueryParameter('purchaseVerification',{allowedValues:verificationValues})??'',vatReview:readQueryParameter('purchaseVatReview',{allowedValues:vatReviewValues})??''});

export function Purchases({canView,canManage,canCreate=false,canEdit=false,canCapitalise=false,autoSelectFirst=false,onCreateDocument,onEditDocument,onCapitalise,onUnauthorized}:{canView:boolean;canManage:boolean;canCreate?:boolean;canEdit?:boolean;canCapitalise?:boolean;autoSelectFirst?:boolean;onCreateDocument?:(type:PurchaseEntryType)=>void;onEditDocument?:(documentId:string)=>void;onCapitalise?:(documentId:string)=>void;onUnauthorized:()=>void}){
 const{t,i18n}=useTranslation();
 const { selectedPeriodId, periodMode, availablePeriodsForSelectedYear, selectedFiscalYearId, availableFiscalYears } = useDateContext();
 const autoSelected=useRef(false);
 const[data,setData]=useState<Purchase[]|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[filters,setFilters]=useState<DiscoveryFilters>(readFilters),[error,setError]=useState(false),[addOpen,setAddOpen]=useState(false);

 // Authoritative global period is the outer boundary; manual from/to may only narrow it
 const scope=useMemo(()=>{
   if (periodMode === 'all') {
     const fiscalYear = availableFiscalYears.find(fy => fy.id === selectedFiscalYearId);
     return fiscalYear ? { from: fiscalYear.start_date, to: fiscalYear.end_date } : null;
   }
   if (selectedPeriodId && periodMode === 'specific') {
     const period = availablePeriodsForSelectedYear.find(p => p.id === selectedPeriodId);
     return period ? { from: period.period_start, to: period.period_end } : null;
   }
   return null;
 }, [selectedPeriodId, periodMode, selectedFiscalYearId, availablePeriodsForSelectedYear, availableFiscalYears]);

 const load=async()=>{const response=await fetch('/api/purchases');if(response.status===401){onUnauthorized();return;}if(!response.ok)throw Error();const next=(await response.json() as {purchases:Purchase[]}).purchases;setData(next);setSelectedId(old=>old&&next.some(item=>item.id===old)?old:null)};
 useEffect(()=>{if(canView)void load().catch(()=>setError(true))},[canView]);
 useEffect(()=>{const restore=()=>setFilters(readFilters());window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore)},[]);
 const suppliers=useMemo(()=>Array.from(new Map((data??[]).filter(x=>x.counterparty_id).map(x=>[x.counterparty_id!,x.supplier_name??t('purchases.unknown')])).entries()),[data,t]);
 useEffect(()=>{if(data&&filters.supplier&&!data.some(x=>x.counterparty_id===filters.supplier))setFilters(current=>({...current,supplier:''}))},[data,filters.supplier]);
 const updateFilter=(name:keyof DiscoveryFilters,value:string)=>{setFilters(current=>({...current,[name]:value}));const parameter={search:'purchaseSearch',supplier:'purchaseSupplier',financial:'purchaseFinancial',review:'purchaseReview',type:'purchaseType',from:'purchaseFrom',to:'purchaseTo',payable:'purchasePayable',verification:'purchaseVerification',vatReview:'purchaseVatReview'}[name];writeQueryParameters({[parameter]:value||null},name==='search'?'replace':'push')};
 const clearFilters=()=>{setFilters({search:'',supplier:'',financial:'',review:'',type:'',from:'',to:'',payable:'',verification:'',vatReview:''});clearQueryParameters(filterParameters)};
 const effFrom=[scope?.from,filters.from].filter(Boolean).sort().pop()??'',effTo=[scope?.to,filters.to].filter(Boolean).sort()[0]??'';
 const rows=useMemo(()=>{const q=filters.search.trim().toLocaleLowerCase();return(data??[]).filter(x=>(!q||[x.reference_number,x.original_filename,x.supplier_name,x.intake_note].some(v=>v?.toLocaleLowerCase().includes(q)))&&(!filters.supplier||x.counterparty_id===filters.supplier)&&(!filters.financial||x.financial_state===filters.financial)&&(!filters.review||x.status===filters.review)&&(!filters.type||x.document_type===filters.type)&&(!effFrom||(x.document_date!==null&&x.document_date>=effFrom))&&(!effTo||(x.document_date!==null&&x.document_date<=effTo))&&(!filters.payable||x.payable_relationship===filters.payable)&&(!filters.verification||x.verification_status===filters.verification)&&(!filters.vatReview||x.vat_review_status===filters.vatReview))},[data,filters,effFrom,effTo]);
 const metrics=useMemo(()=>({total:sumAmounts(rows.map(item=>item.total_amount)),paid:sumAmounts(rows.map(item=>item.paid_amount)),outstanding:sumAmounts(rows.filter(item=>item.payable_relationship==='linked_active'&&!item.payable_cancelled).map(item=>item.remaining_amount))}),[rows]);
 const selected=rows.find(item=>item.id===selectedId)??null;
 useEffect(()=>{if(autoSelectFirst&&!autoSelected.current&&data&&rows.length>0){autoSelected.current=true;setSelectedId(rows[0].id)}},[autoSelectFirst,data,rows]);
 useEffect(()=>{if(selectedId&&!rows.some(item=>item.id===selectedId))setSelectedId(null)},[rows,selectedId]);
 const create=async(purchase:Purchase)=>{const response=await fetch('/api/obligations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({direction:'payable',counterparty_id:purchase.counterparty_id,document_id:purchase.id,original_amount:purchase.total_amount,recognized_on:purchase.document_date,due_on:null,verification_status:'unconfirmed',source_type:'document',source_note:null})});if(response.status===401){onUnauthorized();return;}if(!response.ok){setError(true);return;}await load()};
 if(!canView)return <WorkspacePage><WorkspaceState>{t('purchases.noAccess')}</WorkspaceState></WorkspacePage>;
 const roleLabel=(type:CounterpartyType|null)=>type?(i18n.language==='ar'?({customer:'عميل',supplier:'مورد',government:'جهة حكومية',other:'أخرى'} as const)[type]:({customer:'Customer',supplier:'Supplier',government:'Government',other:'Other'} as const)[type]):'—';
 const integrityIssue=(purchase:Purchase)=>!!purchase.counterparty_id&&purchase.counterparty_type!==null&&purchase.counterparty_type!=='supplier';
 const eligible=(purchase:Purchase)=>canManage&&purchase.payable_relationship==='not_created'&&purchase.status==='approved'&&!!purchase.counterparty_id&&purchase.counterparty_type==='supplier'&&!!purchase.document_date&&!!purchase.total_amount;
 const editable=(purchase:Purchase)=>canEdit&&purchase.status==='uploaded'&&!!onEditDocument;
 const toggle=(id:string)=>setSelectedId(current=>current===id?null:id);
 const financialStatus=(purchase:Purchase)=>purchase.payable_cancelled?<StatusBadge status="cancelled">{t('purchases.cancelled')}</StatusBadge>:purchase.financial_state?<StatusBadge status={purchase.financial_state}>{t(`purchases.${purchase.financial_state}`)}</StatusBadge>:'—';
 const start=(type:PurchaseEntryType)=>{setAddOpen(false);onCreateDocument?.(type)};
 const addLabel=i18n.language==='ar'?'إضافة مستند شراء +':'Add purchase document +';
 const editLabel=i18n.language==='ar'?'تعديل':'Edit';
 const isAr=i18n.language==='ar';
 const currency=isAr?'ر.س':'SAR';
 const fmt=(value:string|null)=>{if(value===null||value==='—')return value??'—';const n=Number(value);return value.trim()!==''&&Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):value};
 const money=(value:string)=>value==='—'?value:`${fmt(value)} ${currency}`;
 const headerAr:Record<string,string>={reference:'رقم المستند',total:'الإجمالي',remaining:'المتبقي'};
 const tableTitle=isAr?'سجل المشتريات':'Purchase register';
 const tableSubtitle=isAr?'عرض وإدارة فواتير المشتريات ومطابقة الضرائب وأرصدة الموردين':'View and manage purchase invoices, tax matching and supplier balances';
 const detailTitle=isAr?'تفاصيل مستند الشراء':'Purchase document details';
 const closeLabel=isAr?'إغلاق التفاصيل':'Close details';
 const allStatuses=isAr?'جميع الحالات':'All statuses';
 const allSuppliers=isAr?'جميع الموردين':'All suppliers';
 const emptyLabel=i18n.language==='ar'?'لا توجد مشتريات أو مصروفات بعد.':'No purchases or expenses yet.';
 const chooserTitle=i18n.language==='ar'?'إضافة شراء أو مصروف':'Add purchase or expense';
 const integrityWarning=i18n.language==='ar'?'تنبيه سلامة البيانات: مستند الشراء/المصروف مرتبط بطرف ليس من نوع مورد. صحح الطرف المقابل قبل إنشاء الذمم الدائنة.':'Data integrity warning: this purchase/expense is linked to a non-supplier counterparty. Correct the counterparty before creating a payable.';
 const addAction=canCreate?<button className="primary purchases-approved__primary-action" onClick={()=>setAddOpen(true)}>{addLabel}</button>:undefined;
 const kpiIcon=(kind:'purchases'|'paid'|'outstanding')=><span className="purchases-approved__metric-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{kind==='purchases'?<><path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5z"/><path d="M14 2v6h6M16 13H8M16 17H8M10 9H8"/></>:kind==='paid'?<><rect x="2" y="6" width="20" height="12" rx="2"/><circle cx="12" cy="12" r="2"/><path d="M6 12h.01M18 12h.01"/></>:<><path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0zM12 9v4M12 17h.01"/></>}</svg></span>;
 const verificationStatus=(purchase:Purchase)=><span className={`purchases-verification purchases-verification--${purchase.verification_status??'pending'}`}>{purchase.verification_status?t(`obligations.${purchase.verification_status}`):t(`documents.statuses.${purchase.status}`)}</span>;
 const rowStatus=(purchase:Purchase)=>purchase.financial_state==='overdue'&&!purchase.payable_cancelled?<span className="purchases-verification purchases-verification--overdue">{t('purchases.overdue')}</span>:verificationStatus(purchase);
 const totals={taxable:sumAmounts(rows.map(item=>item.taxable_amount)),vat:sumAmounts(rows.map(item=>item.vat_amount)),total:sumAmounts(rows.map(item=>item.total_amount)),paid:sumAmounts(rows.map(item=>item.paid_amount)),remaining:sumAmounts(rows.map(item=>item.remaining_amount))};
 const detail=(purchase:Purchase)=><DetailPane label={t('purchases.detail')}><div className="shared-detail-pane__header purchases-v22__detail-header"><h2>{detailTitle}</h2><button type="button" className="purchases-v22__close" aria-label={closeLabel} onClick={()=>setSelectedId(null)}><svg viewBox="0 0 24 24" fill="none" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M7 7l10 10M17 7 7 17"/></svg></button></div>
  <div className="purchases-v22__hero"><strong className="purchases-amount">{purchase.reference_number??purchase.original_filename}</strong>{financialStatus(purchase)}</div>
  {integrityIssue(purchase)&&<WorkspaceState tone="error">{integrityWarning}</WorkspaceState>}
  <SectionCard className="purchases-v22__section"><h3>{t('purchases.documentInfo')}</h3><dl className="purchases-detail__facts"><div><dt>{integrityIssue(purchase)?roleLabel(purchase.counterparty_type):t('purchases.supplier')}</dt><dd>{purchase.supplier_name??t('purchases.unknown')} {purchase.counterparty_type&&<small>({roleLabel(purchase.counterparty_type)})</small>}</dd></div><div><dt>{t('purchases.date')}</dt><dd>{formatDisplayDate(purchase.document_date,i18n.language)}</dd></div><div><dt>{t('purchases.type')}</dt><dd>{t(`purchases.${purchase.document_type}`)}</dd></div><div><dt>{t('purchases.originalFilename')}</dt><dd>{purchase.original_filename}</dd></div><div><dt>{t('documents.intake.note')}</dt><dd>{purchase.intake_note??'—'}</dd></div></dl></SectionCard>
  <SectionCard className="purchases-v22__section"><h3>{t('purchases.processingStatus')}</h3><dl className="purchases-detail__facts"><div><dt>{t('purchases.reviewState')}</dt><dd>{t(`documents.statuses.${purchase.status}`)}</dd></div><div><dt>{t('purchases.verificationStatus')}</dt><dd>{verificationStatus(purchase)}</dd></div></dl></SectionCard>
  <SectionCard className="purchases-v22__section"><h3>{t('purchases.paymentStatus')}</h3><dl className="purchases-detail__facts"><div><dt>{t('purchases.total')}</dt><dd className="purchases-amount">{fmt(purchase.total_amount)}</dd></div><div><dt>{t('purchases.paidAmount')}</dt><dd className="purchases-amount">{fmt(purchase.paid_amount)}</dd></div><div><dt>{t('purchases.remaining')}</dt><dd className="purchases-amount">{fmt(purchase.remaining_amount)}</dd></div><div><dt>{t('purchases.due')}</dt><dd>{formatDisplayDate(purchase.due_on,i18n.language)}</dd></div><div><dt>{t('purchases.payable')}</dt><dd>{t(`purchases.${purchase.payable_relationship}`)}</dd></div>{purchase.payable_original_amount!=null&&<div><dt>{t('purchases.original')}</dt><dd className="purchases-amount">{fmt(purchase.payable_original_amount)}</dd></div>}</dl></SectionCard>
  <SectionCard className="purchases-v22__section purchases-v22__vat"><h3>{t('purchases.vatReview')}</h3><dl className="purchases-detail__facts"><div><dt>{t('purchases.vatReview')}</dt><dd>{t(`purchases.vat_${purchase.vat_review_status}`)}</dd></div><div><dt>{t('purchases.taxDate')}</dt><dd>{formatDisplayDate(purchase.tax_date,i18n.language)}</dd></div><div><dt>{t('purchases.vatTreatment')}</dt><dd>{purchase.vat_treatment?t(`purchases.treatment_${purchase.vat_treatment}`):'—'}</dd></div><div><dt>{t('purchases.taxableAmount')}</dt><dd className="purchases-amount">{fmt(purchase.taxable_amount)}</dd></div><div><dt>{t('purchases.inputVat')}</dt><dd className="purchases-amount">{fmt(purchase.vat_amount)}</dd></div></dl></SectionCard>
  <SectionCard className="purchases-v22__section purchases-detail__history"><h3>{t('purchases.history')}</h3>{purchase.settlement_history.length?<ul>{purchase.settlement_history.map(item=><li key={item.id}><span>{formatDisplayDate(item.transaction_date,i18n.language)}</span><strong className="purchases-amount">{fmt(item.amount)}</strong><span>{item.description??item.bank_reference??'—'}</span></li>)}</ul>:<p>{t('purchases.noPayments')}</p>}</SectionCard>
  <div className="shared-detail-pane__actions purchases-detail__actions"><a className="button-link" href={`/api/documents/${purchase.id}/file`} target="_blank" rel="noreferrer">{t('purchases.openDocument')}</a>{editable(purchase)&&<button type="button" onClick={()=>onEditDocument?.(purchase.id)}>{editLabel}</button>}{eligible(purchase)&&<button className="primary" onClick={()=>void create(purchase)}>{t('purchases.createPayable')}</button>}{canCapitalise&&purchase.document_type==='purchase'&&purchase.status==='approved'&&!purchase.asset_id&&purchase.document_date&&purchase.total_amount&&onCapitalise&&<button onClick={()=>onCapitalise(purchase.id)}>{t('assets.capitalise')}</button>}</div>
 </DetailPane>;
 return <WorkspacePage size="operational" labelledBy="purchases-title" className="purchases-workspace purchases-v22 purchases-approved"><PageHeader className="purchases-approved__header" titleId="purchases-title" title={t('purchases.title')} description={t('purchases.description')}/>{error&&<WorkspaceState tone="error" action={<button onClick={()=>void load()}>{t('common.retry')}</button>}>{t('purchases.error')}</WorkspaceState>}{!data?<WorkspaceState>{t('common.loading')}</WorkspaceState>:data.length===0?<WorkspaceState kind="empty" action={addAction}>{emptyLabel}</WorkspaceState>:<div className="shared-workspace-page__content purchases-approved__body"><MetricStrip className="purchases-approved__metrics"><div className="shared-metric purchases-approved__metric purchases-approved__metric--purchases">{kpiIcon('purchases')}<div className="purchases-approved__metric-text"><span>{t('purchases.totalKpi')}</span><strong>{money(metrics.total)}</strong></div></div><div className="shared-metric purchases-approved__metric purchases-approved__metric--paid">{kpiIcon('paid')}<div className="purchases-approved__metric-text"><span>{t('purchases.paidKpi')}</span><strong>{money(metrics.paid)}</strong></div></div><div className="shared-metric purchases-approved__metric purchases-approved__metric--outstanding">{kpiIcon('outstanding')}<div className="purchases-approved__metric-text"><span>{t('purchases.outstandingKpi')}</span><strong>{money(metrics.outstanding)}</strong></div></div></MetricStrip><WorkspaceToolbar className="purchases-approved__toolbar" ariaLabel={t('purchases.discoveryToolbar')} search={<label className="purchases-approved__search"><span className="purchases-approved__sr">{t('purchases.search')}</span><svg viewBox="0 0 24 24" fill="none" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input type="search" value={filters.search} onChange={e=>updateFilter('search',e.target.value)} placeholder={t('purchases.searchPlaceholder')}/></label>} filters={<><span className="purchases-approved__filter-group"><label className="purchases-approved__select"><span className="purchases-approved__sr">{t('purchases.financialState')}</span><select value={filters.financial} onChange={e=>updateFilter('financial',e.target.value)}><option value="">{allStatuses}</option>{financialValues.map(x=><option key={x} value={x}>{t(`purchases.${x}`)}</option>)}</select></label><label className="purchases-approved__select"><span className="purchases-approved__sr">{t('purchases.supplier')}</span><select value={filters.supplier} onChange={e=>updateFilter('supplier',e.target.value)}><option value="">{allSuppliers}</option>{suppliers.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
<details className="purchases-approved__advanced"><summary>{t('purchases.advancedFilters')}</summary><div className="purchases-approved__advanced-fields"><label>{t('purchases.reviewState')}<select value={filters.review} onChange={e=>updateFilter('review',e.target.value)}><option value="">{t('purchases.all')}</option>{reviewValues.map(x=><option key={x} value={x}>{t(`documents.statuses.${x}`)}</option>)}</select></label>
<label>{t('purchases.type')}<select value={filters.type} onChange={e=>updateFilter('type',e.target.value)}><option value="">{t('purchases.all')}</option>{typeValues.map(x=><option key={x} value={x}>{t(`purchases.${x}`)}</option>)}</select></label>
<label>{t('purchases.from')}<input type="date" value={filters.from} onChange={e=>updateFilter('from',e.target.value)}/></label><label>{t('purchases.to')}<input type="date" value={filters.to} onChange={e=>updateFilter('to',e.target.value)}/></label>
<label>{t('purchases.payable')}<select value={filters.payable} onChange={e=>updateFilter('payable',e.target.value)}><option value="">{t('purchases.all')}</option>{payableValues.map(x=><option key={x} value={x}>{t(`purchases.${x}`)}</option>)}</select></label>
<label>{t('purchases.verificationStatus')}<select value={filters.verification} onChange={e=>updateFilter('verification',e.target.value)}><option value="">{t('purchases.all')}</option>{verificationValues.map(x=><option key={x} value={x}>{t(`obligations.${x}`)}</option>)}</select></label>
<label>{t('purchases.vatReview')}<select value={filters.vatReview} onChange={e=>updateFilter('vatReview',e.target.value)}><option value="">{t('purchases.all')}</option>{vatReviewValues.map(x=><option key={x} value={x}>{t(`purchases.vat_${x}`)}</option>)}</select></label>
</div></details></span>{addAction}</>} resultCount={t('purchases.resultCount',{count:rows.length})} clearAction={Object.values(filters).some(Boolean)?<button onClick={clearFilters}>{t('purchases.clearFilters')}</button>:undefined}/><DataWorkspace withDetail={Boolean(selected)} className="purchases-data-workspace purchases-v22__workspace purchases-approved__workspace">{selected&&detail(selected)}<div className="purchases-table-wrap purchases-approved__table-container"><div className="purchases-approved__table-head"><strong>{tableTitle}</strong><span>{tableSubtitle}</span></div><div className="purchases-approved__table-frame"><table className="purchases-table"><colgroup><col style={{width:'13.5%'}}/><col style={{width:'11.5%'}}/><col style={{width:'10%'}}/><col style={{width:'10%'}}/><col style={{width:'9%'}}/><col style={{width:'7.5%'}}/><col style={{width:'9.5%'}}/><col style={{width:'8.5%'}}/><col style={{width:'8.5%'}}/><col style={{width:'12%'}}/></colgroup><thead><tr>{['reference','supplier','invoiceDate','due','taxableAmount','inputVat','total','paidAmount','remaining','verificationStatus'].map(x=><th key={x}>{isAr&&headerAr[x]?headerAr[x]:t(`purchases.${x}`)}</th>)}</tr></thead><tbody>{rows.map(s=>{const active=selectedId===s.id;return <tr key={s.id} className={`purchases-summary-row${active?' locofy-selected-row':''}`} tabIndex={0} aria-selected={active} aria-expanded={active} onClick={()=>toggle(s.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle(s.id)}}}>
  <td data-label={t('purchases.reference')}><strong>{s.reference_number??s.original_filename}</strong><span className="purchases-type-badge">{t(`purchases.${s.document_type}`)}</span></td>
  <td data-label={t('purchases.supplier')}><strong>{s.supplier_name??t('purchases.unknown')}</strong>{s.counterparty_type&&<small>{roleLabel(s.counterparty_type)}{integrityIssue(s)?' ⚠':''}</small>}</td>
  <td data-label={t('purchases.invoiceDate')} className="purchases-nowrap">{formatDisplayDate(s.document_date,i18n.language)}</td>
  <td data-label={t('purchases.due')} className="purchases-nowrap">{formatDisplayDate(s.due_on,i18n.language)}{s.financial_state==='overdue'&&<small>{financialStatus(s)}</small>}</td>
  <td data-label={t('purchases.taxableAmount')} className="purchases-amount purchases-nowrap">{fmt(s.taxable_amount)}</td>
  <td data-label={t('purchases.inputVat')} className="purchases-amount purchases-nowrap">{fmt(s.vat_amount)}</td>
  <td data-label={t('purchases.total')} className="purchases-amount purchases-nowrap">{fmt(s.total_amount)}</td>
  <td data-label={t('purchases.paidAmount')} className="purchases-amount purchases-nowrap">{fmt(s.paid_amount)}</td>
  <td data-label={t('purchases.remaining')} className="purchases-amount purchases-nowrap">{fmt(s.remaining_amount)}</td>
  <td data-label={t('purchases.verificationStatus')} className="purchases-status-cell">{rowStatus(s)}</td>
 </tr>})}</tbody>{rows.length>0&&<tfoot><tr><td></td><th>{t('purchases.totals')}</th><td></td><td></td><td className="purchases-amount">{fmt(totals.taxable)}</td><td className="purchases-amount">{fmt(totals.vat)}</td><td className="purchases-amount">{fmt(totals.total)}</td><td className="purchases-amount">{fmt(totals.paid)}</td><td className="purchases-amount">{fmt(totals.remaining)}</td><td></td></tr></tfoot>}</table></div>{rows.length===0&&<WorkspaceState kind="no-results">{t('purchases.noResults')}</WorkspaceState>}</div></DataWorkspace></div>}{addOpen&&<Dialog title={chooserTitle} onClose={()=>setAddOpen(false)}><div className="modal-actions"><button type="button" onClick={()=>start('purchase')}>{t('purchases.purchase')}</button><button type="button" onClick={()=>start('expense')}>{t('purchases.expense')}</button></div></Dialog>}</WorkspacePage>;
}
