import {useEffect,useMemo,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {formatDisplayDate} from '../date-format';
import {clearQueryParameters,readQueryParameter,writeQueryParameters} from '../navigation/queryState';
import {DataWorkspace,DetailPane,MetricStrip,PageHeader,SectionCard,StatusBadge,WorkspacePage,WorkspaceState,WorkspaceToolbar} from './SharedUI';
import {useDateContext} from '../context/DateContext';
import './SalesApproved.css';

type Settlement={id:string;amount:string;transaction_date:string;description:string|null;bank_reference:string|null};
type CounterpartyType='customer'|'supplier'|'government'|'other';
type Sale={id:string;original_filename:string;status:string;document_date:string|null;reference_number:string|null;total_amount:string|null;intake_note:string|null;counterparty_id:string|null;customer_name:string|null;counterparty_type:CounterpartyType|null;receivable_id:string|null;receivable_original_amount:string|null;due_on:string|null;verification_status:string|null;receivable_cancelled:boolean;receivable_relationship:'not_created'|'linked_active'|'linked_cancelled';collected_amount:string;remaining_amount:string|null;financial_state:'open'|'partial'|'paid'|'overdue'|null;settlement_history:Settlement[]};
type DiscoveryFilters={search:string;customer:string;financial:string;review:string;from:string;to:string;receivable:string;verification:string};
const financialValues=['open','partial','paid','overdue'] as const,reviewValues=['uploaded','needs_review','approved','incomplete','rejected'] as const,receivableValues=['not_created','linked_active','linked_cancelled'] as const,verificationValues=['confirmed','unconfirmed'] as const;
const filterParameters=['salesSearch','salesCustomer','salesFinancial','salesReview','salesFrom','salesTo','salesReceivable','salesVerification'] as const;
const validDate=(value:string|null)=>value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`))&&new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value?value:'';
const readFilters=():DiscoveryFilters=>({search:readQueryParameter('salesSearch')??'',customer:readQueryParameter('salesCustomer')??'',financial:readQueryParameter('salesFinancial',{allowedValues:financialValues})??'',review:readQueryParameter('salesReview',{allowedValues:reviewValues})??'',from:validDate(readQueryParameter('salesFrom')),to:validDate(readQueryParameter('salesTo')),receivable:readQueryParameter('salesReceivable',{allowedValues:receivableValues})??'',verification:readQueryParameter('salesVerification',{allowedValues:verificationValues})??''});

export function Sales({canView,canManage,canCreate=false,canEdit=false,onCreateDocument,onEditDocument,onUnauthorized}:{canView:boolean;canManage:boolean;canCreate?:boolean;canEdit?:boolean;onCreateDocument?:()=>void;onEditDocument?:(documentId:string)=>void;onUnauthorized:()=>void}){
 const{t,i18n}=useTranslation();
 const { selectedPeriodId, periodMode, availablePeriodsForSelectedYear, selectedFiscalYearId, availableFiscalYears } = useDateContext();
 const[data,setData]=useState<Sale[]|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[filters,setFilters]=useState<DiscoveryFilters>(readFilters),[error,setError]=useState(false),[page,setPage]=useState(1),[loadedAt,setLoadedAt]=useState<Date|null>(null);

 // Map global period to local date range
 const scopeRange=()=>{
   if (periodMode === 'all') {
     const fiscalYear = availableFiscalYears.find(fy => fy.id === selectedFiscalYearId);
     return fiscalYear ? { from: fiscalYear.start_date, to: fiscalYear.end_date } : null;
   }
   if (selectedPeriodId && periodMode === 'specific') {
     const period = availablePeriodsForSelectedYear.find(p => p.id === selectedPeriodId);
     return period ? { from: period.period_start, to: period.period_end } : null;
   }
   return null;
 };
 useEffect(() => {
   const range = scopeRange();
   if (range) setFilters(current => ({ ...current, ...range }));
 }, [selectedPeriodId, periodMode, selectedFiscalYearId, availablePeriodsForSelectedYear, availableFiscalYears]);

 const load=async()=>{const response=await fetch('/api/sales');if(response.status===401){onUnauthorized();return;}if(!response.ok)throw Error();const next=(await response.json() as {sales:Sale[]}).sales;setData(next);setLoadedAt(new Date());setSelectedId(old=>old&&next.some(item=>item.id===old)?old:null)};
 useEffect(()=>{if(canView)void load().catch(()=>setError(true))},[canView]);
 useEffect(()=>{const restore=()=>setFilters({...readFilters(),...scopeRange()});window.addEventListener('popstate',restore);return()=>window.removeEventListener('popstate',restore)},[selectedPeriodId,periodMode,selectedFiscalYearId,availablePeriodsForSelectedYear,availableFiscalYears]);
 const customers=useMemo(()=>Array.from(new Map((data??[]).filter(x=>x.counterparty_id).map(x=>[x.counterparty_id!,x.customer_name??t('sales.unknown')])).entries()),[data,t]);
 useEffect(()=>{if(data&&filters.customer&&!data.some(x=>x.counterparty_id===filters.customer))setFilters(current=>({...current,customer:''}))},[data,filters.customer]);
 const updateFilter=(name:keyof DiscoveryFilters,value:string)=>{setFilters(current=>({...current,[name]:value}));const parameter={search:'salesSearch',customer:'salesCustomer',financial:'salesFinancial',review:'salesReview',from:'salesFrom',to:'salesTo',receivable:'salesReceivable',verification:'salesVerification'}[name];writeQueryParameters({[parameter]:value||null},name==='search'?'replace':'push')};
 const clearFilters=()=>{setFilters({search:'',customer:'',financial:'',review:'',from:'',to:'',receivable:'',verification:'',...scopeRange()});clearQueryParameters(filterParameters)};
 const rows=useMemo(()=>{const q=filters.search.trim().toLocaleLowerCase();return(data??[]).filter(x=>(!q||[x.reference_number,x.original_filename,x.customer_name,x.intake_note].some(v=>v?.toLocaleLowerCase().includes(q)))&&(!filters.customer||x.counterparty_id===filters.customer)&&(!filters.financial||x.financial_state===filters.financial)&&(!filters.review||x.status===filters.review)&&(!filters.from||(x.document_date!==null&&x.document_date>=filters.from))&&(!filters.to||(x.document_date!==null&&x.document_date<=filters.to))&&(!filters.receivable||x.receivable_relationship===filters.receivable)&&(!filters.verification||x.verification_status===filters.verification))},[data,filters]);
 const selected=rows.find(sale=>sale.id===selectedId)??null;
 useEffect(()=>{if(selectedId&&!rows.some(sale=>sale.id===selectedId))setSelectedId(null)},[rows,selectedId]);
 useEffect(()=>setPage(1),[filters]);
 const create=async(sale:Sale)=>{const response=await fetch('/api/obligations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({direction:'receivable',counterparty_id:sale.counterparty_id,document_id:sale.id,original_amount:sale.total_amount,recognized_on:sale.document_date,due_on:null,verification_status:'unconfirmed',source_type:'document',source_note:null})});if(response.status===401){onUnauthorized();return;}if(!response.ok){setError(true);return;}await load()};
 if(!canView)return <WorkspacePage><WorkspaceState>{t('sales.noAccess')}</WorkspaceState></WorkspacePage>;
 const metrics=useMemo(()=>({overdue:rows.filter(s=>s.financial_state==='overdue').reduce((sum,s)=>sum+(parseFloat(s.remaining_amount??'0')||0),0).toFixed(2),collected:rows.reduce((sum,s)=>sum+(parseFloat(s.collected_amount||'0')||0),0).toFixed(2),total:rows.reduce((sum,s)=>sum+(parseFloat(s.total_amount??'0')||0),0).toFixed(2)}),[rows]);
 const roleLabel=(type:CounterpartyType|null)=>type?(i18n.language==='ar'?({customer:'عميل',supplier:'مورد',government:'جهة حكومية',other:'أخرى'} as const)[type]:({customer:'Customer',supplier:'Supplier',government:'Government',other:'Other'} as const)[type]):'—';
 const integrityIssue=(sale:Sale)=>!!sale.counterparty_id&&sale.counterparty_type!==null&&sale.counterparty_type!=='customer';
 const eligible=(sale:Sale)=>canManage&&sale.receivable_relationship==='not_created'&&sale.status==='approved'&&!!sale.counterparty_id&&sale.counterparty_type==='customer'&&!!sale.document_date&&!!sale.total_amount;
 const editable=(sale:Sale)=>canEdit&&sale.status==='uploaded'&&!!onEditDocument;
 const toggle=(id:string)=>setSelectedId(current=>current===id?null:id);
 const isAr=i18n.language==='ar',PAGE_SIZE=10;
 const money=(value:string|null)=>value===null?'—':`${(parseFloat(value)||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})} ${isAr?'ر.س':'SAR'}`;
 const num=(value:string|null)=>value===null?'—':(parseFloat(value)||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
 const statusIcon=(state:string)=>state==='paid'?<svg aria-hidden="true" viewBox="0 0 24 24" width="10" height="10" fill="none" stroke="currentColor" strokeWidth="3"><path d="M5 12.5l4.5 4.5L19 7.5"/></svg>:state==='overdue'?<svg aria-hidden="true" viewBox="0 0 24 24" width="10" height="10" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M12 3L2 21h20L12 3z"/><path d="M12 10v5M12 18h.01"/></svg>:<svg aria-hidden="true" viewBox="0 0 24 24" width="10" height="10" fill="none" stroke="currentColor" strokeWidth="2.5"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>;
 const financialStatus=(sale:Sale)=>sale.receivable_cancelled?<StatusBadge status="cancelled">{t('sales.cancelled')}</StatusBadge>:sale.financial_state?<StatusBadge status={sale.financial_state}>{t(`sales.${sale.financial_state}`)}{statusIcon(sale.financial_state)}</StatusBadge>:'—';
 const pageCount=Math.max(1,Math.ceil(rows.length/PAGE_SIZE)),currentPage=Math.min(page,pageCount),pageRows=rows.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE);
 const digits=(n:number)=>isAr?n.toLocaleString('ar-EG',{useGrouping:false}):String(n);
 const todayLabel=new Date().toLocaleDateString(isAr?'ar-SA-u-nu-arab-ca-gregory':'en-US',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
 const updatedLabel=loadedAt?t('sales.lastUpdated',{time:loadedAt.toLocaleTimeString(isAr?'ar-SA':'en-US',{hour:'2-digit',minute:'2-digit'})}):'';
 const kpiIcon=(kind:'overdue'|'collected'|'total')=><span className="sales-approved__metric-icon" aria-hidden="true">{kind==='overdue'?<svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8"><circle cx="12" cy="12" r="9"/><path d="M12 7.5v5M12 16h.01"/></svg>:kind==='collected'?<svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8"><rect x="2.5" y="6" width="19" height="12" rx="2"/><circle cx="12" cy="12" r="2.5"/><path d="M6 12h.01M18 12h.01"/></svg>:<svg viewBox="0 0 24 24" fill="none" strokeWidth="1.8"><path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8l-5-5z"/><path d="M14 3v5h5"/></svg>}</span>;
 const editLabel=i18n.language==='ar'?'تعديل':'Edit';
 const integrityWarning=i18n.language==='ar'?'تنبيه سلامة البيانات: مستند البيع مرتبط بطرف ليس من نوع عميل. صحح الطرف المقابل قبل إنشاء الذمم المدينة.':'Data integrity warning: this sale is linked to a non-customer counterparty. Correct the counterparty before creating a receivable.';
 const detail=(sale:Sale)=><DetailPane label={t('sales.detail')}><div className="shared-detail-pane__header sales-v22__detail-header"><button type="button" className="sales-v22__close" onClick={()=>setSelectedId(null)} aria-label={t('common.close')}>×</button><div><h2>{t('sales.detail')} | {sale.reference_number??sale.original_filename}</h2></div></div>
  <SectionCard className="sales-v22__section"><h3>{t('sales.documentInfo')}</h3><dl className="sales-detail__facts"><div><dt>{t('sales.customer')}</dt><dd>{sale.customer_name??t('sales.unknown')}</dd></div><div><dt>{t('sales.issueDate')}</dt><dd>{formatDisplayDate(sale.document_date,i18n.language)}</dd></div><div><dt>{t('sales.dueDate')}</dt><dd>{formatDisplayDate(sale.due_on,i18n.language)}</dd></div><div><dt>{t('sales.status')}</dt><dd>{financialStatus(sale)}</dd></div></dl></SectionCard>
  {integrityIssue(sale)&&<WorkspaceState tone="error">{integrityWarning}</WorkspaceState>}
  <SectionCard className="sales-v22__section"><h3>{t('sales.financialAmounts')}</h3><dl className="sales-detail__facts"><div><dt>{t('sales.total')}</dt><dd className="sales-amount sales-amount--total">{money(sale.total_amount)}</dd></div><div><dt>{t('sales.collected')}</dt><dd className="sales-amount sales-amount--collected">{money(sale.collected_amount)}</dd></div><div><dt>{t('sales.remaining')}</dt><dd className="sales-amount sales-amount--remaining">{money(sale.remaining_amount)}</dd></div></dl></SectionCard>
  <details className="sales-detail__more"><summary>{t('sales.moreDetails')}</summary>
  <SectionCard className="sales-v22__section"><h3>{t('sales.receivable')}</h3><dl className="sales-detail__facts"><div><dt>{t('sales.reviewState')}</dt><dd>{t(`documents.statuses.${sale.status}`)}</dd></div><div><dt>{integrityIssue(sale)?roleLabel(sale.counterparty_type):t('sales.customer')}</dt><dd>{sale.customer_name??t('sales.unknown')} {sale.counterparty_type&&<small>({roleLabel(sale.counterparty_type)})</small>}</dd></div><div><dt>{t('sales.reference')}</dt><dd>{sale.reference_number??sale.original_filename}</dd></div><div><dt>{t('sales.receivable')}</dt><dd>{t(`sales.${sale.receivable_relationship}`)}</dd></div><div><dt>{t('sales.verificationStatus')}</dt><dd>{sale.verification_status?t(`obligations.${sale.verification_status}`):'—'}</dd></div>{sale.receivable_original_amount!=null&&<div><dt>{t('sales.original')}</dt><dd className="sales-amount">{sale.receivable_original_amount}</dd></div>}<div><dt>{t('documents.intake.note')}</dt><dd>{sale.intake_note??'—'}</dd></div><div><dt>{t('sales.originalFilename')}</dt><dd>{sale.original_filename}</dd></div></dl></SectionCard>
  <SectionCard className="sales-v22__section sales-detail__history"><h3>{t('sales.history')}</h3>{sale.settlement_history.length?<ul>{sale.settlement_history.map(item=><li key={item.id}><span>{formatDisplayDate(item.transaction_date,i18n.language)}</span><strong className="sales-amount">{item.amount}</strong><span>{item.description??item.bank_reference??'—'}</span></li>)}</ul>:<p>{t('sales.noCollections')}</p>}</SectionCard></details>
  <div className="shared-detail-pane__actions sales-detail__actions"><a className="button-link" href={`/api/documents/${sale.id}/file`} target="_blank" rel="noreferrer">{t('sales.openDocument')}</a>{editable(sale)&&<button type="button" onClick={()=>onEditDocument?.(sale.id)}>{editLabel}</button>}{eligible(sale)&&<button className="primary" onClick={()=>void create(sale)}>{t('sales.createReceivable')}</button>}</div>
 </DetailPane>;
 const addLabel=i18n.language==='ar'?'إضافة فاتورة مبيعات +':'Add sales invoice +';
 const addAction=canCreate&&onCreateDocument?<button className="primary sales-approved__primary-action" onClick={onCreateDocument}>{addLabel}</button>:undefined;
 const emptyLabel=i18n.language==='ar'?'لا توجد فواتير مبيعات بعد.':'No sales invoices yet.';
 const toolbar=<WorkspaceToolbar className="sales-approved__toolbar" ariaLabel={t('sales.discoveryToolbar')} search={<label><span className="sales-sr">{t('sales.search')}</span><input type="search" value={filters.search} onChange={e=>updateFilter('search',e.target.value)} placeholder={t('sales.searchPlaceholder')}/></label>} filters={<><span className="sales-approved__filter-group"><label><span className="sales-sr">{t('sales.customer')}</span><select value={filters.customer} onChange={e=>updateFilter('customer',e.target.value)}><option value="">{t('sales.allCustomers')}</option>{customers.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label><span className="sales-sr">{t('sales.financialState')}</span><select value={filters.financial} onChange={e=>updateFilter('financial',e.target.value)}><option value="">{t('sales.allStatuses')}</option>{financialValues.map(x=><option key={x} value={x}>{t(`sales.${x}`)}</option>)}</select></label>
<details className="sales-approved__advanced"><summary>{t('sales.advancedFilters')}</summary><div className="sales-approved__advanced-fields"><label>{t('sales.reviewState')}<select value={filters.review} onChange={e=>updateFilter('review',e.target.value)}><option value="">{t('sales.all')}</option>{reviewValues.map(x=><option key={x} value={x}>{t(`documents.statuses.${x}`)}</option>)}</select></label><label>{t('sales.from')}<input type="date" value={filters.from} onChange={e=>updateFilter('from',e.target.value)}/></label><label>{t('sales.to')}<input type="date" value={filters.to} onChange={e=>updateFilter('to',e.target.value)}/></label><label>{t('sales.receivable')}<select value={filters.receivable} onChange={e=>updateFilter('receivable',e.target.value)}><option value="">{t('sales.all')}</option>{receivableValues.map(x=><option key={x} value={x}>{t(`sales.${x}`)}</option>)}</select></label><label>{t('sales.verificationStatus')}<select value={filters.verification} onChange={e=>updateFilter('verification',e.target.value)}><option value="">{t('sales.all')}</option>{verificationValues.map(x=><option key={x} value={x}>{t(`obligations.${x}`)}</option>)}</select></label></div></details></span>{addAction}</> } resultCount={t('sales.resultCount',{count:rows.length})} clearAction={Object.values(filters).some(Boolean)?<button onClick={clearFilters}>{t('sales.clearFilters')}</button>:undefined}/>;
 const tableRows=pageRows.map(s=>{const active=selectedId===s.id;return <tr key={s.id} className={`sales-summary-row${active?' locofy-selected-row':''}`} tabIndex={0} aria-selected={active} aria-expanded={active} onClick={()=>toggle(s.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle(s.id)}}}>
  <td data-label={t('sales.docNumber')} className="sales-doc-number">{active&&<i aria-hidden="true"/>}{s.reference_number??s.original_filename}</td>
  <td data-label={t('sales.customer')}><strong>{s.customer_name??t('sales.unknown')}</strong>{integrityIssue(s)&&<small>{roleLabel(s.counterparty_type)} ⚠</small>}</td>
  <td data-label={t('sales.issueDate')} className="sales-nowrap sales-muted">{formatDisplayDate(s.document_date,i18n.language)}</td>
  <td data-label={t('sales.dueDate')} className="sales-nowrap sales-muted">{formatDisplayDate(s.due_on,i18n.language)}</td>
  <td data-label={t('sales.total')} className="sales-amount sales-nowrap"><strong>{num(s.total_amount)}</strong></td>
  <td data-label={t('sales.collected')} className="sales-amount sales-nowrap">{num(s.collected_amount)}</td>
  <td data-label={t('sales.remainingBalance')} className="sales-amount sales-nowrap">{num(s.remaining_amount)}</td>
  <td data-label={t('sales.status')} className="sales-nowrap">{financialStatus(s)}</td>
 </tr>;});
 const metrics_=<MetricStrip className="sales-approved__metrics"><div className="shared-metric sales-kpi sales-kpi--overdue">{kpiIcon('overdue')}<div><span>{t('sales.kpiOverdue')}</span><strong>{money(metrics.overdue)}</strong></div></div><div className="shared-metric sales-kpi sales-kpi--collected">{kpiIcon('collected')}<div><span>{t('sales.kpiCollected')}</span><strong>{money(metrics.collected)}</strong></div></div><div className="shared-metric sales-kpi sales-kpi--total">{kpiIcon('total')}<div><span>{t('sales.totalInvoices')}</span><strong>{money(metrics.total)}</strong></div></div></MetricStrip>;
 const content=!data?<WorkspaceState>{t('common.loading')}</WorkspaceState>:data.length===0?<WorkspaceState kind="empty" action={addAction}>{emptyLabel}</WorkspaceState>:<div className="shared-workspace-page__content sales-approved__body">{metrics_}{toolbar}<DataWorkspace withDetail={Boolean(selected)} className="sales-data-workspace sales-v22__workspace sales-approved__workspace">{selected&&detail(selected)}<div className="sales-table-wrap sales-approved__table-container"><div className="sales-approved__table-head"><h3>{t('sales.tableTitle')}</h3><p>{t('sales.tableSubtitle')}</p></div><div className="sales-approved__table-scroll"><table className="sales-table"><thead><tr>{[['docNumber'],['customer'],['issueDate'],['dueDate'],['total'],['collected'],['remainingBalance'],['status']].map(([x])=><th key={x}>{t(`sales.${x}`)}</th>)}</tr></thead><tbody>{tableRows}</tbody></table></div>{rows.length===0&&<WorkspaceState kind="no-results">{t('sales.noResults')}</WorkspaceState>}{rows.length>0&&<nav className="sales-approved__pagination" aria-label={t('sales.tableTitle')}><span>{t('sales.pageRange',{from:digits((currentPage-1)*PAGE_SIZE+1),to:digits(Math.min(currentPage*PAGE_SIZE,rows.length)),total:digits(rows.length)})}</span><div><button type="button" disabled={currentPage<=1} aria-label={t('sales.prevPage')} onClick={()=>setPage(currentPage-1)}>{isAr?'›':'‹'}</button>{Array.from({length:pageCount},(_,i)=>i+1).map(n=><button key={n} type="button" aria-current={n===currentPage?'page':undefined} className={n===currentPage?'is-active':''} aria-label={t('sales.page',{page:n})} onClick={()=>setPage(n)}>{digits(n)}</button>)}<button type="button" disabled={currentPage>=pageCount} aria-label={t('sales.nextPage')} onClick={()=>setPage(currentPage+1)}>{isAr?'‹':'›'}</button></div></nav>}</div></DataWorkspace>{updatedLabel&&<footer className="sales-approved__footer"><span>{updatedLabel}</span></footer>}</div>;
 return <WorkspacePage size="operational" labelledBy="sales-title" className="sales-workspace sales-v22 sales-approved"><PageHeader className="sales-approved__header" titleId="sales-title" title={t('sales.title')} description={t('sales.description')} action={<time className="sales-approved__today">{todayLabel}</time>}/>{error&&<WorkspaceState tone="error" action={<button onClick={()=>void load()}>{t('common.retry')}</button>}>{t('sales.error')}</WorkspaceState>}{content}</WorkspacePage>;
}