import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Dialog } from './Dialog';
import { DataWorkspace, DetailPane, PageHeader, StatusBadge, WorkspacePage, WorkspaceState, WorkspaceToolbar } from './SharedUI';

type Settlement={id:string;amount:string;transaction_date:string;description:string|null;bank_reference:string|null};
type Sale={id:string;original_filename:string;reference_number:string|null;document_date:string|null;total_amount:string|null;document_status:string;counterparty_id:string|null;customer_name:string|null;receivable_id:string|null;original_amount:string|null;collected_amount:string;remaining_amount:string|null;due_on:string|null;financial_state:'open'|'partial'|'paid'|'overdue';settlement_history:Settlement[]};

export function Sales({canView,canCreateReceivable,onUnauthorized}:{canView:boolean;canCreateReceivable:boolean;onUnauthorized:()=>void}){
 const{t}=useTranslation();const[sales,setSales]=useState<Sale[]|null>(null),[selected,setSelected]=useState<Sale|null>(null),[search,setSearch]=useState(''),[customer,setCustomer]=useState(''),[financial,setFinancial]=useState(''),[review,setReview]=useState(''),[creating,setCreating]=useState(false),[error,setError]=useState(false);
 const load=async()=>{const r=await fetch('/api/sales');if(r.status===401){onUnauthorized();return;}if(!r.ok)throw Error();const next=(await r.json() as {sales:Sale[]}).sales;setSales(next);setSelected(old=>old?next.find(x=>x.id===old.id)??null:null);};
 useEffect(()=>{if(canView)void load().catch(()=>setError(true));},[canView]);
 const customers=useMemo(()=>Array.from(new Map((sales??[]).filter(s=>s.counterparty_id).map(s=>[s.counterparty_id!,s.customer_name])).entries()),[sales]);
 const rows=useMemo(()=>{const q=search.trim().toLocaleLowerCase();return(sales??[]).filter(s=>(!q||[s.customer_name,s.reference_number,s.original_filename].some(v=>v?.toLocaleLowerCase().includes(q)))&&(!customer||s.counterparty_id===customer)&&(!financial||s.financial_state===financial)&&(!review||s.document_status===review));},[sales,search,customer,financial,review]);
 const eligible=selected?.document_status==='approved'&&selected.counterparty_id&&selected.document_date&&selected.total_amount&&!selected.receivable_id;
 const createReceivable=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected||!eligible)return;const f=new FormData(e.currentTarget),r=await fetch('/api/obligations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({direction:'receivable',counterparty_id:selected.counterparty_id,document_id:selected.id,original_amount:selected.total_amount,recognized_on:selected.document_date,due_on:f.get('due_on')||null,verification_status:'unconfirmed',source_type:'document',source_note:null})});if(r.status===401){onUnauthorized();return;}if(!r.ok){setError(true);return;}setCreating(false);setError(false);await load();};
 if(!canView)return <WorkspacePage><WorkspaceState>{t('sales.noAccess')}</WorkspaceState></WorkspacePage>;
 return <WorkspacePage labelledBy="sales-title"><PageHeader titleId="sales-title" eyebrow={t('sales.title')} title={t('sales.title')} description={t('sales.description')}/>{error&&<WorkspaceState tone="error" action={<button onClick={()=>void load()}>{t('common.retry')}</button>}>{t('sales.error')}</WorkspaceState>}{!sales?<WorkspaceState>{t('common.loading')}</WorkspaceState>:<div className="shared-workspace-page__content">
  <WorkspaceToolbar search={<label>{t('sales.search')}<input type="search" value={search} placeholder={t('sales.searchPlaceholder')} onChange={e=>setSearch(e.target.value)}/></label>} filters={<><label>{t('sales.customer')}<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">{t('sales.all')}</option>{customers.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>{t('sales.financialState')}<select value={financial} onChange={e=>setFinancial(e.target.value)}><option value="">{t('sales.all')}</option>{['open','partial','paid','overdue'].map(x=><option key={x} value={x}>{t(`sales.states.${x}`)}</option>)}</select></label><label>{t('sales.reviewState')}<select value={review} onChange={e=>setReview(e.target.value)}><option value="">{t('sales.all')}</option>{['uploaded','needs_review','approved','incomplete','rejected'].map(x=><option key={x} value={x}>{t(`documents.statuses.${x}`)}</option>)}</select></label></>} resultCount={t('sales.resultCount',{count:rows.length})} clearAction={(search||customer||financial||review)?<button onClick={()=>{setSearch('');setCustomer('');setFinancial('');setReview('')}}>{t('sales.clearFilters')}</button>:undefined}/>
  <DataWorkspace withDetail={Boolean(selected)}><div className="responsive-table"><table><thead><tr>{['customer','reference','date','total','collected','remaining','due','financialState','reviewState'].map(x=><th key={x}>{t(`sales.${x}`)}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id} tabIndex={0} aria-selected={selected?.id===s.id} onClick={()=>setSelected(s)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(s)}}}><td>{s.customer_name??t('sales.unknown')}</td><td>{s.reference_number??s.original_filename}</td><td>{s.document_date??t('sales.unknown')}</td><td>{s.total_amount??t('sales.unknown')}</td><td>{s.collected_amount}</td><td>{s.remaining_amount??t('sales.unknown')}</td><td>{s.due_on??t('sales.unknown')}</td><td><StatusBadge status={s.financial_state}>{t(`sales.states.${s.financial_state}`)}</StatusBadge></td><td><StatusBadge status={s.document_status}>{t(`documents.statuses.${s.document_status}`)}</StatusBadge></td></tr>)}</tbody></table>{rows.length===0&&<WorkspaceState>{t('sales.noResults')}</WorkspaceState>}</div>
  {selected&&<DetailPane label={t('sales.detail')}><div className="shared-detail-pane__header"><h2>{selected.reference_number??selected.original_filename}</h2><button onClick={()=>setSelected(null)} aria-label={t('common.close')}>×</button></div><dl><dt>{t('sales.customer')}</dt><dd>{selected.customer_name??t('sales.unknown')}</dd><dt>{t('sales.reviewState')}</dt><dd>{t(`documents.statuses.${selected.document_status}`)}</dd><dt>{t('sales.receivable')}</dt><dd>{selected.receivable_id?t('sales.linked'):t('sales.notCreated')}</dd><dt>{t('sales.original')}</dt><dd>{selected.original_amount??selected.total_amount??t('sales.unknown')}</dd><dt>{t('sales.collected')}</dt><dd>{selected.collected_amount}</dd><dt>{t('sales.remaining')}</dt><dd>{selected.remaining_amount??t('sales.unknown')}</dd><dt>{t('sales.due')}</dt><dd>{selected.due_on??t('sales.unknown')}</dd></dl><h3>{t('sales.collections')}</h3>{selected.settlement_history.length?<ul>{selected.settlement_history.map(s=><li key={s.id}>{s.transaction_date} — {s.amount} — {s.description??s.bank_reference??t('sales.unknown')}</li>)}</ul>:<p>{t('sales.noCollections')}</p>}<div className="shared-detail-pane__actions"><a className="button" href={`/api/documents/${selected.id}/file`} target="_blank" rel="noreferrer">{t('sales.openDocument')}</a>{canCreateReceivable&&eligible&&<button onClick={()=>setCreating(true)}>{t('sales.createReceivable')}</button>}</div></DetailPane>}</DataWorkspace></div>}
  {creating&&selected&&<Dialog title={t('sales.createReceivable')} onClose={()=>setCreating(false)}><form onSubmit={e=>void createReceivable(e)}><p>{t('sales.receivableExplanation')}</p><label>{t('sales.due')}<input name="due_on" type="date" min={selected.document_date??undefined}/></label><button type="submit">{t('common.confirm')}</button></form></Dialog>}
 </WorkspacePage>;
}
