import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { formatDisplayDate } from '../date-format';
import { Dialog } from './Dialog';
import { DataWorkspace, DetailPane, Metric, MetricStrip, PageHeader, SectionCard, StatusBadge, WorkspacePage, WorkspaceState, WorkspaceToolbar } from './SharedUI';
import { VatReportActions } from './VatReportActions';
import { readQueryParameter } from '../navigation/queryState';

type Blockers={unapproved_documents:number;missing_reviews:number;pending_reviews:number;total:number};
type Period={id:string;fiscal_year_id:string;period_start:string;period_end:string;status:'open'|'closed';ready:boolean;blockers:Blockers};
type FiscalYear={id:string;name:string;start_date:string;end_date:string};
type VatDocument={id:string;status:string;original_filename:string;document_type:'purchase'|'expense'|'sale';document_date:string|null;counterparty_name:string|null;total_amount:string|null;review_id:string|null;tax_date:string|null;treatment:'standard'|'zero_rated'|'exempt'|'out_of_scope'|null;taxable_amount:string|null;vat_amount:string|null;review_status:'pending'|'reviewed'|null;review_note:string|null;version:number|null};
interface Props{canView:boolean;canReview:boolean;canClose:boolean;canReopen:boolean;onUnauthorized:()=>void;selectedPeriodId?:string|null}
async function api(url:string,options:RequestInit,onUnauthorized:()=>void){const response=await fetch(url,{credentials:'same-origin',...options});if(response.status===401)onUnauthorized();if(!response.ok)throw new Error(String(response.status));return response;}

export function Vat({canView,canReview,canClose,canReopen,onUnauthorized,selectedPeriodId}:Props){
 const {t,i18n}=useTranslation();const [periods,setPeriods]=useState<Period[]>([]);const [years,setYears]=useState<FiscalYear[]>([]);const [selectedId,setSelectedId]=useState<string|null>(null);const [documents,setDocuments]=useState<VatDocument[]>([]);const [selectedDocument,setSelectedDocument]=useState<VatDocument|null>(null);const [search,setSearch]=useState('');const [reviewFilter,setReviewFilter]=useState('');const [typeFilter,setTypeFilter]=useState('');const [treatmentFilter,setTreatmentFilter]=useState('');const [loading,setLoading]=useState(canView);const [error,setError]=useState(false);const [creating,setCreating]=useState(false);const [editing,setEditing]=useState<VatDocument|null>(null);const [reopen,setReopen]=useState<Period|null>(null);const [saving,setSaving]=useState(false);
 const selected=periods.find(p=>p.id===selectedId)??null;
 const loadPeriods=async()=>{setLoading(true);setError(false);try{const [p,y]=await Promise.all([api('/api/vat-periods',{},onUnauthorized),api('/api/fiscal-years',{},onUnauthorized)]);const next=((await p.json()) as {periods:Period[]}).periods;const from=readQueryParameter('vatFrom'),to=readQueryParameter('vatTo');const requested=from&&to?next.find(period=>period.period_start===from&&period.period_end===to):null;setPeriods(next);setYears(((await y.json()) as {fiscalYears:FiscalYear[]}).fiscalYears);setSelectedId(current=>requested?.id??(current&&next.some(x=>x.id===current)?current:(next[0]?.id??null)));}catch{setError(true)}finally{setLoading(false)}};
 const loadDetail=async(id:string)=>{try{const response=await api(`/api/vat-periods/${id}`,{},onUnauthorized);const data=await response.json() as {period:Period;documents:VatDocument[]};setPeriods(current=>current.map(p=>p.id===id?data.period:p));setDocuments(data.documents);setSelectedDocument(current=>current?data.documents.find(document=>document.id===current.id)??null:null);}catch{setError(true)}};
 useEffect(()=>{if(canView)void loadPeriods();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[canView]);
 useEffect(()=>{if(selectedId)void loadDetail(selectedId);else setDocuments([]);// eslint-disable-next-line react-hooks/exhaustive-deps
 },[selectedId]);
 useEffect(()=>{if(selectedPeriodId&&periods.length>0){const globalPeriod=periods.find(p=>p.id===selectedPeriodId);if(globalPeriod&&selectedId!==globalPeriod.id){setSelectedId(globalPeriod.id);}}},[selectedPeriodId,periods]);
 const totals=useMemo(()=>documents.reduce((acc,d)=>{if(d.review_status!=='reviewed'||!d.vat_amount)return acc;const amount=Number(d.vat_amount);if(d.document_type==='sale')acc.output+=amount;else acc.input+=amount;return acc},{input:0,output:0}),[documents]);
 const visibleDocuments=useMemo(()=>{const query=search.trim().toLocaleLowerCase();return documents.filter(d=>(!query||[d.original_filename,d.counterparty_name,d.review_note].some(value=>value?.toLocaleLowerCase().includes(query)))&&(!reviewFilter||(reviewFilter==='not_reviewed'?!d.review_status:d.review_status===reviewFilter))&&(!typeFilter||d.document_type===typeFilter)&&(!treatmentFilter||d.treatment===treatmentFilter))},[documents,search,reviewFilter,typeFilter,treatmentFilter]);
 const ar=i18n.language.startsWith('ar');
 if(!canView)return <WorkspacePage><WorkspaceState>{t('vat.noAccess')}</WorkspaceState></WorkspacePage>;
 const refresh=async()=>{await loadPeriods();if(selectedId)await loadDetail(selectedId)};
 const create=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);setSaving(true);try{await api('/api/vat-periods',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({fiscal_year_id:data.get('fiscal_year_id'),period_start:data.get('period_start'),period_end:data.get('period_end')})},onUnauthorized);setCreating(false);await loadPeriods()}catch{setError(true)}finally{setSaving(false)}};
 const close=async(period:Period)=>{setSaving(true);try{await api(`/api/vat-periods/${period.id}/close`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'},onUnauthorized);await refresh()}catch{setError(true)}finally{setSaving(false)}};
 const submitReopen=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!reopen)return;const reason=String(new FormData(event.currentTarget).get('reason')??'').trim();if(!reason)return;setSaving(true);try{await api(`/api/vat-periods/${reopen.id}/reopen`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason})},onUnauthorized);setReopen(null);await refresh()}catch{setError(true)}finally{setSaving(false)}};
 const saveReview=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editing)return;const data=new FormData(event.currentTarget);const status=String(data.get('review_status'));const body=status==='pending'?{tax_date:data.get('tax_date'),treatment:null,taxable_amount:null,vat_amount:null,review_status:'pending',review_note:data.get('review_note')||null,...(editing.version?{version:editing.version}:{})}:{tax_date:data.get('tax_date'),treatment:data.get('treatment'),taxable_amount:String(data.get('taxable_amount')??''),vat_amount:String(data.get('vat_amount')??''),review_status:'reviewed',review_note:data.get('review_note')||null,...(editing.version?{version:editing.version}:{})};setSaving(true);try{await api(`/api/documents/${editing.id}/vat-review`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)},onUnauthorized);setEditing(null);if(selectedId)await loadDetail(selectedId);await loadPeriods()}catch{setError(true)}finally{setSaving(false)}};
 return <WorkspacePage labelledBy="vat-title">
  <PageHeader titleId="vat-title" eyebrow={t('vat.title')} title={t('vat.title')} description={t('vat.description')} action={canClose?<button className="primary" onClick={()=>setCreating(true)}>{t('vat.createPeriod')}</button>:undefined}/>
  {error&&<WorkspaceState tone="error" action={<button onClick={()=>void refresh()}>{t('common.retry')}</button>}>{t('vat.error')}</WorkspaceState>}
  {loading?<WorkspaceState>{t('vat.loading')}</WorkspaceState>:periods.length===0?<WorkspaceState>{t('vat.empty')}</WorkspaceState>:<div className="shared-workspace-page__content">
   <WorkspaceToolbar className="vat-period-toolbar" filters={<label>{t('vat.period')}<select value={selectedId??''} onChange={e=>{setSelectedId(e.target.value);setSelectedDocument(null)}}>{periods.map(p=><option key={p.id} value={p.id}>{formatDisplayDate(p.period_start,i18n.language)} — {formatDisplayDate(p.period_end,i18n.language)}</option>)}</select></label>}/>
   {selected&&<SectionCard className={`vat-readiness ${selected.status}`}><div className="fiscal-year-card-header"><h3>{formatDisplayDate(selected.period_start,i18n.language)} — {formatDisplayDate(selected.period_end,i18n.language)}</h3><StatusBadge status={selected.status}>{t(`vat.${selected.status}`)}</StatusBadge></div><p><strong>{selected.ready?t('vat.ready'):t('vat.blocked',{count:selected.blockers.total})}</strong></p>{!selected.ready&&<ul><li>{t('vat.unapproved',{count:selected.blockers.unapproved_documents})}</li><li>{t('vat.missingReviews',{count:selected.blockers.missing_reviews})}</li><li>{t('vat.pendingReviews',{count:selected.blockers.pending_reviews})}</li></ul>}<div className="fiscal-year-actions">{canClose&&selected.status==='open'&&<button className="danger" disabled={!selected.ready||saving} onClick={()=>void close(selected)}>{t('vat.closePeriod')}</button>}{canReopen&&selected.status==='closed'&&<button disabled={saving} onClick={()=>setReopen(selected)}>{t('vat.reopenPeriod')}</button>}{selected.status==='closed'&&<VatReportActions periodId={selected.id} language={i18n.language} onError={()=>setError(true)}/>}</div></SectionCard>}
   <MetricStrip><Metric label={t('vat.outputVat')} value={totals.output.toFixed(2)}/><Metric label={t('vat.inputVat')} value={totals.input.toFixed(2)}/><Metric label={t('vat.netVat')} value={(totals.output-totals.input).toFixed(2)}/></MetricStrip>
   <WorkspaceToolbar search={<label>{t('vat.search')}<input type="search" value={search} placeholder={t('vat.searchPlaceholder')} onChange={e=>setSearch(e.target.value)}/></label>} filters={<><label>{t('vat.reviewStatus')}<select value={reviewFilter} onChange={e=>setReviewFilter(e.target.value)}><option value="">{t('vat.all')}</option><option value="reviewed">{t('vat.reviewed')}</option><option value="pending">{t('vat.pending')}</option><option value="not_reviewed">{t('vat.notReviewed')}</option></select></label><label>{t('vat.type')}<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">{t('vat.all')}</option>{['purchase','expense','sale'].map(x=><option key={x} value={x}>{t(`documents.intake.types.${x}`)}</option>)}</select></label><label>{t('vat.treatment')}<select value={treatmentFilter} onChange={e=>setTreatmentFilter(e.target.value)}><option value="">{t('vat.all')}</option>{['standard','zero_rated','exempt','out_of_scope'].map(x=><option key={x} value={x}>{t(`vat.treatments.${x}`)}</option>)}</select></label></>} resultCount={t('vat.resultCount',{count:visibleDocuments.length})} clearAction={(search||reviewFilter||typeFilter||treatmentFilter)?<button onClick={()=>{setSearch('');setReviewFilter('');setTypeFilter('');setTreatmentFilter('')}}>{t('vat.clearFilters')}</button>:undefined}/>
   {documents.length===0?<WorkspaceState>{t('vat.noDocuments')}</WorkspaceState>:<DataWorkspace withDetail={Boolean(selectedDocument)}><div className="table-wrap"><table><thead><tr><th>{t('vat.document')}</th><th>{ar?'العميل / المورد':'Customer / Supplier'}</th><th>{t('vat.documentDate')}</th><th>{t('vat.type')}</th><th>{t('vat.total')}</th><th>{t('vat.vatAmount')}</th><th>{t('vat.reviewStatus')}</th><th>{t('vat.actions')}</th></tr></thead><tbody>{visibleDocuments.map(d=><tr key={d.id} tabIndex={0} aria-selected={selectedDocument?.id===d.id} onClick={()=>setSelectedDocument(d)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelectedDocument(d)}}}><td>{d.original_filename}</td><td>{d.counterparty_name??'—'}</td><td>{d.document_date?formatDisplayDate(d.document_date,i18n.language):'—'}</td><td>{t(`documents.intake.types.${d.document_type}`)}</td><td>{d.total_amount??'—'}</td><td>{d.vat_amount??'—'}</td><td>{d.review_status?t(`vat.${d.review_status}`):d.status==='approved'?t('vat.notReviewed'):t('vat.documentNotApproved')}</td><td>{canReview&&selected?.status==='open'&&d.status==='approved'?<button onClick={event=>{event.stopPropagation();setEditing(d)}}>{d.review_id?t('vat.editReview'):t('vat.review')}</button>:'—'}</td></tr>)}</tbody></table>{visibleDocuments.length===0&&<WorkspaceState>{t('vat.noResults')}</WorkspaceState>}</div>{selectedDocument&&<DetailPane label={t('vat.documentDetails')}><div className="shared-detail-pane__header"><h2>{selectedDocument.original_filename}</h2><button onClick={()=>setSelectedDocument(null)} aria-label={t('common.close')}>×</button></div><dl><dt>{t('vat.taxDate')}</dt><dd>{selectedDocument.tax_date?formatDisplayDate(selectedDocument.tax_date,i18n.language):'—'}</dd><dt>{t('vat.treatment')}</dt><dd>{selectedDocument.treatment?t(`vat.treatments.${selectedDocument.treatment}`):'—'}</dd><dt>{t('vat.taxable')}</dt><dd>{selectedDocument.taxable_amount??'—'}</dd><dt>{t('vat.vatAmount')}</dt><dd>{selectedDocument.vat_amount??'—'}</dd><dt>{t('vat.note')}</dt><dd>{selectedDocument.review_note??'—'}</dd></dl></DetailPane>}</DataWorkspace>}
  </div>}
  {creating&&<Dialog title={t('vat.createPeriod')} busy={saving} onClose={()=>setCreating(false)}><form className="form-grid" onSubmit={create}><label>{t('vat.fiscalYear')}<select name="fiscal_year_id" required>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>{t('vat.start')}<input name="period_start" type="date" required/></label><label>{t('vat.end')}<input name="period_end" type="date" required/></label><div className="modal-actions"><button type="button" onClick={()=>setCreating(false)}>{t('common.cancel')}</button><button className="primary" disabled={saving}>{t('common.save')}</button></div></form></Dialog>}
  {editing&&<Dialog title={t('vat.review')} busy={saving} onClose={()=>setEditing(null)}><form className="form-grid" onSubmit={saveReview}><label>{t('vat.taxDate')}<input name="tax_date" type="date" required defaultValue={editing.tax_date??editing.document_date??''}/></label><label>{t('vat.reviewStatus')}<select name="review_status" defaultValue={editing.review_status??'reviewed'}><option value="reviewed">{t('vat.reviewed')}</option><option value="pending">{t('vat.pending')}</option></select></label><label>{t('vat.treatment')}<select name="treatment" defaultValue={editing.treatment??'standard'}><option value="standard">{t('vat.treatments.standard')}</option><option value="zero_rated">{t('vat.treatments.zero_rated')}</option><option value="exempt">{t('vat.treatments.exempt')}</option><option value="out_of_scope">{t('vat.treatments.out_of_scope')}</option></select></label><label>{t('vat.taxable')}<input name="taxable_amount" inputMode="decimal" defaultValue={editing.taxable_amount??''}/></label><label>{t('vat.vatAmount')}<input name="vat_amount" inputMode="decimal" defaultValue={editing.vat_amount??''}/></label><label>{t('vat.note')}<textarea name="review_note" maxLength={500} defaultValue={editing.review_note??''}/></label><div className="modal-actions"><button type="button" onClick={()=>setEditing(null)}>{t('common.cancel')}</button><button className="primary" disabled={saving}>{t('common.save')}</button></div></form></Dialog>}
  {reopen&&<Dialog title={t('vat.reopenPeriod')} busy={saving} onClose={()=>setReopen(null)}><form className="form-grid" onSubmit={submitReopen}><label>{t('vat.reason')}<textarea name="reason" required maxLength={500}/></label><div className="modal-actions"><button type="button" onClick={()=>setReopen(null)}>{t('common.cancel')}</button><button className="primary" disabled={saving}>{t('vat.reopenPeriod')}</button></div></form></Dialog>}
 </WorkspacePage>;
}
