import { useState } from 'react';

type Report={
  company:{name:string};
  period:{period_start:string;period_end:string;status:'closed'};
  totals:{output_vat:number;input_vat:number;net_vat:number;sales_total:number;purchase_expense_total:number};
  treatments:Record<string,{count:number;taxable_amount:number;vat_amount:number}>;
  documents:Array<{original_filename:string;counterparty_name:string|null;document_type:string;document_date:string|null;tax_date:string;treatment:string;total_amount:string|null;taxable_amount:string;vat_amount:string}>;
};
interface Props{periodId:string;language:string;onError:()=>void}
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(v:number|string|null)=>Number(v??0).toFixed(2);

export function VatReportActions({periodId,language,onError}:Props){
 const [busy,setBusy]=useState(false); const ar=language.startsWith('ar');
 const typeLabel=(value:string)=>({purchase:ar?'شراء':'Purchase',expense:ar?'مصروف':'Expense',sale:ar?'بيع':'Sale'}[value]??value);
 const treatmentLabel=(value:string)=>({standard:ar?'النسبة الأساسية':'Standard',zero_rated:ar?'نسبة صفر':'Zero rated',exempt:ar?'معفى':'Exempt',out_of_scope:ar?'خارج النطاق':'Out of scope'}[value]??value);
 const print=async()=>{if(busy)return;const popup=window.open('','_blank');if(!popup){onError();return}setBusy(true);try{const response=await fetch(`/api/vat-periods/${periodId}/report`,{credentials:'same-origin'});if(!response.ok)throw new Error(String(response.status));const r=await response.json() as Report;const generatedAt=new Intl.DateTimeFormat(ar?'ar-SA':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date());
 const treatments=[['standard',treatmentLabel('standard')],['zero_rated',treatmentLabel('zero_rated')],['exempt',treatmentLabel('exempt')],['out_of_scope',treatmentLabel('out_of_scope')]];
 popup.document.write(`<!doctype html><html dir="${ar?'rtl':'ltr'}"><head><meta charset="utf-8"><title>${ar?'تقرير إقفال ضريبة القيمة المضافة':'VAT Closing Report'}</title><style>body{font-family:Arial,sans-serif;margin:32px;color:#152536}h1{margin-bottom:4px}small{color:#64748b}.meta{display:flex;gap:18px;flex-wrap:wrap;margin-top:8px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}.card{border:1px solid #dbe3ea;border-radius:8px;padding:12px}table{width:100%;border-collapse:collapse;font-size:12px;margin-top:20px}th,td{border:1px solid #dbe3ea;padding:7px;text-align:start}th{background:#f5f7f9}@media print{button{display:none}body{margin:12mm}}</style></head><body><button onclick="window.print()">${ar?'طباعة / حفظ PDF':'Print / Save PDF'}</button><h1>${ar?'تقرير إقفال ضريبة القيمة المضافة':'VAT Closing Report'}</h1><small>${esc(r.company.name)} · ${esc(r.period.period_start)} — ${esc(r.period.period_end)}</small><div class="meta"><strong>${ar?'حالة الفترة: مقفلة':'Period status: Closed'}</strong><span>${ar?'تاريخ إنشاء التقرير':'Generated at'}: ${esc(generatedAt)}</span></div><div class="summary"><div class="card">${ar?'ضريبة المخرجات':'Output VAT'}<br><strong>${money(r.totals.output_vat)}</strong></div><div class="card">${ar?'ضريبة المدخلات':'Input VAT'}<br><strong>${money(r.totals.input_vat)}</strong></div><div class="card">${ar?'صافي الضريبة':'Net VAT'}<br><strong>${money(r.totals.net_vat)}</strong></div></div><h2>${ar?'ملخص المعالجة':'Treatment summary'}</h2><table><thead><tr><th>${ar?'المعالجة':'Treatment'}</th><th>${ar?'العدد':'Count'}</th><th>${ar?'الخاضع':'Taxable'}</th><th>${ar?'الضريبة':'VAT'}</th></tr></thead><tbody>${treatments.map(([k,label])=>`<tr><td>${label}</td><td>${r.treatments[k]?.count??0}</td><td>${money(r.treatments[k]?.taxable_amount??0)}</td><td>${money(r.treatments[k]?.vat_amount??0)}</td></tr>`).join('')}</tbody></table><h2>${ar?'تفاصيل المستندات':'Document details'}</h2><table><thead><tr><th>${ar?'المستند':'Document'}</th><th>${ar?'العميل / المورد':'Customer / Supplier'}</th><th>${ar?'النوع':'Type'}</th><th>${ar?'تاريخ المستند':'Document date'}</th><th>${ar?'التاريخ الضريبي':'Tax date'}</th><th>${ar?'الإجمالي':'Total'}</th><th>${ar?'المعالجة':'Treatment'}</th><th>${ar?'الخاضع':'Taxable'}</th><th>${ar?'الضريبة':'VAT'}</th></tr></thead><tbody>${r.documents.map(d=>`<tr><td>${esc(d.original_filename)}</td><td>${esc(d.counterparty_name??'—')}</td><td>${esc(typeLabel(d.document_type))}</td><td>${esc(d.document_date??'—')}</td><td>${esc(d.tax_date)}</td><td>${money(d.total_amount)}</td><td>${esc(treatmentLabel(d.treatment))}</td><td>${money(d.taxable_amount)}</td><td>${money(d.vat_amount)}</td></tr>`).join('')}</tbody></table></body></html>`);popup.document.close();}catch{popup.close();onError()}finally{setBusy(false)}};
 const xlsx=async()=>{if(busy)return;setBusy(true);try{const response=await fetch(`/api/vat-periods/${periodId}/working-paper.xlsx`,{credentials:'same-origin'});const type=response.headers.get('content-type')??'';if(!response.ok||!type.includes('spreadsheetml'))throw new Error(String(response.status));const blob=await response.blob();const name=/filename="([^"]+)"/.exec(response.headers.get('content-disposition')??'')?.[1]??'vat-working-paper.xlsx';const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}catch{onError()}finally{setBusy(false)}};
 return <div className="fiscal-year-actions"><button disabled={busy} onClick={()=>void print()}>{ar?'تقرير إقفال الضريبة':'VAT Closing Report'}</button><button disabled={busy} onClick={()=>void xlsx()}>{ar?'تحميل ملف Excel':'Download Excel'}</button></div>;
}
