import { NextFunction, Request, RequestHandler, Response, Router } from 'express';
import { Pool, PoolClient } from 'pg';
import pool from '../../db/pool';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { getAuthenticatedContext, requireActiveCompany, requireAuth, requireCapability } from '../auth/auth.middleware';
import { requireSameOrigin } from '../auth/origin.middleware';
import { assertAccountingDateWritable } from '../monthly-close/accounting-period.guard';

export const vatAdjustmentsRouter=Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MONEY=/^-?(0|[1-9]\d*)(\.\d{1,2})?$/;
const TYPES=['late_document','credit_note','debit_note','tax_date_correction','treatment_correction','recoverability_correction','amount_correction','other'] as const;
type AdjustmentType=typeof TYPES[number];
type Adjustment={id:string;company_id:string;document_vat_review_id:string;original_vat_period_id:string;adjustment_vat_period_id:string;adjustment_type:AdjustmentType;reason:string;taxable_amount_delta:string;vat_amount_delta:string;recoverable_vat_amount_delta:string;status:'draft'|'reviewed'|'applied';created_by_user_id:string;reviewed_by_user_id:string|null;reviewed_at:Date|null;version:number};
export class VatAdjustmentValidationError extends Error{}
export class VatAdjustmentNotFoundError extends Error{}
export class VatAdjustmentConflictError extends Error{constructor(message='Conflict'){super(message)}}
const route=(handler:(req:Request,res:Response)=>Promise<void>):RequestHandler=>(req,res,next:NextFunction)=>void handler(req,res).catch(next);
const context=(req:Request)=>getAuthenticatedContext(req)! as ReturnType<typeof getAuthenticatedContext>&{activeCompanyId:string};
const cents=(value:string)=>{const negative=value.startsWith('-');const raw=negative?value.slice(1):value;const [whole,fraction='']=raw.split('.');const result=BigInt(whole!)*100n+BigInt(fraction.padEnd(2,'0'));return negative?-result:result;};
function parseBody(body:unknown,partial=false){
  if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;
  const allowed=partial?['reason','adjustment_type','taxable_amount_delta','vat_amount_delta','recoverable_vat_amount_delta','version']:['document_vat_review_id','original_vat_period_id','adjustment_vat_period_id','adjustment_type','reason','taxable_amount_delta','vat_amount_delta','recoverable_vat_amount_delta'];
  if(Object.keys(x).some(key=>!allowed.includes(key)))return null;
  for(const key of ['document_vat_review_id','original_vat_period_id','adjustment_vat_period_id'])if(!partial&&(typeof x[key]!=='string'||!UUID.test(x[key] as string)))return null;
  if(typeof x.adjustment_type!=='string'||!TYPES.includes(x.adjustment_type as AdjustmentType)||typeof x.reason!=='string'||x.reason.trim().length<1||x.reason.trim().length>500)return null;
  const values={taxable:x.taxable_amount_delta??'0',vat:x.vat_amount_delta??'0',recoverable:x.recoverable_vat_amount_delta??'0'};
  if(Object.values(values).some(value=>typeof value!=='string'||!MONEY.test(value)))return null;
  if(cents(values.taxable as string)===0n&&cents(values.vat as string)===0n&&cents(values.recoverable as string)===0n)return null;
  const version=x.version===undefined?undefined:x.version;if(version!==undefined&&(typeof version!=='number'||!Number.isInteger(version)||version<1))return null;
  return{documentId:x.document_vat_review_id as string|undefined,originalId:x.original_vat_period_id as string|undefined,adjustmentId:x.adjustment_vat_period_id as string|undefined,type:x.adjustment_type as AdjustmentType,reason:(x.reason as string).trim(),taxable:values.taxable as string,vat:values.vat as string,recoverable:values.recoverable as string,version:version as number|undefined};
}
function versionBody(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const value=(body as Record<string,unknown>).version;return typeof value==='number'&&Number.isInteger(value)&&value>=1&&Object.keys(body).length===1?value:null;}
async function lock(company:string,date:string,client:PoolClient){await client.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`vat-period:${company}:${date.slice(0,7)}`]);}
export class VatAdjustmentService{
  private audit=new AuditLogRepository();constructor(private db:Pool){}
  private async tx<T>(fn:(client:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const value=await fn(c);await c.query('COMMIT');return value;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
  private select=`SELECT a.*,r.tax_date::text,d.document_type,vpo.status original_period_status,vpa.status adjustment_period_status FROM vat_adjustments a JOIN document_vat_reviews r ON r.id=a.document_vat_review_id AND r.company_id=a.company_id JOIN documents d ON d.id=r.document_id AND d.company_id=r.company_id JOIN vat_periods vpo ON vpo.id=a.original_vat_period_id AND vpo.company_id=a.company_id JOIN vat_periods vpa ON vpa.id=a.adjustment_vat_period_id AND vpa.company_id=a.company_id`;
  async list(company:string){return(await this.db.query(`${this.select} WHERE a.company_id=$1 ORDER BY a.created_at DESC`,[company])).rows;}
  async get(company:string,id:string){const row=(await this.db.query(`${this.select} WHERE a.id=$1 AND a.company_id=$2`,[id,company])).rows[0];if(!row)throw new VatAdjustmentNotFoundError();return row;}
  async create(company:string,actor:string,input:NonNullable<ReturnType<typeof parseBody>>){return this.tx(async c=>{const review=(await c.query<{tax_date:string;review_status:string;document_type:string;vat_amount:string;recoverable_vat_amount:string|null}>(`SELECT r.tax_date::text,r.review_status,d.document_type,r.vat_amount::text,r.recoverable_vat_amount::text FROM document_vat_reviews r JOIN documents d ON d.id=r.document_id AND d.company_id=r.company_id WHERE r.id=$1 AND r.company_id=$2 AND d.status='approved' AND d.document_type IN ('purchase','expense','sale') FOR UPDATE`,[input.documentId,company])).rows[0];if(!review||review.review_status!=='reviewed')throw new VatAdjustmentConflictError('Reviewed VAT review is required');const p=(await c.query<{original_status:string;adjustment_status:string;period_start:string}>('SELECT o.status original_status,a.status adjustment_status,a.period_start::text FROM vat_periods o JOIN vat_periods a ON a.id=$3 AND a.company_id=$1 WHERE o.id=$2 AND o.company_id=$1 AND $4::date BETWEEN o.period_start AND o.period_end FOR UPDATE',[company,input.originalId,input.adjustmentId,review.tax_date])).rows[0];if(!p)throw new VatAdjustmentNotFoundError();if(p.original_status!=='closed')throw new VatAdjustmentConflictError('Original VAT period must be closed');if(p.adjustment_status!=='open')throw new VatAdjustmentConflictError('Adjustment VAT period must be open');await lock(company,p.period_start,c);await assertAccountingDateWritable(company,p.period_start,c);if(review.document_type==='sale'&&cents(input.recoverable)!==0n)throw new VatAdjustmentValidationError('Sales cannot have recoverable VAT delta');const row=(await c.query<Adjustment>(`INSERT INTO vat_adjustments(company_id,document_vat_review_id,original_vat_period_id,adjustment_vat_period_id,adjustment_type,reason,taxable_amount_delta,vat_amount_delta,recoverable_vat_amount_delta,status,created_by_user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'draft',$10) RETURNING *`,[company,input.documentId,input.originalId,input.adjustmentId,input.type,input.reason,input.taxable,input.vat,input.recoverable,actor])).rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'vat_adjustment.create',entity_type:'vat_adjustment',entity_id:row.id,before_data:null,after_data:row as never,reason:input.reason},c);return row;});}
  async update(company:string,actor:string,id:string,input:NonNullable<ReturnType<typeof parseBody>>){return this.tx(async c=>{const old=(await c.query<Adjustment>('SELECT * FROM vat_adjustments WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,company])).rows[0];if(!old)throw new VatAdjustmentNotFoundError();if(old.status!=='draft')throw new VatAdjustmentConflictError('Only draft adjustments can be edited');if(input.version!==undefined&&input.version!==old.version)throw new VatAdjustmentConflictError('Adjustment was modified');const period=(await c.query<{status:string}>('SELECT status FROM vat_periods WHERE id=$1 AND company_id=$2',[old.adjustment_vat_period_id,company])).rows[0];if(!period||period.status!=='open')throw new VatAdjustmentConflictError('Adjustment VAT period is closed');const next=(await c.query<Adjustment>('UPDATE vat_adjustments SET adjustment_type=$3,reason=$4,taxable_amount_delta=$5,vat_amount_delta=$6,recoverable_vat_amount_delta=$7,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *',[id,company,input.type,input.reason,input.taxable,input.vat,input.recoverable])).rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'vat_adjustment.update',entity_type:'vat_adjustment',entity_id:id,before_data:old as never,after_data:next as never,reason:input.reason},c);return next;});}
  async transition(company:string,actor:string,id:string,target:'reviewed'|'applied',expected:number){return this.tx(async c=>{const old=(await c.query<Adjustment>('SELECT * FROM vat_adjustments WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,company])).rows[0];if(!old)throw new VatAdjustmentNotFoundError();if((target==='reviewed'&&old.status!=='draft')||(target==='applied'&&old.status!=='reviewed'))throw new VatAdjustmentConflictError('Invalid adjustment transition');if(old.version!==expected)throw new VatAdjustmentConflictError('Adjustment was modified');const period=(await c.query<{status:string;period_start:string}>('SELECT status,period_start::text FROM vat_periods WHERE id=$1 AND company_id=$2 FOR UPDATE',[old.adjustment_vat_period_id,company])).rows[0];if(!period||period.status!=='open')throw new VatAdjustmentConflictError('Adjustment VAT period is closed');if(target==='applied'){await lock(company,period.period_start,c);await assertAccountingDateWritable(company,period.period_start,c);const review=(await c.query<{document_type:string;vat_amount:string;recoverable_vat_amount:string|null}>('SELECT d.document_type,r.vat_amount::text,r.recoverable_vat_amount::text FROM document_vat_reviews r JOIN documents d ON d.id=r.document_id AND d.company_id=r.company_id WHERE r.id=$1 AND r.company_id=$2 FOR UPDATE',[old.document_vat_review_id,company])).rows[0]!;if(review.document_type==='sale'&&cents(old.recoverable_vat_amount_delta)!==0n)throw new VatAdjustmentValidationError('Sales cannot have recoverable VAT delta');if(review.document_type!=='sale'){const prior=(await c.query<{vat:string;recoverable:string}>('SELECT COALESCE(SUM(vat_amount_delta),0)::text vat,COALESCE(SUM(recoverable_vat_amount_delta),0)::text recoverable FROM vat_adjustments WHERE company_id=$1 AND document_vat_review_id=$2 AND status=\'applied\' AND id<>$3',[company,old.document_vat_review_id,id])).rows[0]!;const effectiveGross=cents(review.vat_amount)+cents(prior.vat)+cents(old.vat_amount_delta);const effectiveRecoverable=cents(review.recoverable_vat_amount??'0')+cents(prior.recoverable)+cents(old.recoverable_vat_amount_delta);if(effectiveGross<0n||effectiveRecoverable<0n||effectiveRecoverable>effectiveGross)throw new VatAdjustmentConflictError('Recoverable VAT is outside the effective gross VAT bounds');}}
    const next=(await c.query<Adjustment>(`UPDATE vat_adjustments SET status=$3,reviewed_by_user_id=CASE WHEN $3='reviewed' THEN $4 ELSE reviewed_by_user_id END,reviewed_at=CASE WHEN $3='reviewed' THEN NOW() ELSE reviewed_at END,version=version+1,updated_at=NOW() WHERE id=$1 AND company_id=$2 AND status=$5 AND version=$6 RETURNING *`,[id,company,target,actor,target==='reviewed'?'draft':'reviewed',old.version])).rows[0];if(!next)throw new VatAdjustmentConflictError('Adjustment was modified or already applied');await this.audit.logEvent({company_id:company,actor_user_id:actor,action:`vat_adjustment.${target==='reviewed'?'review':'apply'}`,entity_type:'vat_adjustment',entity_id:id,before_data:old as never,after_data:next as never},c);return next;});}
}
function service(res:Response){if(!pool){res.status(503).json({error:'Database unavailable'});return null;}return new VatAdjustmentService(pool);}
function handle(error:unknown,res:Response){if(error instanceof VatAdjustmentValidationError)res.status(400).json({error:error.message});else if(error instanceof VatAdjustmentNotFoundError)res.status(404).json({error:'Not found'});else if(error instanceof VatAdjustmentConflictError)res.status(409).json({error:error.message});else throw error;}
vatAdjustmentsRouter.get('/vat-adjustments',requireAuth,requireActiveCompany,requireCapability('vat.view'),route(async(req,res)=>{const s=service(res);if(s)res.json(await s.list(context(req).activeCompanyId));}));
vatAdjustmentsRouter.get('/vat-adjustments/:id',requireAuth,requireActiveCompany,requireCapability('vat.view'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new VatAdjustmentValidationError('Invalid request');const s=service(res);if(s)res.json(await s.get(context(req).activeCompanyId,req.params.id));}catch(e){handle(e,res);}}));
vatAdjustmentsRouter.post('/vat-adjustments',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.review'),route(async(req,res)=>{try{const i=parseBody(req.body);if(!i)throw new VatAdjustmentValidationError('Invalid request');const s=service(res);if(s)res.status(201).json(await s.create(context(req).activeCompanyId,context(req).user.id,i as never));}catch(e){handle(e,res);}}));
vatAdjustmentsRouter.patch('/vat-adjustments/:id',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.review'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new VatAdjustmentValidationError('Invalid request');const i=parseBody(req.body,true);if(!i)throw new VatAdjustmentValidationError('Invalid request');const s=service(res);if(s)res.json(await s.update(context(req).activeCompanyId,context(req).user.id,req.params.id,i as never));}catch(e){handle(e,res);}}));
for(const [path,target] of [['reviewed','review'],['applied','apply']] as const)vatAdjustmentsRouter.post(`/vat-adjustments/:id/${target}`,requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.review'),route(async(req,res)=>{try{const version=versionBody(req.body);if(!UUID.test(req.params.id)||version===null)throw new VatAdjustmentValidationError('Invalid request');const s=service(res);if(s)res.json(await s.transition(context(req).activeCompanyId,context(req).user.id,req.params.id,path,version));}catch(e){handle(e,res);}}));
