import { NextFunction, Request, RequestHandler, Response, Router } from 'express';
import { Pool, PoolClient } from 'pg';
import pool from '../../db/pool';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { getAuthenticatedContext, requireActiveCompany, requireAuth, requireCapability } from '../auth/auth.middleware';
import { requireSameOrigin } from '../auth/origin.middleware';
import { loadVatClosingReport, VatClosingReport, VatReportNotFoundError, VatReportOpenPeriodError } from './vat-report';

export const vatReturnsRouter = Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
type Status='draft'|'approved'|'filed';
export interface VatReturn { id:string;company_id:string;vat_period_id:string;status:Status;snapshot_json:VatReturnSnapshot|null;approved_by_user_id:string|null;approved_at:Date|null;filed_by_user_id:string|null;filed_at:Date|null;filing_reference:string|null;filing_note:string|null;created_at:Date;updated_at:Date;version:number; }
export interface VatReturnSnapshot extends VatClosingReport { generated_at:string;approved_at:string;source:{kind:'vat_closing_report';vat_return_snapshot_version:1}; }
export class VatReturnValidationError extends Error {}
export class VatReturnNotFoundError extends Error {}
export class VatReturnConflictError extends Error {}
const route=(handler:(req:Request,res:Response)=>Promise<void>):RequestHandler=>(req,res,next:NextFunction)=>void handler(req,res).catch(next);
const context=(req:Request)=>getAuthenticatedContext(req)! as ReturnType<typeof getAuthenticatedContext>&{activeCompanyId:string};
function versionBody(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const value=(body as Record<string,unknown>).version;return typeof value==='number'&&Number.isInteger(value)&&value>=1&&Object.keys(body).length===1?value:null;}
function createBody(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;return Object.keys(x).length===1&&typeof x.vat_period_id==='string'&&UUID.test(x.vat_period_id)?x.vat_period_id:null;}
function filingBody(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;if(Object.keys(x).some(k=>!['version','filing_reference','filing_note'].includes(k))||typeof x.version!=='number'||!Number.isInteger(x.version)||x.version<1||typeof x.filing_reference!=='string'||!x.filing_reference.trim()||(x.filing_note!==undefined&&x.filing_note!==null&&typeof x.filing_note!=='string'))return null;return{version:x.version,reference:x.filing_reference.trim(),note:typeof x.filing_note==='string'?x.filing_note.trim()||null:null};}

export class VatReturnService {
  private audit=new AuditLogRepository();
  constructor(private db:Pool){}
  private async tx<T>(fn:(client:PoolClient)=>Promise<T>){const c=await this.db.connect();try{await c.query('BEGIN');const result=await fn(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');throw error;}finally{c.release();}}
  async list(company:string){return(await this.db.query<VatReturn>('SELECT * FROM vat_returns WHERE company_id=$1 ORDER BY created_at DESC,id',[company])).rows;}
  async get(company:string,id:string){const row=(await this.db.query<VatReturn>('SELECT * FROM vat_returns WHERE id=$1 AND company_id=$2',[id,company])).rows[0];if(!row)throw new VatReturnNotFoundError();return row;}
  async create(company:string,actor:string,periodId:string){return this.tx(async c=>{const period=(await c.query<{status:string}>('SELECT status FROM vat_periods WHERE id=$1 AND company_id=$2 FOR UPDATE',[periodId,company])).rows[0];if(!period)throw new VatReturnNotFoundError();if(period.status!=='closed')throw new VatReturnConflictError('VAT period must be closed');try{const row=(await c.query<VatReturn>("INSERT INTO vat_returns(company_id,vat_period_id,status) VALUES($1,$2,'draft') RETURNING *",[company,periodId])).rows[0]!;await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'vat_return.create',entity_type:'vat_return',entity_id:row.id,before_data:null,after_data:row as never},c);return row;}catch(error){if((error as {code?:string}).code==='23505')throw new VatReturnConflictError('VAT return already exists for this period');throw error;}});}
  async approve(company:string,actor:string,id:string,expectedVersion:number){return this.tx(async c=>{const old=(await c.query<VatReturn>('SELECT * FROM vat_returns WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,company])).rows[0];if(!old)throw new VatReturnNotFoundError();if(old.status!=='draft')throw new VatReturnConflictError('Invalid VAT return transition');if(old.version!==expectedVersion)throw new VatReturnConflictError('VAT return was modified');let report:VatClosingReport;try{report=await loadVatClosingReport(c,company,old.vat_period_id);}catch(error){if(error instanceof VatReportNotFoundError)throw new VatReturnNotFoundError();if(error instanceof VatReportOpenPeriodError)throw new VatReturnConflictError('VAT period must be closed');throw error;}const approvedAt=new Date().toISOString();const outputAdjustment=report.totals.output_vat_adjustments??0;const recoverableAdjustment=report.totals.recoverable_input_vat_adjustments??0;const snapshot:VatReturnSnapshot={...report,totals:{...report.totals,output_vat_adjustments:outputAdjustment,gross_input_vat_adjustments:report.totals.gross_input_vat_adjustments??0,recoverable_input_vat_adjustments:recoverableAdjustment,final_output_vat:report.totals.final_output_vat??report.totals.output_vat+outputAdjustment,final_recoverable_input_vat:report.totals.final_recoverable_input_vat??report.totals.recoverable_input_vat+recoverableAdjustment,base_net_vat:report.totals.base_net_vat??report.totals.output_vat-report.totals.recoverable_input_vat,net_adjustment_effect:report.totals.net_adjustment_effect??outputAdjustment-recoverableAdjustment,final_net_vat:report.totals.final_net_vat??report.totals.output_vat+outputAdjustment-report.totals.recoverable_input_vat-recoverableAdjustment},adjustments:report.adjustments??[],generated_at:approvedAt,approved_at:approvedAt,source:{kind:'vat_closing_report',vat_return_snapshot_version:1}};const next=(await c.query<VatReturn>("UPDATE vat_returns SET status='approved',snapshot_json=$3,approved_by_user_id=$4,approved_at=$5,updated_at=$5,version=version+1 WHERE id=$1 AND company_id=$2 AND status='draft' AND version=$6 RETURNING *",[id,company,snapshot,actor,approvedAt,expectedVersion])).rows[0];if(!next)throw new VatReturnConflictError('VAT return was modified');await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'vat_return.approve',entity_type:'vat_return',entity_id:id,before_data:old as never,after_data:next as never},c);return next;});}
  async file(company:string,actor:string,id:string,input:{version:number;reference:string;note:string|null}){return this.tx(async c=>{const old=(await c.query<VatReturn>('SELECT * FROM vat_returns WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,company])).rows[0];if(!old)throw new VatReturnNotFoundError();if(old.status!=='approved')throw new VatReturnConflictError('Invalid VAT return transition');if(old.version!==input.version)throw new VatReturnConflictError('VAT return was modified');const next=(await c.query<VatReturn>("UPDATE vat_returns SET status='filed',filed_by_user_id=$3,filed_at=NOW(),filing_reference=$4,filing_note=$5,updated_at=NOW(),version=version+1 WHERE id=$1 AND company_id=$2 AND status='approved' AND version=$6 RETURNING *",[id,company,actor,input.reference,input.note,input.version])).rows[0];if(!next)throw new VatReturnConflictError('VAT return was modified');await this.audit.logEvent({company_id:company,actor_user_id:actor,action:'vat_return.file',entity_type:'vat_return',entity_id:id,before_data:old as never,after_data:next as never},c);return next;});}
}
function service(res:Response){if(!pool){res.status(503).json({ error: 'Database unavailable', code: 'DB_UNAVAILABLE' });return null;}return new VatReturnService(pool);}
function handle(error:unknown,res:Response){if(error instanceof VatReturnValidationError)res.status(400).json({error:error.message});else if(error instanceof VatReturnNotFoundError)res.status(404).json({error:'Not found'});else if(error instanceof VatReturnConflictError)res.status(409).json({error:error.message});else throw error;}
vatReturnsRouter.get('/vat-returns',requireAuth,requireActiveCompany,requireCapability('vat.view'),route(async(req,res)=>{const s=service(res);if(s)res.json(await s.list(context(req).activeCompanyId));}));
vatReturnsRouter.get('/vat-returns/:id',requireAuth,requireActiveCompany,requireCapability('vat.view'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new VatReturnValidationError('Invalid request');const s=service(res);if(s)res.json(await s.get(context(req).activeCompanyId,req.params.id));}catch(e){handle(e,res);}}));
vatReturnsRouter.post('/vat-returns',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.close'),route(async(req,res)=>{try{const period=createBody(req.body);if(!period)throw new VatReturnValidationError('Invalid request');const s=service(res);if(s)res.status(201).json(await s.create(context(req).activeCompanyId,context(req).user.id,period));}catch(e){handle(e,res);}}));
vatReturnsRouter.post('/vat-returns/:id/approve',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.close'),route(async(req,res)=>{try{const version=versionBody(req.body);if(!UUID.test(req.params.id)||version===null)throw new VatReturnValidationError('Invalid request');const s=service(res);if(s)res.json(await s.approve(context(req).activeCompanyId,context(req).user.id,req.params.id,version));}catch(e){handle(e,res);}}));
vatReturnsRouter.post('/vat-returns/:id/file',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.close'),route(async(req,res)=>{try{const input=filingBody(req.body);if(!UUID.test(req.params.id)||!input)throw new VatReturnValidationError('Invalid request');const s=service(res);if(s)res.json(await s.file(context(req).activeCompanyId,context(req).user.id,req.params.id,input));}catch(e){handle(e,res);}}));
