import { NextFunction, Request, RequestHandler, Response, Router } from 'express';
import { Pool, PoolClient } from 'pg';
import pool from '../../db/pool';
import { AuditLogRepository } from '../audit-log/audit-log.repository';
import { getAuthenticatedContext, requireActiveCompany, requireAuth, requireCapability } from '../auth/auth.middleware';
import { requireSameOrigin } from '../auth/origin.middleware';
import { assertAccountingDateWritable } from '../monthly-close/accounting-period.guard';
import { CompanyAccountingProfileRepository } from '../company-accounting-profile/company-accounting-profile.repository';
import { loadVatReconciliation } from './vat-reconciliation';

export const vatRouter = Router();
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const DATE=/^\d{4}-\d{2}-\d{2}$/;
const MONEY=/^(0|[1-9]\d*)(\.\d{1,2})?$/;
const TREATMENTS=['standard','zero_rated','exempt','out_of_scope'] as const;
const RECOVERABILITY=['not_applicable','fully_recoverable','non_recoverable','partially_recoverable','needs_review'] as const;
type Treatment=typeof TREATMENTS[number];
type Recoverability=typeof RECOVERABILITY[number];
type Period={id:string;company_id:string;fiscal_year_id:string;period_start:string;period_end:string;status:'open'|'closed';created_at:Date;updated_at:Date};
type VatReview={id:string;company_id:string;document_id:string;tax_date:string;treatment:Treatment|null;taxable_amount:string|null;vat_amount:string|null;review_status:'pending'|'reviewed';reviewed_by_user_id:string|null;reviewed_at:Date|null;review_note:string|null;recoverability_status:Recoverability;recoverable_vat_amount:string|null;recoverability_reason:string|null;recoverability_reviewed_by_user_id:string|null;recoverability_reviewed_at:Date|null;created_at:Date;updated_at:Date;version:number};
export type VatReadiness={blockers:{unapproved_documents:number;missing_reviews:number;pending_reviews:number;vat_recoverability_pending:number;vat_ledger_mismatches:number;total:number};ready:boolean};
export class VatValidationError extends Error{}
export class VatNotFoundError extends Error{}
export class VatConflictError extends Error{constructor(message='Conflict'){super(message)}}
const route=(handler:(req:Request,res:Response)=>Promise<void>):RequestHandler=>(req,res,next:NextFunction)=>void handler(req,res).catch(next);
const context=(req:Request)=>getAuthenticatedContext(req)! as ReturnType<typeof getAuthenticatedContext>&{activeCompanyId:string};
function validDate(value:unknown):value is string{return typeof value==='string'&&DATE.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`));}
function nullableNote(value:unknown){if(value===undefined||value===null||value==='')return null;if(typeof value!=='string')throw new VatValidationError('Invalid request');const x=value.trim();if(x.length>500)throw new VatValidationError('Invalid request');return x||null;}
function parseCreate(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;if(Object.keys(x).some(k=>!['fiscal_year_id','period_start','period_end'].includes(k))||typeof x.fiscal_year_id!=='string'||!UUID.test(x.fiscal_year_id)||!validDate(x.period_start)||!validDate(x.period_end)||x.period_end<x.period_start)return null;return{fiscalYearId:x.fiscal_year_id,start:x.period_start,end:x.period_end};}
function parseReason(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;if(Object.keys(x).length!==1||typeof x.reason!=='string')return null;const reason=x.reason.trim();return reason&&reason.length<=500?reason:null;}
function parseReview(body:unknown){if(!body||typeof body!=='object'||Array.isArray(body))return null;const x=body as Record<string,unknown>;const allowed=['tax_date','treatment','taxable_amount','vat_amount','review_status','review_note','version','recoverability_status','recoverable_vat_amount','recoverability_reason'];if(Object.keys(x).some(k=>!allowed.includes(k))||!validDate(x.tax_date)||(x.review_status!=='pending'&&x.review_status!=='reviewed'))return null;const note=nullableNote(x.review_note),reason=nullableNote(x.recoverability_reason);const version=x.version===undefined?undefined:x.version;if(version!==undefined&&(!Number.isInteger(version)||Number(version)<1))return null;if(x.review_status==='pending'){if(x.treatment!=null||x.taxable_amount!=null||x.vat_amount!=null||x.recoverability_status!=null||x.recoverable_vat_amount!=null||reason!==null)return null;return{taxDate:x.tax_date,status:'pending' as const,treatment:null,taxable:null,vat:null,note,recoverability:undefined,recoverable:null,reason:null,version:version as number|undefined};}if(typeof x.treatment!=='string'||!TREATMENTS.includes(x.treatment as Treatment)||typeof x.taxable_amount!=='string'||!MONEY.test(x.taxable_amount)||typeof x.vat_amount!=='string'||!MONEY.test(x.vat_amount))return null;if(x.recoverability_status!==undefined&&(typeof x.recoverability_status!=='string'||!RECOVERABILITY.includes(x.recoverability_status as Recoverability)))return null;if(x.recoverable_vat_amount!==undefined&&x.recoverable_vat_amount!==null&&(typeof x.recoverable_vat_amount!=='string'||!MONEY.test(x.recoverable_vat_amount)))return null;return{taxDate:x.tax_date,status:'reviewed' as const,treatment:x.treatment as Treatment,taxable:x.taxable_amount,vat:x.vat_amount,note,recoverability:x.recoverability_status as Recoverability|undefined,recoverable:(x.recoverable_vat_amount??null) as string|null,reason,version:version as number|undefined};}
function cents(value:string){const [whole,fraction='']=value.split('.');return BigInt(whole!)*100n+BigInt(fraction.padEnd(2,'0'));}
function resolveRecoverability(documentType:string,input:Exclude<ReturnType<typeof parseReview>,null>){if(input.status==='pending')return{status:'needs_review' as Recoverability,amount:null,reason:null,reviewed:false};const gross=cents(input.vat!);let status=input.recoverability;if(documentType==='sale')status=status??'not_applicable';else if(gross===0n)status=status??'fully_recoverable';else status=status??'needs_review';let amount=input.recoverable==null?null:cents(input.recoverable);if(gross===0n&&documentType!=='sale'&&input.recoverable==null)amount=0n;if(documentType==='sale'){if(status!=='not_applicable'||amount!==null)throw new VatValidationError('Invalid recoverability');return{status,amount:null,reason:input.reason??null,reviewed:false}}if(gross===0n){if(status!=='fully_recoverable'||amount!==0n)throw new VatValidationError('Invalid recoverability');return{status,amount:'0.00',reason:input.reason??null,reviewed:false}}if(status==='needs_review'){if(amount!==null)throw new VatValidationError('Invalid recoverability');return{status,amount:null,reason:input.reason??null,reviewed:false}}if(status==='fully_recoverable'&&amount!==gross||status==='non_recoverable'&&amount!==0n||status==='partially_recoverable'&&(amount===null||amount<=0n||amount>=gross)||status==='not_applicable'||amount!==null&&(amount<0n||amount>gross))throw new VatValidationError('Invalid recoverability');return{status,amount:input.recoverable!,reason:input.reason??null,reviewed:true};}
function monthKey(date:string){return date.slice(0,7)}
async function lockVatDates(companyId:string,dates:string[],client:PoolClient){for(const bucket of [...new Set(dates.map(monthKey))].sort())await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`vat-period:${companyId}:${bucket}`]);}
async function lockVatRange(companyId:string,start:string,end:string,client:PoolClient){const cursor=new Date(`${start.slice(0,7)}-01T00:00:00Z`),last=new Date(`${end.slice(0,7)}-01T00:00:00Z`),dates:string[]=[];while(cursor<=last){dates.push(cursor.toISOString().slice(0,10));cursor.setUTCMonth(cursor.getUTCMonth()+1)}await lockVatDates(companyId,dates,client);}

export class VatService{
 private audit=new AuditLogRepository();
 private profiles=new CompanyAccountingProfileRepository(this.db);
 constructor(private db:Pool){}
 private async tx<T>(fn:(client:PoolClient)=>Promise<T>){const client=await this.db.connect();try{await client.query('BEGIN');const value=await fn(client);await client.query('COMMIT');return value}catch(error){await client.query('ROLLBACK');if((error as{code?:string}).code==='23505')throw new VatConflictError('VAT period overlaps an existing period');throw error}finally{client.release()}}
 async readiness(companyId:string,start:string,end:string,client:PoolClient|Pool=this.db):Promise<VatReadiness>{const {rows}=await client.query<{unapproved_documents:string;missing_reviews:string;pending_reviews:string;vat_recoverability_pending:string}>(`SELECT
   (SELECT COUNT(*) FROM documents d WHERE d.company_id=$1 AND d.document_type IN ('purchase','expense','sale') AND d.document_date BETWEEN $2 AND $3 AND d.status<>'approved')::text unapproved_documents,
   (SELECT COUNT(*) FROM documents d WHERE d.company_id=$1 AND d.status='approved' AND d.document_type IN ('purchase','expense','sale') AND d.document_date BETWEEN $2 AND $3 AND NOT EXISTS(SELECT 1 FROM document_vat_reviews r WHERE r.company_id=d.company_id AND r.document_id=d.id))::text missing_reviews,
   (SELECT COUNT(*) FROM document_vat_reviews r JOIN documents d ON d.id=r.document_id AND d.company_id=r.company_id WHERE r.company_id=$1 AND r.review_status='pending' AND (r.tax_date BETWEEN $2 AND $3 OR d.document_date BETWEEN $2 AND $3))::text pending_reviews,
   (SELECT COUNT(*) FROM document_vat_reviews r JOIN documents d ON d.id=r.document_id AND d.company_id=r.company_id WHERE r.company_id=$1 AND d.status='approved' AND d.document_type IN ('purchase','expense') AND r.review_status='reviewed' AND r.vat_amount>0 AND (r.recoverability_status IS NULL OR r.recoverability_status='needs_review') AND r.tax_date BETWEEN $2 AND $3)::text vat_recoverability_pending`,[companyId,start,end]);const unapproved_documents=Number(rows[0]!.unapproved_documents),missing_reviews=Number(rows[0]!.missing_reviews),pending_reviews=Number(rows[0]!.pending_reviews),vat_recoverability_pending=Number(rows[0]!.vat_recoverability_pending??0);const reconciliation=await loadVatReconciliation(client,companyId,start,end);const vat_ledger_mismatches=reconciliation.documents.filter(document=>document.reconciliation_status!=='reconciled'&&Number(document.expected_vat_amount??document.reviewed_vat_amount)>0).length;const total=unapproved_documents+missing_reviews+pending_reviews+vat_recoverability_pending+vat_ledger_mismatches;return{blockers:{unapproved_documents,missing_reviews,pending_reviews,vat_recoverability_pending,vat_ledger_mismatches,total},ready:total===0};}
 async list(companyId:string){const {rows}=await this.db.query<Period>('SELECT *,period_start::text,period_end::text FROM vat_periods WHERE company_id=$1 ORDER BY vat_periods.period_start DESC',[companyId]);return{periods:await Promise.all(rows.map(async p=>{const readiness=await this.readiness(companyId,p.period_start,p.period_end);return{...p,...readiness}}))};}
 async get(companyId:string,id:string){const period=(await this.db.query<Period>('SELECT *,period_start::text,period_end::text FROM vat_periods WHERE id=$1 AND company_id=$2',[id,companyId])).rows[0];if(!period)throw new VatNotFoundError();const readiness=await this.readiness(companyId,period.period_start,period.period_end);const {rows:documents}=await this.db.query(`SELECT d.id,d.status,d.original_filename,d.document_type,d.document_date::text,d.counterparty_name,d.total_amount::text,
   r.id review_id,r.tax_date::text,r.treatment,r.taxable_amount::text,r.vat_amount::text,r.review_status,r.review_note,r.version,r.recoverability_status,r.recoverable_vat_amount::text,r.recoverability_reason,r.recoverability_reviewed_by_user_id,r.recoverability_reviewed_at
   FROM documents d LEFT JOIN document_vat_reviews r ON r.document_id=d.id AND r.company_id=d.company_id
   WHERE d.company_id=$1 AND d.document_type IN ('purchase','expense','sale') AND ((d.document_date BETWEEN $2 AND $3) OR (r.tax_date BETWEEN $2 AND $3))
   ORDER BY COALESCE(r.tax_date,d.document_date) DESC,d.created_at DESC`,[companyId,period.period_start,period.period_end]);const reconciliation=await loadVatReconciliation(this.db,companyId,period.period_start,period.period_end);return{period:{...period,...readiness},documents,reconciliation};}
 async create(companyId:string,actor:string,fiscalYearId:string,start:string,end:string){return this.tx(async client=>{await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`vat-periods:${companyId}`]);const fy=(await client.query<{start_date:string;end_date:string}>('SELECT start_date::text,end_date::text FROM fiscal_years WHERE id=$1 AND company_id=$2',[fiscalYearId,companyId])).rows[0];if(!fy)throw new VatNotFoundError();if(start<fy.start_date||end>fy.end_date)throw new VatValidationError('Period must be within its fiscal year');const startProfile=await this.profiles.current(companyId,start,client),endProfile=await this.profiles.current(companyId,end,client);if(!startProfile||!endProfile||startProfile.id!==endProfile.id)throw new VatConflictError('No single approved accounting profile governs this VAT period');const profile=startProfile;if(profile.vat_status==='not_registered'||profile.vat_status==='needs_review')throw new VatConflictError('VAT registration status does not permit period creation');if(profile.vat_registered_from&&start<profile.vat_registered_from)throw new VatConflictError('VAT period starts before VAT registration');if(profile.vat_status==='deregistered'&&(!profile.vat_deregistered_from||end>=profile.vat_deregistered_from))throw new VatConflictError('VAT period is outside the VAT registration window');const startDate=new Date(`${start}T00:00:00Z`),endDate=new Date(`${end}T00:00:00Z`),lastDay=new Date(Date.UTC(startDate.getUTCFullYear(),startDate.getUTCMonth()+1,0)).toISOString().slice(0,10);if(profile.vat_filing_frequency!=='monthly'&&profile.vat_filing_frequency!=='quarterly')throw new VatConflictError('VAT filing frequency is required');if(profile.vat_filing_frequency==='monthly'&&(start.slice(8)!=='01'||end!==lastDay))throw new VatConflictError('VAT period must be one complete calendar month');if(profile.vat_filing_frequency==='quarterly'){const month=startDate.getUTCMonth(),quarterStart=Math.floor(month/3)*3,quarterEnd=new Date(Date.UTC(startDate.getUTCFullYear(),quarterStart+3,0)).toISOString().slice(0,10);if(start!==`${startDate.getUTCFullYear()}-${String(quarterStart+1).padStart(2,'0')}-01`||end!==quarterEnd)throw new VatConflictError('VAT period must be one complete calendar quarter');}if((await client.query('SELECT 1 FROM vat_periods WHERE company_id=$1 AND period_start<=$3 AND period_end>=$2',[companyId,start,end])).rowCount)throw new VatConflictError('VAT period overlaps an existing period');const period=(await client.query<Period>("INSERT INTO vat_periods(company_id,fiscal_year_id,period_start,period_end,status) VALUES($1,$2,$3,$4,'open') RETURNING *,period_start::text,period_end::text",[companyId,fiscalYearId,start,end])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'vat_period.create',entity_type:'vat_period',entity_id:period.id,before_data:null,after_data:period as never},client);return period;});}
 async saveReview(companyId:string,actor:string,documentId:string,input:Exclude<ReturnType<typeof parseReview>,null>){return this.tx(async client=>{
  const doc=(await client.query<{id:string;status:string;document_type:string|null}>('SELECT id,status,document_type FROM documents WHERE id=$1 AND company_id=$2 FOR UPDATE',[documentId,companyId])).rows[0];
  if(!doc)throw new VatNotFoundError();if(doc.status!=='approved'||!['purchase','expense','sale'].includes(doc.document_type??''))throw new VatConflictError('Document is not eligible for VAT review');
  const recoverability=resolveRecoverability(doc.document_type!,input);
  const existing=(await client.query<VatReview>('SELECT *,tax_date::text,taxable_amount::text,vat_amount::text,recoverable_vat_amount::text FROM document_vat_reviews WHERE document_id=$1 AND company_id=$2 FOR UPDATE',[documentId,companyId])).rows[0];
  const dates=[...new Set([input.taxDate,...(existing?[existing.tax_date]:[])])].sort();await lockVatDates(companyId,dates,client);
  if((await client.query('SELECT 1 FROM vat_periods WHERE company_id=$1 AND status=\'closed\' AND ($2::date BETWEEN period_start AND period_end OR $3::date BETWEEN period_start AND period_end) LIMIT 1',[companyId,dates[0],dates[1]??dates[0]])).rowCount)throw new VatConflictError('VAT period is closed');
  for(const date of dates)await assertAccountingDateWritable(companyId,date,client);if(existing&&input.version!==existing.version)throw new VatConflictError('VAT review was modified');
  const reviewer=recoverability.reviewed?actor:null,reviewedAt=recoverability.reviewed?new Date():null;let review:VatReview;
  if(existing){review=(await client.query<VatReview>(`UPDATE document_vat_reviews SET tax_date=$3,treatment=$4,taxable_amount=$5,vat_amount=$6,review_status=$7,reviewed_by_user_id=$8,reviewed_at=$9,review_note=$10,recoverability_status=$11,recoverable_vat_amount=$12,recoverability_reason=$13,recoverability_reviewed_by_user_id=$14,recoverability_reviewed_at=$15,updated_at=NOW(),version=version+1 WHERE document_id=$1 AND company_id=$2 RETURNING *,tax_date::text,taxable_amount::text,vat_amount::text,recoverable_vat_amount::text`,[documentId,companyId,input.taxDate,input.treatment,input.taxable,input.vat,input.status,input.status==='reviewed'?actor:null,input.status==='reviewed'?new Date():null,input.note,recoverability.status,recoverability.amount,recoverability.reason,reviewer,reviewedAt])).rows[0]!;
   await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'document_vat_review.update',entity_type:'document_vat_review',entity_id:review.id,before_data:existing as never,after_data:review as never},client);
  }else{review=(await client.query<VatReview>(`INSERT INTO document_vat_reviews(company_id,document_id,tax_date,treatment,taxable_amount,vat_amount,review_status,reviewed_by_user_id,reviewed_at,review_note,recoverability_status,recoverable_vat_amount,recoverability_reason,recoverability_reviewed_by_user_id,recoverability_reviewed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *,tax_date::text,taxable_amount::text,vat_amount::text,recoverable_vat_amount::text`,[companyId,documentId,input.taxDate,input.treatment,input.taxable,input.vat,input.status,input.status==='reviewed'?actor:null,input.status==='reviewed'?new Date():null,input.note,recoverability.status,recoverability.amount,recoverability.reason,reviewer,reviewedAt])).rows[0]!;
   await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'document_vat_review.create',entity_type:'document_vat_review',entity_id:review.id,before_data:null,after_data:review as never},client);}
  return review;
 });}

 async close(companyId:string,actor:string,id:string){return this.tx(async client=>{const period=(await client.query<Period>('SELECT *,period_start::text,period_end::text FROM vat_periods WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!period)throw new VatNotFoundError();if(period.status!=='open')throw new VatConflictError('VAT period is not open');await lockVatRange(companyId,period.period_start,period.period_end,client);const readiness=await this.readiness(companyId,period.period_start,period.period_end,client);if(!readiness.ready)throw new VatConflictError('VAT period has blockers');const after=(await client.query<Period>("UPDATE vat_periods SET status='closed',updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *,period_start::text,period_end::text",[id,companyId])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'vat_period.close',entity_type:'vat_period',entity_id:id,before_data:{status:'open'},after_data:{status:'closed'}},client);return{...after,...readiness};});}
 async reopen(companyId:string,actor:string,id:string,reason:string){return this.tx(async client=>{const period=(await client.query<Period>('SELECT *,period_start::text,period_end::text FROM vat_periods WHERE id=$1 AND company_id=$2 FOR UPDATE',[id,companyId])).rows[0];if(!period)throw new VatNotFoundError();if(period.status!=='closed')throw new VatConflictError('VAT period is not closed');await lockVatRange(companyId,period.period_start,period.period_end,client);const after=(await client.query<Period>("UPDATE vat_periods SET status='open',updated_at=NOW() WHERE id=$1 AND company_id=$2 RETURNING *,period_start::text,period_end::text",[id,companyId])).rows[0]!;await this.audit.logEvent({company_id:companyId,actor_user_id:actor,action:'vat_period.reopen',entity_type:'vat_period',entity_id:id,before_data:{status:'closed'},after_data:{status:'open'},reason},client);return after;});}
}
function service(res:Response){if(!pool){res.status(503).json({error:'Database unavailable'});return null}return new VatService(pool)}
function handle(error:unknown,res:Response){if(error instanceof VatValidationError)res.status(400).json({error:error.message});else if(error instanceof VatNotFoundError)res.status(404).json({error:'Not found'});else if(error instanceof VatConflictError)res.status(409).json({error:error.message});else throw error;}
vatRouter.get('/vat-periods',requireAuth,requireActiveCompany,requireCapability('vat.view'),route(async(req,res)=>{const value=service(res);if(value)res.json(await value.list(context(req).activeCompanyId));}));
vatRouter.get('/vat-periods/:id',requireAuth,requireActiveCompany,requireCapability('vat.view'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new VatValidationError('Invalid request');const value=service(res);if(value)res.json(await value.get(context(req).activeCompanyId,req.params.id));}catch(error){handle(error,res)}}));
vatRouter.post('/vat-periods',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.close'),route(async(req,res)=>{try{const body=parseCreate(req.body);if(!body)throw new VatValidationError('Invalid request');const value=service(res);if(value)res.status(201).json(await value.create(context(req).activeCompanyId,context(req).user.id,body.fiscalYearId,body.start,body.end));}catch(error){handle(error,res)}}));
vatRouter.put('/documents/:id/vat-review',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.review'),route(async(req,res)=>{try{if(!UUID.test(req.params.id))throw new VatValidationError('Invalid request');const body=parseReview(req.body);if(!body)throw new VatValidationError('Invalid request');const value=service(res);if(value)res.json(await value.saveReview(context(req).activeCompanyId,context(req).user.id,req.params.id,body));}catch(error){handle(error,res)}}));
vatRouter.post('/vat-periods/:id/close',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.close'),route(async(req,res)=>{try{if(!UUID.test(req.params.id)||Object.keys(req.body??{}).length)throw new VatValidationError('Invalid request');const value=service(res);if(value)res.json(await value.close(context(req).activeCompanyId,context(req).user.id,req.params.id));}catch(error){handle(error,res)}}));
vatRouter.post('/vat-periods/:id/reopen',requireSameOrigin,requireAuth,requireActiveCompany,requireCapability('vat.reopen'),route(async(req,res)=>{try{const reason=parseReason(req.body);if(!UUID.test(req.params.id)||!reason)throw new VatValidationError('Reason is required');const value=service(res);if(value)res.json(await value.reopen(context(req).activeCompanyId,context(req).user.id,req.params.id,reason));}catch(error){handle(error,res)}}));

